### ISSUE TITLE
Feature request: the "TV" and "Mic" buttons.

### ISSUE THREAD

**Issue by lightbord** [postlund/pyatv#100]
On the 4th Gen Apple TV remotes (also called the "Siri" remote, can be seen [here](https://www.apple.com/shop/product/MLLC2LL/A/siri-remote), there are two new buttons: the TV button which is kinda like the home button on iOS devices, and the Mic button which activates Siri. The Siri button isn't as important, as you'd need the microphone in the remote in order to do anything with it anyway. Double clicking the TV button will basically bring up a home screen where you can close or switch apps like you can in iOS; single clicking it will bring you back to the home screen (kinda like `top_menu`; and holding it down will bring up a little menu that allows you to put the Apple TV to sleep.

**Comment by jonathanweinberg** [comment]
I wonder if this is a cheating way around the lack of HDMI CEC?

**Comment by postlund** [comment]
I'm all for this, but I don't think DAAP supports this button. So it's the same issue as with a lot of other things currently. Support for MediaRemoteProtocol is needed and I'm not sure that I have time to work on that at the moment (would need a new ATV as well, I only have a 3rd gen).

If anyone wants to give it a spin and implement support for it, just go for it! 👍  Since SRP is used as authentication method, maybe the same code that is used for device authentication can be used.

**Comment by postlund** [comment]
I am still not sure how these buttons work, but I'm planning for support in v0.4.0. No date is set for that though, so it will probably take a while (not even basic protocol logic is in place yet).

**Comment by postlund** [comment]
Moving milestone to 0.4.1 to. I want 0.4.0 to match the features on 0.3.x more or less for the same of priority.

**Comment by postlund** [comment]
I will implement the TV button today, but defer the mic/Siri button until later as that is a little special (it needs some special handling since it continues to send audio as long as it is pressed, single presses are not really relevant). Siri button will be done in #170.

**Comment by postlund** [comment]
Ok, didn't realize this at first but the "TV" button is actually the same as `top_menu`, so it is already implemented. There is however no way to do for instance long-press or double tap, so I will have to come up with a solution for that. I will write a new issue for it though as it's a different matter.

**Comment by postlund** [comment]
For reference: #472.
