### ISSUE TITLE
pyatv no longer installs on Raspbian

### ISSUE THREAD

**Issue by makzdot** [postlund/pyatv#103]
pyatv will no longer on a Raspberry Pi (Raspbian) ARM-7

`distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1`

`----------------------------------------`
`Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-gzvblv_a/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-27mwr394-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-gzvblv_a/cryptography
Storing debug log for failure in /root/.pip/pip.log `

regards,
Makz

**Comment by postlund** [comment]
Did you install the necessary packages as stated on the main page?

**Comment by makzdot** [comment]
Doh! That fixed it. Sorry 'bout that

**Comment by postlund** [comment]
I updated the instructions two days ago so I don't blame you, it wasn't very clear to me that this was needed 😊
