### ISSUE TITLE
atvremote app_list function not working after reboot AppleTV

### ISSUE THREAD

**Issue by pdecrom** [postlund/pyatv#1034]
**Describe the bug**

I initially noticed this when I tried the new feature to get the app list with the atvremote app_list function.
The atvremote application crashes, see debug log:

[debug.log](https://github.com/postlund/pyatv/files/6369719/debug.log)

**To Reproduce**
restart the AppleTV
execute:
```
atvremote -s <ip-adress atv> --mrp-credentials secret  --companion-credentials secret app_list
```

**Expected behavior**
return all installed applications

**System Setup (please complete the following information):**
 - OS: Darwin macbook 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
 - Python: 3.9.1
 - pyatv: 0.7.7
- Apple TV:  4K tvOS 14.4

**Additional context**
If this crash occurs, you can solve it like this:
1. on an iPhone make a shortcut: open app on appletv and browse the app list
2. this already triggers something that causes the atvremote app_list command to start working and returns all apps without crashing

**Comment by postlund** [comment]
Thanks for creating the issue, I will take a look when I have some time 👍

**Comment by postlund** [comment]
Tried `app_list` after restarting my Apple TV and it worked 😬

**Comment by postlund** [comment]
I have figured out how to fix this, will try to come up with a fix by tonight or so. If you have time to verify it for me, that would be swell 👍

**Comment by pdcrom** [comment]
Sure, I am available to test a fix.

**Comment by postlund** [comment]
Great! I think I have something that works, will push it later tonight!

**Comment by postlund** [comment]
Now there's hopefully a fix in #1106!

**Comment by pdcrom** [comment]
It works!
This is how I tested.
1. cloned the repo
2. switched to master branch
3. restart atv
4. check the app_list command, it crashed
5. switch to applist branch
6. check the app_list command again, it showed all apps correctly

**Comment by postlund** [comment]
That's a perfect way to test if, thanks! 👍 I will update and merge it immediately!

**Comment by postlund** [comment]
Fixed!
