### ISSUE TITLE
Deepcopy is slow

### ISSUE THREAD

**Issue by cchampignon** [postlund/pyatv#1038]
Running aiodebug I'm getting log messages that look like this

```log
WARNING:aiodebug.log_slow_callbacks:Executing <Task finished name='Task-28541' coro=<PlayerStateManager._handle_set_default_supported_commands() done, defined at /home/pi/.pyenv/versions/3.8.8/lib/python3.8/site-packages/pyatv/mrp/player_state.py:313> result=None> took 2.087 seconds

WARNING:aiodebug.log_slow_callbacks:Executing <Task finished name='Task-28543' coro=<PlayerStateManager._handle_set_state() done, defined at /home/pi/.pyenv/versions/3.8.8/lib/python3.8/site-packages/pyatv/mrp/player_state.py:258> result=None> took 4.793 seconds
```

Looks the deepcopy calls are the culprit

![image](https://user-images.githubusercontent.com/804077/116013996-fffe5180-a600-11eb-8075-9a4b3798324b.png)

This is causing my app to be unresponsive. I'm using pyatv as the backend for a remote app I've written. When it hits these deepcopy calls my remote app appears dead (no longer can control the atv4k) Once the deepcopy is done all my button presses fire immediately, one right after the other, as if there were queued up during the deepcopy.

As a workaround I have wrapped those deepcopy calls in their own threads, which has help quite a bit, but not solved it (still get smaller delays infrequently). That suggests to me there may be something else going on (potentially in my code) but blocking for multiple seconds to do the copy does seem like an issue worth looking at.

Running on a pi zero w with pyatv 0.7.7 
This issue seemed related https://github.com/postlund/pyatv/issues/773

**Comment by postlund** [comment]
I can acknowledge that doing `deepcopy` is slow as the protobuf message can be relatively large. So there's definitely a penalty doing so, mostly done for flexibility (as all information will be there) and to avoid having to create additional data structure to store the information. Seems strange that it would be so expensive though, what's the time scale in the picture? Even if the pi zero is very slow, I woldn't expect it to be that slow. Trying to do the I/O in separate threads/tasks won't really fix the issue, only optimizing will do that and perhaps I can take a look at the soon-ish.

Please also stick to the issue templates in the future, they are there for a reason.

**Comment by cchampignon** [comment]
Sorry I'm not sure how to tell the time scale of the graph. 

However I did at some simple print debugging at the lines before and after the 2 deep copy calls which further corroborate what aiodebug and py-spy are showing - a gap of multiple seconds.

```
Apr 15 15:41:43  WARNING:pyatv.mrp.player_state:start deepcopy @line:105
Apr 15 15:41:45  WARNING:pyatv.mrp.player_state:end deepcopy @line:105
Apr 15 15:41:45  WARNING:aiodebug.log_slow_callbacks:Executing <Task finished name='Task-46405' coro=<PlayerStateManager._handle_set_state() done, defined at /home/pi/.pyenv/versions/3.8.8/lib/python3.8/site-packages/pyatv/mrp/player_state.py:258> result=None> took 2.123 seconds
Apr 15 15:41:45  WARNING:pyatv.mrp.player_state:start deepcopy @line:112
Apr 15 15:41:47  WARNING:pyatv.mrp.player_state:stop deepcopy @line:112
Apr 15 15:41:47  WARNING:aiodebug.log_slow_callbacks:Executing <Task finished name='Task-46406' coro=<PlayerStateManager._handle_set_state() done, defined at /home/pi/.pyenv/versions/3.8.8/lib/python3.8/site-packages/pyatv/mrp/player_state.py:258> result=None> took 2.063 seconds
```

**Comment by postlund** [comment]
I've been thinking a bit about this lately and... I think copying isn't necessary at all anymore since I don't store any references to player states (#943). So they should be possible to remove altogether, which is nice. I'll prepare a commit later today or maybe tomorrow to fix that.
