### ISSUE TITLE
`tag_definition` `cang` for genre of currently playing media

### ISSUE THREAD

**Issue by jmery** [postlund/pyatv#106]
Raspberry Pi 3b
Hassbian 1.23
HA 0.52.1

I'm seeing warnings in the HA logs like this:
```
WARNING (MainThread) [pyatv.tag_definitions] Unknown data: b'cang\x00\x00\x00\nSoundtrackcanl\x00\x00\x001'
```

A little research shows that `cang` clearly ties to the genre of the currently playing song.  E.G. the above is from tracks on the "Tron:Legacy" album.  "Tron:Legacy Reconfigured" then changes this to `Unknown data: b'cang\x00\x00\x00\nElectroniccanl\x00\x00\x00\x19'` which follows the album genre.  Etc, etc...

I can submit a PR to add this to `tag_definitions.py` if someone can point me to where I can find the correct corresponding mapping value.

**Comment by postlund** [comment]
Definitely looks like a missing tag, for sure. Also seems easy enough to just be a string as well, it should be decoded like this:
```
b'cang\x00\x00\x00\nElectroniccanl\x00\x00\x00\x19'
-> tag: cang, length: \x00\x00\x00\n = 0x000000A = 10, value: Electronic
-> tag: canl, length: \x00\x00\x00\x1 = 0x0000001 = 1, value: 9
```
So I guess the output is not really complete here. If you just try adding it to ``tag_definitions.py`` using ``read_str``, it should hopefully work. Would also be nice to add ``genre`` to the metadata API. It requires a bit more work, extending ``interface.py``, adding tests, documentation and so on. If you are up for the challenge, I welcome a PR 👍 (should be straight-forward by looking at for example ``artist`` as a template but I can help you out if you need any help)

**Comment by postlund** [comment]
I have implemented support for genre now and it will be part of 0.3.5. Hopefully I'll get that out tomorrow with a PR to Home Assistant as well.

**Comment by jmery** [comment]
Awesome and thank you for this.  I've been completely buried for the last several weeks and didn't even get a chance to look into it.  Cheers!

**Comment by postlund** [comment]
No worries, I hope it solves your problem! 😊 I know how it is, it’s really hard to find time sometimes and lately I’ve put my own focus into MRP. Hopefully I can have something working soon!
