### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by domtik** [postlund/pyatv#1066]
Hello,

Probably you are already aware of this. Just reporting the error for other to wait for the fix before upgrading Home assistant in June.
"2021-05-10 12:03:15 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'apple_tv'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'apple_tv'"

Thank you for the great work. This plugin is working perfectly for me
Best Regards

**Comment by postlund** [comment]
Right, yeah, I should fix that. There's nothing in that repo that isn't already in Home Assistant so you wouldn't miss out (it's probably better to run official version anyway). Thanks for mentioning it!

**Comment by postlund** [comment]
Added it now: https://github.com/postlund/hass-atv-beta
