### ISSUE TITLE
power_state returns wrong state

### ISSUE THREAD

**Issue by setBoolean** [postlund/pyatv#1082]
Summary:
`power_state` returns `PowerState.On` regardless of actual state.

How to reproduce:
Send `turn_off` command --> ATV turns off correctly --> send `power_state` command --> replies `PowerState.On`.

Model/SW: 4K tvOS 14.5

**Comment by postlund** [comment]
Are you using e.g. a HomePod as output device?

**Comment by setBoolean** [comment]
Yes I'am using a OG HomePod Stereo setup as audio output.

**Comment by crxporter** [comment]
Related #958 I believe you have the same issue as me.

**Comment by setBoolean** [comment]
Sorry everyone I should also have searched the closed issues. Will close this now as it seems unfixable.

**Comment by setBoolean** [comment]
@crxporter I don't know your exact use case but I fixed the problem using `pyatv` in combination with `homebridge-cmdswitch2`, maybe it suits your needs too.

I use my TV exclusively with the ATV, so when my TV is on my ATV also is and vice versa. Now I use 'ping' to check if my TV is on as it stops replying to ping probes after the ATV turns it off via CEC. And that's how I get the state of my ATV. Then I just had to add the proper 'atvremote' commands for 'ON' and 'OFF'. Now I can turn on/off my ATV in HomeKit Scenes.

Here is my config if you need it.

```
{
            "name": "Apple TV",
            "on_cmd": "ATVREMOTE_COMMAND",
            "off_cmd": "ATVREMOTE_COMMAND",
            "state_cmd": "ping -c 2 -W 1 ATV_IP | grep -i '2 received'",
            "polling": true,
            "interval": 10
}
```

Depending on your TV this might work for you too.

**Comment by crxporter** [comment]
I've done a bit of workaround programming in nodered which has my tv working mostly as I want. I have a Samsung The Frame tv so instead of turning it off, I want it to go to art mode when I'm done watching Apple TV. Unfortunately the CEC command turns it all the way off. 

Its a bit messy but it's been working well for a while so I'm happy until we find some better way to know the Apple TV is off!
