### ISSUE TITLE
Using play_url, I always get "line 61, in play_url     raise exceptions.AuthenticationError("Status code: " + str(status)) pyatv.exceptions.AuthenticationError: Status code: 403"

### ISSUE THREAD

**Issue by RyanTamulevicz** [postlund/pyatv#1085]
**What's on your heart?**
I am not sure what section to put this under, but I am unsure how to properly play a URL from either python or through the atvremote.

I entered atvremote --id IDNUMBER play_url=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

I have also tried using --mrp-credentials in here. I have tried this a few times in python as well to no success with the same error. What could this possibly be?

"line 61, in play_url raise exceptions.AuthenticationError("Status code: " + str(status)) pyatv.exceptions.AuthenticationError: Status code: 403"

**Comment by postlund** [comment]
`play_url` uses AirPlay to play media, so you need to provide AirPlay credentials (`atvremote ... --protocol airplay pair` and pass what you get to `--airplay-credentials`).

**Comment by RyanTamulevicz** [comment]
> `play_url` uses AirPlay to play media, so you need to provide AirPlay credentials (`atvremote ... --protocol airplay pair` and pass what you get to `--airplay-credentials`).

i understand. i actually just got it working and saw this before reading this. i am struggling to get it working in python but i will do my best to work out how to do that. thank you!

**Comment by postlund** [comment]
Do you want an example on how to do it in python? Both pairing or just the streaming part?

**Comment by RyanTamulevicz** [comment]
> Do you want an example on how to do it in python? Both pairing or just the streaming part?

Well I found the example that does the pairing in Python. I got the mrp credentials from that so I think getting airplay credentials would be the same. Streaming example would be great though! Thank you so much 👍

**Comment by postlund** [comment]
Yeah, the pairing example should work for getting credentials. I should update it a bit however as it's not taking older devices in consideration (like Apple TV 3, where you input a PIN on the device itself). Doesn't matter in your case though.

Made a simple example here, also showing how to insert credentials:
```python
"""Example of playing a video file via AirPlay.

python play_url.py <id> <airplay credentials> <url>
"""

import sys
import asyncio

import pyatv
from pyatv.const import Protocol


async def play_url(
    device_id: str, airplay_credentials: str, url: str, loop: asyncio.AbstractEventLoop
):
    """Connect to an Apple TV and stream file via AirPlay."""
    print("* Discovering device on network...")
    atvs = await pyatv.scan(loop, identifier=device_id)
    if not atvs:
        print("* Device found", file=sys.stderr)
        return

    conf = atvs[0]
    conf.set_credentials(Protocol.AirPlay, airplay_credentials)
    atv = await pyatv.connect(conf, loop)

    try:
        print(f"* Streaming {url} to {conf.address}")
        await atv.stream.play_url(url)
    finally:
        await atv.close()


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(
        play_url(sys.argv[1], sys.argv[2], sys.argv[3], asyncio.get_event_loop())
    )
```

I will add it to the other examples too, it's well suited there. As this is mostly boiler plate, I intend to add a more appropriate helper method as well. Maybe in time for 0.8.0, not sure yet though.

This section describes how you deal with credentials:

https://pyatv.dev/development/scan_pair_and_connect/#managing-credentials

It was a while back I wrote it, so I see that it needs some attention (should not be placed under pairing, but rather under connect for instance). Feel free to leave me comments on things that are unclear and I'll try to fix them. I want the documentation to be as clear as possible, but it's easy to get blind when writing it as I know the API quite good myself.
