### ISSUE TITLE
Script to let AppleTV sleep only works once, then no longer and with errors

### ISSUE THREAD

**Issue by guidokieboom** [postlund/pyatv#1120]
When using the below script from https://www.home-assistant.io/integrations/apple_tv/ I can run this script only successfully once. A second (third, etc.) time the script doesn't work. Error message "failed to call script...." appears. Error log see below. Could you advise what to change in my script? (AppleTV and Home Assistant have latest updates installed)

<img width="738" alt="Screenshot 2021-06-05 at 09 37 14" src="https://user-images.githubusercontent.com/65387179/120884186-bcc0d680-c5e1-11eb-9097-ea53ca52cfea.png">

![image](https://user-images.githubusercontent.com/65387179/120884245-38bb1e80-c5e2-11eb-801d-f40526e8e21c.png)

The following error log : 
Logger: homeassistant.components.script.1616336919533
Source: components/apple_tv/remote.py:63 
Integration: Scripts (documentation, issues) 
First occurred: 8:56:50 (9 occurrences) 
Last logged: 9:40:13

Make the Apple TV sleep: Error executing script. Unexpected error for call_service at pos 1: Command not found. Exiting sequence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/remote.py", line 63, in async_send_command
    raise ValueError("Command not found. Exiting sequence")
ValueError: Command not found. Exiting sequence

**Comment by postlund** [comment]
That's really strange, can't really say why that happens. Does the media player entity work before you call the script a second time? Anything else of interest in the log?

**Comment by guidokieboom** [comment]
Thanks @postlund for your quick response. As I wasn't sure if the mediaplayer.appletv works well in my system, I've removed the related AppleTV script and also deleted the AppleTV integration. Then restarted HA. Then reinstalled the AppleTV integration. Then indeed some mediaplayer errors.

<img width="763" alt="Screenshot 2021-06-05 at 13 32 58" src="https://user-images.githubusercontent.com/65387179/120890368-952e3600-c602-11eb-84c0-529a0d1a89ec.png">

The related log is as follows:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/apple_tv/media_player.py:261 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 13:26:48 (3 occurrences) 
Last logged: 13:28:59

[2920237328]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 261, in async_media_play
    await self.atv.remote_control.play()
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 304, in play
    await self._send_command(CommandInfo_pb2.Play)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 273, in _send_command
    resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 180, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 188, in _receive
    await asyncio.wait_for(semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

Can I give you other information or screen shots?

**Comment by guidokieboom** [comment]
I've done some more tries....

I noticed that once copied the .yaml example into the script and use the HA script visual editor, then the syntax is changed.
<img width="286" alt="Screenshot 2021-06-05 at 14 08 12" src="https://user-images.githubusercontent.com/65387179/120891192-84cc8a00-c607-11eb-9a22-97ba1c137150.png">
is converted into: 
<img width="272" alt="Screenshot 2021-06-05 at 14 09 02" src="https://user-images.githubusercontent.com/65387179/120891209-9c0b7780-c607-11eb-9f8b-a15bba7f1554.png">

When going to the .yaml editor and make as in the example (so with the commands over different lines and with dash, it works well. Looks like the HA visual editor changes things and cause this issue... I have to do that every time when I've been in the edit mode.

Other modification (triggered by your question on the media player) is to remove the section
<img width="353" alt="Screenshot 2021-06-05 at 14 11 13" src="https://user-images.githubusercontent.com/65387179/120891272-f0165c00-c607-11eb-8868-52bcc0b1b7e3.png">
I'm doing this to be able to use the 'sleep' script repeatedly (after AppleTV & SonyTV via HDMI-CEC have been turned on again). I tried to keep it, but when I switch on the AppleTV with the physical remote, then HA does not recognise that the media player is on again (looks like this is a different bug).

**Comment by postlund** [comment]
Ok, that looks like a bug in the editor or something. I believe you can write it as a typical array:
```yaml
command: [home_hold, select]
```

I know there's an issue when turning off the device, that it won't come back in Home Assistant again. I haven't looked into it yet, but if you provide logs from right before you turn off up until after you have turned on the device again (and some additional time), I can take a look at it.

**Comment by guidokieboom** [comment]
That's very kind. Actually the log file is huge and I'm not sure how to get this across to you. Could you advise where I can download a log file in HA? 
I have following in configuration.yaml
logger:
  logs:
    pyatv: debug
    homeassistant.components.apple_tv: debug

**Comment by postlund** [comment]
You can probably send it by email to me (it shouldn't be that large I hope?). My address is in my profile.

**Comment by guidokieboom** [comment]
Thank you Pierre for getting back on this as I had abondoned the AppleTV use via Home Assistant. I’m only a very basic user and have no clue in programming.
Still things don’t work as I am looking for, which is simple install of an integration and then use to do Volume Up and Down in Home Assistant and put ATV to sleep (which then also switches off my TV - same as when I use the Apple remote and press buttons to switch off)

I did following: 
still with tvOS14.x
1. Goto integrations and removed Apple TV
2. Added new integration: Apple TV ( I don’t know how to use GitHub)
3. Installation failed after having entered 4digit pincode from TV into HA (various error codes; see attached)
4. restarted HA
5. The ATV was auto-discovered and I entered again the two 4digit PINcodes and installation was successful
6. But still no change:not possible to use the + and - volume buttons and the atvsleep script also does not work (only the pause and play buttons work)
7. I have no clue where to make or find logs

Then updated ATV to tvOS 15.0
1. Goto integrations and removed Apple TV
2. Added new integration: Apple TV ( I don’t know how to use GitHub)
3. Installation failed after having entered 4digit pincode from TV into HA (various error codes; see attached)
4. restarted HA
5. The ATV was auto-discovered and I entered again the two 4digit PINcodes…. But here now I got errors in between: Failed to add service (MRP….) and Aborted
6. Tried again after restart HA and reboot ATV; still same issue of not able to install the AppleTV integration



Regards, Guido

**Comment by guidokieboom** [comment]
Hi Pierre,
I realized I should first load your GitHub link via HACS… I found how to do…
Then after restart HA, I tried again to configure teh Apple TV… It worked with the pincodes now (3 times now).
But still no change… cannot control volume and the atvsleep script does not work.
Hope this helps for you to.
regards, guido

**Comment by guidokieboom** [comment]
I tried to find how to set up but cannot find. I found followin, but van only remove these.

**Comment by postlund** [comment]
Sorry @guidokieboom, I must have missed your response here. It seems strange that the Apple remote would work but not pyatv. Just as a quick check before we proceed, do you own an iOS device? In case you do, can you check if the volume controls are available from media player in Control center (if you bring down control center, long press the media controls widget and pick your Apple TV)?

**Comment by guidokieboom** [comment]
Thank you Pierre for getting back on this.
Yes I own an iOS device (iPhone with latest updates installed)
I’ve made 2 screenshots based on your question. See attached. Looks like volume controls are greyed out (but I don’t know how to activate).
Hope you have an idea how I can activate these. I also swithed my VPN on my iPhone (Norton360), but this did not change the greyed out volume controls.
Regards, Guido

**Comment by postlund** [comment]
I don't think it's possible to attach images when you respond via email (they are not shown here). But I have the same thing on my Apple TV, so I know what you mean. As long as it doesn't work on iOS, it won't work in pyatv either. So something must be configured on the Apple TV and/or whatever you have it connected to. Maybe this page can help as a start:

https://www.sony.com/electronics/support/articles/00161073

**Comment by postlund** [comment]
Feel free to ask further questions, but I think the main issue has been resolved (CEC is not an issue of pyatv). So I will close this now.

**Comment by guidokieboom** [comment]
Thank you Pierre for your multiple tries to help troubleshooting. Seems like an issue between my Sony TV and my AppleTV.
