### ISSUE TITLE
Audio not playing if auth-setup not completed for some receiver

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1134]
**Describe the bug**
When trying to stream to my receiver, an old Yamaha RX-V773, things seems to work just fine but no audio plays. If I however do not send `/auth-setup` (which is required on the AirPort Express) it works just fine. So I need to find a way to deal with this.

**To Reproduce**
Play an audio file with `atvremote stream_file=...` and it won't work.

**Expected behavior**
Audio should play as expected.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: since 5f5ad5b669fa72c0bfbb1ee99d8dd2acee0fd2eb (#1098)
 - Apple TV: Yamaha RX-V773

**Additional context**
No

**Comment by Schlaubischlump** [comment]
I think Raop-Player handles this case by checking the encryption type (et) zeroconf entry. 
Only MFi devices (et 4) require the auth-setup request.

**Comment by postlund** [comment]
I do that too, but the thing is that my receiver reports et=0,4 (just like the AirPort Express) and supports MFi authentication, but does not enforce it in any way. So the sender does not need to perform it. But if the sender initiates it, it seems like it must follow through.

**Comment by postlund** [comment]
Now fixed by #1145.
