### ISSUE TITLE
Pyatv fails to install on M1 Mac because of miniaudio dependency

### ISSUE THREAD

**Issue by shamanskyh** [postlund/pyatv#1162]
**Describe the bug**
Hi, thank you so much for this library. I have been using it without issue for a while now on an M1 Mac mini. I believe one of the more recent releases added the miniaudio library as a dependency, and this is failing to build when I try to upgrade pyatv to the latest version. I believe it's an issue caused by the dependency, and I'll open a GitHub issue with that package as well after this. Here's the log output I get:

```
ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-install-xr993ftf/miniaudio_41126c03fa9b4343962ac371bf368fd5/setup.py'"'"'; __file__='"'"'/private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-install-xr993ftf/miniaudio_41126c03fa9b4343962ac371bf368fd5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-wheel-e7yp9d8l
       cwd: /private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-install-xr993ftf/miniaudio_41126c03fa9b4343962ac371bf368fd5/
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14.6-arm64-3.8
  copying miniaudio.py -> build/lib.macosx-10.14.6-arm64-3.8
  running build_ext
  generating cffi module 'build/temp.macosx-10.14.6-arm64-3.8/_miniaudio.c'
  creating build/temp.macosx-10.14.6-arm64-3.8
  building '_miniaudio' extension
  creating build/temp.macosx-10.14.6-arm64-3.8/build
  creating build/temp.macosx-10.14.6-arm64-3.8/build/temp.macosx-10.14.6-arm64-3.8
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -DMA_NO_GENERATION=1 -I/private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-install-xr993ftf/miniaudio_41126c03fa9b4343962ac371bf368fd5 -I/private/var/folders/0z/cx87zyvn7ssfpp4fc7bff4rw0000gn/T/pip-install-xr993ftf/miniaudio_41126c03fa9b4343962ac371bf368fd5 -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c build/temp.macosx-10.14.6-arm64-3.8/_miniaudio.c -o build/temp.macosx-10.14.6-arm64-3.8/build/temp.macosx-10.14.6-arm64-3.8/_miniaudio.o -g1 -O3 -ffast-math -mtune=native -march=native
  clang: error: the clang compiler does not support '-march=native'
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for miniaudio
```

**To Reproduce**
Run `pip install pyatv` on an M1 Mac.

**Expected behavior**
Running `pip install pyatv` completes without error.

**System Setup (please complete the following information):**
 - OS: macOS 12.0 developer beta 1
 - Python: 3.8.2
 - pyatv: 0.8.0
 - Apple TV: Apple TV 4K tvOS 15.0 developer beta 1

**Additional context**

**Comment by shamanskyh** [comment]
Also filed as https://github.com/irmen/pyminiaudio/issues/30

**Comment by postlund** [comment]
Thanks for reporting this! It was mentioned earlier during testing, hopefully it will be fixed upstream soon. Will leave the issue open until there is a fix in miniaudio.

**Comment by fidesachates** [comment]
So I had the same issue, but on an intel macbook pro. I left the details in the upstream ticket. Just commented here to say that I got around this by putting this into my requirements.txt file:

```
pyatv==0.8.2
git+git://github.com/fidesachates/pyminiaudio.git
```

The second line there points to my fork of pyminiaudio where I removed the compiler flags that were causing me issues. Hope this helps someone. Obviously not a long term fix, but if anyone just wants to get it working for now while they wait for the underlying issue to be fixed.

**Comment by postlund** [comment]
I see this as a problem that I would like fixed, upstream development seems to move at rather low pace right now. Not sure what the best way to proceed is, but a proper pypi release is needed.

**Comment by irmen** [comment]
(author of pyminiaudio here)
I don't have access to a M1 apple system, so need some help on this. Posted my questions in irmen/pyminiaudio#30

**Comment by postlund** [comment]
From what I have gathered this should be fixed once the next release of pyminiaudio is out 👍

**Comment by irmen** [comment]
I've just released 1.45 of pyminiaudio

**Comment by davidbaraff** [comment]
I tried pip install pyatv. just moments ago on an Intel laptop (running Big Sur) and hit the miniaudio problem.  What's the best fix to get pyatv installed at the moment?

**Comment by davidbaraff** [comment]
Also, this:
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

?

**Comment by fidesachates** [comment]
@irmen respectfully I reported it to you on the linked ticket in your repo that the issue also existed on intel macs; I was the first comment after op.

**Comment by irmen** [comment]
Yes that is true! However on oct 4 someone else reported successful build on intel mac with the changes that were made...  I am confused now

**Comment by postlund** [comment]
What CPU is it? I thought someone reported an issue on the latest revision not supported by the compiler?

**Comment by davidbaraff** [comment]
I got past it.  I did a direct install of the cryptography module, and then did something to finesse the mini audio problem, hopefully I wrote it down somewhere…. Maybe it was a direct install of mini audio from a more recent version?

**Comment by postlund** [comment]
I can't tell what you did, but since it seems to work and no one else has spoken up, I guess we can close this for now. Thanks everyone for helping out fixing this! 👍
