### ISSUE TITLE
Missing dmap tags

### ISSUE THREAD

**Issue by Schlaubischlump** [postlund/pyatv#1181]
**What feature would you like?**
Add missing tags.

**Describe the solution you'd like**
Add the tags according to these definitions: 

https://github.com/mattstevens/dmap-parser/blob/master/dmap_parser.c
`asai`: `daap.songalbumid` (uint)
`aeGs`: `com.apple.itunes.can-be-genius-seed` (bool)
`aels`: `com.apple.itunes.liked-state` (uint)
`astm`: `daap.songtime` (uint)

https://github.com/jurriaan/dmapparser/blob/master/lib/dmapparser/tag_definitions.rb
`ceGS`: `com.apple.itunes.genius-selectable` (str)

**Any other information to share?**
`ceQu`: Has most likely something to do with the iTunes play queue (bool)

**Comment by postlund** [comment]
Tags are included in #1182. So this will be fixed when that is merged.

**Comment by postlund** [comment]
Fixed and merged #1182 now. As established before, this only works with maxOS < 11.4. But decided that it was worth committing as the code will just rot otherwise.
