### ISSUE TITLE
atvremote scans fine from one Mac; fails from another

### ISSUE THREAD

**Issue by Ramias1** [postlund/pyatv#1183]
Two Macs; same wired switch.  Three Apple TV's also on same switch.  Mac2018 used to work; now it only sees one of my three ATVs - I have two Gen 4s and one 20201 4k.  Only one of the Gen 4's is seen from Mac2018.

**./atvremote -s 192.168.0.xx --debug --protocol mrp pair** from my M1 Mac works fine.  Fails on the 2018.

**dns-sd -B _mediaremotetv._tcp** shows all three ATVs when run from either Mac.

I need this to work on Mac2018.  Any ideas of that I can do?  Have cycled the switch, rebooted the Mac, rebooted the ATVs.

Thanks

**Comment by postlund** [comment]
When you say that it used to work, which version of pyatv did you use? Maybe you can rollback and try the older version, that would help me narrow down why it isn't working.

**Comment by Ramias1** [comment]
I only discovered Pyatv a week ago.  I’m using a plug-in on Indigo Domitics that is built on pyatv.  It was discovering my Apple TV’s.  I did rename two of the ATVs after they were discovered.  That seems to be when discovery from the one Mac stoped but the other still works.

**Comment by postlund** [comment]
Sounds strange to me. I did release 0.8.1 a few days ago, that's basically what happened in the world of pyatv. But there's no changes in there that should affect scanning. You an try downgrading to 0.8.0 and see if it makes any difference. Based on what you are saying, I assume all devices are on the same VLAN?

**Comment by Ramias1** [comment]
Same VLAN.

So here's some detail that may help:

I installed this probably last Sunday; it was able to scan and create the devices as a result of the scan in my home automation system.  But I was unable to send commands.  I then removed via pip3 (installed originally with --user) and reinstalled with sudo; and I was able to issue commands.  In hindsight, this new install was probably a newer version that did not need to scan (since I already had the devices created) but was able to issue commands.

I then renamed my ATV's and deleted the devices created in my system -- it was unable to recreate any -- so I went to the command line and started with atvremote.

The version on my M1 that worked for atvremote scan was version 0.7.7.

The version on my Mac2018 today was 0.8.1.

Removed it and am on 0.7.7 on my Mac2018 and am now able to scan and detect all three ATV's.

(Prior to posting here I had removed and reinstalled the pip package a few times).  So at least on my network there's an issue with atvremote scan that fails with version 0.8.1 but works with 0.7.7.  I will continue to tweak things.

Thanks for the help.

**Comment by postlund** [comment]
Thanks, that's a great analysis 👍 A lot happened between 0.7.7 and 0.8.x, so it's a bit tricky to pin-point exactly what could be the problem (my time is a bit limited now due to vacation 😎 as well). One thing I want to check first though. Does the name of your devices contain any "special" characters? Just to rule out if it's an encoding issue. If you run `atvremote --debug--mdns-debug scan` you should get more debug data. Can you see any responses from IP addresses belonging to your devices?

**Comment by Ramias1** [comment]
ok upgraded to the latest.  Same issue - "Main Floor" still detected but "Bedroom Apple TV" and "Theater Apple TV" not detected.

Renamed bedroom to "Bedroom ATV" - not detected.  Even this:
python3 atvremote.py -s 192.168.0.41 --debug --protocol mrp pair
2021-06-27 17:38:56 DEBUG [pyatv.support.knock]: Knocking at ports [3689, 7000, 49152, 32498] on 192.168.0.41
2021-06-27 17:38:56 ERROR [root]: Could not find any Apple TV on current network
Renamed to "Bedroom AT" -- detected.  
Renamed back to "Bedroom ATV" -- not detected.
Renamed to "Bedroom AT" -- detected.  

Looks like spaced are allowed in Apple TV name but length max is 10.

Note: I did not restart the Apple TV during these name changes.

**Comment by postlund** [comment]
I'm not sure what is happening to be honest, it's probably my zeroconf implementation that is buggy. I'm moving over to python-zeroconf soon and hopefully that will solve this situation as it is much more stable than what I have managed to come up with.

**Comment by postlund** [comment]
@Ramias1 Can you try if 0.8.2 works?

**Comment by Ramias1** [comment]
Looks good.  Gave my Apple TV a longer name, ran the command line and was able to pair after upgrading to 0.8.2.

thank you
