### ISSUE TITLE
Stream to Homepod Mini from remote/cloud/nas source?

### ISSUE THREAD

**Issue by xpnewmedia** [postlund/pyatv#1186]
**What's on your heart?**

Can the library stream media to the homepod mini from a non-local source?

**Comment by postlund** [comment]
I already opened a feature request for it #1122. So it's not supported yet, but planned at some point. In 0.8.1 however, you can pipe output from another process to `atvremote` (or do it programmatically of course), so it's sort-of possible. I recommend that you check out the release notes:

https://github.com/postlund/pyatv/releases/tag/v0.8.1

**Comment by postlund** [comment]
Ok to close this in favor of #1122?

**Comment by xpnewmedia** [comment]
Cool
