### ISSUE TITLE
Recreate CLI command in Python?

### ISSUE THREAD

**Issue by xpnewmedia** [postlund/pyatv#1195]
**What's on your heart?**
How Can I recreate this command line command into Python ?

```
 while ($true) {
>>    atvremote -s 10.0.0.164 --debug stream_file="Doja Cat ft The Weeknd- You Right (Chopped and Screwed)-LNQbaFMuKKM.mp3";
>> }
```

I want to incorporate this instruction into a flow with other services ie. Redis and RabbitMQ, using Python.

**Comment by postlund** [comment]
It depends on how advanced you want it to be. The simplest (but also "ugliest" way) is to just write a loop that calls the shell command with `subprocess`. I would recommend calling the API instead and I think the stream example might serve as some inspiration (everything related to push updates listener, e.g. the `PushUpdatePrinter` class can be ignored). Let me know if you need more assistance as I don't know how comfortable you are with python.

https://github.com/postlund/pyatv/blob/master/examples/stream.py

**Comment by postlund** [comment]
Anything more I can help you with? Otherwise maybe we can close the issue?

**Comment by xpnewmedia** [comment]
Can close. The py file you mentioned is sufficient.

**Comment by postlund** [comment]
Thanks! 👍
