### ISSUE TITLE
Installation on Raspberry fails

### ISSUE THREAD

**Issue by graq** [postlund/pyatv#1217]
Installation on a fresh Raspberry Pi OS Lite fails. 

Seems to be a problem with pendulum 2.1.2.
What to do to get the installation done?

[pyatv_fail.log](https://github.com/postlund/pyatv/files/6824886/pyatv_fail.log)

**Comment by postlund** [comment]
Maybe the same as this one:

https://github.com/sdispater/pendulum/issues/504

I suggest that you try `pip install pendulum==2.1.1` before installing pyatv.

**Comment by graq** [comment]
Seen it, done it.
So, I can install pendulum 2.1.1, the workaround using --upgrade didn't work.
Unfortunatelly 'pip3 install pyatv' tries to install pendulum 2.1.2 over it, which fails.

Like [sdispater/pendulum#504/issuecomment-806751169]( https://github.com/sdispater/pendulum/issues/504#issuecomment-806751169) stated, it seems to be a bug with the setup.py for this version failing only on a pi OS.

The pyatv installation on my Ubuntu Desktop PC works well, but I want it on a Raspberry 

Can I somehow change the pendulum version for pyatv?

**Comment by postlund** [comment]
I'm not sure, but it *should* be possible to just install a version of pendulum that satisfies the constraints. It's an indirect dependency to pyatv via the audio-metadata library and it has the following constraints:

https://github.com/thebigmunch/audio-metadata/blob/4931aa5c5768d7231027f246f73872bc15de93db/pyproject.toml#L27

Maybe there's a flag you can pass to pip so it doesn't try to upgrade/re-install dependencies that are already installed? More like a work-around than anything else.

**Comment by postlund** [comment]
Did you make any progress on this? I'm still a bit curious about the result.

**Comment by graq** [comment]
Unfortunatelly not. 
I succeeded to do the following actions on my Ubuntu desktop installation
```
pip3 install pendulum==2.1.1
pip3 install pyatv --upgrade-strategy only-if-needed
```
which installs atvremote with pendulum 2.1.1 which works fine.

But it doesn't work on the raspberry. There it seems like the --update-stategy switch doesn't work. 
After having installed pendulum 2.1.1. The pyatv installation tries to update it to 2.1.2 with the known error.

**Comment by postlund** [comment]
Interesting. Which version of pip do you have on Ubuntu contra Raspberry ip?

**Comment by postlund** [comment]
Maybe if you try a later version of pip in a venv:

```shell
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install --upgrade pip
$ pip install pendulum==2.1.1
$ pip install pyatv --upgrade-strategy only-if-needed
```
Any difference with that?

**Comment by graq** [comment]
Unfortunatelly it's not getting better.
So I installed pendulum v2.1.1, upgraded pip to v21.2.1, tried to install pyatv with the upgrade only if needed strategy.
Don't know what happened to pendulum, but the installation exits now with :
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

I tried the --no-binary workaround from https://github.com/custom-components/alexa_media_player/issues/526
without any effort.

Next, I'll try it on a Ubuntu for Pi4 (https://ubuntu.com/download/raspberry-pi/thank-you?version=21.04&architecture=desktop-arm64+raspi) system

**Comment by postlund** [comment]
That's a bummer, not sure what to do 😕Hopefully a later base OS can help. I've also considered providing docker images for pyatv, making it simple to run that way. But I haven't come around looking at that yet.

**Comment by postlund** [comment]
I have switched from `audio-metadata` to `mediafile` on master, so pendulum is not a dependency anymore. Can you try installing from master instead and verify if it works? It will be part of next release.

**Comment by bytedealer** [comment]
Hi @postlund,

I can confirm the problems of @graq. And I tried your solutions just a few seconds ago. Hope, I dit it the right way with: 
`pip3 install --upgrade git+https://github.com/postlund/pyatv.git`

I got this error:
`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/postlund/pyatv.git
  Cloning https://github.com/postlund/pyatv.git to /tmp/pip-req-build-sq01ok5b
  Running command git clone -q https://github.com/postlund/pyatv.git /tmp/pip-req-build-sq01ok5b
  Resolved https://github.com/postlund/pyatv.git to commit 2495e56c59506562ff3ce800cd51f68dcd713c3c
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting bitarray>=2.1.2
  Using cached https://www.piwheels.org/simple/bitarray/bitarray-2.3.2-cp37-cp37m-linux_armv7l.whl (176 kB)
Collecting aiohttp<5,>=3.1.0
  Using cached https://www.piwheels.org/simple/aiohttp/aiohttp-3.7.4.post0-cp37-cp37m-linux_armv7l.whl (1.3 MB)
Collecting mediafile>=0.8.0
  Using cached https://www.piwheels.org/simple/mediafile/mediafile-0.8.0-py3-none-any.whl (21 kB)
Collecting zeroconf>=0.28.2
  Using cached https://www.piwheels.org/simple/zeroconf/zeroconf-0.36.2-py3-none-any.whl (93 kB)
Collecting protobuf<4,>=3.17.3
  Using cached https://www.piwheels.org/simple/protobuf/protobuf-3.17.3-py2.py3-none-any.whl (173 kB)
Collecting netifaces>=0.10.0
  Using cached https://www.piwheels.org/simple/netifaces/netifaces-0.11.0-cp37-cp37m-linux_armv7l.whl (39 kB)
Collecting cryptography>=2.6
  Using cached https://www.piwheels.org/simple/cryptography/cryptography-3.4.8-cp37-cp37m-linux_armv7l.whl (1.5 MB)
Collecting miniaudio>=1.44
  Using cached https://www.piwheels.org/simple/miniaudio/miniaudio-1.44-cp37-cp37m-linux_armv7l.whl (455 kB)
Collecting srptools>=0.2.0
  Using cached https://www.piwheels.org/simple/srptools/srptools-1.0.1-py2.py3-none-any.whl (13 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached https://www.piwheels.org/simple/async-timeout/async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting chardet<5.0,>=2.0
  Using cached https://www.piwheels.org/simple/chardet/chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0.tar.gz (53 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting attrs>=17.3.0
  Using cached https://www.piwheels.org/simple/attrs/attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting yarl<2.0,>=1.0
  Using cached https://www.piwheels.org/simple/yarl/yarl-1.6.3-cp37-cp37m-linux_armv7l.whl (262 kB)
Collecting typing-extensions>=3.6.5
  Using cached https://www.piwheels.org/simple/typing-extensions/typing_extensions-3.10.0.2-py3-none-any.whl (27 kB)
Collecting cffi>=1.12
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.14.6-cp37-cp37m-linux_armv7l.whl (346 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting six>=1.9
  Using cached https://www.piwheels.org/simple/six/six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting mutagen>=1.45
  Using cached https://www.piwheels.org/simple/mutagen/mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting idna>=2.0
  Using cached https://www.piwheels.org/simple/idna/idna-3.2-py3-none-any.whl (59 kB)
Collecting ifaddr>=0.1.7
  Using cached https://www.piwheels.org/simple/ifaddr/ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: pyatv, multidict
  Building wheel for pyatv (PEP 517) ... done
  Created wheel for pyatv: filename=pyatv-0.8.2-py3-none-any.whl size=404019 sha256=d3db87b359a7311fd7a5f8def141383969c9c044a9db63cec12d757627b4c5d0
  Stored in directory: /tmp/pip-ephem-wheel-cache-lubleqtj/wheels/6e/24/d1/1abdaa959d7652be40ead5d1ebbfea1afd85999d46397138e5
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/pyatv_venv/bin/python /home/pi/pyatv_venv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmplw8hk_21
       cwd: /tmp/pip-install-ogovxr45/multidict_61a5f972e461439598c59926761fcb07
  Complete output (48 lines):
  *********************
  * Accelerated build *
  *********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  creating build/lib.linux-armv7l-3.7/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/_compat.py -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/_abc.py -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/__init__.py -> build/lib.linux-armv7l-3.7/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  adding license file 'LICENSE'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/_multidict.c -> build/lib.linux-armv7l-3.7/multidict
  copying multidict/py.typed -> build/lib.linux-armv7l-3.7/multidict
  creating build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-armv7l-3.7/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-armv7l-3.7
  creating build/temp.linux-armv7l-3.7/multidict
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/pyatv_venv/include -I/usr/include/python3.7m -c multidict/_multidict.c -o build/temp.linux-armv7l-3.7/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  multidict/_multidict.c:1:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for multidict
Successfully built pyatv
Failed to build multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly`

**Comment by bytedealer** [comment]
Hi @postlund,

and a docker image would be very great! ;-)

Bye and thanks for your cool solution!!!
bytedealer

**Comment by postlund** [comment]
@bytedealer Looks ok to me but you need to install the python development files (e.g. `apt install python3-dev`, more about it [here](https://pyatv.dev/documentation/#installing-pyatv)).

I've considered providing container images for pyatv as well, just haven't come around fixing that yet. But I might do that. Will probably just be for releases though.

**Comment by graq** [comment]
Hi,

just came back from holidays. 
Will check it tommorow.

**Comment by bytedealer** [comment]
Hi @postlund,

you were right! And I could successfully install pyatv on last os version of raspberry pi taking the master branch.

Bye and thanks!
bytedealer

**Comment by graq** [comment]
Hi @postlund,

I also can confirm a successful installation on raspberry pi with the master branch.
The scan, turn_on and turn_off commands work so far.

Thanks a lot, great job.

**Comment by postlund** [comment]
Thanks for verifying 👍 Then we can close this.
