### ISSUE TITLE
Running pyatv in Docker

### ISSUE THREAD

**Issue by eXpress48** [postlund/pyatv#1228]
Hi

I'm trying to build a simple PushUpdater which just retrieves the current device state from an Apple TV for further processing. I came up with the following code through various examples/tutorials:

```python
import sys
import asyncio
import pyatv
from pyatv.interface import PushListener

class MyPushListener(PushListener):
    def playstatus_update(self, updater, playstatus):
        print(playstatus.device_state.name)
        # do stuff based on device state...

    def playstatus_error(self, updater, exception):
        print("Got an exception:", exception)

async def main():
    print('Starting the script')
    loop = asyncio.get_event_loop()

    atvs = await pyatv.scan(loop, identifier="AA:BB:CC:DD:EE:FF")
    if not atvs:
        print("No device found", file=sys.stderr)
        return

    atv = await pyatv.connect(atvs[0], loop)
    listener = MyPushListener()
    try:
        atv.push_updater.listener = listener
        atv.push_updater.start()

        print("Press ENTER to quit")
        await loop.run_in_executor(None, sys.stdin.readline)

    except:
        atv.close()

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

The above snippet works without any issue when running under Windows in a cmd. It will output the playstate whenever I press Play/Pause for example.

```
Starting the script
Press ENTER to quit
Paused
Playing
Playing
Paused
Playing
Playing
Paused
Playing
Playing
Paused
Playing
Playing
```

Running the same script in a Docker container, then the main script will constantly get restarted when looking at the container log:

```
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
Press ENTER to quit
Paused
Starting the script
```

My guess is that it is related to the following line which seems to behave differently in docker as no User Input can be made:

```python
await loop.run_in_executor(None, sys.stdin.readline)
```

Any idea how I can modify the script so the PushUpdater basically runs forever until it runs into an error and terminate? If this happens then the script will get restarted by Docker, which then would of course be expected and also needed.

Thanks in advance.

**Comment by postlund** [comment]
Well, a very easy way is to just write an infinite loop with a long sleep in it:

```python
while True:
    await asyncio.sleep(10**6)
```

Not pretty but it works. I'm actually not sure what a best-practice way of just "wait here forever" would be. Maybe block by waiting for a signal?

**Comment by eXpress48** [comment]
Simple as that..

Thanks :)
