### ISSUE TITLE
tvOS 14.7 devices not discovered

### ISSUE THREAD

**Issue by ogiewon** [postlund/pyatv#1242]
@postlund - First, just wanted to say thank you for the time and effort you have spent in creating this integration.  Great work!

Second, I have a question and could not find any similar discussions via searching...so here goes.  I have 4 AppleTV devices in my home, two 1st gen AppleTV-4K devices and two 4th gen AppleTV devices.  Both of the AppleTV 4K devices have been upgraded to tvOS 14.7, while the two other devices are still running tvOS 14.6.  I have been running Home Assistant OS on a Raspberry PI 4 for about 6 months, and it is fully up to date.  I know that previously all 4 AppleTV's used to show up in the Integrations sections as being discovered, but now only the two tvOS 14.6 devices appear.  Today was the first day that I attempted to use the AppleTV integration, and thus was a little surprised to only see half of my devices available.  I attempted to manually add the _missing_ devices via their IP address, but that was unsuccessful as well.

Other possibly useful information...  My home network is a full Ubiquiti UnFi stack, with a single LAN.  Nothing complicated whatsoever, and I did restart all of my network switches and access points just to make sure there wasn't something screwed up with one of those devices.  The AppleTV's are all using hardwired Ethernet connections, not WiFi, and are 'pingable' on the network.  The HassOS RPi is also hardwired.

My hypothesis is that something changed in tvOS 14.7, but I am not seeing any other issues regarding this.  I do see plenty of tvOS 15 issues being discussed, though.

Any thoughts?

Again, I really appreciate what you have created!

**Comment by postlund** [comment]
Thanks for the kind words and the report 😊 You might be experiencing the same thing a few other people have, which is solved in 0.8.2 and also bumped into next version of home assistant. I suggest that you either wait for that version, try dev or install pyatv and run `atvremote scan` and verify if all your devices are discovered.

**Comment by ogiewon** [comment]
Thank you for the quick reply.  I will patiently wait for the next version of Home Assistant, which I am guessing should be available within the next week.
