### ISSUE TITLE
Error while trying to pair with HomePod mini 14.7 via raop

### ISSUE THREAD

**Issue by 00Snider** [postlund/pyatv#1243]
Hello,

i am using home assistant on a pi and try to implement my Home Pod mini. My goal is to use the TTS with my HomePod. I already found the issue https://github.com/postlund/pyatv/issues/917 and i am following it. 

I can pair my HomePod via airplay.

Now i tried to pair my HomePod mini via raop:

$ atvremote --id abc --protocol raop pair

But there is the following Error message:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 698, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 481, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 664, in _exec_command
    value = await tmp(*args)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/scripts/atvremote.py", line 171, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/usr/local/lib/python3.7/dist-packages/pyatv/__init__.py", line 124, in pair
    raise RuntimeError(f"missing implementation for {protocol}")
RuntimeError: missing implementation for Protocol.RAOP`

Thanks for your help.

**Comment by postlund** [comment]
It's not supported to pair RAOP as it's not needed. Just skip that step.

**Comment by 00Snider** [comment]
Ah. Thanks! I can get some information from my HomePod like the version or features.

Feature list:
-------------
VolumeUp: Available
VolumeDown: Available
Title: Unavailable
Artist: Unavailable
Album: Unavailable
TotalTime: Unavailable
Position: Unavailable
PushUpdates: Available
PlayUrl: Unavailable
StreamFile: Available
Volume: Available
SetVolume: Available

Do you have a simple command to test, if the HomePod responds to commands at all? The following commands seem to have no effect:

$ atvremote --id abc --protocol raop volume_up
$ atvremote --id abc --protocol raop set_volume=50

Thanks again.

**Comment by postlund** [comment]
Best way to test is to use `stream_file`, as that is currently the only method sending any requests to the device (except for volume controls). The problem you are facing however is that you are trying to execute remote control commands w

**Comment by 00Snider** [comment]
Thanks a lot for your answer!
