### ISSUE TITLE
Illegal instruction on executing atvscript scan

### ISSUE THREAD

**Issue by sklever** [postlund/pyatv#1249]
Hi @postlund 

using a fresh image from [https://www.raspberrypi.org/software/operating-systems/], (https://www.raspberrypi.org/software/operating-systems/) with Python 3.7.3 installed.

When executing `atvscript scan` it's saying:
`Illegal instruction`

When using `sudo atvscript scan` it's saying:
```
File "/usr/bin/atvscript", line 5, in <module>
    from pyatv.scripts.atvscript import main
ModuleNotFoundError: No module named 'pyatv'
```

How to solve this?
Same happens when executing `atvremote`

Your support is much appreciated.
Many thanks.
Regards
Simon

**Comment by postlund** [comment]
A similar issue has been reported to Home Assistant core as well here: https://github.com/home-assistant/core/issues/54098. It sounds reasonable that it has to do with miniaudio. Maybe we should double check that first perhaps? Can you try running:

    python3 -c 'import miniaudio'

Illegal instruction?

**Comment by sklever** [comment]
When executing `python3 -c 'import miniaudio' `  it‘s also saying `illegal instruction`

**Comment by postlund** [comment]
Good, then we have isolated it to miniaudio at least. Please try uninstalling miniaudio:

    pip uninstall miniaudio

Then installing from source:

    pip install --no-binary :all: miniaudio

You might need some additional system packages, but we'll notice that later.

**Comment by sklever** [comment]
Many thanks. That really helped. Now I can execute atvscript scan and what’s playing 
☺️👍🏻
Next step is to get this included into node-red. 😉
This one can be closed now

**Comment by postlund** [comment]
Great that it worked, it was a long shot from my end 😉 Best of luck with your project! I have opened a PR to add this workaround to the FAQ for the future (#1250).
