### ISSUE TITLE
Detecting AppleTV PowerState for Home Assistant automation

### ISSUE THREAD

**Issue by VoiceOfSoftware** [postlund/pyatv#1264]
Thank you so much for your hard work -- pyatv works great from command line, and I am getting very reliable info about the power state of my AppleTV.

Question: where would I look in the source code to add a feature to Home Assistant that would detect changes to power state, to help with automation? I am a coder, but unfortunately do not know Python or the HA plugin model, but I'm willing to learn.

**Comment by postlund** [comment]
I suggest you try this: https://github.com/home-assistant/core/pull/51520

**Comment by postlund** [comment]
The PR was merged a while back and part of the beta component. I will close this now, please open new issue with more specific problems to how this works if things are not working as expected.
