### ISSUE TITLE
pairing lost after AppleTV reboot.

### ISSUE THREAD

**Issue by vandalon** [postlund/pyatv#127]
Not sure if this is something that can be fixed within pyatv. When I pair my atvremote with my atv all works fine until I reboot the atv. The pairing is just gone.

**Comment by postlund** [comment]
Thad’s strange, the pairing should be stored in the ATV. I haven’t tried it on my 4K but it worked fine on my ATV3. Scan you see the remote (called “pyatv” unless you changed it) in the Remote menu? Do you use the same login id after reboot?

**Comment by postlund** [comment]
Or are you talking about “auth”, I.e. airplay credentials?

**Comment by vandalon** [comment]
> Op 1 dec. 2017, om 10:41 heeft Pierre Ståhl <notifications@github.com> het volgende geschreven:
> 
> Thad’s strange, the pairing should be stored in the ATV. I haven’t tried it on my 4K but it worked fine on my ATV3. Scan you see the remote (called “pyatv” unless you changed it) in the Remote menu? Do you use the same login id after reboot?

I see the pyatv remote in the remote menu after paring, after reboot it’s gone. I keep using the same ID.

**Comment by vandalon** [comment]
Even without reboot, after a while the remote is just gone from the remotes list. Very strange.

**Comment by postlund** [comment]
Is this behavior still present with latest tvOS version?

**Comment by vandalon** [comment]
Yes, (sorry for the late reaction). latest tvOS still loses the pairing after reboot.

**Comment by robbiet480** [comment]
[Possibly related](https://www.reddit.com/r/homeassistant/comments/940rrt/apple_tv_4/)?

**Comment by postlund** [comment]
@vandalon I believe this is fixed in #161, please try it out if you can. Or if you can try it @robbiet480, that is fine too 😉

**Comment by postlund** [comment]
Fixed by #161 as confirmed by @crxporter.
