### ISSUE TITLE
Start playlist with command?

### ISSUE THREAD

**Issue by jsve** [postlund/pyatv#128]
Not really an issue, but more of a question / improvement suggestion.

Looking at your script, it doesn't seem possible, but do you know of a way to start a playlist, either by name or by ID or similar, without stepping throught the menues of the Apple TV?

**Comment by postlund** [comment]
Hmm, not sure. Are you referring to a playlist accessed via home sharing?

**Comment by postlund** [comment]
Any update on this?

**Comment by postlund** [comment]
No response, closing.
