### ISSUE TITLE
New Apple TV beta integration is missing version in the manifest

### ISSUE THREAD

**Issue by coolguymatt** [postlund/pyatv#1334]
### Describe the bug

New Apple TV beta integration is missing the version in the manifest and will not load as a result.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Install the beta integration.

### What is expected behavior?

The integration loads

### Operating System

Hass OS

### Python

3.9

### pyatv

0.9.1

### Device

Apple TV 4K

### Additional context

New Apple TV beta integration is missing version in the manifest

**Comment by postlund** [comment]
Ah, yes. I have added it now. Let me know if it works!

**Comment by coolguymatt** [comment]
I added it manually before and it worked perfectly. Thanks so much.

**Comment by postlund** [comment]
Great, thanks for testing! 👍

**Comment by coolguymatt** [comment]
Same thing with the new beta.
