### ISSUE TITLE
Yamaha Reciever support

### ISSUE THREAD

**Issue by devrosx** [postlund/pyatv#134]
Hello, tried to test with Yamaha recivers JTR-4066 (with airplay support)
from macosx works without problem

with Pyatv: no device found
here is Bonjour info
`AirTunos (,raop._tcp.) - 1
 OOAODEAZAA 1 C@JTR-4066

192.116.8.3.11:1025
txtvors=1
ch=2
cn=0,1
da=true
ot=0,4
ft=ox44FOAo0
md=0,2
pw=false
sv=false
sr=44100
88:16
tp=UDP
vn=65537
vs=141.9
am=HTR~4066
fv=59239.1034.0`

any idea if this device could work with this library

**Comment by postlund** [comment]
That's a different part of AirPlay only dealing with audio. This question has been up before (but with AirPort express) and I decided that this is out of scope for this library (it's not related to Apple TV). More information about the protocol here:

https://git.zx2c4.com/Airtunes2/about/

I believe there are other libraries that can do what you want.

**Comment by postlund** [comment]
RAOP is out of scope for pyatv, so I close this issue.
