### ISSUE TITLE
Devices cannot be added (already configured)

### ISSUE THREAD

**Issue by medivb** [postlund/pyatv#1354]
### Describe the bug

I have removed the devices and repository completely before updating my devices to tvos15. Now, after re-installing the repository in HACS (and restarting hass), I am unable to add my devices. They are not listed as detected, but when trying to add them manually, they come back as “Device is already configured “. Is there a way to clear them more thoroughly?

### Error log

```log
<place log here>
```

### How to reproduce the bug?

See above

### What is expected behavior?

I should be able to re-add my devices from scratch after removing them completely.

### Operating System

Hassio 5.10.62

### Python

3.9

### pyatv

ca2cd5e

### Device

Apple TV 4K tvos 15

### Additional context

None

**Comment by postlund** [comment]
That shouldn't happen, no. Did you verify that they were not present in `.storage/core.config_entries`, just to be sure?

At which step do you get the error message and what devices are you adding?

**Comment by medivb** [comment]
I had removed my devices as per your advise (using integrations panel in hass) before installing the previous tvos15 - capable version you released. Then installed the update, saw the apple tv’s (I have 4 in total) being detected and tried to configure them. This failed on several protocols and the devices were detected multiple times (as well as my airplay2 compatible bose devices by the way) and I decided to wait for an update from you when I saw similar issues being reported by others. Removed all devices and even the whole repository (just to be sure) to start with a clean slate. Unfortunately now I don’t see detected devices anymore nore can I add them manually (device already configured-message). I was not aware of that core.config, so will check that…

**Comment by postlund** [comment]
Ok, that sounds a bit peculiar. You mean that the devices are not auto-discovered in the latest update of the component? Should I interpret that as you get "Already configured" after the first step, I.e. when you enter an IP address or device name and press submit?

**Comment by medivb** [comment]
Yes, that is correct.

**Comment by postlund** [comment]
That means there are config entries left in the mentioned file for some reason. Did you check the log? Because one reason this would happen is if the config entry is loaded but the setup fails when doing so.

**Comment by medivb** [comment]
This is what I see in the log after restarting:

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:111 
Integration: Apple TV 
First occurred: 11:38:37 (4 occurrences) 
Last logged: 11:38:41

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_zeroconf
    return await self.async_find_device_wrapper(self.async_found_zeroconf_device)
  File "/config/custom_components/apple_tv/config_flow.py", line 203, in async_find_device_wrapper
    return await next_func()
  File "/config/custom_components/apple_tv/config_flow.py", line 181, in async_found_zeroconf_device
    await self.async_set_unique_id(self.device_identifier)
  File "/config/custom_components/apple_tv/config_flow.py", line 111, in device_identifier
    if self.atv.identifier in entry.data[CONF_IDENTIFIERS]:
KeyError: 'identifiers'

I'm not able to find .storage/core.config_entries. I guess that might be where the issue is and the old devices somehow still reside...

Thanks so much!

**Comment by medivb** [comment]
Update: I was able to find the .storage/core.config_entries file and indeed the devices were still present in that. When removing them there and a restart I was prompted about the detected devices. First Apple TV was added flawless, second and third one failed on one of the protocols causing the adding to fail and not being able to restart the pairing.

I guess the original issue can be closed, although it is not clear to me how the devices could have ended up in this state. 

Thanks for your help and looking forward to the next update(s)!

**Comment by postlund** [comment]
They was my best guess as well. I added a new field in the config entry, which is mandatory. The praxis is to write code that assumes the field is there in such a case, but that becomes a problem when it's not. Normally one can bump version number and write a migrator, but I'm not gonna bother too much about that in the beta component. But great that it works now! 👍

If you can't find any already open issues for your other problems, feel free to open new ones.
