### ISSUE TITLE
What is the cleanest way to detect a change in playing state?

### ISSUE THREAD

**Issue by Mizuna737** [postlund/pyatv#1355]
### What's on your mind?

I'm trying to detect a change of states and use it to change lighting through homebridge. This works, but it's clunky:
```
while(True):
     atvs = await scan(loop)
     atv = atvs[0]
     atv.set_credentials(Protocol.AirPlay, 'XXXXXXX')
     livingRoom = await connect(atv, loop)
     playing = str(await livingRoom.metadata.playing())
     #Use playing with regex
     livingRoom.close()
```

I tried looping only the last step and leaving the connection opened, but the state didn't actually update with metadata.playing(). I also tried to loop just the connection through the close, but it errors out. I think I'm probably missing something obvious here. I looked into listeners but as far as I can tell they don't support the AirPlay protocol, and I'll admit they're a bit above my head.

**Comment by postlund** [comment]
Generally you shouldn't look at the string output as you have properties for everything. You have the reference here:

https://pyatv.dev/api/interface#pyatv.interface.Playing

If you want to check for instance device state, you should do something like this:

```python
from pyatv.const import DeviceState
playing = await livingRoom.metadata.playing()
if playing.device_state == DeviceState.Playing:
    # do something 
else:
    # do something else
```
You have other properties for album, title and so on, depending on what you need.

Polling like this should work fine:

```python
 atvs = await scan(loop)
 atv = atvs[0]
 atv.set_credentials(Protocol.AirPlay, 'XXXXXXX')
 livingRoom = await connect(atv, loop)

 while True:
    playing = await livingRoom.metadata.playing()

    # do something 

    # sleep a while
    await asyncio.sleep(1)

livingRoom.close()
```
But I recommend that you look at push updates instead. You have an example here:

https://github.com/postlund/pyatv/blob/master/examples/stream.py

And some documentation:

https://pyatv.dev/development/listeners/#push-updates

**Comment by Mizuna737** [comment]
Ah, so push updates will work with Airplay. That's good news. I'll look in that direction. Thank you for the thorough response!

**Comment by postlund** [comment]
Well... yes and no. AirPort does not support push updates (yet). But since you are interacting with an Apple TV, the MRP protocol will be set up (over AirPlay) which do support push updates. Whatever you play over AirPlay is mirrored over MRP, so you get push updates that way. It will not work with a pure AirPlay device though.
