### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by lorenzoCuevas** [postlund/pyatv#1370]
### What's on your mind?

Hi again, the last time we talk I talked about how I'm trying to create a python script to automatically dim the lights when the movie is playing. Now what I'm trying to do is implementing the python script into homebridge. So I could execute the script in the home app rather than going into cmd line to type it in. My question is that if possible could you recommend some homebridge plugins that would execute python scripts when a home app switch is turned on or ends it when it turns off.

**Comment by postlund** [comment]
Unfortunately no, I have never used Homebridge myself. I barely use HomeKit either, but I have it set up via Home Assistant and that works at least. Maybe they have a community forum?

**Comment by lorenzoCuevas** [comment]
Okay I'll check that out

**Comment by jdebardi** [comment]
Hi, I use this to run scripts which then invoke atvscript 

https://github.com/pponce/homebridge-script2

**Comment by jdebardi** [comment]
I should add, my scripts use pid files to work out state (as is supported by the plugin) so it can call a kill script to turn off.
