### ISSUE TITLE
Function getting crashed while initiating pair request.

### ISSUE THREAD

**Issue by rexterdigivalet** [postlund/pyatv#1375]
### Describe the bug

When I try to scan with command `atvremote scan`. It is working properly and showing the multiple devices.
But when I am trying to pair with my device, or any other device, it is getting crashed. 

![Screenshot from 2021-10-06 11-25-37](https://user-images.githubusercontent.com/92011161/136148084-99e7bb86-085a-49a0-ac1d-b83a4a6f602e.png)

### Error log

```
[root:/home/amoghsaxena/Desktop/tmp]# atvremote --id DC:56:E7:59:79:46 --protocol mrp pair

Traceback (most recent call last):
  File "/home/amoghsaxena/Desktop/tmp/.direnv/python-3.9.5/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 716, in _run_application
    return await cli_handler(loop)
  File "/home/amoghsaxena/Desktop/tmp/.direnv/python-3.9.5/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 504, in cli_handler
    return await _exec_command(glob_cmds, args.command[0], print_result=False)
  File "/home/amoghsaxena/Desktop/tmp/.direnv/python-3.9.5/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 682, in _exec_command
    value = await tmp(*args)
  File "/home/amoghsaxena/Desktop/tmp/.direnv/python-3.9.5/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 175, in pair
    pairing = await pair(conf, self.args.protocol, self.loop, **options)
  File "/home/amoghsaxena/Desktop/tmp/.direnv/python-3.9.5/lib/python3.9/site-packages/pyatv/__init__.py", line 114, in pair
    raise exceptions.NoServiceError(f"no service available for {protocol}")
pyatv.exceptions.NoServiceError: no service available for Protocol.MRP

>>> An error occurred, full stack trace above
```

![Screenshot from 2021-10-05 15-06-15](https://user-images.githubusercontent.com/92011161/136148397-c760e92d-08a7-49cf-a691-74f24c48f75e.png)

### How to reproduce the bug?

```
pip3 install pyatv
atvremote scan
atvremote --id <ID> --protocol mrp pair
```

### What is expected behavior?

```
atvremote --id 00:11:22:33:44:54 --protocol mrp pair
Enter PIN on screen: 1234
Pairing seems to have succeeded, yey!
You may now use these credentials: 1650c36b816812561ee1a2ce55441c4d59aeee8287d3d0b90ad41e221c2ccc9b:eb6d47687f82327501d26e77bc3ee8b752034ad397c80cba37d91132717a1721:61383462633431372d383336362d346464632d386533622d333964356265303932663132:39376263616162332d356330652d343136362d623634302d326438656135616161636237
```

### Operating System

Lunix

### Python

3.9

### pyatv

0.9.2

### Device

Apple TV 4

### Additional context

Please Help.

**Comment by postlund** [comment]
I can't see the output for the particular device you are trying to pair with, but the error means it doesn't support MRP (or the service for it is not found). Can you include the full scan output? Also, if you are running tvOS 15 (or any beta), you shouldn't pair MRP at all as it doesn't work. You only need AirPlay for most functionality. The next version of pyatv will ignore that particular service (MRP) for tvOS 15 devices, just to avoid confusion.

**Comment by postlund** [comment]
As I said, it is expected for MRP and tvOS 15 so just ignore that. Does pairing airplay work?

**Comment by postlund** [comment]
Ok, great! Just pair and pass the credentials you get to `--airplay-credentials`. After that, most actions should work. I don't know what you are trying to do, so I can't give any particular examples.

Remember, if you want app functionality (`launch_app` or `app_list`) you also need to pair Companion and pass those credentials (`--companion-credentials`). Same goes for RAOP, if you want to stream audio with `stream_file` (i.e you need to pair raop and pass credentials with `--raop-credentials`). All in all you need to pair and pass credentials for three protocols for all functionality.

You have some documentation for `atvremote` here:

https://pyatv.dev/documentation/atvremote/

**Comment by rexterdigivalet** [comment]
Thank

> Ok, great! Just pair and pass the credentials you get to `--airplay-credentials`. After that, most actions should work. I don't know what you are trying to do, so I can't give any particular examples.
> 
> Remember, if you want app functionality (`launch_app` or `app_list`) you also need to pair Companion and pass those credentials (`--companion-credentials`). Same goes for RAOP, if you want to stream audio with `stream_file` (i.e you need to pair raop and pass credentials with `--raop-credentials`). All in all you need to pair and pass credentials for three protocols for all functionality.
> 
> You have some documentation for `atvremote` here:
> 
> https://pyatv.dev/documentation/atvremote/

Thank you so much for your help. It is really a great feature. 

and also one small doubt...
Is there any way to control Apple TV with tvOS 15 ?
Like i want to control it like apple tv remote but with the computer. [ like moving up down etc. ]

**Comment by postlund** [comment]
tvOS 15 will work as long as you include AirPlay credentials. MRP is tunneled over AirPlay in tvOS 15.

**Comment by rexterdigivalet** [comment]
Thank you so much, Sir!

**Comment by rexterdigivalet** [comment]
Did the Support for tvOS15 is available now ?
