### ISSUE TITLE
Apple TV state behaviour is not updated correctly when using Netflix (and possibly other apps)

### ISSUE THREAD

**Issue by aleszczynskig** [postlund/pyatv#1378]
### Describe the bug

The status (paused, idle, playing) in HA remains on paused when using Netflix regardless of the playback status. Interestingly when on the menu selection screen, if a video plays in the background, this state does reflect in HA correctly.

I have not validated all of my apps, but the state is reflected correctly in other apps. I tested with Infuse 7.2.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Start playback in Netflix and use the developer tools in HA to view the state of the paired Apple TV.

### What is expected behavior?

The state should correctly reflect the playback status (playing, paused, idle) etc.

### Operating System

Linux (HA container)

### Python

3.9

### pyatv

Beta

### Device

Apple TV OS 15

### Additional context

Nothing to add

**Comment by aleszczynskig** [comment]
I've just discovered that after I select my HomePods to output audio too (they are not in a stereo pair), this functionality springs to life. If I unselect the HomePods as output devices, it continues to work even after a restart. Incidentally I have the HomePods paired with HA as well though when I paired both my AppleTV and the HomePods I got a message that the companion link pairing failed - I am not sure what the significance of this is or whether it means my setup is broken.

**Comment by aleszczynskig** [comment]
Regarding the pairing ...

The issue presented when pairing with both the Apple TV and the HomePods. The message is as follows

Pairing not possible
Pairing is required for Companion but it is disabled on the device. Please review potential access restrictions (e.g. allow all devices on the local network to connect) on the device.

You may continue without pairing this protocol, but some functionality will be limited.

**Comment by postlund** [comment]
Ok, you need to make sure access setting for AirPlay is se to "all on the same network" and no password.

**Comment by aleszczynskig** [comment]
Thanks - the pairing has worked correctly now.

I have run the commands as you requested above, the logs are attached. Was I supposed to do something while running this command? It just output to the log but nothing happened on the Apple TV.

Despite unpairing my Apple TV from HA and re-adding it, the functionality is now working correctly. I am not sure how to reproduce i
[playing.log](https://github.com/postlund/pyatv/files/7307169/playing.log)
t.

**Comment by postlund** [comment]
Ok, then I can't draw any conclusions from it. I need logs when there's a mismatch. Just let me know when you have some logs and I'll most certainly take a look!
