### ISSUE TITLE
Open App on Apple TV

### ISSUE THREAD

**Issue by maddox** [postlund/pyatv#1387]
### What's on your mind?

Are there any plans to offer Open `App` on `Apple TV` as a service to the HASS component?

It's very helpful in shortcuts vs using remote commands. It's also helpful at dismissing the screensaver. 

 I saw that the protocol that enables this was implemented. I'm just hoping it makes it to the component vs just staying in the lib.

**Comment by postlund** [comment]
Initial support for launching apps just landed in the beta component repo, feel free to try it out and let me know how it works. You need Home Assistant 2021.12.0 beta to run it though (out on saturday).

**Comment by maddox** [comment]
👍

**Comment by postlund** [comment]
Support was merged to core yesterday, so it will be in the next Home Assistant release.
