### ISSUE TITLE
Connection fails to gen 3 Apple TV

### ISSUE THREAD

**Issue by sergem155** [postlund/pyatv#1418]
### Describe the bug

Same routine that connects to gen 4 successfully, fails with exception on gen 3. (Using gen 3 because it has optical output)

### Error log

exception:

```Discovering devices on network...
       Name: Big Stereo
   Model/SW: Apple TV 3, ATV SW 8.4.4
    Address: 192.168.1.176
        MAC: B8:78:2E:4C:CB:EB
 Deep Sleep: False
Identifiers:
 - B8:78:2E:4C:CB:EB
 - 61FBE455BD6E3BF2
 - B8782E4CCBEB
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: DMAP, Port: 3689, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
Connecting to 192.168.1.176
Traceback (most recent call last):
  File "./avt_tracker.py", line 98, in <module>
    sys.exit(loop.run_until_complete(what_is_playing(loop)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./avt_tracker.py", line 72, in what_is_playing
    atv = await pyatv.connect(atvs[0], loop)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/__init__.py", line 101, in connect
    await atv.connect()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/core/facade.py", line 470, in connect
    if await setup_data.connect():
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/dmap/__init__.py", line 674, in _connect
    await requester.login()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/dmap/daap.py", line 99, in login
    resp = await self._do(_login_request, is_login=True)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/dmap/daap.py", line 130, in _do
    resp, status = await action()
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/dmap/daap.py", line 92, in _login_request
    url = self._mkurl("login?[AUTH]&hasFP=1", session=False, login_id=True)
  File "/usr/local/lib/python3.8/dist-packages/pyatv/protocols/dmap/daap.py", line 157, in _mkurl
    if re.match(r"0x[0-9A-Fa-f]{16}", self._login_id):
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

```
log:
```
2021-10-22 18:59:35 DEBUG [pyatv.support.net]: Binding on *:5353
2021-10-22 18:59:35 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-10-22 18:59:35 DEBUG [pyatv.support.net]: Binding on 192.168.1.171:0
2021-10-22 18:59:35 DEBUG [pyatv.core.scan]: Auto-discovered Big Stereo at 192.168.1.176:7000 via Protocol.AirPlay ({'deviceid'
: 'B8:78:2E:4C:CB:EB', 'features': '0x5A7FFFF7,0x1E', 'flags': '0x44', 'model': 'AppleTV3,2', 'pk': '9e456060d821f737ba5253187a
b2460196a86b05e8ef2b041b074aa301c9f81f', 'pi': 'a3dd25ff-59c1-4f59-a813-c682b278bf77', 'srcvers': '220.68', 'osvers': '8.4.4', 
'vv': '2'})
2021-10-22 18:59:35 DEBUG [pyatv.core.scan]: Auto-discovered 61FBE455BD6E3BF2 at 192.168.1.176:3689 via Protocol.DMAP ({'txtver
s': '1', 'atsv': '65541', 'dbid': 'A9C932FA987B8650', 'ctln': 'Big Stereo', 'dvty': 'AppleTV', 'dvsv': '1792', 'atcv': '65539',
 'ver': '131077'})
2021-10-22 18:59:35 DEBUG [pyatv.core.scan]: Auto-discovered B8782E4CCBEB@Big Stereo at 192.168.1.176:7000 via Protocol.RAOP ({
'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x5A7FFFF7,0x1E', 'md': '0,1,2', 'am': 'AppleTV3,2', 'pk': '9e456060d821f7
37ba5253187ab2460196a86b05e8ef2b041b074aa301c9f81f', 'sf': '0x44', 'tp': 'UDP', 'vn': '65537', 'vs': '220.68', 'ov': '8.4.4', '
vv': '2'})
2021-10-22 18:59:35 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.AirPlay
2021-10-22 18:59:35 DEBUG [pyatv.protocols.airplay]: Remote control not supported by device
2021-10-22 18:59:35 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.DMAP
2021-10-22 18:59:35 DEBUG [pyatv.core.facade]: Adding handler for protocol Protocol.RAOP
2021-10-22 18:59:35 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.AirPlay
2021-10-22 18:59:35 DEBUG [pyatv.core.facade]: Connecting to protocol: Protocol.DMAP
```

### How to reproduce the bug?

obtain airplay credentials with atvremote -s <addr> --protocol airplay pair
try to connect from python code
```
	atvs = await pyatv.scan(loop, identifier="B8:78:2E:4C:CB:EB", timeout=3)
	if not atvs:
		print('No device found', file=sys.stderr)
		return
	print(atvs[0])
	print('Connecting to {0}'.format(atvs[0].address))
	atvs[0].set_credentials(Protocol.AirPlay, ":08dd1ca9a681fe9807fdd16144133d37341e0b2f21c70959350d957611245eab::88b920edab78bc3d")
	atv = await pyatv.connect(atvs[0], loop)
```

### What is expected behavior?

connection without exceptions

### Operating System

Ubuntu 20.04

### Python

3.8

### pyatv

0.9.5

### Device

Apple TV 3rd gen

### Additional context

just trying to get start/stop playing events to turn my stereo power on and off

**Comment by sergem155** [comment]
Worked fine when I specified both DMAP and Airplay credentials. OK to close the issue from my side.

**Comment by postlund** [comment]
> This is what I ended up with. When you said yesterday that I didnt really need to create a service I could just use what is found during the scan it didnt initially make sense, but it does more so now. You can see below I dont even add the AirPlay service at all. Im honestly not entirely sure even adding the credentials is necessary. Without the creds though, you receive those generic errors "x command is not supported". Its mostly just scan then connect, add creds, and you are good to go.

Using what you get from `pyatv.scan` is absolutely what I recommend. It's the safest and easiest approach. I added an example for how to quite easily restore credentials here:

https://github.com/postlund/pyatv/blob/master/examples/connect_with_credentials.py

AirPlay credentials are needed if you want to stream something or use the "remote control" support required by tvOS 15. If you don't include credentials, AirPlay will still be set up but the only functionality you get is `play_url` and it will only work with older devices (Apple TV 3 and earlier) assuming device verification is turned off.

Whenever you get "x command is not supported", that means that no protocol you have added implements that functionality. When you call a function in the API, e.g. `RemoteControl.left`, pyatv will look at all the protocols you have added via the config and pick the most appropriate one and use that.

> The most annoying part of all this, and it has nothing to do with pyatv is trying to detect when to send select vs play\pause. Also when you double tap the home button really quickly on the remote you can browse through your open apps, there isnt a way to emulate this, not even atvremote exe has this feature. So I tried to rapidly queue two of the home commands back to back. Sometimes it works, sometimes it doesnt, but there isnt really a great way to solve for that I feel. Due to the event loop the commands run back to back, just sometimes not fast enough to trigger the open app selection.

You can use the features interface to get an idea of whether a particular function is supported or not:

https://pyatv.dev/development/features/

pyatv supports a few different input actions (e.g. double tap or "hold") for some buttons, so you can most definitely do that natively. It's documented here:

https://pyatv.dev/development/control/#input-actions

You can simulate it with atvremote as well:

    atvremote -s <ip> ... home=1

You can use 0 for single tap, 1 for double tap and 2 for hold (as defined here: https://github.com/postlund/pyatv/blob/master/pyatv/const.py#L174)

> Is there any down side to staying connected and not closing the connection?

Not really, that is how I recommend that you implement it.

> My vision for this would be more so like, have a function that builds the objects \ auths you. And a separate function that is strictly for sending the commands through. Once I am connected I wouldnt really want to disconnect per say. I feel like what I am doing below still wastes a lot of time, its faster than the remote app is but still not as fast as I think it likely can be. When I sent through a remote command it has to scan, loop, build objects, authenticate, and then finally send to where its supposed to go, then it closes, and the next command I send through all that has to happen again.

That's what I recommend as well. Basically scan, insert credentials and connect. Then keep the connection open. Use a device listener to get feedback if the connection is lost so you can re-connect.

https://pyatv.dev/development/listeners/#device-updates

**Comment by postlund** [comment]
The discussion is however unrelated to the initial issue, so feel free to open a new issue with any further questions you have. I will close this issue now.
