### ISSUE TITLE
Youtube app entity_picture

### ISSUE THREAD

**Issue by matt8707** [postlund/pyatv#1420]
### What feature would you like?

Youtube entity_picture in home assistant, if not at least video id

### Describe the solution you'd like

If the app exposes the video id or from stream url, as a home assistant attribute?

### Any other information to share?

As a workaround I tried the youtube api using `media_title` and `media_artist` but fairly quickly hit the api quota

**Comment by postlund** [comment]
I believe we have concluded that YouTube does not set the content identifier. If they did, it would be accessible.
