### ISSUE TITLE
Are you using the Home Assistant integration for TTS? Look at this!

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1435]
### What's on your mind?

To support TTS in the Apple TV (beta) integration I have made a hack. This hack will never make it into core, a proper implementation is needed and as soon as the integration uplift is made back to core my hack will be removed, thus removing TTS support with AirPlay receivers and HomePods.

Adding proper support requires some minor architectural changes that I can't manage on my own, but need help from core developers. In order for that to happen, interest in the features must be displayed.

**If you use (or care) for TTS support in the Apple TV integration, please upvote and make some noise the discussion linked below. Otherwise the support will be dropped! Tell your friends!**

https://github.com/home-assistant/architecture/discussions/576

**Comment by postlund** [comment]
Thanks everyone for voting on this! 👍 I still believe support for this is motivated, but as pyatv supports streaming from HTTP(S) now, TTS will work without the need for this. I will close this issue but leave the discussion in architecture open.

**Comment by adriaanvanrossum** [comment]
Thanks for all the great work, Pierre!

Will the above comment mean that in Home Assistant we can use the service `media_player.play_media`?

Let's say we have this config:
- `Content ID` = `https://tts.adriaan.workers.dev/?text=Some%20text%20that%20is%20converted%20to%20voice` 
- `Content type` = `music`

<kbd><img width="1072" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/145493587-f31df342-f531-4078-abb5-82b77ae1bb1d.png"></kbd>

If so, that would be amazing!

**Comment by postlund** [comment]
@adriaanvanrossum That is correct. It should work with hass-atv-beta right now, assuming you run Home Assistant 2021.12.0 beta.

**Comment by adriaanvanrossum** [comment]
Ah cool, I'm running 2021.11, but will download it as soon as it becomes available! Thanks.
