### ISSUE TITLE
Migration error on v1.9.0

### ISSUE THREAD

**Issue by Stuke00** [postlund/pyatv#1448]
### Describe the bug

Just upgraded to 1.9.0 and the integration is not loading

### Error log

```log
Logger: homeassistant.config_entries
Source: config_entries.py:511
First occurred: 7:04:14 PM (1 occurrences)
Last logged: 7:04:14 PM

Migration handler not found for entry Living Room Apple TV 4K for apple_tv
```

### How to reproduce the bug?

Install v 1.9.0

### What is expected behavior?

Expecting the integration to load

### Operating System

Home Assistant Operating System

### Python

Other

### pyatv

1.9.0

### Device

Apple TV 4K 2nd Generation

### Additional context

Just updated to v1.9.0, running HA 11.0

**Comment by postlund** [comment]
Yes, as described in the release notes you need to remove and add the devices again (for the last time).
