### ISSUE TITLE
Keyboard characters for Search

### ISSUE THREAD

**Issue by MarcoMerconi** [postlund/pyatv#145]
Thanks for all the hard work!

Is it possible to post characters/digits from the atvremote application or the library?

With a bluetooth keyboard, or using the Apple TV remote app, keystrokes can be sent for search or when an input field is available.  It would be fantastic to be able to post keystrokes (characters/digits) in some way.

I am a senior dev (new to python), so if there's any way I can help with pyatv, don't hesitate to let me know.

**Comment by postlund** [comment]
Thanks, hope you find it useful 😄 

Currently no, there is no support for keyboards in pyatv. I haven't had any priority in implementing this as I haven't had much use for it myself, but I would love to have support for it. So if you would like to take a crack at it, that would be very helpful!

My suggestion is to start with the DMAP implementation and add support in the master branch. There are lots of changes compared to the stable versions (0.3.x) code-wise, so it's best to stay on master. Figuring out how it works can probably be done blackbox as DMAP is not encrypted in any way. The tricky part is that you cannot directly do that on a device running tvOS (ATV 4 or 4K) as the remote app will default to use the Media Remote Protocol (MRP) instead. So the easiest way is to use a older device, like ATV3. If you don't have one laying around, it should be possible to spoof a DMAP device. More or less write a script that uses Zeroconf to broadcast a `_appletv-v2._tcp.local.` service. You can look at what your own device says with some bonjour browser (I usually use iNet on my phone) and replicate that. Just change the name and put the IP-address to your Apple TV and then try to connect to it using the Remote app.

Once you have a connection, sniff the traffic with Wireshark and just navigate to a search box and type some characters. Wireshark already has support for DMAP but it doesn't support all tags. So you will manually have to look at the payload and try to figure out what is happening. Some tags you can google, others you will have to guess what they are and some you will not know. You can read more about the protocol here: https://pyatv.readthedocs.io/en/master/protocol.html

If you can define URLs that are used as well as the payload, that would be a great start before digging into the pyatv implementation 👍

**Comment by masikh** [comment]
Question: I am also digging into this issue. Is there any progress to report? Can I somehow help?

**Comment by masikh** [comment]
[wire shark.zip](https://github.com/postlund/pyatv/files/2068002/wire.shark.zip)

**Comment by postlund** [comment]
I have answered your email, you can find more details there! I'll see if I can make a prototype.

**Comment by masikh** [comment]
When I wireshark the communication it gives me wrong tags.

I made a keyboard_tags but unfortunately no success yet. Strange thing is that the dump I get from wireshark now is identical to the ones I made in a working situation??? Odd very odd..

def keyboard_tag(value):
    return 'cmcc'.encode('utf-8') + b'\x00\x00\x00\x01\x39' + \
           'cmbe'.encode('utf-8') + b'\x00\x00\x00\x0c' + \
           'PromptUpdatecmte'.encode('utf-8') + b'\x00\x00\x00' + \
           len(value).to_bytes(1, byteorder='big') + value.encode('utf-8')

This will result in something like:

b'cmcc\x00\x00\x00\x019cmbe\x00\x00\x00\x0cPromptUpdatecmte\x00\x00\x00\x0bHello World'

At least I am sure that the tag being build is ok. I wonder if we need to send all the headers along too? 
Experimenting with it!!

**Comment by masikh** [comment]
![wireshark-dump-ok](https://user-images.githubusercontent.com/773227/41192259-8cb63518-6bfb-11e8-8982-0752a5bcd603.png)
This is a successful communication I captured earlier. As you can see the headers are different from the ones pyatv sends

**Comment by masikh** [comment]
![wireshark-notok](https://user-images.githubusercontent.com/773227/41192296-f280a932-6bfb-11e8-99d5-cffb4036166e.png)
This is a UN-successful communication I captured. As you can see the headers are different from the ones of a successful communication.

**Comment by masikh** [comment]
It seems to me we first need to call this function (daap.py)

....@asyncio.coroutine
.... def get(self, cmd, daap_data=True, timeout=None, **args):
........"""Perform a DAAP GET command."""
........def _get_request():
............return self.http.get_data(
....................self._mkurl(cmd, *args),
....................headers=_DMAP_HEADERS,
....................timeout=timeout)
....
........yield from self._assure_logged_in()
........return (yield from self._do(_get_request, is_daap=daap_data))

with cmd == 'ctrl-int/1/controlpromptupdate?[AUTH]&prompt-id=1'

which yields something like:

[{'cmcp': [{'mstt': 200}, {'miid': 926}, {'mdcl': [{'cmce': 'kKeybMsgKey_String'}, {'cmcv': '308202C33082022CA003020102020D3333AF080604AF0001AF000001300D06092A864886F70D0101050500307B310B300906035504061302555331133011060355040A130A4170706C6520496E632E31263024060355040B131D4170706C652043657274696669636174696F6E20417574686F72697479312F302D060355040313264170706C652046616972506C61792043657274696669636174696F6E20417574686F72697479301E170D3038303630343231333030315A170D3133303630333231333030315A3066310B300906035504061302555331133011060355040A130A4170706C6520496E632E31173015060355040B130E4170706C652046616972506C61793129302706035504031320526F7369652E333333334146303830363034414630303031414630303030303130819F300D06092A864886F70D010101050003818D0030818902818100DCB60285A26C6B4DE502C49C842A527176C0185B082DCE6C646B55A2640706A6967DED8F23C8542E284107A9A22709E1056E934BC3C4F01798BD54391829490665205F296E9BE2595E0419AEDEDA77D44560CC7AF1E3A72F37EFE9AED51263ED0807FED2CCB723F51D08CD8DFB41F675770671E03C29E29E39C53161057453BD0203010001A360305E300E0603551D0F0101FF0404030203B8300C0603551D130101FF04023000301D0603551D0E041604148F4E4787070D6D84FD1F307932107EBC04CEAC55301F0603551D23041830168014FA0DD411911BE6B24E1E06499411DD6362075964300D06092A864886F70D010105050003818100153F2F1572D279E5DB1E1776CCA603131D7788B598BD1EFC7C1703A40A06C905C762CE1665440912A1BCA88F766861C436543A1A9AB536DEB479BF2803F383E92A75B7360B47B8197387A6BB4EB82554C6762C06C4E236A890139396F56138C1B69395FCFED8CB74BF94D91E0E98F6F8276A2B49172847498A5843847ED00FC8'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SessionID'}, {'cmcv': '298'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_KeyboardType'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_Version'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MaxCharacters'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MessageType'}, {'cmcv': '3'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SubText'}, {'cmcv': '01576120704EC4F53FAAE27BCB'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_SecureText'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_MinCharacters'}, {'cmcv': '0'}]}, {'mdcl': [{'cmce': 'kKeybMsgKey_TextInputType'}, {'cmcv': '0'}]}]}]

After which the keyboard command should be called:

tag building should look like this I guess!

def keyboard_tag(value):
....return 'cmcc'.encode('utf-8') + b'\x00\x00\x00\x01\x39' + 
........ 'cmbe'.encode('utf-8') + b'\x00\x00\x00\x0c' + 
........ 'PromptUpdatecmte'.encode('utf-8') + 
........len(value).to_bytes(4, byteorder='big') + value.encode('utf-8')

BUT!!! I assume we also need to do something with the first reply, although I cannot find any evidence for my assumption within the provided wireshark dumps (which are from a working setup, hence the keyboard actually did something as in it showed 'abcde..'

Honestly, I am stuck!

**Comment by gojosh** [comment]
The key here is to use **controlpromptupdate** GET to initiate a listener (with a long timeout interval - I think the internal dmap default is 30 mins), to which the ATV will send a latent response whenever a text entry field is encountered. (This enables automatically popping a text entry field.) That response includes the kKeybMsgKey dictionary, which contains **kKeybMsgKey_SessionID**. You then compose a **controlpromptentry** POST with the httpBody including a **cmcc** value of the **kKeybMsgKey_SessionID**, and a **cmte** value of the text enter into the field. Of course these values need to be packaged using the proper TLV format.

In the Wireshark capture above, the the kKeybMsgKey_SessionID returned was 298, but the value used in the response was x39, or 57.

**Comment by postlund** [comment]
Sounds similar to how it works with play updates then. Shouldn't be that hard to support. A new interface must be defined though, so would be good to look at MRP and find synergies.

**Comment by gojosh** [comment]
Agreed. There are a few other implementation details - the kKeybMsgKey_SubText is a string labeling the text entry field, and I suspect kKeybMsgKey_SecureText is something to do with data masking for password entry. I haven't had a chance to investigate, as I just figured this out last night. The mdcl dictionary format is odd -- seems like a retrofit to dmap, with all string type keys and values.

**Comment by postlund** [comment]
Appreciate it that you are looking at it! If you post some data dumps I can try to help figuring out what the fields means. If you are up for the challenge to add keyboard support I can coach you with that. Even a prototype would be great.

**Comment by gojosh** [comment]
Thanks - I may give that a shot, but Python isn't my native language. My work in this context has been in Javascript and Swift.

**Comment by postlund** [comment]
No pressure there, only in case you have time and feel like it 😊 It's always fun to see progress outside of my own work.

**Comment by postlund** [comment]
This was implemented in 0.12.0 via Companion.
