### ISSUE TITLE
Timed out while waiting for TTS file - New message texts with no cached file

### ISSUE THREAD

**Issue by Gloomyeye** [postlund/pyatv#1452]
### Describe the bug

Hello,

I read that no issues regarding TTS on homepod should be created with the current beta release. However, I saw under the release notes that the implemented workaround will be updated and the current workaround is not usable with the current beta realease. So far, I cannot use the TTS service with a new text which is not cached. Cached files will be executed with success. New message texts not. Therefore, the TTS service is not usable.

My currrent tts configuration:
tts:
  - platform: google_translate
    language: 'de'
    cache: true
    cache_dir: /tmp/tts

### Error log

```log
Logger: custom_components.apple_tv.media_player
Source: custom_components/apple_tv/media_player.py:252
Integration: Apple TV
First occurred: 21:32:30 (1 occurrences)
Last logged: 21:32:30

Timed out while waiting for TTS file
```

### How to reproduce the bug?

Use service call:

service: tts.google_translate_say
data:
  entity_id: <media player entity id>
  message: A new text
  cache: true

### What is expected behavior?

TTS service call should be executed without any error

### Operating System

Rasp with Home Assistant 2021.11.1 docker container

### Python

3.9

### pyatv

1.9.1

### Device

Apple Homepod 15.1.1

### Additional context

I hope that the current implemented workaround will be updated, so that the new file for the tts can be downloaded or the timeout limit will be increased.

**Comment by postlund** [comment]
I will focus on #1482 to support HTTP streaming, thus allowing for proper support instead. When I get some time to do so.

**Comment by Gloomyeye** [comment]
Okay, I would love to use this as TTS integration for my HomePods. Maybe this could help: https://github.com/georgezhao2010/apple_airplayer

**Comment by jusxon** [comment]
Installing this apple tv beta integration breaks https://github.com/georgezhao2010/apple_airplayer functionality.

**Comment by postlund** [comment]
@jusxon In what way? Any logs?

**Comment by postlund** [comment]
@Gloomyeye I just pushed an update to the beta component that utilizes the new streaming support from HTTP in pyatv, so this should not be a problem anymore. Please test and confirm! 👍

**Comment by Gloomyeye** [comment]
Hi @postlund , my current homepods are not reachable after updating to pyatv 2.0. So, I deleted the homepods. However, it is not possible to insert the homepods again due to the current failure in the integration window:

<img width="424" alt="Bildschirmfoto 2021-12-06 um 11 33 02" src="https://user-images.githubusercontent.com/69754128/144831310-2126b30b-3ea5-49a4-a2d8-d679765698f9.png">

My current installation "Home Assistant 2021.11.5 docker container" with pyatv 2.0.

Logger: homeassistant
Source: custom_components/apple_tv/config_flow.py:149
Integration: Apple TV
First occurred: 11:36:09 (1 occurrences)
Last logged: 11:36:09

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
    class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
    self, discovery_info: zeroconf.ZeroconfServiceInfo
AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'

**Comment by postlund** [comment]
> Hi @postlund , my current homepods are not reachable after updating to pyatv 2.0. So, I deleted the homepods. However, it is not possible to insert the homepods again due to the current failure in the integration window:
> 
> 
> 
> <img width="424" alt="Bildschirmfoto 2021-12-06 um 11 33 02" src="https://user-images.githubusercontent.com/69754128/144831310-2126b30b-3ea5-49a4-a2d8-d679765698f9.png">
> 
> 
> 
> My current installation "Home Assistant 2021.11.5 docker container" with pyatv 2.0.
> 
> 
> 
> Logger: homeassistant
> 
> Source: custom_components/apple_tv/config_flow.py:149
> 
> Integration: Apple TV
> 
> First occurred: 11:36:09 (1 occurrences)
> 
> Last logged: 11:36:09
> 
> 
> 
> Error doing job: Task exception was never retrieved
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
> 
>     flow, result = await task
> 
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
> 
>     flow = await self.async_create_flow(handler, context=context, data=data)
> 
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
> 
>     integration.get_platform("config_flow")
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
> 
>     cache[full_name] = self._import_platform(platform_name)
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
> 
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
> 
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 
>   File "/config/custom_components/apple_tv/config_flow.py", line 59, in <module>
> 
>     class AppleTVConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
> 
>   File "/config/custom_components/apple_tv/config_flow.py", line 149, in AppleTVConfigFlow
> 
>     self, discovery_info: zeroconf.ZeroconfServiceInfo
> 
> AttributeError: module 'homeassistant.components.zeroconf' has no attribute 'ZeroconfServiceInfo'
> 
> 

Bah, not this again 😕 The `ZeroconfServiceInfo` is new in latest core so it will only work in the next version(which should come out this weekend). Very unfortunate and I will have to update instructions. Please rollback to previous version of the component or update to HA beta.

**Comment by Gloomyeye** [comment]
Now, I installed the latest beta version (core-2021.12.0b1) and now I can confirm that the TTS service (with new text commands) works now! Thank you very much!

<img width="429" alt="Bildschirmfoto 2021-12-06 um 13 28 47" src="https://user-images.githubusercontent.com/69754128/144847644-e8ad5726-e577-4b3c-b0e2-47afa5c70ab9.png">
<img width="417" alt="Bildschirmfoto 2021-12-06 um 13 28 52" src="https://user-images.githubusercontent.com/69754128/144847650-c8a33422-9236-4ec1-a91c-b167697ae0cb.png">

The only thing I found out is that two TTS service calls at once causes the error "already streaming to device":

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/apple_tv/media_player.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:42:20 (1 occurrences)
Last logged: 13:42:20

[2902175672] already streaming to device
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 238, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 311, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 315, in stream_file
    self.playback_manager.acquire()
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 129, in acquire
    raise exceptions.InvalidStateError("already streaming to device")
pyatv.exceptions.InvalidStateError: already streaming to device

However, I think this is another topic which should not be discussed here ;-)

**Comment by postlund** [comment]
Great! 👍 

It is only possible to stream from one source at the time, so I have a lock in pyatv to prevent someone from trying to take over an existing stream. That is a design decision from my end (a better error message could be provided though).
