### ISSUE TITLE
Volume_set has no function on homepod

### ISSUE THREAD

**Issue by Gloomyeye** [postlund/pyatv#1453]
### Describe the bug

The service "media_player.volume_set" has no function with a homepod (mini). No volume changes are made by the service call.
The services "media_player.volume_down" and "media_player.volume_up" are working correctly.

### Error log

No logs will be created.

### How to reproduce the bug?

service: media_player.volume_set
target:
  entity_id: <media player entityid>
data:
  volume_level: 0.3

service: media_player.volume_set
target:
  entity_id: <media player entityid>
data:
  volume_level: 0.6

### What is expected behavior?

The volume is set to 30% by the first service call. The volume is increased by 30% (to 60%) after the second service call.

### Operating System

Rasp with Home Assistant 2021.11.1 docker container

### Python

3.9

### pyatv

1.9.1

### Device

Apple Homepod 15.1.1

### Additional context

Integration does seem to work fine. If I use the standard buttons (volume up and volume down), volume changes were made:

<img width="405" alt="media_player" src="https://user-images.githubusercontent.com/69754128/140623815-d6c6a5d4-fa11-41df-8f19-1e944bc0a07d.png">

**Comment by postlund** [comment]
The `volume_set` service is not implemented in the component. I was certain it was, but apparently not. I will try to fix that once I get things into core.

**Comment by postlund** [comment]
So, this PR will add support for reading out current volume and changing volume:

https://github.com/home-assistant/core/pull/61107

Won't be available in official Home Assistant until January release, but it is available in the beta component (but you need Home Assistant 2021.12.x beta to run it).

**Comment by Gloomyeye** [comment]
Thank you very much! It works perfectly.
