### ISSUE TITLE
apple TVOS15 only works on version 1.60

### ISSUE THREAD

**Issue by acctech1** [postlund/pyatv#1454]
### Describe the bug

I upgraded to 1.91 hopping the new version would work like 1.60 but integration dies as soon as i upgrade
when back to 1.60 all is good
what am I missing??

### Error log

```log
<place log here>
```

### How to reproduce the bug?

upgrade to 1.91 or any other then 1.60

### What is expected behavior?

 not to break integration 

### Operating System

hass

### Python

3.6

### pyatv

0.8.2

### Device

tvOS 15 apple 

### Additional context

 rfrfr

**Comment by postlund** [comment]
Please try latest version of the beta component with the latest version of Home Assistant.

**Comment by postlund** [comment]
Should be fixed.
