### ISSUE TITLE
I got ver 1.91 working with my apple tv but it finds other things that are not apple tv's in the integrations tab

### ISSUE THREAD

**Issue by acctech1** [postlund/pyatv#1455]
### What's on your mind?

I get new device discovered on all my sonos and tv's 
they all come up as a new discovered device in HA and it thinks there all new apple tv's 
other then ignoring them is there any fix

**Comment by postlund** [comment]
It's in the component readme file:

https://github.com/postlund/hass-atv-beta#new-features

**Comment by FinestDice17** [comment]
> It's in the component readme file:
> 
> https://github.com/postlund/hass-atv-beta#new-features

Im having the same issue and looked where you stated above but unless im blind, I don't see where it states that and/or how to fix it.

**Comment by postlund** [comment]
This part:

*Basic support for arbitrary AirPlay speakers. Metadata ONLY works when streaming from Home Assistant, i.e. it will not reflect what someone else is streaming to the device (the HomePod being an exception). Only Stop button works.*

They are AirPlay capable and that is why they show up.

**Comment by postlund** [comment]
I believe the question itself is answered, it's a matter of communicating this better.
