### ISSUE TITLE
some discovered devices cannot be ignored

### ISSUE THREAD

**Issue by jnewland** [postlund/pyatv#1457]
### Describe the bug

Using the latest code from https://github.com/postlund/hass-atv-beta, I observe that some newly-supported devices appear in Home Assistant auto-discovery *without an ignore link*:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/47/140746009-20f6e17b-2141-4c21-b012-7c5bdd12d3b8.png">

This device is a Sonos "Room". I've successfully ignored other Sonos devices, but am not able to ignore this one for some reason.

### How to reproduce the bug?

Install https://github.com/postlund/hass-atv-beta, add Sonos device to network.

### What is expected behavior?

Ignore link should appear on all discovered devices

### Operating System

Linux

### Python

3.8

### pyatv

0.9.6

### Device

Sonos Arc + Two SLs configured as a group

### Additional context

Device is on different subnet yet MDNS packets are being relayed by my router's [MDNS repeater functionality](https://docs.vyos.io/en/latest/configuration/service/mdns.html), discovery may be adversely affected by that.

**Comment by Stuke00** [comment]
I get this too. Both my Sonos, my HomePod mini and my MacBook Pro all show up and not able to be ignored or dismissed.

**Comment by postlund** [comment]
This is a bit strange as it suggests that devices were found without a proper unique id (I guess). Do you also have your device on a separate VLAN @Stuke00?

**Comment by Stuke00** [comment]
I do not have a separate VLAN.  They are on the same network as home assistant.

**Comment by postlund** [comment]
It would help me a lot of if anyone of you could drop the output of `atvremote --debug scan` here. I would like to look at the zeroconf output.

**Comment by jnewland** [comment]
Here's scan output for a Sonos Move that's currently appearing without an ignore link:

```
2021-11-27 02:21:34 DEBUG [pyatv.core.scan]: Auto-discovered move at 192.168.4.81:7000 via Protocol.AirPlay ({'acl': '0', 'deviceid': '48:A6:B8:EE:98:16', 'features': '0x445F8A00,0x1C340', 'rsf': '0x0', 'fv': 'p20.66.4-23090', 'flags': '0x4', 'model': 'Move', 'manufacturer': 'Sonos', 'serialnumber': '48-A6-B8-EE-98-16:1', 'protovers': '1.1', 'srcvers': '366.0', 'pi': '48:A6:B8:EE:98:16', 'gid': '48:A6:B8:EE:98:16', 'gcgl': '0', 'pk': 'da7c49e05e67cfea4f5974f73be448a670a8cc44138fe616bde1199a7a182c44'})
2021-11-27 02:21:34 DEBUG [pyatv.core.scan]: Auto-discovered 48A6B8EE9816@move at 192.168.4.81:7000 via Protocol.RAOP ({'cn': '0,1', 'da': 'true', 'et': '0,4', 'ft': '0x445F8A00,0x1C340', 'fv': 'p20.66.4-23090', 'md': '0,1,2', 'am': 'Move', 'sf': '0x4', 'tp': 'UDP', 'vn': '65537', 'vs': '366.0', 'pk': 'da7c49e05e67cfea4f5974f73be448a670a8cc44138fe616bde1199a7a182c44'})
Scan Results
========================================
       Name: move
   Model/SW: Move, Unknown OS
    Address: 192.168.4.81
        MAC: 48:A6:B8:EE:98:16
 Deep Sleep: True
Identifiers:
 - 48:A6:B8:EE:98:16
 - 48A6B8EE9816
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 ```

**Comment by postlund** [comment]
There have been a few updates to the integration as I'm merging stuff into core. Some things are still left to sort out, but I will merge back soon and hopefully this problem will go away.

**Comment by postlund** [comment]
I just release 2.2.0, please try that out and let me know if it seems to resolve the issue.

**Comment by postlund** [comment]
I believe this is fixed nowadays, just let me know if you have any additional problems!
