### ISSUE TITLE
atvremote scan via docker is not detecting Apple TV 4K 2021 (tvOS 15.0)

### ISSUE THREAD

**Issue by sklever** [postlund/pyatv#1476]
Using pyatv via docker as given in instructions: [https://github.com/postlund/pyatv/pkgs/container/pyatv ](https://github.com/postlund/pyatv/pkgs/container/pyatv )
`$ docker pull ghcr.io/postlund/pyatv:sha-5eb4152 `

when executing 
`$ docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan `
it's saying:
`ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network`

when executing:
`$ docker run  --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan`
it's saying:
```
Scan Results
========================================
```

Apple TV and Docker (running on a MacBook) is in same network, so it should work I'd say.
For some reasons it's not working as expected as mentioned above.

Any suggestions how to fix / resolve this?

**Comment by postlund** [comment]
I have not studied this in detail, but it likely has to do with docker on macOS. Maybe this works?

https://stackoverflow.com/questions/52555007/docker-mac-alternative-to-net-host

I would start in that end at least.

**Comment by sklever** [comment]
hmm not sure if this is helping as some other stuff is running perfectly fine in docker, so I'd say docker installation is done correctly

**Comment by postlund** [comment]
Most things does not require direct access to the network because of multicast. So it very much depends on what you mean by "other stuff". You can try sniffing traffic on the network with wireshark and ensure that MDNS traffic passes through. It uses port 5353 UDP.

**Comment by sklever** [comment]
FYI
using Docker Desktop on a MacBook Pro, have just tried master image from ghcr.io/postlund/pyatv so you can use command `atvremote scan `and `atvscript scan` directly but it is not detecting any devices

never used wireshark before, is this really required?

**Comment by postlund** [comment]
I'm 100% certain that it has to do with networking in docker at least. Multicast traffic is not forwarded to the container. I believe macvlan will solve this for you:

https://docs.docker.com/network/macvlan/

**Comment by postlund** [comment]
Did you make any progress on this? I'm a bit interested in regards to #1494.

**Comment by sklever** [comment]
unfortunately not, no further progress even though macvlan has been added

**Comment by postlund** [comment]
I'm not sure I will be able to assist further I'm afraid. Staying away from docker on macOS myself and just run VirtualBox instead since it docker support on macOS still is not native anyway.

**Comment by postlund** [comment]
Unfortunately I will not be able to assist this further and it's really a docker issue as I see it. Will close this issue, but feel free to report back if you have any success in the matter.
