### ISSUE TITLE
Is it possible to play specific songs via Apple Music? 

### ISSUE THREAD

**Issue by fastender** [postlund/pyatv#1486]
### What feature would you like?

Play Apple Music Songs

### Describe the solution you'd like

Choosing in HA and start playin

### Any other information to share?

No.

**Comment by postlund** [comment]
It's not supported. no. I believe there's a similar issue open regarding starting certain playlist. Problem is that I have no idea how any of those works technically. I guess maybe AirPlay is used somehow. As I don't use Apple Music myself, how does output device selection work?

I know there's this library to integrate with Apple Music via the official API:

https://github.com/mpalazzolo/apple-music-python

So assuming I can figure out how I request something to play, I can probably make use of that.

**Comment by davidbilge** [comment]
I think the library you mentioned is a wrapper around Apple's Apple Music API. That API allows querying the Apple Music library but is not concerned with playback, I think.

Playing Apple Music songs on the AppleTV can be done via AirPlay or via a "remote control" feature (I do not know the official name). The "remote control" feature hands off playback to the AppleTV (or HomePod, I think) and playback can then be controlled by any iPhone on the local network.

**Comment by postlund** [comment]
Yes, it is used to query music. If you want to play a specific song using pyatv on its own, you need some way to find that song (album, artist or whatever) and get an identifier which can be sent to the device. My intention was to add a "database" concept (which exists in the world of DAAP/DACP/DMAP, not implemented in pyatv though) to support querying Apple Music directly from pyatv. So it would only serve that purpose.

It's the "remote control" feature that I'm curious about. I wonder how that is implemented. I don't think I have seen anything in MRP suggesting it could be done using that, but maybe I haven't looked enough.

**Comment by fastender** [comment]
Thank you very much for the valuable information. I am already very happy to be able to use TTS with our Homepods and don't regret for a second selling our Echos.
