### ISSUE TITLE
Error reported after upgrading to core-2021.12.0b0

### ISSUE THREAD

**Issue by jcbshw** [postlund/pyatv#1495]
### Describe the bug

After upgrading to 2021.12 multiple entries of this error appeared in my logs.

### Error log

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:94 
First occurred: 3:29:48 PM (12 occurrences) 
Last logged: 3:30:05 PM

Detected integration that accessed discovery_info['type'] instead of discovery_info.type; this will fail in version 2022.6. Please report issue to the custom component author for apple_tv using this method at custom_components/apple_tv/config_flow.py, line 153: service_type = discovery_info["type"][:-1] # Remove leading .

### How to reproduce the bug?

Install the custom component

### What is expected behavior?

No errors

### Operating System

HASSOS

### Python

3.9

### pyatv

1.9.1

### Device

Apple TV 4K tvOS 15

### Additional context

Running core-2021.12.0b1

**Comment by postlund** [comment]
Fixed in the update I just pushed.
