### ISSUE TITLE
Unclosed Client Session (aiohttp.client.clientsession)

### ISSUE THREAD

**Issue by dlcorlew21** [postlund/pyatv#150]
I am receiving an unclosed client session warning for “aiohttp.client.clientsession” when executing via CLI or API for all commmands.

**Comment by dlcorlew21** [comment]
More specifically the error that is returning is:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyatv/internal/apple_tv.py:509: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self._session.close()
ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10247b710>
ERROR: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x101f10be0>, 3883.001728804)]']
connector: <aiohttp.connector.TCPConnector object at 0x1026a57b8>

**Comment by dlcorlew21** [comment]
Downgraded aiohttp and it solved the issue.

**Comment by NebzHB** [comment]
Hello, i have the same problem, how did you downgraded it and to what version ?

**Comment by postlund** [comment]
I believe that aiohttp changed `close` from being a regular python function to be a coroutine in some later version. IIRC I changed this on master when working on that, but I will have to fix this on the release branch as well and bump least required version of aiohttp. Can you specify which version works and which does not work?

**Comment by postlund** [comment]
As I said, I believe I fixed this on master (which suspend is based on) so it should work as expected there. But release_0_3_x (or any official release) assumes that `close` is a function, which is not the case in later versions of aiohttp.

It looks to me like aiohttp 3.x changed `close` to being async:

https://github.com/aio-libs/aiohttp/commit/439c732f5bf29a83779dce6da4a55e7efd433cf8

So I would need to bump lowest required version of aiohttp to 3.x and add `yield from` when calling `close`. I have another change I have to make so I'll fix this tonight and make a new relase.

**Comment by postlund** [comment]
@NebzHB Please try the PR #154 and let me know if it works. I will make the release to pypi afterwards.

**Comment by postlund** [comment]
Version 0.3.11 is out that fixes this.
