### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by Blackpander** [postlund/pyatv#1504]
### Describe the bug

After upgrading from 1.9.1 which was working to 2.1.0 I found my Apple TV unavailable. After deleting the integration and trying to add it again I got the following message:

- Config flow could not be loaded

### Error log

```log
There is no logging from this integration after a restart.
```

### How to reproduce the bug?

Upgrade from 1.9.1 to 2.1.0 and delete the Apple Tv integration, then add it again. I think this has some more variables to it.

### What is expected behavior?

An upgraded version with a working entity.

### Operating System

macOS

### Python

Other

### pyatv

2.1.0

### Device

Apple TV 4K, tvOS 15

### Additional context

Didn't know how to find my Python version so chose other.

**Comment by postlund** [comment]
You need to run Hone Assistant 2021.12.0 beta for it to work (mentioned in the changes).

**Comment by Blackpander** [comment]
Sorry, had to read those first!
