### ISSUE TITLE
Companion protocol ?

### ISSUE THREAD

**Issue by Oliv17** [postlund/pyatv#1508]
Hello.
In the manual you say:
...Only works on devices running tvOS and if Companion has been paired...
Can you tell me what the companion protocol is?
thank you

**Comment by postlund** [comment]
Apple uses Companion for all kinds of things nowadays but they first introduced it for handoff and continuity as far as I know. In the context of pyatv, it's mainly used app launching (`app_list` and `launch_app`) and power controls (`turn_on` and `turn_off`). Most of the buttons are also supported by Companion. Not sure if you had any particular question in mind?

**Comment by postlund** [comment]
Sure, like any other protocol:

    atvremote -s <ip> --protocol companion pair

**Comment by Oliv17** [comment]
Sorry.
I may not be given enough information. Are we talking about apple tv beta in home assistant?
If so, when should I put this line?

**Comment by postlund** [comment]
No, that's if you are using `atvremote` directly (wasn't clear we were talking about home assistant). The implementation in Home Assistant will automatically pair all supported protocols, so you don't have to care too much about that. If you want to verify, you can remove the device and add it again. The dialogs will tell you which protocols you are pairing, e.g. AirPlay, RAOP and Companion.

**Comment by postlund** [comment]
I assume we can close this now, right?

**Comment by Oliv17** [comment]
Yes thanks !
