### ISSUE TITLE
Migrate from netifaces to ifaddr

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1509]
### What feature would you like?

Since netifaces is not maintained anymore it's good to move to something that is.

https://pypi.org/project/ifaddr/

### Describe the solution you'd like

Should work as before.

### Any other information to share?

https://github.com/home-assistant/core/issues/61186#issuecomment-988505472

**Comment by bdraco** [comment]
Confirmed exception is gone and everything appears to be working correctly.

**Comment by postlund** [comment]
Thanks! 👍

**Comment by postlund** [comment]
This is done.
