### ISSUE TITLE
select_source  apple tv beta home assistant 

### ISSUE THREAD

**Issue by Oliv17** [postlund/pyatv#1510]
I installed version 2.1 without problem in home assistant.
I am trying the select source function. But nothing is happening. Here is my script.
Can you tell me what I did wrong please.

`alias: Netflix test
sequence:
  - service: media_player.select_source
    data:
      source: Netflix
    target:
      entity_id: media_player.sejour
mode: single`

**Comment by postlund** [comment]
Is the source list populated with all the apps? Does it work if you use the source list in the media player from frontend? Please also check the log, maybe there are some clues in there.

**Comment by Oliv17** [comment]
Sorry I'm a beginner.
Do I have to fill out a source list of apps?
Where? in the config.yaml file?
How do I do?

**Comment by postlund** [comment]
No, just click the three dots on the media player card for your Apple TV. Do you see the sources list there with all the apps filled in?

**Comment by postlund** [comment]
Example looks like this:
<img width="438" alt="Skärmavbild 2021-12-08 kl  13 03 05" src="https://user-images.githubusercontent.com/5982179/145205413-96382172-b062-40ec-822e-db9242fe6e1d.png">

**Comment by Oliv17** [comment]
Perfect.
It works.
For that.
I deleted the integration, and I also delete all the Remotes App from my apple tv.
Before reinstalling everything.
Thank you very much for your help.

**Comment by wuhuwuhuhu** [comment]
> No, just click the three dots on the media player card for your Apple TV. Do you see the sources list there with all the apps filled in?

Hi @postlund sorry to bother you. I met the exact issue you mentioned, there is no source list at all on my front end. Do you know how could I solve this? thank you
![image](https://user-images.githubusercontent.com/29944124/151265326-736ad798-0838-455d-8d3b-138375bfc39e.png)

**Comment by postlund** [comment]
@wuhuwuhuhu Remove it, add it again and make sure all protocols pair OK. If Companion fails, it won't work.
