### ISSUE TITLE
RemoteControl commands intermittint/sticking

### ISSUE THREAD

**Issue by thedave42** [postlund/pyatv#1516]
### Describe the bug

When using atvremote or atvscript to send navigation commands to the AppleTV, the AppleTV is responding inconsistently to the command.  It either

- works
- doesn't respond
- acts like the key is being repeatedly pressed

in all of the above scenarios I receive a 'success' response from the API.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

1. Pair AppleTV with airplay protocol
2. Pair AppleTV with companion protocol
3. Attempt to use remote commands via `atvremote` or `atvscript`

Examples of commands I ran:

```
atvscript -i 50:32:37:8E:C1:17 --airplay-credentials *** --companion-credentials *** --raop-credentials *** right

{"result": "success", "datetime": "2021-12-09T13:20:19.488878-08:00", "command": "menu"}
```

Here is a video showing the different behavior:

https://user-images.githubusercontent.com/50186003/145478777-9672c21e-cdf7-4a10-9865-d849c29b6723.MOV

### What is expected behavior?

Each command executes only once and always executes on the AppleTV

### Operating System

Windows 10

### Python

3.9

### pyatv

0.9.7

### Device

AppleTV HD tvOS 15.0

### Additional context

I'm attempting to use batch files and the atvscript command to automate navigation to different applications and channels on my AppleTV.

**Comment by postlund** [comment]
Right, I need to do something about this. There are some timing issues that cause this. As a work-around you can add delay=1000 at the end of atvremote to make it sleep a second before exiting (you can experiment with the value):

    atvremote -i xxx ... right delay=1000

Hopefully that will work better.

**Comment by postlund** [comment]
I have a theory for how to fix this a little bit better and I've made an implementation attempt in #1521 (some minor things left to sort out though). Would be great if you could evaluate it for me!

**Comment by postlund** [comment]
Seems to work fine in my tests. Even things like `atvremote ... down down right left up up` seems to work better now.
