### ISSUE TITLE
Running in command line, getting error 503

### ISSUE THREAD

**Issue by crxporter** [postlund/pyatv#152]
I've been running Home Assistant for a couple of months using it's built in apple tv media player (which I understand is just this program). I'd been having disconnect issues with just one of my apple TVs (4K version, ethernet connection, CEC enabled, home sharing on). The home assistant system would stop being able to connect to the TV after 2 or 3 days. Restarting the TV worked for a little while - but that stopped functioning as well.

Long story short, I erased both of my apple tvs and started a "roll my own" solution with the command line pyatv interface running in node-red. my command is:
`atvremote --address (IP) --login_id (ID) push_updates`
This works quite well but, again, after 2 or 3 days I end up with no connection to the apple tv. The error I'm getting from the command line is:
`An error occurred (restarting): failed to login: 503`

I know there were some issues previously about this, I didn't really see any concrete solutions that I could follow. Any chance you've had an epiphany over the last few months on how to solve this?

PS-for those interested I'm running OpenHAB with a Node-Red exec flow to watch the atvremote push_updates come through to control lighting in the house.

**Comment by crxporter** [comment]
I forgot to mention: I tried both the home sharing and pairing solution.

For some reason the pairing worked fine but would disappear from the ATV every time my apple tv restarted. This does not happen on my "older" non-4k apple tv.

**Comment by postlund** [comment]
As you mention, this is a known issue and the only "solution" found to this is to:

- Disable home sharing
- Restart device
- Enable home sharing again

and after this, hope that is continues to work. It has for me for several months (I have an ATV 4K). Did you try that?

I would hope for a better solution, but as of today no one has found the "real" problem and thus no solution either, I'm afraid.

**Comment by crxporter** [comment]
Yes I did that and the system is working - for now. I can only hope I'm lucky this round and can go for a several month round. When I was running Home Assistant I never got more than 3 days out of it even with this work-around.

Thanks!

**Comment by crxporter** [comment]
Update on this - it ran almost 3 weeks. I reset (home sharing off, restart, home sharing on) on Thursday and it’s dropped again today. 

Any tips would be great to get more time out of it! This only happens with my 4K atv, not the 1080p model

**Comment by crxporter** [comment]
Back for another update - turns out I spoke too soon. Both TVs lost the connection (returned error 503). 

I've now disabled home sharing and paired them with "atvremote pair" - it works for now, time will tell how long it lasts.

PS - this is one of my favorite bits of home automation when it's working properly.

**Comment by postlund** [comment]
@crxporter Is it still working with the manually paired id?

**Comment by crxporter** [comment]
Hey good to see you! Some updates:

The "atvremote pair" actually did not work, I can't get it to stay paired after reboots. Any hints on how to have it remember that?

I'm back with home sharing and I have to do the disable-restart-enable sequence 3 or 4 times since I last commented - so every 2 or 3 weeks it seems.

**Comment by postlund** [comment]
Ok, so I assume the pairing process worked and that you could used the login_id you got until reboot? That is actually the same behavior I see now as well, so that make things a lot easier to investigate. I have some ideas on what to check, so I'll look into that next week or so.

**Comment by crxporter** [comment]
Yes pairing worked until reboot. 

Let me know if I can help - I will go install 0.3.11 and setup a log system to save everything coming out of push_updates so I can report if I home sharing stops again. 

Might get something helpful, who knows.

**Comment by postlund** [comment]
@crxporter I _think_ I found the problem. When pairing, pyatv will report back to the ATV that is is an iPod. The reason for this is mostly legacy and that other libraries does that, so I followed the pattern. I sniffed the traffic from the iTunes Remote app and found that it sends iPhone instead, which also was the only difference I could see in the traffic. After changing from `ipod` to `iPhone` the pairing seems to stick like it used to.

Would be really great if you would try it out for me, you have the change in #161.

**Comment by crxporter** [comment]
I'll try it right after work today and report back! Thanks!

**Comment by crxporter** [comment]
Pairing seems to work great and stay paired after restarting.

I guess the original issue is still an issue - but pairing is working properly so I'll go with that!

Thanks!

**Comment by postlund** [comment]
Great, thanks for trying it out! The fix is merged to the 0.3.x branch, I will make a new release soon. Working on some other fixes.

The initial problem likely still exists, not sure what the actual problem is there. I need to investigate that further.

**Comment by postlund** [comment]
I'm gonna close this one since we have another issue open for the play status issues at #124.
