### ISSUE TITLE
Pairing is required for Companion but it is disabled on the device.

### ISSUE THREAD

**Issue by xXDjMikeXx** [postlund/pyatv#1524]
### What's on your mind?

When I try to connect my AppleTv 4k in HomeAssistant it says....

**Pairing is required for Companion but it is disabled on the device. Please review potential access restrictions (e.g. allow all devices on the local network to connect) on the device.

You may continue without pairing this protocol, but some functionality will be limited.**

I can't figure out what to do that this will Protocol can pair....

**Comment by postlund** [comment]
Go in to the AirPlay menu on your Apple TV and make sure access restriction is set to "Allow anyone on the same network".

**Comment by xXDjMikeXx** [comment]
ah okay thank you I will try that
