### ISSUE TITLE
parseable or json format

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#153]
Dear,

Thank you for your amazing work.

Would that be possible to have something like : atvremote scan --parseable 
with an output like : 
appletvName,ip,protocol,whatever
appletvName2,ip,protocol,whatever

or a json output ?

same for playing or other command returning datas ?

because it's quite confusing when the format change and if i need to parse differently

BR's

Nebz

**Comment by postlund** [comment]
It would of course be possible, but there is really no good way of doing that today. `atvremote` is more to be seen as an "example" of how to use pyatv, so it would probably be quite some work adding support for alternative output decently. I'm not opposed to doing so if someone want to give it a try (and can come up with a good solution), I however have to time to do so.

**Comment by postlund** [comment]
@NebzHB I started working on something to provide this functionality. Please see https://github.com/postlund/pyatv/issues/475#issuecomment-600326840 if you are still interested.

**Comment by NebzHB** [comment]
yes ! thank you !
