### ISSUE TITLE
Support triggering URL Schemes for app deep linking

### ISSUE THREAD

**Issue by Tloram** [postlund/pyatv#1545]
### What feature would you like?

iOS and tvOS apps support URL Schemes for deep linking when opening apps (eg. instead of just opening the app in its default or last state, it can be opened to a specific feature within the app, or automatically play a specific channel/video stream).

Is there any possibility this can be supported here in some way?

### Describe the solution you'd like

Any :)

### Any other information to share?

https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

Here are some random examples of protocols/deep links I found:

**Netflix app:**
nflx://www.netflix.com/title/70291117 - Will open a show page
nflx://www.netflix.com/watch/70291117 - Will begin playing the video
https://stackoverflow.com/questions/34730105/how-do-i-deep-link-to-netflix-on-tvos

**BBC iPlayer app:**
bbciplayer://channels/bbc_news24 - Will open and begin streaming the news channel
https://www.reddit.com/r/iplayer/comments/ielai0/ios_users_is_there_a_deep_link_to_the_bbc_news/

**Misc**
Also I found this user who has created a native Apple TV app, which seems to just act as a http server on the Apple TV itself allowing you to address the Apple TV using its IP Address/Hostname and pass a URL scheme to it, not sure if this can help with investigation: https://www.reddit.com/r/shortcuts/comments/iowagq/deeplink_app_for_tvos/

**Comment by postlund** [comment]
Maybe, do you have any example of how to trigger this on tvOS? I need something that I start reverse engineering from.

**Comment by postlund** [comment]
Theoretically it would be possible with the current API, but from what I can see there is no way to pass a URL to the app. In the log it looks like this:

    förval	11:01:09.975327+0100	PineBoard	Process Manager handling open request {bundleID: com.netflix.Netflix, trusted: YES, URL: (null)} from (null)}

Assuming I could set URL, maybe it would be possible. There is however nothing in the code suggesting I can do that, so another way in is needed.

**Comment by Tloram** [comment]
Ok, sounds potentially promising... I added a few examples to the OP.

**Comment by postlund** [comment]
So far I believe we are out of luck. My guess is that these links are mainly for apps to use. But perhaps they add a way to open deep links externally as well.

**Comment by postlund** [comment]
This was shipped in 0.12.1.
