### ISSUE TITLE
TTS error on version 0.9.8 (2.2.0)

### ISSUE THREAD

**Issue by causefx** [postlund/pyatv#1546]
### Describe the bug

![image](https://user-images.githubusercontent.com/16184466/146615817-6b08428e-1b9c-4399-ae65-ab7a38ab9569.png)

Getting an error from HA API when testing out TTS from the homepod mini.

Testing out TTS on google mini and worked fine.

### Error log

```log
2021-12-17 15:33:49 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139695694657808] HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 286, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 350, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 457, in open_source
    return await InternetSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 339, in open
    source = await loop.run_in_executor(None, PatchedIceCastClient, url)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miniaudio.py", line 1091, in __init__
    with urllib.request.urlopen(req) as result:
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

### How to reproduce the bug?

Type in a TTS message for homepod mini entity and get error right away.

### What is expected behavior?

Message to come through

### Operating System

Docker

### Python

3.9.7

### pyatv

0.9.8

### Device

Apple HomePod Mini

### Additional context
```
System Health

version: core-2021.12.3
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 4.4.0-210-generic
arch: x86_64
timezone: America/Phoenix


```
Let me know if anything else is needed.

**Comment by postlund** [comment]
Looks like pyatv is not allowed to access the TTS file. Does it work with other media players (if you have something to test with)?

**Comment by causefx** [comment]
Yes, TTS works with other media players.

**Comment by postlund** [comment]
Ok, hmm, that's strange. I'll take a peek at the code and see if I find anything peculiar.

**Comment by causefx** [comment]
sounds good. thank you.

**Comment by postlund** [comment]
Can you enable additional debug logs and send the log to me? I need some more for troubleshooting. These would be sufficient:

https://github.com/postlund/hass-atv-beta#debug-logs

**Comment by causefx** [comment]
I sure can. i'll set that up once i get back to my pc.

**Comment by causefx** [comment]
@postlund here you go:
https://captures.sonflix.com/Xena1/pogoRipe19.txt

**Comment by postlund** [comment]
Ok, I know the problem now. It's Cloudflare that blocks any requests made by urllib which is currently used internally to stream the audio file. A workaround from your end is to disable browser integrity check as per this issue:

https://github.com/datopian/datahub-qa/issues/81

The long-term solution is to replace urllib with aiohttp. I can take a look at that.

**Comment by postlund** [comment]
Improving the code by using requests instead of urllib is easy enough and something I should do pretty much immediately. However, it still doesn't seem to work with your file. I downloaded it and I'm not able to play it with anything, just seems to be a short distorted noise. Maybe it's possible to generate the audio in for instance MP3 instead?

**Comment by causefx** [comment]
hey there @postlund,

I updated Cloudflare with the new page rule and now it doesn't 403 anymore.  The new problems is it crashes HA now.  
Here are the new logs.

https://captures.sonflix.com/Xena1/zeYebEKA75.txt

**Comment by postlund** [comment]
I got the same error as well (`failed to unit decoder`), will look into that.

**Comment by causefx** [comment]
it seems like it is an issue with google cloud... 

![image](https://user-images.githubusercontent.com/16184466/146810172-d3c0e01c-5349-46cc-9b4c-7b9510a2a9d2.png)
the bottom 2 options work fine.

**Comment by postlund** [comment]
Interesting. But they all work fine with another media player?

**Comment by causefx** [comment]
yes sir.

**Comment by postlund** [comment]
👍 I will try to figure out what is happening tomorrow.

**Comment by postlund** [comment]
#1553, which I just merged, fixes the initial `Forbidden` problem though.

**Comment by causefx** [comment]
> 👍 I will try to figure out what is happening tomorrow.

take your time, no hurry,  Also if you need any other logs or help of any kind - just let me know.

**Comment by postlund** [comment]
I believe the problem is that the files generated by Google TTS requires seeking within the file, i.e. it cannot just be parsed as a plain byte stream. That is a problem as I don't support that. Mainly because it's simply not feasible to buffer entire files in case they are very large. Can you provide a few other files so I can compare behavior? Another file generated by Google with  a longer phrase would be great as well (as I can't seem to get the original one working).

**Comment by causefx** [comment]
Sure let me submit a few more sentences.

Here is one: 
https://ha.sonflix.com/api/tts_proxy/b4d1da3a54a6edc7b08d8bb1730a4c36d3f63c6f_en-us_a603c2e3e9_google_cloud.linear16

**Comment by causefx** [comment]
https://ha.sonflix.com/api/tts_proxy/2a751d38ad3740e6c06b73d43fbd6f6232b914cd_en-us_a603c2e3e9_google_cloud.linear16

**Comment by postlund** [comment]
Great! Can you post one that is working as well?

**Comment by causefx** [comment]
https://ha.sonflix.com/api/tts_proxy/bc6601387140e62e7ad627c6285c61e9a8dbd682_en_-_google_translate.mp3

**Comment by causefx** [comment]
@postlund you are correct, the issue is with linear encoding.  I went ahead and applied the encoding to mp3 and it works now.  This was my fault for not checking.  now hopefully miniaudio allows to be built with custom flags.

**Comment by postlund** [comment]
That was my hypothesis as well. Some file formats aren't suitable for streaming since required data might be scattered across the file, which would require seeking and potentially buffering "large" amount of data (something I want to avoid doing). It should work fine if streamed as a local file though as I miniaudio supports the format. But I guess we can't do much more here right now and can possibly close the issue? Perhaps it's a good idea to make a note about it in the documentation to help others. I assume linear encoding is something you opt-in for?

**Comment by causefx** [comment]
Correct, the default is `mp3` for google_cloud.  I can't remember why I was using linear...  You are also correct about noting this in the docs.  Thank you for all your help :)
