### ISSUE TITLE
Apple TV 4 - Re-Authentication & Abort

### ISSUE THREAD

**Issue by ZachBurm** [postlund/pyatv#1549]
### Describe the bug

I have had success with my newer Apple TVs but one of them doesn't seem to want to connect. I have attached a screenshot of what happens at the end of the TV configuration. It prompts me for multiple codes, all seem to be successful but I get this message and the TV is not created. 
![IMG_3333](https://user-images.githubusercontent.com/7583640/146657844-f9c5ebef-bb81-4af4-a418-59813336630f.PNG)

### Error log

Still looking through logs, haven't identified anything relevant yet. I have logging on for both the component and the library. 

### How to reproduce the bug?

Unsure.

### What is expected behavior?

Device is added to Apple Tv

### Operating System

HA OS

### Python

3.8

### pyatv

0.9.8

### Device

Apple TV HD a1625

### Additional context

Apple TV v2.2.0

**Comment by postlund** [comment]
Sounds like the same issue as https://github.com/postlund/pyatv/issues/1548#issuecomment-997216524. I will have to look into it.

Did you already have the devices added before and actually did a reconfiguration or did you add a new device?

**Comment by ZachBurm** [comment]
I had it added back in October before the tv updated to tvOS 15. After that I deleted the configurations and installed the beta. It also doesn't get auto discovered. 
The other two apple tvs in the house do get discovered and connect just fine. Both of those are 4K ones. 
I have checked through all the entities and devices but can't find anything left over from that Apple TV.

**Comment by postlund** [comment]
Some times there are leftovers in `.storage/core.config_entries` for some reason. That might be the reason for it not showing up (as it technically already exists) but it would also match the "error" message you get as that would only happen if the config entry already exists. It's a minor implementation detail in Home Assistant... You can tell the config flow to abort but update some properties before doing so. Typically that is what happens during re-authentication, if for instance password expires. It yields an error message with success message though...

**Comment by ZachBurm** [comment]
@postlund that totally did it. Found and deleted the entry and it was recognized by the integration and added successfully.

**Comment by postlund** [comment]
Ok, "good" I guess. It's so strange this happens. Just to be sure, the old Apple TV did not appear under the Integrations page at all before you removed it from `.storage/core.config_entries`?

**Comment by ZachBurm** [comment]
Correct. I couldn't find any traces of it on any of the UI pages. I also found it leftover in the `core.area_registry` file.

**Comment by postlund** [comment]
It's so strange that something like that can even happen. When I get some time I will investigate that and see if I can come up with a fix for it. Not being able to see and remove broken config entries from the frontend is a very bad experience.
