### ISSUE TITLE
Can't pair with Denon AVR-X6400H.

### ISSUE THREAD

**Issue by scyto** [postlund/pyatv#1554]
### Describe the bug

My Denon AVR-X6400H is detected by hass auto discovery.
I get prompted for pin when no pin is required on these devices.

### Error log

```
2021-12-20 14:56:33 ERROR (MainThread) [custom_components.apple_tv.config_flow] Authentication problem
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 33, in error_handler
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/auth/hap.py", line 77, in finish_pairing
resp = await self.http.post(
File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 359, in post
return await self.send_and_receive(
File "/usr/local/lib/python3.9/site-packages/pyatv/support/http.py", line 412, in send_and_receive
raise exceptions.HttpError(
pyatv.exceptions.HttpError: HTTP/1.1 method POST failed with code 470: Connection Authorization Required
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/apple_tv/config_flow.py", line 424, in async_step_pair_with_pin
await self.pairing.finish()
File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/pairing.py", line 74, in finish
await error_handler(
File "/usr/local/lib/python3.9/site-packages/pyatv/support/__init__.py", line 41, in error_handler
raise fallback(str(ex)) from ex
pyatv.exceptions.PairingError: HTTP/1.1 method POST failed with code 470: Connection Authorization Required
```
****

### How to reproduce the bug?

Power on Denon
Reboot hass if needed to force redection.
Wait for denon to be discovered.
Start setup
Get prompted for pin.
No pin shown on screen.

### What is expected behavior?

Should not be prompted for pin.
Should be added as airplay device.

### Operating System

home assistant (linux) 2021.12.3

### Python

3.9

### pyatv

0.9.8

### Device

Denon AVR-X6400H 

### Additional context

its is airplay 2 according to this https://support.denon.com/app/answers/detail/a_id/6712/~/denon-avrs-supporting-airplay-2

**Comment by scyto** [comment]
does this help?

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/alex/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/alex/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/alex/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Entry | Info
-- | --
Name | 0005CDE3789E@Denon   AVR-X6400H
Type | _raop._tcp.
Type   Description | Remote   Audio Output Protocol (AirTunes)
Domain | local.
Port | 39833
Host   Name | Home-Theater.local.
Address | 192.168.1.100:39833
Data: |  
da | true
et | 0,4
vs | 366.0
cn | 0,1
pk | 1e885b6d39f109a7aaa909a849a94a5969b26d66b5a67e55076e749690c7a941
am | AVR-X6400H
ft | 0x445F8A00,0x1C340
md | 0,1,2
vn | 65537
sf | 0x4
fv | p20.1.583.161
tp | UDP




</body>

</html>

**Comment by scyto** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/alex/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/alex/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/alex/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Name | Denon   AVR-X6400H
-- | --
Type | _airplay._tcp.
Type   Description | Protocol   for streaming of audio/video content
Domain | local.
Port | 39833
Host   Name | Home-Theater.local.
MAC | 00:05:CD:E3:78:9E
Address | 192.168.1.100:39833
Data: |  
manufacturer | Sound   United
protovers | 1.1
model | AVR-X6400H
deviceid | 00:05:CD:E3:78:9E
srcvers | 366.0
pi | e87828b1-d062-4be0-81b2-8f88dcd57f9f
flags | 0x4
rsf | 0x0
acl | 0
pk | 1e885b6d39f109a7aaa909a849a94a5969b26d66b5a67e55076e749690c7a941
gid | e87828b1-d062-4be0-81b2-8f88dcd57f9f
serialNumber | AVP15170801143
features | 0x445F8A00,0x1C340
gcgl | 0
fv | p20.1.583.161




</body>

</html>

**Comment by postlund** [comment]
Thanks for the detailed post 👍 I noted this for other devices as well and I think I found the reason for it. Hopefully #1544 will fix it in the next pyatv release. Due to limited support of AirPlay in pyatv, we will be limiting which devices are auto-discovered to Apple TVs, HomePods and AirPort Expresses. But you can still add the device manually and hopefully that will work. I will let you know when the next release is out and when I have updated the beta component so you can try it out.

**Comment by scyto** [comment]
Thanks, sounds good. TBH I didn't even know Denon had added airplay until this component detected it.

I agree limiting detection is a sensible way to go. Happy to try an update beta, I added 5 ATV yesterday with zero discovery or pin issues.  Have yet to test most functions. Nice work on this and the integration. Thanks.

**Comment by postlund** [comment]
Great 👍 If you want to help out right away, you can just run `atvremote` directly. Either install it (some instructions are [here](https://pyatv.dev/documentation/#installing-pyatv)) or run via docker:

    $ docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan

Look for the result for your Denon receiver. Hopefully `Pairing` should say `NotNeeded`. If that's the case you should for instance be able to stream a file like this:

    $ docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote -s <ip to receiver> stream_file=https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3

**Comment by scyto** [comment]
step one done, will test streaming later, looks good on denon, and interestingly i had forgot the sony - that was not detected in hasss.

Included all results including ATVs just incase complex env is interesting
(and no i am not bothered about posting IP and MACs they are not secrets :-) )
```
Scan Results
========================================
       Name: Denon AVR-X6400H
   Model/SW: AVR-X6400H, Unknown OS
    Address: 192.168.1.100
        MAC: 00:05:CD:E3:78:9E
 Deep Sleep: False
Identifiers:
 - 00:05:CD:E3:78:9E
 - 0005CDE3789E
Services:
 - Protocol: AirPlay, Port: 51214, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 51214, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Sony
   Model/SW: MSA4G-N108, Unknown OS
    Address: 192.168.1.150
        MAC: 04:5D:4B:B2:72:8A
 Deep Sleep: False
Identifiers:
 - 04:5D:4B:B2:72:8A
 - 045D4BB2728A
Services:
 - Protocol: AirPlay, Port: 5000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded
 - Protocol: RAOP, Port: 5000, Credentials: None, Requires Password: False, Password: None, Pairing: NotNeeded

       Name: Master Bed ATV
   Model/SW: Apple TV 4K, tvOS 14.6 build 18L569
    Address: 192.168.1.187
        MAC: D0:D2:B0:8D:B2:4D
 Deep Sleep: True
Identifiers:
 - D0:D2:B0:8D:B2:4D
 - D0D2B08DB24D
 - 0AA6B762-2763-4DA1-B684-052344C98271
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: MRP, Port: 59045, Credentials: None, Requires Password: False, Password: None, Pairing: Optional

       Name: Guest Room ATV
   Model/SW: Apple TV 4K, tvOS 15.3 build 19K5527e
    Address: 192.168.1.138
        MAC: D0:D2:B0:99:CE:F8
 Deep Sleep: True
Identifiers:
 - D0:D2:B0:99:CE:F8
 - 276A1667-5600-4E2E-8D34-430999C20540
 - D0D2B099CEF8
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: MRP, Port: 49154, Credentials: None, Requires Password: False, Password: None, Pairing: Optional (Disabled)
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory

       Name: Living Room ATV
   Model/SW: Apple TV 4K, tvOS 15.2
    Address: 192.168.1.119
        MAC: 6C:4A:85:01:B1:D0
 Deep Sleep: False
Identifiers:
 - 6C:4A:85:01:B1:D0
 - 6C4A8501B1D0
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory

       Name: Basement ATV
   Model/SW: Apple TV 4K, tvOS 14.7 build 18M5552d
    Address: 192.168.1.181
        MAC: 50:DE:06:8C:9F:C7
 Deep Sleep: True
Identifiers:
 - 50:DE:06:8C:9F:C7
 - 8D7036EA-AF52-4898-9496-6DB1A16E4DDC
 - 50DE068C9FC7
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: MRP, Port: 56400, Credentials: None, Requires Password: False, Password: None, Pairing: Optional
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory

       Name: Study ATV
   Model/SW: Apple TV 4K (gen2), tvOS 15.2
    Address: 192.168.1.104
        MAC: 4C:AB:4F:8F:42:F3
 Deep Sleep: False
Identifiers:
 - 4C:AB:4F:8F:42:F3
 - 4CAB4F8F42F3
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
```

**Comment by scyto** [comment]
for the streaming i get this for both the sont and the denon

```alex@Docker02:~$ sudo  docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote -s 192.168.1.150 stream_file=https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3
2021-12-24 00:06:14 ERROR [pyatv.scripts.atvremote]: Could not find any Apple TV on current network```

**Comment by scyto** [comment]
closing as fixed
