### ISSUE TITLE
scan not finding all devices on network

### ISSUE THREAD

**Issue by langmeister** [postlund/pyatv#1562]
### What do you need help with?

I understood the latest version of pyatv supports tvOS15 devices.

I am using 0.9.8; while atvremote --debug scan is finding my AVR (support for airplay) and an older ATV running 14.0.2, it is not finding my ATV 4K (running tvOS 15.x).  However, other devices on the network (iPads, Mac) can see it just fine.

**Comment by postlund** [comment]
That's strange, it should show up. Are they all on the same network or are you using an MDNS relayer/responder? Also, can you try if `atvremote -a <ip of device> scan` "finds" the device?

**Comment by langmeister** [comment]
Everything is on a single, private class-c network (gateway is a Ubiquiti USG and wifi is served up with a pair of UniFi APs).  Multicast DNS was enabled; for giggles, I tried to disable but didn't change anything.

The ATV that is not being found (tvOS 15.1.1) is connected to ethernet.  The APs and ATV connect into the same gigabit switch.

When scanning the specific ID, it does show up, though.

I plan to use through Node-Red.  Unfortunately, you have to select the device from a drop-down, and it doesn't allow you to manually enter an IP, so I might be stuck until it starts showing up in the general device scan list.

**Comment by postlund** [comment]
When you say *When scanning for a specific ID...* I assume you mean specifying the `-I` or `--id` flag? Just to be sure. Would be really strange if that is the case since it's the exact same scanning method, just, an "exit early" filter. Output from `atvremote --debug scan` might help me troubleshoot in that case.

**Comment by langmeister** [comment]
Sorry for not being clear - hopefully this makes more sense to you:

"scan" shows the output of atvremote --debug scan
"direct" shows the output of atvremote --debug -s 192.168.2.167

[scan.txt](https://github.com/postlund/pyatv/files/7764654/scan.txt)
[direct.txt](https://github.com/postlund/pyatv/files/7764655/direct.txt)

**Comment by postlund** [comment]
Huh, really strange. Never seen that behavior before. Can you try `atvremote --mdns-debug --debug scan` as well? It will show more of the actual traffic, might help tracking down if the device is responding at all.

**Comment by langmeister** [comment]
(debug sent via email)

As a test, I disconnected the ethernet on the ATV so that it would connect to Wifi.  It shows up in the scan without issue.

**Comment by postlund** [comment]
Based on the logs I could only see one response from the device, which isn't really normal. Not sure why that is and it is very hard to debug. It's also very strange that in works on Wifi as it's not very uncommon that wifi has multicast filtering to lower bandwidth usage. Does it stop being discovered if you connect Ethernet again? Any difference if you restart the device?

**Comment by langmeister** [comment]
Ok this is bizarre.  I plugged the ethernet back in (which reverted it back to its original IP).  It's now being discovered.  I'm going to do more tests (to rule out network issues), but am happy to close this off for now.

**Comment by langmeister** [comment]
Ok...so after 15 minutes, it stopped being discovered again.

As a test, I installed pyatv on another RPI that's plugged into the same switch. It also cannot find it.

Baffling...

**Comment by postlund** [comment]
I wonder if it has anything to do with it going to sleep or something? If you wake it up so you can see the main screen, is it still not detected?

**Comment by langmeister** [comment]
> I wonder if it has anything to do with it going to sleep or something? If you wake it up so you can see the main screen, is it still not detected?

Afraid not.  The ATV it set to never sleep, and I tried “waking up from screensaver” which didn’t make a difference, either.

I also tried updating to 15.2 (from 15.1.1) in case it was a firmware bug, and updated my Unifi Gateway.  Neither made a difference.

The only two theories I have right now are:
- something on my lan is blocking the multicast when looking for the mac address (I had something similar with some wifi-enabled lights way back when), 
- there’s something funky with tvOS15

I might update my older, non-4K ATV to tvOS15 later today, and see if it starts encountering the same problem.

**Comment by langmeister** [comment]
I think I might have found the issue (and happily for you, it's not a pyatv issue).

While my gigabit "easy smart" switch had a bare-bones config, IGMP snooping was enabled.  After disabling this, the missing ATV is now showing up on scans.

I'll close this off, but will reopen if it reverts back to the undesirable behaviour.  Thanks for all your help!

**Comment by postlund** [comment]
Thanks for reporting back @langmeister! Sounds like a potential issue. Let's hope it keeps working!
