### ISSUE TITLE
Not able to control the Apple HD Device using the pyatv commands after the OS Upgrade to 15.x.x Version

### ISSUE THREAD

**Issue by MalathiBethu** [postlund/pyatv#1568]
### Describe the bug

When we are controlling the Apple HD Device via an IPAddress using atv commands It does not perform the specific actions properly say if we give the down command it navigates to the complete down on the device and after that if we press up it does not perform any action. Whereas the commands work properly in Apple 4K Devices.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

1 Download pyatv library
2 atvremote --scan-hosts ipaddress scan // to fetch the ipaddress of the device
3. In command prompt we should use the below commands.
4. atvremote -s <IPAdresss of the device> -protocol companion pair // This will ask to enter a pin which is displayed on the device Once we enter the PIN it generates a passcode
5. atvremote -s <IPaddress of the device> --airplay-credentials <passcode generated in the above steps <command as down,up etc>

### What is expected behavior?

when pressed right once it should navigate to right on the device only once.

### Operating System

windows

### Python

3.9

### pyatv

0.9.3

### Device

15.1.1

### Additional context

When given right command once it navigates to the extreme right on the device by pressing right multiple times. The same happens with other commands as well

**Comment by postlund** [comment]
It's fixed in 0.9.8, please upgrade and try that.

**Comment by postlund** [comment]
I will close this due to lack of response and because this is fixed in 0.9.8. Feel free to open again if problem still exists.

**Comment by MalathiBethu** [comment]
Sure.. It works fine in the latest version.


With Regards,
Malathi Bethu
