### ISSUE TITLE
episode_number on ATV 4K

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#1573]
### What feature would you like?

Is there any way, at all, to get episode_number and other fields marked as supported with DMAP only? 

I realize we have to rely on the app (e.g. Netflix, Computers, TV Shows..., HBO Max) to actually fill in the fields on their end...

### Describe the solution you'd like

Add these to Playing class

### Any other information to share?

My use case would be to (where possible) to show the season and episode number and show title in the browser and allow click on this to take you to imdb page for show/season/episode number.

**Comment by postlund** [comment]
Episode number, season number and series name are already supported. But, as you say, it is up to the app to set these fields and I think I have only ever seen Apple do that 😕 It's a bit sad that apple isn't forcing app developers to provide meaningful metadata. At least to some extent. It is also only implemented by MRP, but I guess DMAP should also be pretty easy to fix with the correct tags.

**Comment by mschwartz** [comment]
I’ve not seen anything but None for those fields for any app, including streaming on the LAN using home sharing.

bummer

**Comment by mschwartz** [comment]
I have some information that might be of interest.

I am watching the NBA app.  The data coming in vain pyatv has:

* app: “NBA”
* media type: unknown
* device state: playing 
* Position: 1492
* Total time: 1800

so we blame NBA for not providing any more info, like title should be “Orlando at Chicago”…

but, if I look at what’s playing in control enter on my iPad, there’s a small NBA app logo.  It would be nice to know where they get the image to show on the iPad.  I am watching the NBA app on the Apple TV, obviously.   See the app logo on the lower right of the touchpad area.

![F7B8218E-A15C-435C-91DE-5AAB10FF420A](https://user-images.githubusercontent.com/329637/148005966-8be16077-94cb-45b0-96fe-6b5993509844.jpeg)

**Comment by mschwartz** [comment]
Regarding above, they can’t assume I have the app on my iPad to get the artwork from.

**Comment by postlund** [comment]
I believe they look up the icon locally in case the app is installed, otherwise use the iTunes API to find a URL and download it. My intention is to do something similar, see #1536. It is the bundle identifier, e.g. `com.netflix.Netflix` that is used for lookups.
