### ISSUE TITLE
$ atvremote scan doesn't work after installation

### ISSUE THREAD

**Issue by nicomzk** [postlund/pyatv#1574]
### What do you need help with?

Hey guys,

after installing pyatv the command atvremote doesn't work for me. The console says "bash: atvremote: command not found". My homebridge is running on a raspberry pi.

Some lines from my console:
`pi@homebridge:/var/lib/homebridge $ pip3 install pyatv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyatv in /home/pi/.local/lib/python3.9/site-packages (0.9.8)
Requirement already satisfied: cryptography>=2.6 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (36.0.1)
Requirement already satisfied: protobuf<4,>=3.18.0 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (3.19.1)
Requirement already satisfied: aiohttp<5,>=3.1.0 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (3.8.1)
Requirement already satisfied: bitarray>=2.1.2 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (2.3.4)
Requirement already satisfied: srptools>=0.2.0 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (1.0.1)
Requirement already satisfied: mediafile>=0.8.1 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (0.9.0)
Requirement already satisfied: zeroconf>=0.28.2 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (0.38.1)
Requirement already satisfied: ifaddr>=0.1.7 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (0.1.7)
Requirement already satisfied: miniaudio>=1.45 in /home/pi/.local/lib/python3.9/site-packages (from pyatv) (1.45)
Requirement already satisfied: frozenlist>=1.1.1 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (5.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (2.0.9)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/pi/.local/lib/python3.9/site-packages (from aiohttp<5,>=3.1.0->pyatv) (1.7.2)
Requirement already satisfied: cffi>=1.12 in /home/pi/.local/lib/python3.9/site-packages (from cryptography>=2.6->pyatv) (1.15.0)
Requirement already satisfied: pycparser in /home/pi/.local/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.6->pyatv) (2.21)
Requirement already satisfied: mutagen>=1.45 in /home/pi/.local/lib/python3.9/site-packages (from mediafile>=0.8.1->pyatv) (1.45.1)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from mediafile>=0.8.1->pyatv) (1.16.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<5,>=3.1.0->pyatv) (2.10)
pi@homebridge:/var/lib/homebridge $ atvremote scan
bash: atvremote: command not found
pi@homebridge:/var/lib/homebridge $ `

(I'm pretty new to this and only want to turn my Apple TV 4K on/off right in the HomeApp tbh)

Would very nice to get some advise :)

**Comment by postlund** [comment]
It's because you are installing it to your home directory, so the scripts does not end up in your PATH, I.e. you shell won't find them. I recommend a virtual environment instead. You have some instructions here:

https://pyatv.dev/documentation/#virtual-environment

Another way is to run via docker. Instructions are in the same place. Let me know if you have any issues!

**Comment by nicomzk** [comment]
yes this helped a lot, thanks! installation has worked now.

But now the control mrp pair command isn't working:
<img width="1134" alt="Bildschirmfoto 2022-01-13 um 21 09 43" src="https://user-images.githubusercontent.com/96869422/149402256-ce896d33-973e-418e-952a-a1010a7af148.png">

**Comment by postlund** [comment]
You cannot (and shall not) pair of your devices is running tvOS 15. Just to `airplay` and possibly `companion` if you want to launch apps and things like that.

**Comment by nicomzk** [comment]
Okay... so is there any solution atm to control my appletv, meaning turning it on and off, directly inside the Home app? Since npm install -g node-appletv-x is also not working with tvOS15 I'm curious if it's even possible right now or if we have to wait for apple to add this function the HomeKit by themself?

**Comment by nicomzk** [comment]
because I thought that pyatv offers a workaround for this problem, to still be able to control your atv even when it's running tvOS15

**Comment by postlund** [comment]
MRP is tunneled over AirPlay instead of being it's own protocol. So pairing AirPlay gives back the same functionality you had prior to tvOS 15. Pairing companion gives you proper power management (turn_on/turn_off work like they should) and app management. So those two protocols in combination gives you more or less all functionality you need. If you want to stream audio, make sure to pair `raop` as well.

**Comment by postlund** [comment]
Did you get this to work?

**Comment by nicomzk** [comment]
Hey, I haven‘t had the time for it since your last comment but I will let you know as soon as I‘m working on it again!

**Comment by nicomzk** [comment]
I found some time to look into this again and after some searching I found out about the companion protocol to pair the atv over AirPlay which you mentioned in your comment. I couldn't find any helpful thread about how to use that protocol or even "how to get it running". 
Or did I understood something totally wrong?
Please elaborate on your comment.

**Comment by postlund** [comment]
I think I will have to refer you to the author of the plug-in for support on this unfortunately.
