### ISSUE TITLE
new email

### ISSUE THREAD

**Issue by Neustradamus** [postlund/pyatv#1577]
### What do you need help with?

@postlund: Hello, I have sent a second mail, have you received?
Please reply in private.
Thanks in advance.

**Comment by postlund** [comment]
Hi, yes I have received it. What is the best way to respond with (a private) message?

**Comment by Neustradamus** [comment]
In private of course ^^

Thanks!

**Comment by postlund** [comment]
Yeah, but via email or what do you prefer?

**Comment by Neustradamus** [comment]
Yes by email to talk, it is better

**Comment by postlund** [comment]
Then I need an address, I only have emails from GitHub.

**Comment by Neustradamus** [comment]
@postlund: Maybe in spams folder? :/
I have sent two emails to you:
- 21-07-16
- 22-01-03

**Comment by Neustradamus** [comment]
@postlund: Have you received?

**Comment by postlund** [comment]
@Neustradamus Yeah, will respond later tonight.

**Comment by Neustradamus** [comment]
@postlund: Thanks!
