### ISSUE TITLE
Aborted

### ISSUE THREAD

**Issue by shadowpuck99** [postlund/pyatv#1578]
### Describe the bug

I'm certain this is related to other reported bugs that are similar, but, i'm uncertain as to next steps or how to clean out the entries in the core_config.entries file if that's what is needed.

I was able to add two of my ATVs that had not been in HA before.  However, when I try to add in the one I did have, I get prompted to enter the three pins and get the "Aborted" UI notification.  

This particular ATV is an ATV HD running latest OS (15.2).  I moved it to a new room and renamed it before trying to add it back into HA.

It's also perhaps worth noting that it does not show up to be added in HA or when I tell it to add it by adding the integration.  if I type in the new name or the IP, it is then found and I can go through the PIN entry process, but it aborts as noted.

![](https://community-assets.home-assistant.io/original/4X/a/b/6/ab665545525fd822c370335ce7715c72553249f0.png)

_Originally posted by @Colorado4Wheeler in https://github.com/postlund/pyatv/issues/1548#issuecomment-997216524_

### Error log

I did enable logging per this instruction (https://www.home-assistant.io/integrations/apple_tv/) but nothing appears beyond normal system logs

### How to reproduce the bug?

Add AppleTV integration in HA
add ATV either by IP or Name
Enter PINs as prompted
After 3rd pin is entered abort message is displayed

### What is expected behavior?

ATV once added in HA, can be setup as an entity, etc.

### Operating System

HA - Linux

### Python

Other

### pyatv

Latest version

### Device

Apple TV HD 15.2

### Additional context

I'm suspecting since this was a previously entered ATV I have some sort of conflict in the config entries file but I'm uncertain how to address that.

**Comment by postlund** [comment]
I have tried in any way I can think of to replicate this locally, but the device shows up under *Integrations* or generate an error message no matter what I do. It would be interesting if you could share how the config entry actually looks like as that might give me some clues. Output from `atvremote scan` would be helpful as well, if you can manage that. But how the config entry looks like is more important to start with. Best would be if you sent it by email to me (address is in in my profile).

**Comment by shadowpuck99** [comment]
thank you! i have sent you an email.

**Comment by postlund** [comment]
Ok, so the conclusion here is that the integration was *ignored*. After un-ignoring it, everything works again. I guess we can close it based on that?

**Comment by shadowpuck99** [comment]
i agree - as soon as the integration for this device was un-ignored, it immediately worked.
