### ISSUE TITLE
Getting App Name/ID from API

### ISSUE THREAD

**Issue by 13mralex** [postlund/pyatv#1582]
### What do you need help with?

Hello, I am having trouble figuring out the api. I am using the example webserver script as a base. While everything else works great, I can't find a way to return the current app name/id. I can do `atv.metadata.playing()` and get basic stats:
```
  Media type: Music
Device state: Playing
       Title: Stereo Hearts (feat. Adam Levine)
      Artist: Gym Class Heroes
       Album: The Papercut Chronicles II
       Genre: Pop
    Position: 86s
      Repeat: Off
     Shuffle: Off
```

I can do this with `atvremote` with success:
```
atvremote -i <id> --airplay-credentials <creds> app
App: Music (com.apple.TVMusic)
```

What do I need to call within the api to return the app name and id?

**Comment by postlund** [comment]
You have an `app` property in metadata for that. It's easiest to find in the API reference here:

https://pyatv.dev/api/interface#pyatv.interface.Metadata.app

**Comment by 13mralex** [comment]
I must be doing something wrong then. When I do that, I get:
`atv.metadata.app()`: `'FacadeMetadata' object is not callable` or
`status = atv.metadata() ... status.app`: `'App' object is not callable`

**Comment by 13mralex** [comment]
Nevermind, I got it. I was still using `await` and parenthesis and I guess that wasn't neccessary.

**Comment by postlund** [comment]
Yeah, it's not a coroutine so it's not needed.
