### ISSUE TITLE
Via pyatv CLI, is it possible to know if Apple TV is on, off or in standby state?

### ISSUE THREAD

**Issue by Herbertzz** [postlund/pyatv#159]
Via pyatv CLI, is it possible to know if Apple TV is on, off or in standby state?

**Comment by jdebardi** [comment]
I have been trying to work this out, the problem is, every kind of packet you send to the ATV to test it will wake it up!
I read one thread where a guy actually put a light dependant resistor in front of the LED and used that to tell!!

**Comment by Herbertzz** [comment]
> I have been trying to work this out, the problem is, every kind of packet you send to the ATV to test it will wake it up!
> I read one thread where a guy actually put a light dependant resistor in front of the LED and used that to tell!!

Good idea, thank you very much!!!
