### ISSUE TITLE
how to visualize cover on the media player when streaming HTTP content on HomePod mini

### ISSUE THREAD

**Issue by labactani** [postlund/pyatv#1599]
### What do you need help with?

I am not sure if either this is not supported yet or I do not know how to make it work.

I can play HTTP radio stream on my HomePod mini with no issues, but the cover of my mini:media player (or the standard media player) looks like this:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/80811693/148942144-f4a9742b-c404-433a-bfe4-749424261583.png">

Is there a way to show the radio station information/cover image same as if I play the radio station using the TuneIn service embedded in the HomePod mini?

<img width="388" alt="image" src="https://user-images.githubusercontent.com/80811693/148942495-2653ec57-0a8e-46cc-953b-5a0847fd40bc.png">

Or this is not supported/implemented yet?

thanks!

**Comment by postlund** [comment]
It's technically possible to implement but it's not supported yet. I can add it as a feature request.

**Comment by labactani** [comment]
That would be awesome!!!

**Comment by postlund** [comment]
Just want to make it clear that I'm aiming for programmatically supporting custom metadata when starting the stream, e.g. you can provide title or artwork (image) when starting to stream. It won't be read from the source file.

**Comment by postlund** [comment]
It is notes possible to do this with custom metadata as described here:
https://pyatv.dev/development/stream/#custom-metadata
I however find implementing it in Home Assistant as out of scope for this project.
