### ISSUE TITLE
HASS apple TV OS 15 playing NLZIET always status "paused"

### ISSUE THREAD

**Issue by tomdh76** [postlund/pyatv#1601]
### Describe the bug

I am using the beta version of the apple tv integration for HASS as my apple tv has OS 15. The status of the apple tv is correctly displayed when playing netflix (playing, paused) but not for NLZIET, a streaming app for Dutch TV. The status is always "paused" The rest of the info is correct like media_title and app_name

### Error log

```log
<place log here>
```
I cannot find logs

### How to reproduce the bug?

It is always in status paused and during playing several times the status is updated to "paused"

### What is expected behavior?

That during playing the status is reported as playing

### Operating System

home assistatn

### Python

3.8

### pyatv

0.8.2

### Device

Apple TV os 15.2

### Additional context

none

**Comment by postlund** [comment]
Does it work as expected in iOS?

**Comment by tomdh76** [comment]
You mean using my iphone and playing and resuming the stream? That works, I can start and stop the stream and in the screen it correctly shows if it is playing or pausing

**Comment by postlund** [comment]
Ok, great! If iOS shows that it is playing then we can conclude that it's a bug. I will need debug logs to troubleshoot this. Basically do this (do not enable any other log points, it makes the output too hard to read):

https://github.com/postlund/hass-atv-beta#debug-logs

Start playing something that is shown as "paused" in Home Assistant but playing in iOS. Then extract the log and send it to me by email. Address is in my profile.

**Comment by tomdh76** [comment]
I have send the logs but after a restart of HASS status of the mediaplayer is correct...

**Comment by postlund** [comment]
Ok, that's strange. I'll have a look at the logs as soon as I have some time.

**Comment by tomdh76** [comment]
Hi,
It stopped working again. Always is status on pause. See logs


Van: Pierre Ståhl ***@***.******@***.***>>
Verzonden: donderdag 13 januari 2022 11:29
Aan: postlund/pyatv ***@***.******@***.***>>
CC: Tom ***@***.******@***.***>>; Author ***@***.******@***.***>>
Onderwerp: Re: [postlund/pyatv] HASS apple TV OS 15 playing NLZIET always status "paused" (Issue #1601)


Ok, that's strange. I'll have a look at the logs as soon as I have some time.

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpostlund%2Fpyatv%2Fissues%2F1601%23issuecomment-1012001555&data=04%7C01%7C%7C13454f7747cb4a0bc98c08d9d67f8faf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637776665626523162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wUi7ebogmTi%2BO9INUXVOfIFrGPBOZdct2%2Bwn3CaNXQc%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKCIXH4CL2A3PQITDSBWL6TUV2SQBANCNFSM5LXI3UBA&data=04%7C01%7C%7C13454f7747cb4a0bc98c08d9d67f8faf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637776665626523162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F0rN5GoF1n6%2F%2BpEck4P0RmBmPz8pWnlOwg%2FEwWKqkIE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C13454f7747cb4a0bc98c08d9d67f8faf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637776665626523162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0towK%2Fc%2FEWVezmxEIOHJgR1sREb4d51ffOBThLAFpto%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C13454f7747cb4a0bc98c08d9d67f8faf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637776665626523162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cTCqJFWqr7MBKalZmZG60qar1pjuKjMW%2BAMWpuvv2Jc%3D&reserved=0>.

**Comment by postlund** [comment]
I have run into the same problem. iOS reports that it is playing, but current position is stuck at a fixed position so I still believe it's not acting correctly. Is it the same for you?

**Comment by tomdh76** [comment]
Yep, right now the status on IOS is playing but in HASS it is on pause. The "media position" in HASS keeps on having the same number. However if I look in the IOS screen the time of playing also keeps the same ! If I in ios stop and then resume the "media position" is being updates but status keeps the same on pausing. It seems though to randomly work sometimes.

**Comment by postlund** [comment]
I think the behavior is a combination of a bug in tvOS/the app and also pyatv. A player in tvOS can either in "Stopped" or "Playing" (there are a few other states which are never used). One must however look at "playback rate" as well, to determine what is actually happening. If it is zero, then media is assumed to be paused. Playing would be 1.0 and everything else is either fast forward or rewind (there's no such thing as "slow motion" here). In my case, the problem seems to be that the playback state is "Playing" but playback rate is (incorrectly) reported as zero. It seems like iOS just derives that the device is playing by looking at the player state and not the playback rate. There have however been several cases in the past where playback state has been set to "paused" but playback rate set to 1.0, which is interpreted as playing. So it's not really consistent as there would be no way to derive a paused state... But I guess if playback state is "playing", I should always report as playing and only report paused in case player state is paused. It's so annoying, how hard can this be? How bad could they screw this up... Why the position is wrong is a mystery in itself, but I would it's a bug in tvOS.

**Comment by postlund** [comment]
Should be fixed by #1624.
