### ISSUE TITLE
How to pair Apple TV with Home Pod mini?

### ISSUE THREAD

**Issue by lancercncs1** [postlund/pyatv#1602]
### What do you need help with?

I am able to do TTS and play media with hass-atv-beta (so long as those are not mixed together!) however I am having real trouble pairing my Home Pod mini even though it is discovered by HASS.
I get the following messages even though my Home App is set so that everyone on the network has access to all of the devices:

1)**Confirm adding Apply TV**
_You are about to add Office of type Home Pod Mini to Home Assistant
To complete the process, you may have to enter multiple PIN codes._

2)**Pairing not possible**

_Pairing is required for Companion but it is disabled on this device. Please review potential access restrictions (e.g. allow all deices on the local network to connect) on the device.
You may continue without pairing this protocol, but some functionality will be limited._

And if I continue with the process, it aborts and does not get paired. What may be going on here and how would I resolve?

Thank you!

**Comment by postlund** [comment]
This is most likely the same issue as in #1586. I have a potential fix there but need verification.

**Comment by lancercncs1** [comment]
Oddly enough somehow I got my Home Pod mini paired this time instead of aborting.. I do not know what happened, but I'll take it! :)

**Comment by postlund** [comment]
I believe that I look at an unrelated flag that might have changed for some reason and that's likely why it started to work. But I think #1586 is the proper fix.

**Comment by postlund** [comment]
Should be fixed on master now, will be part of 0.10.0.

**Comment by lancercncs1** [comment]
Great! I’ve redownloaded the master version. THANKS!!!
