### ISSUE TITLE
Integration of 2 different Apple TV failed with Abort message

### ISSUE THREAD

**Issue by Moustik2002** [postlund/pyatv#1606]
### Describe the bug

Similar issue reported  in #1548 but my situation is kinda different.

I've already succeffully add my Apple TV named 'Bureau' (Desk Room) and i'm able to control it through media control.
Now i'm trying to add my other Apple TV called 'Séjour (Dinning Room) through the same process but i'm still experiencing same error message :

![image](https://user-images.githubusercontent.com/7987482/149597383-2085ed4e-b04c-4bea-921f-42b1cdada081.png)

Despite the fact i'm dialing the 3 pin code quickly (no time out happening there).

BTW there is also a glitch when pin begins with a 0, it doesn't show up after typing second digit ( ie. 0798 will show 798, 0056 will show 56)

### Error log

no error reported in HA about it

### How to reproduce the bug?

Add a dsecond Apple TV and try add it throught beta integration

### What is expected behavior?

to be able to add my second device

### Operating System

Windows

### Python

3.9

### pyatv

don't know where to find it

### Device

Apple TV 4K 15.3

### Additional context

nothing else to add

**Comment by postlund** [comment]
You probably already have it added but it is ignored. Try showing ignored devices in the integrations page.

**Comment by Moustik2002** [comment]
indeed ! i saw all of them. I feel idiot now :).
I've activated it and now I able to play with Thx !

![image](https://user-images.githubusercontent.com/7987482/149623221-0c6b3b31-bafd-4898-8caf-44f6bdd7535a.png)

**Comment by Moustik2002** [comment]
oddly since i've set 2 differents apple TV integration i'm not able to use it naymore through media control.

Get this error message in log:

Logger: homeassistant.components.apple_tv
Source: components/apple_tv/__init__.py:282
Integration: Apple TV (documentation, issues)
First occurred: 22:24:11 (53 occurrences)
Last logged: 23:49:34

Failed to connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 228, in _connect_loop
    conf = await self._scan()
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 282, in _scan
    protocol = Protocol(self.config_entry.data[CONF_PROTOCOL])
KeyError: 'protocol'


Should i have to remove and create another brand new integration or is it a way to fix this ?

**Comment by Moustik2002** [comment]
nevermind i did a mess w/ another integration for android TV  and i put python files in the wrong folder.
