### ISSUE TITLE
iSponsorBlockTV uses pyatv

### ISSUE THREAD

**Issue by dmunozv04** [postlund/pyatv#1608]
### What do you need help with?

I am the author of [iSponsorBlockTV](https://github.com/dmunozv04/iSponsorBlockTV) and I wanted to let you know that it used pyatv. Thanks for creating this amazing library.

**Comment by postlund** [comment]
Cool, thanks for mentioning this! 👍 I will add a link on the main page. Should probably add a few other projects as well that I know of.

**Comment by dmunozv04** [comment]
Thanks!
