### ISSUE TITLE
Exclude AirPlay 2 devices from scan results

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1617]
### What feature would you like?

Pure AirPlay 2 devices are currently not supported by pyatv, so it would be good to exclude them until I manage to fix support. I'm not entirely sure how to conclude if a device is AirPlay 2-only, but I can make some guesses. All devices from apple support both versions, so they should pass through scanning as usual.

### Describe the solution you'd like

Just ignore devices supporting AirPlay 2, except for Apple devices (always include).

### Any other information to share?

This would open up for supporting generic AirPlay devices in home assistant. Because of filtering, only Apple devices are discovered now.

**Comment by cybergrimes** [comment]
Hey there-- I see this is mentioned in release notes for v3.0.0 but I'm now seeing the opposite. I'm seeing discovered Sonos devices that were not being discovered previously. Did I misunderstand the beta notes?

> This release will no longer discover generic AirPlay devices, e.g. Sonos speakers
> or TVs supporting AirPlay. Only Apple devices will be discovered.

**Comment by postlund** [comment]
Proper support for AirPlay 2 streaming has been added, so issue is not relevant.
