### ISSUE TITLE
Documentation on how to revert from hass-atv-beta to production

### ISSUE THREAD

**Issue by justinlawrence** [postlund/pyatv#1620]
### What do you need help with?

I installed hass-atv-beta to try out some of the upcoming new features, but am not able to revert back to the production version. I was thinking that it might be useful to add a small section to the documentation about how to revert back? (I was unable to find any information like that). Thank you.

**Comment by postlund** [comment]
What isn't working? There shouldn't be any real issues, other than it stops working when going back to current stable version (integration should still be there though). It should start working again when upgrading to beta or next stable release in February.

**Comment by mountainsandcode** [comment]
I'm also having some issues with this.
- Home Assistant version: 2022.02.0b4
- Previously had the custom_component installed, but the folder has been removed
- I've deleted all entries from the HomeAssistant config files core.config_entries, core.entity_registry, core.device_registry etc.
- I still get a persistent error being logged (even while not trying to add the integration) and I can't re-add the integration.

I'm not fully sure whether here or the HA repo is the right place to raise this, but given that the traceback links back to pyatv, I thought I'd start here. Appreciate any help you might be able to provide.

> Logger: homeassistant
> Source: config_entries.py:740
> First occurred: 14:06:32 (1 occurrences)
> Last logged: 14:06:32
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 6, in <module>
>     from pyatv import connect, exceptions, scan
>   File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 24, in <module>
>     from pyatv.protocols import PROTOCOLS
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/__init__.py", line 10, in <module>
>     from pyatv.protocols import airplay as airplay_proto
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/airplay/__init__.py", line 28, in <module>
>     from pyatv.protocols import mrp
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/__init__.py", line 56, in <module>
>     from pyatv.protocols.mrp import messages, protobuf
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/messages.py", line 8, in <module>
>     from pyatv.protocols.mrp import protobuf
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protobuf/__init__.py", line 6, in <module>
>     from .ProtocolMessage_pb2 import ProtocolMessage
>   File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/mrp/protobuf/ProtocolMessage_pb2.py", line 21, in <module>
>     _ERRORCODE = DESCRIPTOR.message_types_by_name['ErrorCode']
> AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 733, in async_create_flow
>     integration.get_platform("config_flow")
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 575, in get_platform
>     raise ImportError(
> ImportError: Exception importing homeassistant.components.apple_tv.config_flow
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
>     await gather_with_concurrency(
>   File "/usr/src/homeassistant/homeassistant/util/async_.py", line 174, in gather_with_concurrency
>     return await gather(
>   File "/usr/src/homeassistant/homeassistant/util/async_.py", line 172, in sem_task
>     return await task
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
>     flow, result = await task
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 740, in async_create_flow
>     raise data_entry_flow.UnknownHandler
> homeassistant.data_entry_flow.UnknownHandler

**Comment by justinlawrence** [comment]
> What isn't working?

@postlund apologies for the delayed response. The issue is that (1) all my Sonos speakers keep coming up as new integrations and (2) there is no 'ignore' button like there are for the other integrations. Personally, I'm not wanting my Sonos speakers to show as Apple TV integrations, because I have them configured under the Sonos integration. Hope that makes sense. Thanks.

**Comment by postlund** [comment]
Filters should make unsupported devices Not appearing anymore. If removing the Integration via HACS doesn't work, then files must be removed manually.
