### ISSUE TITLE
home assistant restart break the Apple TV integration

### ISSUE THREAD

**Issue by addich** [postlund/pyatv#1621]
### Describe the bug

I run HA with docker on a raspi with Ubuntu 64bit.
After stop and start the HA container the Apple TV integration does not work anymore.
To solve I have to login to configuration open the integration page and reload the Apple TV integration

### Error log

```log
<place log here>
```

### How to reproduce the bug?

working Home Assistant with working Apple TV integration.
Stop HA
Start HA
the Apple TV will be shown in status Off (instead standby). Any status change on Apple TV will not be reflected in HA

to resolve go into HA configuration and reload the Apple TV integration. (I have to do this after each HA restart)

### What is expected behavior?

after restart of HA the Apple TV integraion should work without additonal reload

### Operating System

Linux

### Python

3.9

### pyatv

 0.9.8 (HA Apple TV Beta 2.2.0)

### Device

Apple TV 4K tvOS 15

### Additional context

.

**Comment by postlund** [comment]
This will be fixed in the next update.

**Comment by postlund** [comment]
This should not be an issue anymore.
