### ISSUE TITLE
Reading the Screen Menu

### ISSUE THREAD

**Issue by emilbaron** [postlund/pyatv#1622]
### What do you need help with?

Hi,
 Thanks for this very interesting project.
I started playing around with the atvremote app and it looks great. i intend to use python in the future.
Used sofar the companion and airplay protocols to control the RC (it looks great). the third available protocol is RAOP, but i didnt try yet.
The AppleTV version is 15.2 and pyatv version is 0.9.8.
My question is regarding the TVsettings screen: if i accidentally changed to unsouported video format (4K) and screen becomes blank, is it possible to retrieve the available options with a "get..." command (what currently is on displayed by device), so i could change the format back?

Thanks,
Emil

**Comment by postlund** [comment]
Hey!

Unfortunately no. All of the protocols focus on media playback or specific functions, nothing on what it looks like on screen. So not much I can do I'm afraid.

**Comment by emilbaron** [comment]
OK, Pierre, understood.
It's still an excellent project :-)
