### ISSUE TITLE
Volume Down does not Work

### ISSUE THREAD

**Issue by nathanlbell** [postlund/pyatv#1625]
### Describe the bug

When attempting to call service

service: media_player.volume_down
target:
  entity_id: media_player.living_room

Nothing occurs.  I am running 2.2 that I downloaded from HACS on a 4k appletv and I have all CEC commands set to run audio through my receiver.  Volume up works as expected and volume down or set volume do not work.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

call the following

service: media_player.volume_down
target:
  entity_id: media_player.<appletv.

### What is expected behavior?

volume should go down

### Operating System

Linux

### Python

Other

### pyatv

2.2.0

### Device

Appletv 4k TVOS 15

### Additional context

N/A

**Comment by postlund** [comment]
A lot of improvements have been made in regards to volume handling, so I think this is fixed. Can you verify with latest HA release?

**Comment by postlund** [comment]
Pretty sure this works now, please re-open if you still have problems.
