### ISSUE TITLE
Run pyatv in Homebridge Docker

### ISSUE THREAD

**Issue by carlosveny** [postlund/pyatv#1630]
### Describe the bug

Hello, I have Homebridge running in a docker in my NAS. I wanted to use this plugin to control my Apple TV. However when I try to install it inside the docker with the command `pip install pyatv` or `pip3 install pyatv` I get an error.
I've tried using this instruction `docker run -it --rm --network=host ghcr.io/postlund/pyatv:master atvremote scan` and it works from the terminal of the NAS but that is not useful for me because then it doesn't work in the Homebridge docker and I can't control de Apple TV.
What I'm looking for is to get the commands to work inside de Homebridge Docker.
Any help?

### Error log

```log
pip3 install pyatv
Collecting pyatv
  Using cached pyatv-0.10.0-py3-none-any.whl (399 kB)
Collecting bitarray>=2.1.2
  Using cached bitarray-2.3.5.tar.gz (88 kB)
Collecting zeroconf>=0.38.1
  Using cached zeroconf-0.38.1-py3-none-any.whl (105 kB)
Collecting miniaudio>=1.45
  Using cached miniaudio-1.46.tar.gz (546 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ksijvlnm/miniaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ksijvlnm/miniaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tq1x56m0
         cwd: /tmp/pip-install-ksijvlnm/miniaudio/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-tmb639o6/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-tmb639o6/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b4nusti_
           cwd: /tmp/pip-wheel-tmb639o6/cffi/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpr75pyhap', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ksijvlnm/miniaudio/setup.py", line 20, in <module>
        setup(
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpr75pyhap', '--quiet', 'cffi>=1.12.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### How to reproduce the bug?

Install pyatv inside a Homebridge Docker in a NAS or something similar and you will get the error.

### What is expected behavior?

As I've said, if I can get the commands to work inside the Homebridge Docker I could control the Apple TV with Homebridge.

### Operating System

Linux (QTS 5.0 NAS Operating System)

### Python

3.8

### pyatv

0.10.0

### Device

Apple TV HD tvOS 15.2

### Additional context

I am open to receive new ideas about running this plugin from the Homebridge Docker.
Any help is appreciated.

**Comment by carlosveny** [comment]
Yes, I've found a solution that works creating a new Container with both homebridge and pyatv.
Thanks!!

**Comment by postlund** [comment]
Excellent! Do you have any link for future references?

**Comment by mcarame** [comment]
> Yes, I've found a solution that works creating a new Container with both homebridge and pyatv.
> Thanks!!

Hi @carlosveny I'm interested too.
Could you please share the solution you found? Thanks!

**Comment by carlosveny** [comment]
Sorry @postlund GitHub didn't notify me about your comment. And @mcarame, I managed to create the container running Homebridge and pyatv, then I also managed to pair with my Apple TV using pyatv but I couldn't turn it on or off. It is a shame but I gave up and I found a workaround for what I was trying to do (turn my TV on and off) without using the Apple TV.

**Comment by mcarame** [comment]
> Sorry @postlund GitHub didn't notify me about your comment. And @mcarame, I managed to create the container running Homebridge and pyatv, then I also managed to pair with my Apple TV using pyatv but I couldn't turn it on or off. It is a shame but I gave up and I found a workaround for what I was trying to do (turn my TV on and off) without using the Apple TV.
> 
> However if you are interested, have a look at this Reddit thread: https://www.reddit.com/r/homebridge/comments/qsuvx4/apple_tv_plugins/hkg1t6k/?context=3 An user helped me to alter the Dockerfile in order to install homebridge and pyatv in the same container.

@carlosveny Thank You!
