### ISSUE TITLE
Port number for using atvremote with third party control system

### ISSUE THREAD

**Issue by manamandem** [postlund/pyatv#1634]
### What do you need help with?

Forgive me if I am not using the right terminology, but I'll try. I have successfully set up pyatv and atvremote on a Mac mini, and am able to control Apple TV via the terminal on the Mac mini. 

What I am trying to do is use my third party control system to use the same commands to control the Apple TV. I have been using Homebridge Apple TV remote plugin but the developer says it will not be developed further, plus atvremote has a wider range of commands. 

In order to use atvremote with my system I need to add it as a device with IP address (I guess this is the Mac mini IP not the Apple TV) plus a port number. I also need to form the command properly. In Terminal, the command formed eg atvremote --id C8:69:CD:7C:78:80 down works fine. But this command does not work in my system. 

I am currently using port 41952 which does not work with the command sent as mentioned. I have also tried port 41953, but this does not work. Additionally, some of the (what I call 'advanced') commands, mainly launching an app does not work, even in Terminal it says 'not supported'. I would be grateful for any guidance as to how to get the commands formed properly to work in my system, and a bonus would be to get the 'advanced' commands with feedback working too. In my control system, usually I have to add a command suffix like \x0D\x0A etc to the end of a command for a device, but this has not worked in the case of atvremote. 

I should note that the third party control system has its own processor which I guess would send commands to the Mac mini on which atvremote is installed.

Any guidance greatly appreciated and I am happy to reimburse anyone knowledgeable enough for a bit of 1:1 assistance with this.

**Comment by postlund** [comment]
Dealt via email.
