### ISSUE TITLE
Команда для отключения не запускается.

### ISSUE THREAD

**Issue by matcik890** [postlund/pyatv#1637]
Thank you for your work, it helps a lot. But I ran into such a problem. When you turn off your apple TV, sometimes the shutdown command does not work correctly and only calls the apple tv side window, but the device does not switch during sleep. Then after 20 seconds, the apple tv starts playing again. Sometimes the shutdown command is triggered correctly. I use Cmdswitch2 No Logs plugin in home bridge and disable apple tv with the command: atvremote -i 08:66:98:EF:55:E8 --airplay-credentials: 4843b438797.... turn_off. Could you please help me in this matter. Thank you in advance!!!🤝

**Comment by postlund** [comment]
I would recommend that you pair the Companion protocol as well and provide credentials (`--companion-credentials`) as the power management in MRP is not very good. Hopefully that will make things more stable.

**Comment by matcik890** [comment]
> I would recommend that you pair the Companion protocol as well and provide credentials (`--companion-credentials`) as the power management in MRP is not very good. Hopefully that will make things more stable.

It worked great. Your advice helped. I replaced --airplay-credentials with --сompanion-credentials and now the shutdown works correctly. Thanks!
