### ISSUE TITLE
custom integration 'apple_tv' does not have a version key in the manifest file and was blocked from loading

### ISSUE THREAD

**Issue by rrubin0** [postlund/pyatv#1639]
### Describe the bug

Home Assistant Core v 2021.12.10
AppleTV Beta v3.0.0 (upgrade from 2.2.0)

### Error log

```log
2022-02-02 17:41:07 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'apple_tv' does not have a version key in the manifest file and was blocked from loading. 
See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

### How to reproduce the bug?

Upgrade to 3.0.0 caused the error/blocked load upon restart, post-installation via HACS.

### What is expected behavior?

expect it not to be blocked upon restart.

### Operating System

Linux Ubuntu Server

### Python

3.9

### pyatv

latest

### Device

AppleTV 4K TVOS 15

### Additional context

none - possibly a simple manifest file missing?

**Comment by postlund** [comment]
I'm sure I added the version, so no idea how this happened. A new version has been pushed and should be available soon. Thanks for reporting!
