### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by systemcrash** [postlund/pyatv#1653]
### What do you need help with?

wonder whether that should read "sender"?

https://github.com/postlund/pyatv/blob/671c24a0b98346e5605e86d080af24a442d485ea/pyatv/protocols/mrp/protobuf/DeviceInfoMessage.proto#L41

my butterfly keyboard is a #$%^ing liability nowadays...

**Comment by systemcrash** [comment]
See #1654

**Comment by postlund** [comment]
Yeah, that's a typo. Thought I fixed that...
