### ISSUE TITLE
When change the volume of HomePod Mini in the Home App, the volume value does not change in HA

### ISSUE THREAD

**Issue by muxiachuixue** [postlund/pyatv#1662]
### Describe the bug

I imported my HomePod Mini to HA using the Apple TV integration. When I set the volume of the HomePod Mini in HA, it works well and the volume bar changes in the Home App. However, when I set the volume in the Home App, the volume value does not change in HA. It seems that the integration can not get the state of the volume while can control it.

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Set the value of HomePod Mini in Home App, the volume value of the device does not change in HA. 

### What is expected behavior?

When change the volume of HomePod Mini in the Home App, the volume value synchronously changes in HA.

### Operating System

Linux raspberrypi 5.10.60-v7l+

### Python

3.9

### pyatv

0.8.2

### Device

Homepod Mini 15.3

## System Health

version | core-2022.2.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.60-v7l+
arch | armv7l
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 1044
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | pending
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.8
disk_total | 58.2 GB
disk_used | 16.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Node-RED (10.2.0), Terminal & SSH (9.3.0), Portainer (2.0.0), AirSonos (3.2.0), Let's Encrypt (4.12.0), NGINX Home Assistant SSL proxy (3.1.1), Nginx Proxy Manager (0.11.0), ZeroTier One (0.12.2), AdGuard Home (4.4.2), InfluxDB (4.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 16
views | 4
mode | storage

</details>

**Comment by postlund** [comment]
This should be fixed now.
