### ISSUE TITLE
atvremote: command not found

### ISSUE THREAD

**Issue by MrKGado** [postlund/pyatv#168]
I am relatively inexperienced when it comes to python and command line in general, so this is likely my lack of understanding instead of a bug.  I have installed pyatv via pip, but do not know how to use the CLI in order to scan for my AppleTV.  Is there a particular program I need to run to make the CLI work?  Or can it be run in any Linux terminal window?  Every time I run 'atvremote scan' , I receive an 'atvremote:  command not found' error.  Thanks in advance for any help!

**Comment by postlund** [comment]
atvremote should be available as soon as you have pyatv installed. How did you install it? Did you use a virtual environment?

**Comment by MrKGado** [comment]
I did not install it in a virtual environment; I used Linux Mint 19 on my main pc.  It did start working, though I do not exactly know what I did to get it to work.  It started working after I installed home assistant, restarted my computer, and installed pyatv again.  

However, I installed it on my Raspberry Pi, and it worked immediately.  I am assuming it had to do with my python libraries, but I could be wrong.

**Comment by MrKGado** [comment]
Scratch the comment about working on the RPi.  I had installed it on a VM in virtualbox (Linux Mint 19) and got it working right from the beginning.  I did not set it up in it's own virtual environment aside from being in the VM.  I also downloaded python3 for my LG G7 cell phone and it worked easily.  

I am trying to get it working on the RPi and am having similar issues to what I experienced on my Linux Mint 19 pc.  

I installed wheel and pyatv via pip3, running python 3.5.3.

**Comment by postlund** [comment]
If you start a python3 shell an do "import pyatv", what happens?

**Comment by MrKGado** [comment]
It seems to import just fine.  It moves to the next line and does not give any errors.

**Comment by postlund** [comment]
Maybe PATH does not include where python scripts are installed? Could you check what it is set to?

**Comment by MrKGado** [comment]
pyatv and pyatv-0.3.12.dist-info are both in   
    /home/USER/.local/lib/python3.5/site-packages

When I print all the sys.path in the python interpreter, the following paths are printed:
   /usr/lib/python35.zip
   /usr/lib/python3.5
   /usr/lib/python3.5/plat-arm-linux-gnueabihf
   /usr/lib/python3.5/lib-dynload
   /home/USER/.local/lib/python3.5/site-packages
   /usr/local/lib/python3.5/dist-packages
   /usr/lib/python3/dist-packages

It seems that the PATH is looking at the correct directory.

**Comment by postlund** [comment]
What does $PATH point to?

**Comment by MrKGado** [comment]
I was just about to edit my previous post.  I still have much to learn about python and linux in general, but that was exactly the issue.  $PATH was not pointing to the directory with pyatv.  I navigated to /home/USER./local/bin where pyatv is located and was able to run atvremote.  

Thank you for your help, I learned quite a bit in the process.

**Comment by crxporter** [comment]
I currently trying to move to a different raspberry pi (raspbian) and I’m running into this problem. I’ve installed pyatv successfully a few times in the past (6+ months ago) and don’t remember having problems about where things are installed. 

I’m seeing installs go to `~/.local/bin` now (tried on two pi’s). I believe the old installation (which is included in PATH) is `/usr/local/bin` which worked great. 

I guess I have two questions. 1- how do I decided where pip installs things? 2- is there any reason moving atvremote to the `/usr/local/bin` would be a problem?

Hopefully someone knowledgeable reads this. Thanks as always!
