### ISSUE TITLE
Can't remove Apple TV Beta from Home Assistant

### ISSUE THREAD

**Issue by mark1foley** [postlund/pyatv#1680]
### Describe the bug

I am trying to remove the Apple TV Beta from my Home Assistant implementation as it stopped working and I am not using it.  By stopped working I mean that it started to throw errors on HA startup and the integration has a status of "Not Loaded".  As I am not using it I tried to delete it to get rid of the error notifications.
If I try and delete it from HACS I get a message that the integration is configured and this needs to be removed first.  If I try and delete the integration nothing happens and I get the errors in the log.
How can I delete it from HA?

### Error log

Error doing job: Task exception was never retrieved
06:26:27 – (ERROR) config_entries.py - message first occurred at 7 March 2022, 11:34:40 and shows up 8843 times
Error occurred loading configuration flow for integration apple_tv: Exception importing custom_components.apple_tv.config_flow
06:26:27 – (ERROR) config_entries.py - message first occurred at 7 March 2022, 11:34:40 and shows up 8854 times
Unexpected exception importing component custom_components.apple_tv
06:26:27 – (ERROR) Apple TV (custom integration) - message first occurred at 7 March 2022, 11:34:14 and shows up 8860 times

### How to reproduce the bug?

Try and remove again

### What is expected behavior?

Remove from HA

### Operating System

Home Assistant OS 7.4

### Python

3.6

### pyatv

3.0.1

### Device

Apple TV 4K 

### Additional context

.

**Comment by postlund** [comment]
Probably not relevant anymore? Otherwise I recommend manually removing, e.g. via ssh.
