### ISSUE TITLE
[Help Request] Home Assistant - Apple TV 4k not found

### ISSUE THREAD

**Issue by stratus-ss** [postlund/pyatv#1681]
### What do you need help with?

HA information:

```
Version | core-2022.3.3
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.98
CPU Architecture | x86_64
Timezone | America/Chicago
```

Supervisor Info:

```


Host Operating System | Home Assistant OS 7.4
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.03.3
Docker Version | 20.10.9
Disk Total | 46.5 GB
Disk Used | 26.2 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok
Installed Add-ons | ADB - Android Debug Bridge (0.8.0), Samba share  (9.5.1), File editor (5.3.3), InfluxDB (4.3.0), Mosquitto broker  (5.1.1), Node-RED (11.1.0), Terminal & SSH (9.3.0), ESPHome  (2022.2.6), Grafana (7.4.1), Z-Wave JS to MQTT (0.36.0), Z-Wave JS  (0.1.54), HassOS SSH port 22222 Configurator (0.8), TasmoAdmin (0.16.0),  rest980_2 Docker Image (20220113), php-nginx_2 Docker Image (latest),  Zigbee2mqtt (1.24.0-1)
```

I tried using just the normal HA Integration through the UI, but it finds the TV neither by IP nor by Device name

I then installed ATV Beta 3.0.1 through HACs and have restarted HA multiple times (as well as rebooting the host)

I have the following set in `configuration.yaml`

```
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
    pyatv: debug
    custom_components.apple_tv: debug
```

However, I don't know where to find these logs.

When I install `atvremote` via pip on my desktop, the scan works. If I log into HA shell and use the docker container, the scan also succeeds.

Results output:

```
atvremote --debug scan
2022-03-10 10:17:11 DEBUG [pyatv.scripts]: Running with pyatv 0.10.0
2022-03-10 10:17:11 DEBUG [pyatv.support.net]: Binding on *:5353
2022-03-10 10:17:11 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2022-03-10 10:17:11 DEBUG [pyatv.support.net]: Binding on 192.168.99.198:0
2022-03-10 10:17:14 DEBUG [pyatv.core.scan]: Auto-discovered Projector at 192.168.99.221:49152 via Protocol.Companion ({'rpmac': '1', 'rphn': '51ca404b3497', 'rpfl': '0xB6782', 'rpmd': 'AppleTV11,1', 'rpvr': '330.5', 'rpmrtid': '4EE8353D-249E-43B6-A50B-7C3C999B6092', 'rpad': '0cfd69eca173', 'rpba': '42:88:A8:8B:83:8B'})
2022-03-10 10:17:14 DEBUG [pyatv.core.scan]: Auto-discovered Projector at 192.168.99.221:7000 via Protocol.AirPlay ({'acl': '0', 'btaddr': 'F0:B3:EC:07:B6:B6', 'deviceid': 'F0:B3:EC:18:3E:2C', 'fex': '1d9/St5/FbwI', 'features': '0x4A7FDFD5,0xBC157FDE', 'flags': '0x244', 'gid': 'B8BB4008-6300-4654-B5F0-94C0019C62CA', 'igl': '1', 'gcgl': '1', 'model': 'AppleTV11,1', 'protovers': '1.1', 'pi': 'fe5af559-2990-481e-92e3-80fb493f211b', 'psi': '4EE8353D-249E-43B6-A50B-7C3C999B6092', 'pk': '22bd8faee28808af4cc928578b4bdfd45094d01960a616cba981f9bfb6c23aea', 'srcvers': '605.1', 'osvers': '15.3', 'vv': '2'})
2022-03-10 10:17:14 DEBUG [pyatv.core.scan]: Auto-discovered F0B3EC183E2C@Projector at 192.168.99.221:7000 via Protocol.RAOP ({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft': '0x4A7FDFD5,0xBC157FDE', 'sf': '0x244', 'md': '0,1,2', 'am': 'AppleTV11,1', 'pk': '22bd8faee28808af4cc928578b4bdfd45094d01960a616cba981f9bfb6c23aea', 'tp': 'UDP', 'vn': '65537', 'vs': '605.1', 'ov': '15.3', 'vv': '2'})
Scan Results
========================================
       Name: Projector
   Model/SW: Apple TV 4K (gen2), tvOS 15.3
    Address: 192.168.99.221
        MAC: F0:B3:EC:18:3E:2C
 Deep Sleep: True
Identifiers:
 - F0:B3:EC:18:3E:2C
 - F0B3EC183E2C
Services:
 - Protocol: Companion, Port: 49152, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Mandatory
```
The UI simply returns this:
![image](https://user-images.githubusercontent.com/8162705/157708291-0a3d3e63-1ea8-41ee-b0f6-b25be587c4c3.png)

How can I go about debugging this further? The Apple TV is set to allow from devices on the same network as itself. 

Thanks

**Comment by stratus-ss** [comment]
Is this not the correct forum to pose this question?

**Comment by postlund** [comment]
Sorry, I have been very distant from the project due to personal matters. Can you start by removing the beta integration and just running with stock version in Home Assistant and see what happens?

**Comment by bobisaperson1** [comment]
I am having the same issue with one of my 2 atvs, funnily my had atv is having the issue and my 4K still works, not sure about to run the atvremote command on ha though

**Comment by bobisaperson1** [comment]
> @bobisaperson1 Are you running the beta integration or stock integration included with Home Assistant?

Stock included with ha

**Comment by bobisaperson1** [comment]
I solved my issue, turned out that my atv hd and raspi running ha were connected to different access points for my network (mesh wifi) and the atv 4K was connected to the same one the raspi was on.

I am running a deco mesh network for anyone having the same issue

**Comment by Ripper2909** [comment]
Hello @postlund & @bobisaperson1,

I kinda have the same issue :
- HA is running on 192.168.1.X (main subnetwork)
- Apple TV is running on 192.168.99.X, which is a hostapd subnetwork hosted on HA as an addon (every IoT devices of my home are connected there)
- If I ping 192.168.99.X (Apple TV) from HA SSH addon (192.168.1.X), it reaches out without issue
- But if I try to integrate 192.168.99.X (Apple TV) with the Apple TV integration (I tried with the beta component and official one too), it says "No devices found on the network"

So my question : is it possible to tell the Apple TV integration to lookout on other subnetworks such as 192.168.99.X ?
That would be awesome, since all my IoT devices are running on the HA hostapd addon

Thanks for your consideration ! Any help would be appreciated :)

**Comment by postlund** [comment]
It will only work if you set up an MDNS responder and forward all the MDNS packets across the VLANs.

**Comment by Ripper2909** [comment]
> It will only work if you set up an MDNS responder and forward all the MDNS packets across the VLANs.

Thank you @postlund !
I can’t find how to do so on hostapd. Any idea how if this is in your scope ?
Cheers

**Comment by postlund** [comment]
@Ripper2909 Unfortunately no, network setup is kinda out of scope for the project. But I hope you managed to get it working!
