### ISSUE TITLE
ImportError: cannot import name 'conf' from 'pyatv'

### ISSUE THREAD

**Issue by kilian579** [postlund/pyatv#169]
Tried to understand how the _manual_connect_ example works unfortunately it doesn't seem to get too far:

> ImportError: cannot import name 'conf' from 'pyatv' (C:\ProgramData\Anaconda3\lib\site-packages\pyatv\__init__.py)

**Comment by postlund** [comment]
That module is only available from master branch, did you install from git and also remove any 0.3.x releases you might have installed?

**Comment by kilian579** [comment]
Seems like I still used the pip3 version. Tried importing the master branch version.
But still the imports won't work with the masterbranch _pyatv_

> from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

**Comment by postlund** [comment]
Verify that you have the protobuf package installed, it should work.

**Comment by postlund** [comment]
Issue is idle so I will close it now. Re-open or create a new issue of problem still exists.
