### ISSUE TITLE
Stream multiple mp3 files

### ISSUE THREAD

**Issue by printmanpro** [postlund/pyatv#1697]
### What do you need help with?

Is it possible to stream multiple mp3 files, one after the other..?

**Comment by postlund** [comment]
If you are using `atvremote` you can just continue passing `stream_file` over and over:

    atvremote ... stream_file=1.mp3 stream_file=2.mp3 stream_file=3.mp3

**Comment by postlund** [comment]
No, unfortunately not. You should also uninstall that and use the stock integration in Home Assistant instead as that has a lot of fixes in it.

**Comment by postlund** [comment]
I believe this issue has been solved from the perspective of pyatv, so will close.
