### ISSUE TITLE
Arrow keys for Apple TV 4

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#17]
Based on my testing, the protocol differs for how arrow keys are handled. From the looks of it, the reverse engineered keys are based on the touch interface of ATV4. We can see that [here](http://pastebin.com/mDHc353A):

```
  'up': [
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchDown&time=0&point=20,275",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchMove&time=1&point=20,270",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchMove&time=2&point=20,265",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchMove&time=3&point=20,260",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchMove&time=4&point=20,255",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1DtouchMove&time=5&point=20,250",
    "cmcc\x00\x00\x00\x01\x30cmbe\x00\x00\x00\x1BtouchUp&time=6&point=20,250"
  ],
```

It's basically a bunch of new DAAP/DMAP data (cmcc, cmbe). Should be easy enough to implement _but_ this means that the implementation will differ for ATV4 and pre-ATV4 devices. Since I don't want to mix code between them, two implementations will have to be made (some subclassing and re-use in ``pyatv.internal``). Tests will also have to be split, e.g, rename test_functional.py to base_function.py and create two subclasses: one for ATV4 and one for ATV3. Tests for arrow keys shall be added in the ATV4 suite. Have to think about naming.

**Comment by entmike** [comment]
Thanks, this is explains why using "left", "right", etc isn't working for me.

**Comment by postlund** [comment]
@entmikeI just created #59 which adds support for arrow keys. If you have the possibility to try it out, I will merge it after that.
