### ISSUE TITLE
Is there any way to use Keyboard Inputs for Apple TV ?

### ISSUE THREAD

**Issue by AmoghSaxena** [postlund/pyatv#1705]
### What do you need help with?

I have Apple TV with tvOS15 and its working fine with PyATV Module. Thanks to @postlund For this super awesome repo.

I just had a small doubt. Is there any way to put my keyboard inputs via PyAtv?

Like while watching Netflix, or SignIn we have to manually more Arrows Up/Down to select the letters. 
But if there  is a direct way to send the keyboard input directly  to the Machine that will be a lot more easier thing.

**Comment by The00Dustin** [comment]
I would also be interested in this, but I am using HAOS and presumably on tvOS16.  It's possible from an iPhone that is behaving as a remote, but I don't know that the same remote protocol is used when the text is being entered.

**Comment by postlund** [comment]
It is implemented via Companion in version 0.12.0 and later.
