### ISSUE TITLE
Meta Data doesn't update when binge watching

### ISSUE THREAD

**Issue by InnovoDeveloper** [postlund/pyatv#1723]
### Describe the bug

in HA, when I start a series on Netflix, I am finding out that when the next episode starts, the meta data doesn't update and it stays on the first episode.  The timeline also doesn't update in HA.  If I stop and start playing again, the meta data is refreshed.  

### Error log

```log
<place log here>
```

### How to reproduce the bug?

Binge watch a series on Netflix

### What is expected behavior?

Meta data should update on a regular basis but it does so only periodically.

### Operating System

HA 22.05.00

### Python

3.9

### pyatv

0.10.0

### Device

Apple TV 4K TVoS 15.3

### Additional context

---

**Comment by postlund** [comment]
I believe this is a bug in the Netflix app as I experience the same thing also in iOS. Can you confirm?

**Comment by InnovoDeveloper** [comment]
Confirmed.  Only with Netflix.  Thank you.  Tried several other channels and it works like a charm.
