### ISSUE TITLE
Help installing on synology docker

### ISSUE THREAD

**Issue by imeSven** [postlund/pyatv#1739]
### What do you need help with?

can u help me out with a line instructions to install pyatv on my synology with docker ? cause i tried all .. cant find the good repo and settings to start it up

**Comment by postlund** [comment]
I unfortunately have no idea how synology works, so I'm not the right person to help. But maybe you can get some guidance from this issue:

https://github.com/postlund/pyatv/issues/1717

Would actually by great to get a guide up in the documentation for it.

**Comment by postlund** [comment]
Will close due to inactivity.
