### ISSUE TITLE
Channel Remote Control Command

### ISSUE THREAD

**Issue by a13xmay** [postlund/pyatv#1754]
### What feature would you like?

Channel up and down

### Describe the solution you'd like

I noticed the Apple TV remote on my iOS device shows CH Up and Down on the bottom right of the screen. Are these commands able to be exposed and added to the pyatv remote interface?

### Any other information to share?

![IMG_3132](https://user-images.githubusercontent.com/74129410/174455652-d3addbb8-771b-4ac6-abd4-7a35c8934edb.PNG)

**Comment by postlund** [comment]
They are currently not exposed by pyatv, no. But they would be easy to add so I can try to fix that within the next few days as I'm planning for a release.

**Comment by a13xmay** [comment]
Thank you, much appreciated!

**Comment by postlund** [comment]
I merged this and it will be part of 0.10.1, but please feel free to verify that it actually work (I'm pretty sure it does though).

**Comment by a13xmay** [comment]
Working perfectly, thank you!
