### ISSUE TITLE
Issues connect u

### ISSUE THREAD

**Issue by garbage98** [postlund/pyatv#177]
I have big problems to get the ATV connected with the script. The ATV is in the same submask as the PC but the ATV is not found when the autodetection is finished. 

How can I tackle down the problem the best way? Is there a possibility to setup up a manual connection to establish a realiby connection ?

**Comment by kilian579** [comment]
Having troubles with this issue as well.

**Comment by postlund** [comment]
There are a lot of issues with zeroconf finding devices, no idea why. Will probably have to take a couple of days looking at it.

**Comment by postlund** [comment]
I believe this is fixed on `master`. I will close this issue now (report any additional issues in #214).
