### ISSUE TITLE
iTunes home sharing

### ISSUE THREAD

**Issue by jacksteraz** [postlund/pyatv#178]
I have homesharing turned on on iTunes, but atvremote scan shows that it is disabled.
`atvremote scan
Found Apple TVs:
 - Jackâs Library at 192.168.0.XX (home sharing disabled)
 - Office at 192.168.0.XX (login id: 00000000-05b5-59c8-XXXXXXXXXXXXXXXXXX)
 - Apple TV at 192.168.0.XX (login id: 00000000-05b5-59c8-XXXXXXXXXXXXXXXX)`

 Commands do work if I do atvremote pair, then use commands like this:

` atvremote --address 192.168.0.29 --login_id 0xXXXXXXXXXXXXX play`

I know that you wrote this to control Apple TV, not iTunes.

**Comment by postlund** [comment]
The thing is that "home sharing disabled" only means that no zeroconf/bonjour service matching the one home sharing uses was found. So technically it doesn't necessarily mean that home sharing is disabled. There are a lot of issues with this that I think is related to the zeroconf library, but I have not looked further into it. I don't know if iTunes exposes the same zeroconf service, so I'm not sure if it's "supposed to work".

**Comment by postlund** [comment]
I believe this to be fixed more or less on `master`. Will close now, open a new issue if issue still exists `master`.
