### ISSUE TITLE
atvscript scan doesn't display the Model but atvremote scan do

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#1789]
### What feature would you like?

atvscript scan to display the full model name and the OS and Version of the scanned device like atvremote scan do

### Describe the solution you'd like

adding in the json of atvscript the model name, the os and the version

### Any other information to share?

nope

**Comment by postlund** [comment]
@NebzHB Please try #1793.

**Comment by NebzHB** [comment]
Seems Nice, will you add the os and the osversion too ?

**Comment by postlund** [comment]
Sure, I can add that too!

**Comment by postlund** [comment]
Yeah, that would be the ideal case. `atvscript` has always been extended according to user needs (I.e. feature requests), so it's far from feature completele.

**Comment by NebzHB** [comment]
```
{
	"result": "success",
	"datetime": "2022-07-14T16:54:52.647259+02:00",
	"devices": [{
			"name": "Apple TV A",
			"address": "192.168.1.1",
			"identifier": "AB:AB:AB:AB:AB:AA",
			"model": "AppleTV4KGen2",
			"model_str": "Apple TV 4K (gen2)",
			"services": [{
					"protocol": "companion",
					"port": 49152
				}, {
					"protocol": "airplay",
					"port": 7000
				}, {
					"protocol": "raop",
					"port": 7000
				}
			]
		}, {
			"name": "Apple TV B",
			"address": "192.168.1.2",
			"identifier": "AB:AB:AB:AB:AB:AB",
			"model": "Gen4",
			"model_str": "Apple TV 4",
			"services": [{
					"protocol": "companion",
					"port": 49152
				}, {
					"protocol": "airplay",
					"port": 7000
				}, {
					"protocol": "raop",
					"port": 7000
				}
			]
		}, {
			"name": "Apple TV C",
			"address": "192.168.1.3",
			"identifier": "AB:AB:AB:AB:AB:AC",
			"model": "Gen4K",
			"model_str": "Apple TV 4K",
			"services": [{
					"protocol": "companion",
					"port": 49152
				}, {
					"protocol": "airplay",
					"port": 7000
				}, {
					"protocol": "raop",
					"port": 7000
				}
			]
		}
	]
}
```
here is the scan for my 3 apple TVs, i got a 4, a 4k and a 4kGen2, the "model" is a bit strange on the 4kGen2 (not consistent with the model of the other ones...)

**Comment by postlund** [comment]
`model` comes directly from https://pyatv.dev/api/const#pyatv.const.DeviceModel. As pyatv supports other devices than Apple TVs now (HomePods for instance), I have started to include device type in the name. That's why 4K gen2 is different. At some point I will make a big breaking change and rename things to be more consistent, but at this time backwards compatibility is more important. `model_str` is just a user presentable string, also taking `raw_model` in consideration in case a device is not Apple hardware (like a third party AirPlay receiver).

**Comment by NebzHB** [comment]
ok, just waiting for the os and osVersion then :) thank you for your explanation

**Comment by postlund** [comment]
`operating_system` and `version` has been added and everything has been merged now. I can make a release later if you need it?

**Comment by NebzHB** [comment]
Thank you alot ! i'll test that.

(don't need release thx)

**Comment by NebzHB** [comment]
Tested succesfully ! Nice job thx !
