### ISSUE TITLE
Items in Hassio log

### ISSUE THREAD

**Issue by mcfarlde** [postlund/pyatv#179]
The Apple TV is exposing a few new tags that pyatv (the underlying library) does not recognize. 
Log Details (WARNING)
Mon May 27 2019 19:05:06 GMT-0600 (Mountain Daylight Time)
Unknown data: b'ceNR\x00\x00\x00\x0eBritney Spearsaead\x00\x00\x00\x01'
Connection lost. Reconnecting…
followed by.
Mon May 27 2019 19:05:06 GMT-0600 (Mountain Daylight Time)
Unknown data: b'aead\x00\x00\x00\x01\x00casc\x00\x00\x00\x01'
Connection lost. Reconnecting…

**Comment by postlund** [comment]
Cool, thanks. I will add them later.
