### ISSUE TITLE
Failure to install on MacOS

### ISSUE THREAD

**Issue by UKenGB** [postlund/pyatv#1794]
### What do you need help with?

Trying to find something that works to report Apple TV state in Homebridge (running on Mac), as no ATV plugins for Homebridge (running on Mac) now seem to work.

So trying to use the pyatv with cmd4 plugin solution, but first problem is 'pip install pyatv' fails with:-

"Could not fetch URL https://pypi.python.org/simple/pyatv/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement pyatv (from versions: )
No matching distribution found for pyatv"

Python is v3.10. Any suggestions how to avoid above problem?

**Comment by postlund** [comment]
This is not a pyatv issue, it has to do with certificate verification (in macOS). This might help:

https://github.com/pypa/pip/issues/5236
