### ISSUE TITLE
push_updates with volume modifications (from lib or from other means) for homepods

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#1798]
### What feature would you like?

receiving {"volume":20.5} in atvscript push_updates when the volume has been modified from any means (lib, +/- buttons on top, airplay, ...) on HomePods at least (i know volume management on apple tv is strange).

could be a part of the playing json or separated like power_state, as you wish

### Describe the solution you'd like

each time the volume is changed, a line should appear in push_updates

### Any other information to share?

no

**Comment by postlund** [comment]
I currently don't have an external interface for volume changes that I can use, would have to come up with something for that first.

**Comment by postlund** [comment]
`atvscript` is an application built using `pyatv` as a library. I can only use whatever the library exposes. The simplest solution is to extend the Playing interface, but that isn't very pretty. Second solution is to add a new listener interface to `Audio`, which I guess is the correct solution at this time. My intention is however to replace listeners with a more flexible callback based system (#1301), but that's not ready yet. I've been refraining from adding more listeners as that means more breaking changes further down the road. But that might be a minor problem anyways... I can take a look at adding a new listener, it's not hard. Home Assistant would benefit from this as well.

**Comment by NebzHB** [comment]
yes, sadly my knowledge about the asyncio loop in python are not enough to code my own python daemon (i've followed your tutorial but i can't add my input calls from my system and all that to the asyncio ....

so i still depend on these "newbe" interfaces... but anyway that's a nice way from now ;) i spawn 2 processes by apple tv in nodejs and now it works fine ;) i just have to manage some crash and stuffs ;)

**Comment by michalmo** [comment]
Since I would like this in Home Assistant, I've added a listener interface to `Audio` in PR #1975.
