### ISSUE TITLE
app command

### ISSUE THREAD

**Issue by UKenGB** [postlund/pyatv#1801]
### What do you need help with?

Using atvremote directly, after pairing and with credentials all correct (it will turn the ATV on and off), but the result of using the 'app' command is somewhat random.

In most cases, it reports nothing (even when the AppleTV app is running on screen, same with Plex and Disney). When NOW is running, that seems to be reported correctly, but then I tried Amazon Prime and it still reported NOW was the current app.

The app_list command seems to work and all are listed, but currently pyatv seems unable to determine which one is current.

**Comment by postlund** [comment]
With noting is that `app` reports what is playing something, not what app is currently active. The app is derived from playing media and there's no api for just asking what app is active (unfortunately).

**Comment by UKenGB** [comment]
Ah, that might be it. The docs say 'Active app' and I assumed that meant current/front. I'll try when playing something.

**Comment by UKenGB** [comment]
Just played something and atvremote reported the corerct app and what was playing. So it was just my misunderstanding of what you meant by 'active' app.

However, power_state is still reporting as Off.

**Comment by postlund** [comment]
That sounds about right then. It would be an error in the documentation if it says "active app", where did you see that (so I can fix if)? I've tried to be consistent but sometimes...

**Comment by UKenGB** [comment]
I wouldn't say 'active' is wrong, just ambiguous.

	https://pyatv.dev/documentation/atvremote/

Apps

Show active app:




Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by postlund** [comment]
Yeah, you are correct! I will update the documentation when I get a few minutes, thanks for reporting!

**Comment by UKenGB** [comment]
🙂
