### ISSUE TITLE
Is it possible to update artist via atvscript?

### ISSUE THREAD

**Issue by sklever** [postlund/pyatv#1817]
Really want to enter directly a channel from TV, running in the app. Is it possible to update artist, e.g. change from artist": "ZDF" to artist": "WDR" so TV channel is switched?

**Comment by postlund** [comment]
That's not possible, no. That's a pure metadata field. There are previous/next APIs available for channels, but I haven't seen any API for selecting a specific channel. Is that possible via iOS somehow?

**Comment by sklever** [comment]
Ok, thanks anyway.
In iOS it's also only up / down for channel switching.

**Comment by postlund** [comment]
Yeah, I think that's the only thing supported in tvOS. It's supported in pyatv as well with `channel_up` and `channel_down`.

**Comment by postlund** [comment]
Nothing more to do here from what I can see.
