### ISSUE TITLE
UnknownMediaKind: 32770

### ISSUE THREAD

**Issue by schmittx** [postlund/pyatv#182]
Currently getting this error in HomeAssistant from a 3rd gen AppleTV while watching an iTunes rental movie.

I'm not familiar with `pyatv` details but wanted to feed this back. If you need more info, I'll be happy to share.

`pyatv.exceptions.UnknownMediaKind: Unknown media kind: 32770`

**Comment by postlund** [comment]
I didn't find the correct value for this, but mapped it to Unknown until something better comes along. It is not listed among the "normal" values of other media kinds, but 32770 is 0x8002, so I assume there's a special range from 0x8000 and upwards. Maybe some compatiblity layer.
