### ISSUE TITLE
TTS HTTP Help

### ISSUE THREAD

**Issue by Spross1** [postlund/pyatv#1830]
### What do you need help with?

I don't really know how to phrase this question necessarily but I'm struggling to get TTS to work again. I see that I need to use the play_media service but I don't know how to get a HTTP URL to input in the media_content_id blank. I looked at the Home Assistant TTS Documentation and tried to use a rest api to create the HTTP URL. I tried a few different platforms(apple Tv, pyatv) but keep getting 404 errors. I also don't even know if this is the correct/best way to do it so any help you could provide would be greatly appreciated. I'm sorry if this is a stupid question, I've spent some time looking into it and I just can't figure it out. Thank you for your work with this integration!!

**Comment by postlund** [comment]
Please try any of the tts services instead, like `tts.google_translate_say` if you use Google's service. Hopefully that will work.

**Comment by postlund** [comment]
Old issue, will close this now. Please re-open if issue persists.
