### ISSUE TITLE
Any way to launch screen saver directly with `atvremote`?

### ISSUE THREAD

**Issue by jlian** [postlund/pyatv#1839]
### What do you need help with?

My desired outcome is to have one command that launches screen saver on my Apple TV as quickly as possible.

I checked `atvremote commands` and couldn't find a way to it via one command. I thought it might be possible because there's a Shortcut for it 

![image](https://user-images.githubusercontent.com/2320572/189503545-3d0570f1-feda-4cbe-b53f-104cdb4f4872.png)

So right now I'm doing

```bash
atvremote -s <IP> --companion-credentials <creds> home \
&& atvremote -s <IP> --companion-credentials <creds> home \
&& atvremote -s <IP> --companion-credentials <creds> menu
```

Which works but it's slower compared to the shortcut since (I assume) it scans before each button press and there are 3 button presses.

Looks like instead of using the command line tool I should just write a small python program instead. Before I do that I'd like to know

1. Is there a command that launches the screen saver directly like the shortcut?
2. Is a way to do multiple button presses with one `atvremote` command?
3. Is there a way to bypass the scanning for repeated commands? I tries [the `--manual` thing](https://pyatv.dev/documentation/atvremote/#manually-specifying-a-device) and couldn't get it to work, always says "error: no device identifier"

  ```bash
  pi@homebridge:/var/lib/homebridge $ atvremote --manual --address 192.168.5.31 --port 49153 --protocol companion --companion-credentials <creds> --id test menu
  Traceback (most recent call last):
    File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 717, in _run_application
      return await cli_handler(loop)
    File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 518, in cli_handler
      return await _handle_commands(args, config, loop)
    File "/home/pi/.local/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 602, in _handle_commands
      atv = await connect(config, loop, protocol=args.protocol)
    File "/home/pi/.local/lib/python3.9/site-packages/pyatv/__init__.py", line 101, in connect
      raise exceptions.DeviceIdMissingError("no device identifier")
  pyatv.exceptions.DeviceIdMissingError: no device identifier
  
  >>> An error occurred, full stack trace above
  ```

Thanks a lot!

**Comment by postlund** [comment]
Quick answers:
1. Currently no, but it is easy to implement and I have considered to do that. I'm currently swamped so I unfortunately have not been able to put any time into pyatv, but I will consider adding this once I get some time again.
2. You can just pass additional commands like so: `atvremote down left menu`. You can also add some delay if you have to: `atvremote select delay=1000 select`
3. The `--manual` flag is only for special cases (mainly during development), I recommend that you use `-s` if you have a static IP assigned to your device (just like you did).

**Comment by jlian** [comment]
> Currently no, but it is easy to implement and I have considered to do that. I'm currently swamped so I unfortunately have not been able to put any time into pyatv, but I will consider adding this once I get some time again.

Sweet! If you ever get the chance to work on it, would it also possible to poll the Apple TV on if it's in screen saver mode or not? I guess my ultimate fantasy would be to have a HomeKit switch "Apple TV Screen Saver" that can turn on/off screensaver and reflect the accurate state. And then I'd be able to use it for automation e.g. "turn on Apple TV screen saver when Xbox turns off and if the TV is on". I just looked it up and it looks like nobody else on the internet has this need and I'm not in a rush 🙃

> You can just pass additional commands like so: `atvremote down left menu`. You can also add some delay if you have to: `atvremote select delay=1000 select`

Thanks for the tip on the delay. I actually did try this and the lack of delay made it not work. Once I made `atvremote -s <IP> home delay=1000 home delay=700 menu` it works pretty well.

**Comment by postlund** [comment]
As far as I know there's no way of checking that, but I have not looked into it that much though. My guess is that it's not possible as the protocols generally focus on the state of media playback, which "screensaver" is not really part of. But if it's possible to see, then I can add it of course.

**Comment by postlund** [comment]
@jlian A billion years later... but now I have merged screensaver support. Will be in the next release.

**Comment by postlund** [comment]
@jlian By accident I stumbled across an event in the Companion protocol that actually reports if the screensaver is active, so I think it would be possible to implement that (once I have handling of the event in place). Just wanted to let you know.
