### ISSUE TITLE
Artwork is always a black image on tvOS 16 on Homepod Mini only

### ISSUE THREAD

**Issue by NebzHB** [postlund/pyatv#1848]
### Describe the bug

when i run artwork_save, i always receive a black image on homepod mini (homepod and atv is working fine !) (probably since tvOS 16...)

if i get the id and download the artwork it's ok... i've tried with 1200 x 1200 to avoid resizing maybe... but doesn't work

### Error log

see attachment (too long) (at the end there is a artwork_id and a wget of the url)

### How to reproduce the bug?

doing the commands on homepod mini

### What is expected behavior?

receiving artwork.png with the correct artwork (works fine on homepod and atv !!)

### Operating System

Linux debian 11

### Python

3.9

### pyatv

0.10.3

### Device

Homepod mini tvOS 16.0

### Additional context

no

**Comment by NebzHB** [comment]
[pyatv.log](https://github.com/postlund/pyatv/files/9673143/pyatv.log)

**Comment by Clarus-Moof** [comment]
Same here. When I added a new HomePod mini to HA, the artwork was visible for a short time, but after a while it also turned black.

**Comment by michalmo** [comment]
@postlund #1958 has been merged and released, so this can be closed. I didn't correctly link that PR to this issue.

**Comment by postlund** [comment]
@michalmo Got it, thanks! 👍
