### ISSUE TITLE
Remote Command: select_hold

### ISSUE THREAD

**Issue by VeniceNerd** [postlund/pyatv#1854]
### What feature would you like?

Would it be possible to integrate a select_hold command for the AppleTV remote? This would be useful to be able to delete or move apps on the Home Screen as well as certain in app behavior. Currently it appears as if home_hold is the only hold command supported?

Would love if select_hold could be added. 

### Describe the solution you'd like

Select_hold command that will send a long press of the select button to AppleTV

### Any other information to share?

N/A

**Comment by mschwartz** [comment]
double tap, too

**Comment by postlund** [comment]
Both of these are already supported programmatically via [InputAction](https://pyatv.dev/api/const#pyatv.const.InputAction). Example for using it is [here](https://pyatv.dev/development/control/#input-actions). If you want to try it with `atvremote`, you would do something like `atvremote ... select=X` where X=0 > single tap, X=1 => double tap and X=2 => hold. Please try if that works.

**Comment by mschwartz** [comment]
@postlund you are awesome.  Thanks!

**Comment by postlund** [comment]
@mschwartz Great, thanks! I assume it worked 😊 Some of the other buttons support it as well, just check the API reference and you'll see which ones that does.

**Comment by mschwartz** [comment]
One more question.

Once you double tap, you get the carousel of running apps.  If you swipe up with the remote, it kills the app.  Is this swipe (or any swipe) gesture supplorted?

**Comment by postlund** [comment]
Unfortunately no, the touch API os not implemented yet. I think there's an issue about that.

**Comment by mschwartz** [comment]
All we need is swipe(up/down/left/right).

I might post some screenshots of my custom home automation software and how I have integrated pyatv (as an MQTT bridge microservice) and The Movie Database.

I really wish Apple implemented a REST API or a serial port over TCP like many devices do (Denon AVR, TiVo, Roku, etc.)

**Comment by postlund** [comment]
Left and right seems to work with the regular navigation keys, but not up/down. Implementing via touch should be fairly easy, especially since @michalmo has fixed the companion proxy so we can look at the traffic now. I used to do HID events for some buttons before (like up/down/left/right)  with MRP and I think it's more or less the same data, just another encapsulation. Would require some work with adding a new API for touch input as well.

**Comment by michalmo** [comment]
@mschwartz you can also double tap `up` to close an app when the app carousel is open

**Comment by mschwartz** [comment]
Seems like double tap up would be a nice method to be able to call as swipe_up() in pyatv?
