### ISSUE TITLE
Please make a guide for boneheads who don’t understand this

### ISSUE THREAD

**Issue by kylewhirl** [postlund/pyatv#1855]
### What do you need help with?

The documentation on the website is very thorough, but there is no order to anything. You pretty much just describe what everything does. That’s great, but I’ve found I’ve tried 20 different commands and still have yet to control the Apple TV in any way. No commands have worked for me. I would love a clear and concise version of a step-by-step guide on how to set this up. Maybe I just haven’t found it?

**Comment by jzucker2** [comment]
Have you tried this yet?

https://github.com/postlund/pyatv#great-but-how-do-i-use-it

**Comment by kylewhirl** [comment]
That 

> Have you tried this yet?
> 
> https://github.com/postlund/pyatv#great-but-how-do-i-use-it

This just shows how to scan for devices, but you also have to get credentials and some credentials don’t work with commands like turning on the Apple TV.

**Comment by postlund** [comment]
This is very relevant, I feel with you. It's hard to write good documentation is all I can say. The thing is also that there are two sides to the coin: people only using the bundled scripts (like `atvremote`) but also developers, which is the main target.

I would say that the [atvremote](https://pyatv.dev/documentation/atvremote/) page is the easiest page to follow to just get going, but some re-structuring would not hurt. I'll see if I can write a better getting started page.

**Comment by postlund** [comment]
In the latest release, 0.14.0, I added both storage support for credentials and a wizard in `atvremote` to set up up new devices. You basically run `atvremote wizard`, pick a device and follow the instructions. Once finished, credentials and passwords will be saved to storage (a file) for future use. So you don't have to care about what protocols to pair or saving and restoring credentials anymore: pyatv will take care of that for you. The "Getting started" guide has been updated with instructions, so please check that out.

https://pyatv.dev/documentation/getting-started/
