### ISSUE TITLE
Add long press home button

### ISSUE THREAD

**Issue by SylvainCecchetto** [postlund/pyatv#186]
Hi,
Thank you for this code!

Did you already try to add the "long press home button" support?

Thank you!

**Comment by postlund** [comment]
Hi! No, not a big priority. Does this work in the Remote app or just the physical remote?

**Comment by SylvainCecchetto** [comment]
By "Remote app" you mean the Remote app on the iPhone/iPad.
So yes, it works with the Remote app.

Does the remote app uses MRP?

**Comment by postlund** [comment]
Yeah, I mean that app. Ok, great! Then it's probably possible to add. I will not put any effort into adding new functionality before 0.4.0 is released. If someone else wants to give it a shot, then it's fine.

**Comment by SylvainCecchetto** [comment]
Hi, I not found yet the long press code but I found another one:
**Siri button press: [1, 0x4]**

**Comment by postlund** [comment]
> Hi, I not found yet the long press code but I found another one:
> **Siri button press: [1, 0x4]**

That is good to know! I believe [12, 0x04] should work as well? I left a comment about it at least:

https://github.com/postlund/pyatv/blob/master/pyatv/mrp/__init__.py#L33 
 
> Edit: I made a script that brute force every possible HID code... Not sure that this is the best idea xD

It's called fuzzing and it's quite in now 😉 As long as you can keep track of what button combination does what.

**Comment by MorpheusAV** [comment]
Is emulating swiping possible?

**Comment by postlund** [comment]
> Is emulating swiping possible?

It is technically possible of course, but not implement yet. An API should be added for the touch interface in a future release. You can write a feature request for it if you like.

**Comment by postlund** [comment]
@ckeehan This corresponds to `home_hold` in #262, right?

**Comment by ckeehan** [comment]
@postlund Yes, the `home_hold` command implements this request

**Comment by postlund** [comment]
Then this can be closed, awesome!
