### ISSUE TITLE
Error message when pairing anything but AirPlay

### ISSUE THREAD

**Issue by kilian579** [postlund/pyatv#1889]
### What do you need help with?

_Is there anything I need to do before trying to pair a protocol? I'm not sure what to do with the pairing error I received._

I have RAOP, Companion and AirPlay available. However pairing Companion leads to an error, same results for RAOP protocol. It is only possible to pair AirPlay.

`atvremote scan`

> Model/SW: AppleTV14,1, Unknown OS 16.1.1
> ...
> Services:
>  - Protocol: Companion, Port: 49153, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
>  - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled
>  - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False, Password: None, Pairing: Disabled

`atvremote --id ... --protocol companion pair`

> Traceback (most recent call last):
>   File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 717, in _run_application
>     return await cli_handler(loop)
>   File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 505, in cli_handler
>     return await _exec_command(glob_cmds, args.command[0], print_result=False)
>   File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 683, in _exec_command
>     value = await tmp(*args)
>   File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/scripts/atvremote.py", line 176, in pair
>     pairing = await pair(conf, self.args.protocol, self.loop, **options)
>   File "/home/pi/BuzzEnv/lib/python3.9/site-packages/pyatv/__init__.py", line 153, in pair
>     raise exceptions.NoServiceError(f"no service available for {protocol}")
> pyatv.exceptions.NoServiceError: no service available for Protocol.Companion

**Comment by postlund** [comment]
You need to go into the AirPlay menu on your Apple TV and change access setting to allow anyone on the same network to connect (it probably says anyone on the home now).
