### ISSUE TITLE
Can apps (like MasterClass) choose to not expose their playing state and data?

### ISSUE THREAD

**Issue by deviantintegral** [postlund/pyatv#1899]
### What to investigate?

I noticed that none of my usual automations in Home Assistant triggered when playing a video using the MasterClass app. Taking a look, it appears that playing a video there doesn't cause any of the state or attribute properties to update. However, I can launch the app using the "Source" list.

So, is this a bug in pyatv (I doubt it's an HA issue), or is it that apps can somehow be written using different or non-standard APIs that don't surface the playing state?

### Expected outcome

At the least, I expected the playing state to be updated, even if the attributes aren't.

If we think this is a possible pyatv bug, let me know and I can provide debug logs.

If this is not a bug in pyatv, but a likely bug in the app, then I'd like an actionable summary I can send to their support and development team for feedback. Or, if it's more of a missing feature, such as MasterClass not implementing an optional API, then I'd like to be able to correctly frame my message to them that way.

If multiple apps have this problem, and it's due to some misguided attempt to hide "proprietary" information, then I'd like to see pyatv maintain a list of offending apps so users can know to avoid them or at least not file issues when there's nothing pyatv can do.

**Comment by postlund** [comment]
Yes, some apps does not hook into the media API, e.g. when they use their own media player. You can verify this either by looking at the logs or simply by just looking at what iOS reports.
