### ISSUE TITLE
Two apple TVs in automation

### ISSUE THREAD

**Issue by T-IOOO** [postlund/pyatv#1902]
### What to investigate?

I have two Apple TVs setup as on/off switches.

create a scene in homekit with both apple tvs where one should be OFF and the other one ON. Now, before activating the scene, make sure both apple tvs are in the state OFF. Pressing the button for the scene will result in both apple tvs turning on and not how it is suppose to work.

### Expected outcome

It should result in one apple tv turning on and the other one staying off

**Comment by postlund** [comment]
I'm not really sure what to get from this? Is this a pyav problem or HomeKit problem (in whatever way you manage to integrate with that)?

**Comment by T-IOOO** [comment]
Im running cmd switch with homebridge if that is saying anything at all

**Comment by postlund** [comment]
I still don't really understand how it relates to pyatv. Is the per state not reported correctly?

**Comment by T-IOOO** [comment]
The issue was resolved by simply changing some parameters. Everything is working as it should

https://github.com/postlund/pyatv/issues/2034

**Comment by postlund** [comment]
Out of curiosity: what parameters did you change?

**Comment by T-IOOO** [comment]
> Out of curiosity: what parameters did you change?

It’s from your comment from issue #2034

I changed from…

atvremote -s (IP) --airplay-credentials (SERIAL) turn_off

To…

atvremote -s <ip> --companion-credentials <from previous command> turn_off
