### ISSUE TITLE
Allow configuration of port ranges used for ROAP client timing and control ports

### ISSUE THREAD

**Issue by andatche** [postlund/pyatv#1910]
### What feature would you like?

Currently pyatv binds to ephemeral UDP ports (which are typically allocated from the ephemeral range randomly by the OS) for the ROAP client timing and control ports when initialising a new ROAP context.

This presents a problem when using pyatv behind a restrictive firewall or NAT (e.g. Docker); because the client and control ports could be anywhere in the ephemeral range (typically 32768-60999 in Linux), it's necessary to permit/forward the entire range to ensure everything works correctly. This is often impractical/impossible.

### Describe the solution you'd like

Ideally, pyatv should support configuring a range of ports to use for the ROAP client timing and control ports (and any other ports it's necessary to bind to) so these can be known in advance and permitted through the firewall or DNATed as appropriate.

### Any other information to share?

Related Issues:

https://github.com/postlund/pyatv/issues/1884
https://github.com/postlund/pyatv/issues/1642
https://github.com/home-assistant/core/issues/80419

**Comment by postlund** [comment]
I agree with this. Generally pyatv should have a concept of configurable settings. Everything from timeout values, different kind of names (e.g. named used when pairing) and ports should be configurable.

**Comment by postlund** [comment]
This will be possible to implement quite easily once #2151 is merged, so I might give it a go next week or so. No promises, but at least wanted to give a heads up.

**Comment by postlund** [comment]
I added these settings in #2180:

https://pyatv.dev/api/settings/#pyatv.settings.RaopSettings.control_port
https://pyatv.dev/api/settings/#pyatv.settings.RaopSettings.timing_port

You can set them for instance using `atvremote`:

    atvremote -s <ip> change_setting=protocols.raop.timing_port,12345
