### ISSUE TITLE
How can I see if media not playing but an app is being used.

### ISSUE THREAD

**Issue by Symbiot78** [postlund/pyatv#1913]
### What do you need help with?

I have an automation that turns off tv & apple tv on idle after x time.

But if the kids are playing 'just dance' or similar on the apple tv .. the state is always idle.. meaning I cannot use my automation.

can I somehow see this ?

**Comment by postlund** [comment]
You cannot I'm afraid. The protocol is focused around media and not apps, so pyatv will only know if something is playing (and can derive the app from that).
