### ISSUE TITLE
No changes to the repo for 6 months

### ISSUE THREAD

**Issue by mschwartz** [postlund/pyatv#1921]
### What do you need help with?

@postlund is this going to get continued support?

I really appreciate the work you did on this.

**Comment by postlund** [comment]
Yeah, I can assure you it will! Busy with other stuff currently, but I will try to take up pyatv soon!

**Comment by mschwartz** [comment]
Outstanding!  I would have guessed that you had other work.  Don’t we all?  😀

**Comment by Ghawken** [comment]
Great to hear.  Thanks!

**Comment by postlund** [comment]
I will work at a slow pace, but I will at least try to put some work in every now and then. Will close this now.
