### ISSUE TITLE
Position in MP3 File In push_updates? (Yamaha Musiccast Player)

### ISSUE THREAD

**Issue by coofercat** [postlund/pyatv#1922]
I feel this ought to be simple, but I'm missing something... I'm using the example https://github.com/postlund/pyatv/blob/master/examples/stream.py to stream an MP3 file and get push_updates (playing to a Yamaha Musiccast device). The push updates look correct, and get updated as the music starts to play:
```
$ ./atvstream.py 10.20.1.139 /tmp/11.mp3
* Discovering device on network...
* Connecting to 10.20.1.139
* Starting to stream /tmp/11.mp3
------------------------------
   Media type: Unknown
Device state: Idle
------------------------------
   Media type: Music
Device state: Playing
       Title: For Those About to Rock (We Salute You)
      Artist: AC/DC
       Album: For Those About to Rock (We Salute You)
    Position: 0/344s (0.0%)
```
...but that's all the console output I ever get until the end of the track, when I get this:
```
------------------------------
   Media type: Unknown
Device state: Idle
```
My question is: How can I get "progress" updates about the position of the player in the song?

I suspect the Yamaha doesn't supply the same details as an Apple device (anecdotally, the API and general operation are pretty janky), but is it possible to get updates from `pyatv` itself - ie. how many seconds of audio it's put on the output socket (or something else? Perhaps just the number of bytes streamed or something?)?

---
Not really the same point, but I'll put it here for anyone else stumbling across it. Volume changes also aren't reported by `pyatv`. However, you can get these from Yamaha's UDP updates. These updates are quite talkative if you play a track from a server or a music service, but go very quiet when using Airplay (so you can't get playing progress from them), but they do tell you about volume changes. One other observation is the "play/pause" physical button on the Yamaha doesn't do anything when playing Airplay.

**Comment by postlund** [comment]
The push updater API will not update on position changes solely. You will have to keep track on when the latest update came (e.g. current system), calculate the difference between then and "now" and add that to the reported position. This is to avoid spamming with updates when nothing really happens. This is a very common pattern that most libraries do AFAIK.
