### ISSUE TITLE
Error when attempting to pair

### ISSUE THREAD

**Issue by agrimm15** [postlund/pyatv#1935]
### What do you need help with?

I also can't get atvremote to find one of my ATVs but this is my big issue as of now. It fails when attempting to pair with the one ATV it can find. This is on Windows 10, here's a screenshot:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/2708415/222214881-1b0c978d-77d6-4c9b-81c7-bb03e8f6aa59.png">

**Comment by b5i** [comment]
Your Apple TV does not support MRP protocol so it gives you this error.

**Comment by postlund** [comment]
As @b5i said, your device does not support standalone MRP protocol. You should pair the other ones, i.e. `companion`, `airplay` and `raop`.
