### ISSUE TITLE
How can I connect speakers with Apple TV via ssh?

### ISSUE THREAD

**Issue by remlio** [postlund/pyatv#1939]
### What do you need help with?

Hi there! I have RPi with installed pyatv so now I can connect to my ATV HD via ssh, i.e. I can switch it on or off, pausing it or stream some file/url etc. But I still can't realize how to connect some airplay2 speakers with Apple TV via ssh. Could you explain it somehow please?

**Comment by remlio** [comment]
exactly, what I meant is somehow to change audio output device of for the Apple TV. thanks, now I understand that it's impossible

**Comment by michalmo** [comment]
This is something I wanted to investigate at some point, since outputs of ATV and HomePod can be adjusted through iOS, and also though HomeKit automation (Resume Audio action with selected Airplay devices). I think it is done over AirPlay protocol or MRP over AirPlay.

**Comment by remlio** [comment]
> also though HomeKit automation (Resume Audio action with selected Airplay devices). 

That's exactly why I thought it was possible.

**Comment by postlund** [comment]
I'm for this if it can be done, so absolutely feel free to go ahead with it!
