### ISSUE TITLE
When Apple TV is in standby, state is reported as paused

### ISSUE THREAD

**Issue by TimBeekman** [postlund/pyatv#1940]
### Describe the bug

Once the apple tv is turned off the media player entityreport as paused, causing automations based on entity state not to work properly

### Error log

```log
<place log here>
```

### How to reproduce the bug?

1. Turn off Apple TV
2. Check reported state in developer tools

### What is expected behavior?

Once theApple TV has been turned off, the state should change to Idle or Standby

### Operating System

Linux

### Python

3.6

### pyatv

Newest

### Device

Apple TV 4K TVOS16.3

### Additional context

https://github.com/home-assistant/core/issues/76781

**Comment by stevedngo** [comment]
Having the same issue but it seems to based on the app I'm using.  Haven't tested it on all my apps but I noticed it doesn't change to standby from paused on Plex.  Hulu seems to be working fine though.

**Comment by pickett** [comment]
I also see this pretty clearly in the Developer Tools. It actually cycles every 15-20 seconds between off and Paused for me.

**Comment by mschwartz** [comment]
I see it too.  And I see other probably related issues.

Maybe this one isn't so easy?

**Comment by postlund** [comment]
Can someone fix a log when reproducing this? Logs for the component in home Assistant must be enabled (can be done via the Integrations page nowadays) and pyatv as well.

**Comment by postlund** [comment]
I posted an update about this in the mentioned issue at Home Assistant and opened #2048, which hopefully solves the problem.

**Comment by postlund** [comment]
Can someone verify if this still happens with latest release?

**Comment by postlund** [comment]
Great, thanks @mschwartz!
