### ISSUE TITLE
Help installing on Homebridge Pi 

### ISSUE THREAD

**Issue by addisonjames** [postlund/pyatv#1955]
### What do you need help with?

Hi, trying to install pyatv on my Homebridge running on a Pi. Would really appreciate some help (not a python expert).

homebridge-config-ui-x v4.50.2
Node.js Version | v16.19.1
Python 2.7.16

When I try to install via **pip install pyatv** I get the error:
**ImportError: No module named pathlib**
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-0Usxvh/pyatv/**

I've tried installing with sudo, with pip3- etc. 

Can't find any resources online, would super appreciate if anyone could help. Thanks

**Comment by postlund** [comment]
You need at least python 3.7 to run pyatv.

**Comment by Crox77** [comment]
Having the same error message while trying to install:

pi@homebridge:/var/lib/homebridge $ sudo apt install python3 -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.7.3-1).
python3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 165 not upgraded.
pi@homebridge:/var/lib/homebridge $ 
pi@homebridge:/var/lib/homebridge $ pip install pyatv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyatv
  Using cached https://files.pythonhosted.org/packages/10/a8/25564cd6a99dab0b480ae0ab7edc914912702eb66f4a7bab8e9ae203bf9c/pyatv-0.8.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nBoG3m/pyatv/setup.py", line 4, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nBoG3m/pyatv/
pi@homebridge:/var/lib/homebridge $ 

I am running latest version of Python
Thanks
Paul

**Comment by postlund** [comment]
Also due to too old version of python.

**Comment by Crox77** [comment]
thank you for your reply, can you advise on which version of Python I should install
