### ISSUE TITLE
Home assistant Too slow to keep up for seqno error

### ISSUE THREAD

**Issue by dvandijk27** [postlund/pyatv#1990]
### What do you need help with?

when I cast media from home assistant to the apple tv the following error continuously appears in the log: Too slow to keep up for seqno

<img width="419" alt="image" src="https://github.com/postlund/pyatv/assets/133059823/845ceede-32b7-4fe5-b2d6-f9acdf3a0631">

**Comment by postlund** [comment]
It means the streaming can't keep up with the pace, which happens either if your system is too slow or too loaded. Getting a few is usually not a problem, you might hear some distortion if you are unlucky though.

**Comment by postlund** [comment]
Not much more to do about this, will close the issue now.
