### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by tkw23** [postlund/pyatv#1996]
### What do you need help with?

Not sure how to get past this, please help

OSError: [Errno 66] Directory not empty: '/private/var/folders/fr/9g563kz94kg8xxq7nv89y9gm0000gn/T/pip-install-8771k_0h/miniaudio_3566aa37133c4c8b869b04d93a4592d1/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/fr/9g563kz94kg8xxq7nv89y9gm0000gn/T/pip-install-8771k_0h/miniaudio_3566aa37133c4c8b869b04d93a4592d1/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for miniaudio
Failed to build miniaudio
ERROR: Could not build wheels for miniaudio, which is required to install pyproject.toml-based projects

**Comment by postlund** [comment]
Can you provide some more output? Can't say much from this.

**Comment by postlund** [comment]
This probably relates to https://github.com/irmen/pyminiaudio/issues/67. Try installing 1.57 first (`pip install miniaudio=1.57`) and the install pyatv afterwards.

**Comment by postlund** [comment]
Pretty sure that is it, will close this issue. Please re-open if issue persists,
