### ISSUE TITLE
Compatibility with tvOS 17

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#2034]
### What do you need help with?

Apple has presented tvO17 and I usually create a compatibility issue when a new major version is available, so I'll do that again. If there are any dare devils out there running tvOS 17, feel free to leave any test reports here. Usually there are a few quirks in the beginning, but would be nice to see if there are any major problems early.

**Comment by T-IOOO** [comment]
Running TVOS 17 and noticed that the off function doesn’t work. It seems like there needs to be a keypress added or something

**Comment by T-IOOO** [comment]
Yes, it is the turn_off command. I don’t know how to test it though since Im not that advanced user but I can tell you how my setup is.
I am using homebridge with cmdswitch2-no-logs plugin and I have followed a tutorial to set it up with the necessary commands for atvremote to work.

the turn_off command looks something like this:

atvremote -s <IP> --airplay-credentials <SERIAL> turn_off

**Comment by postlund** [comment]
Yeah, that would be right for AirPlay. That's the one you see problems with? If you try companion instead, same thing? You would need to pair:

    atvremote -s <ip> --protocol companion pair

Then do the same thing but with the credentials you got:

    atvremote -s <ip> --companion-credentials <from previous command> turn_off

**Comment by T-IOOO** [comment]
Thanks! It worked like a charm!

**Comment by postlund** [comment]
The MRP based solution is based on navigation, basically pushing buttons and navigate to "sleep" on screen. I guess Apple likely changed the UI for this in tvOS 17 then and we have to add a special case for that now. If someone is up for that task, I'd be willing so support (as I don't tun tvOS 17 myself).

**Comment by aleszczynskig** [comment]
I have inadvertently installed the developer beta on my main Apple TV. The integration with home assistant is no longer working. Is there anything I can do to test home assistant integration and help out. Hopefully in the process I will restore all of my automations as well. 

I've installed the master branch from HACS on my home assistant yellow but it hasn't brought the integration back to life.

**Comment by postlund** [comment]
@aleszczynskig Apple enjoys reverting settings when upgrading, so just go to Settings->AirPlay on your Apple TV and change access setting to "Everyone on the same network" and you should be fine. The beta is old so do not run that.

**Comment by aleszczynskig** [comment]
@postlund - thank you for the information. Is there a working beta of the new "Grandpa release" for home assistant that has the proper state support?

**Comment by postlund** [comment]
@aleszczynskig Current `dev` is bumped to 0.13.0, so I guess it's part of the beta channel. But I'm not entirely sure how that is managed, so it's just a guess.

**Comment by postlund** [comment]
tvOS 17 seems to be rather uneventful, so I think we can close this. Thanks everyone for reporting in!
