### ISSUE TITLE
Implement power management via Companion

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#2048]
### Short feature/function description

I stumbled across the `SystemStatus` event in Companion which I think is very usable for power management. It can be subscribed to like this:

```
{'_i': '_interest', '_t': 1, '_c': {'_regEvents': ['SystemStatus']}, '_x': 43056}
```

It will then trigger events like these:
```
{'_i': 'SystemStatus', '_x': 798412996, '_c': {'state': 1}, '_t': 1}
```

Based on some testing, `state` seems to take these values:

1. Off/standby
2. Screensave active
3. On

Pretty cool. I have no idea when this was added or how to check if it is supported. I am running tvOS 16.5 and it works there at least.

### What needs to be done?

Must subscribe to this event and implement power management to report state based on this in Companion.

### Is this a breaking change?

No

### Anything else worth knowing?

I have not found the exact names for the different values, so there might be additional values. I believe it's part of the `SystemStatus` framework. I think it would be a good idea to look up when that (private) framework was added dig a bit into it to figure out correct values.

**Comment by postlund** [comment]
I believe `state` can have these values:
1. Asleep
2. Screensaver
3. Awake
4. Idle
Not sure when `Idle` would happen as I haven't managed to trigger that.

I also figured out how to fetch current system status:
```
>> {'_i': 'FetchAttentionState', '_t': 2, '_c': {}, '_x': 63791}
<< {'_c': {'state': 3}, '_t': 3, '_x': 63791}
```

Should be everything I need hopefully.

**Comment by mschwartz** [comment]
Is there any way to power off the ATV via software?  I'm guessing not because none of the ATV remote software I've seen has the capability.  Just long press on power button on the remote does this.

**Comment by postlund** [comment]
@mschwartz You mean like real power off where it's woken either by the remote or via WOL (sleep proxy to be exact)? Not sure if that is possible, no, maybe? I think `RemoteControl.sleep` used to do that, but has transitioned to suspend a few major release back. To me that makes more sense since the Apple TV has changed its role quite a bit since it was released. Now it's used both as a HomeKit hub as well as a Thread router, requiring the device to br on anyways to function. It's a very low power device when in standby, so I don't really see the point in putting it to deep sleep anyways. This changed has solved a lot of pain for me too, as the old behavior yielded a lot of issues being reported due to lost connections and whatnot. So I'm welcoming it with open arms.

**Comment by mschwartz** [comment]
I have CEC enabled on my AVR and my TV.  Turning on the ATV turns on all the devices.  Long press on the power button turns them all off.

Otherwise, low power would be perfectly fine :)

**Comment by mschwartz** [comment]
OK, so I took a look at my code and it does look like there's a power off call for pyatv.


`
            elif message == "SUSPEND":
                await atv.remote_control.home()
            elif message == "HOME":
                await atv.power.turn_on()
                await atv.remote_control.home()
            elif message == "POWERON":
                await atv.power.turn_on()
            elif message == "POWER":
                await atv.power.turn_off()
            elif message == "POWEROFF":
                await atv.power.turn_off()
`

**Comment by postlund** [comment]
Yeah, `turn_off` is the same as long pressing TV-button and selecting sleep from the menu if only AirPlay (i.e. MRP) is paired. If you have Companion paired, it's the same functionality as when using a shortcut to turn off. I belive both should yield the result you want, at least the Companion solution.

**Comment by postlund** [comment]
Merged and done!

**Comment by crxporter** [comment]
Could this finally take care of #958 ?? 

I need to test this asap - how would I subscribe to this event using atvscript?

(feel free to continue discussing here or at #958 - I'll watch both)

**Comment by postlund** [comment]
Yes, it should. It's in 0.13.0 and since `atvscript` supports power events, it should just work. It assumes you provide Companion credentials. So just upgrade and make sure you provide Companion credentials, that should be it.
