### ISSUE TITLE
Trouble with using atvremote play_url on tvOS 16.6

### ISSUE THREAD

**Issue by SaszaZ** [postlund/pyatv#2058]
### What do you need help with?

Hi
I need help with streaming to appleTV 4k on tvOS16.6 via airplay. Right now, when i use command
`atvremote --id <id> --airplay-credentials <airplay-credentials> play_url=<url>` 
i get a spinning loading circle and then appleTV goes back to idle state without playing the stream specified in url. Is there anything i might do to make it work?

**Comment by postlund** [comment]
See this comment: https://github.com/postlund/pyatv/issues/1768#issuecomment-1575626478

**Comment by postlund** [comment]
Will hopefully work soon, see #2064.
