### ISSUE TITLE
HomePod 2 reported as "Model/SW: AudioAccessory6,1, Unknown OS 16.5"

### ISSUE THREAD

**Issue by dresken** [postlund/pyatv#2060]
### Describe the bug

I have a HomePod 2 and it is being reported as:
   Model/SW: AudioAccessory6,1, Unknown OS 16.5
Mostly for me it is not being picked up by a script which looks for a match on pyatv.const.OperatingSystem.TvOS

### How to reproduce the bug?

atvremote scan

### What is expected behavior?

I presume:
   Model/SW: HomePod 2, tvOS 16.5

### Operating System

Linux

### Python

3.9

### pyatv

0.13.0

### Device

HomePod 2, tvOS 16.5

### Additional context

n/A

**Comment by postlund** [comment]
Yeah, it needs to be added as a new device. I'll try to do that today, I'm planning to make a release anyways so would be great to include this.

**Comment by postlund** [comment]
PR #2061 adds second gen HomePod.
