### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by Crox77** [postlund/pyatv#2066]
### What do you need help with?

Good Morning

I have installed PYatv correct I believe but when I try to run the atvremote scan I get a command not found message.

Here is the logs pi@homebridge:/var/lib/homebridge $ pip3 install pyatv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyatv
  Using cached https://files.pythonhosted.org/packages/10/11/2ef80cbe30db482c387faf87e4a3a8a523278b07dc0f5274e8f7e15f2460/pyatv-0.10.3-py3-none-any.whl
Collecting mediafile>=0.8.1 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/5a/db/f08befa54604a8192fbd4fc009f99585c693f43bd175f73162695978ee30/mediafile-0.11.0-py3-none-any.whl
Collecting aiohttp<5,>=3.8.1 (from pyatv)
  Using cached https://www.piwheels.org/simple/aiohttp/aiohttp-3.8.4-cp37-cp37m-linux_armv7l.whl
Collecting bitarray>=2.1.2 (from pyatv)
  Using cached https://www.piwheels.org/simple/bitarray/bitarray-2.7.5-cp37-cp37m-linux_armv7l.whl
Collecting requests>=2.23.0 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl
Collecting miniaudio>=1.45 (from pyatv)
  Using cached https://www.piwheels.org/simple/miniaudio/miniaudio-1.59-cp37-cp37m-linux_armv7l.whl
Collecting chacha20poly1305-reuseable>=0.0.3 (from pyatv)
Collecting async-timeout>=4.0.2 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl
Collecting srptools>=0.2.0 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/8d/b8/3f935d7f7d6bc25a88859beb0a6e246313012a12ae4844665322f771a5cb/srptools-1.0.1-py2.py3-none-any.whl
Collecting ifaddr>=0.1.7 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/9c/1f/19ebc343cc71a7ffa78f17018535adc5cbdd87afb31d7c34874680148b32/ifaddr-0.2.0-py3-none-any.whl
Collecting zeroconf>=0.38.1 (from pyatv)
Collecting cryptography>=36.0.2 (from pyatv)
  Using cached https://files.pythonhosted.org/packages/19/8c/47f061de65d1571210dc46436c14a0a4c260fd0f3eaf61ce9b9d445ce12f/cryptography-41.0.1.tar.gz
  Installing build dependencies ... done
Collecting protobuf>=3.19.3 (from pyatv)
  Using cached https://www.piwheels.org/simple/protobuf/protobuf-4.23.3-cp37-cp37m-linux_armv7l.whl
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from mediafile>=0.8.1->pyatv) (1.12.0)
Collecting mutagen>=1.46 (from mediafile>=0.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/03/ee/114d7016d2e34f341e212fefb5e7bd87785077ebcfff0ad23a497c70eea1/mutagen-1.46.0-py3-none-any.whl
Collecting aiosignal>=1.1.2 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl
Collecting asynctest==0.13.0; python_version < "3.8" (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/e8/b6/8d17e169d577ca7678b11cd0d3ceebb0a6089a7f4a2de4b945fe4b1c86db/asynctest-0.13.0-py3-none-any.whl
Collecting multidict<7.0,>=4.5 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://www.piwheels.org/simple/multidict/multidict-6.0.4-cp37-cp37m-linux_armv7l.whl
Collecting attrs>=17.3.0 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/f0/eb/fcb708c7bf5056045e9e98f62b93bd7467eb718b0202e7698eb11d66416c/attrs-23.1.0-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://www.piwheels.org/simple/yarl/yarl-1.9.2-cp37-cp37m-linux_armv7l.whl
Collecting typing-extensions>=3.7.4; python_version < "3.8" (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/5f/86/d9b1518d8e75b346a33eb59fa31bdbbee11459a7e2cc5be502fa779e96c5/typing_extensions-4.6.3-py3-none-any.whl
Collecting frozenlist>=1.1.1 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://www.piwheels.org/simple/frozenlist/frozenlist-1.3.3-cp37-cp37m-linux_armv7l.whl
Collecting charset-normalizer<4.0,>=2.0 (from aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/ef/81/14b3b8f01ddaddad6cdec97f2f599aa2fa466bd5ee9af99b08b7713ccd29/charset_normalizer-3.1.0-py3-none-any.whl
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.23.0->pyatv) (2.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.23.0->pyatv) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.23.0->pyatv) (2018.8.24)
Collecting cffi>=1.12.0 (from miniaudio>=1.45->pyatv)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp37-cp37m-linux_armv7l.whl
Collecting importlib-metadata; python_version < "3.8" (from attrs>=17.3.0->aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/ff/94/64287b38c7de4c90683630338cf28f129decbba0a44f0c6db35a873c73c4/importlib_metadata-6.7.0-py3-none-any.whl
Collecting pycparser (from cffi>=1.12.0->miniaudio>=1.45->pyatv)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->attrs>=17.3.0->aiohttp<5,>=3.8.1->pyatv)
  Using cached https://files.pythonhosted.org/packages/5b/fa/c9e82bbe1af6266adf08afb563905eb87cab83fde00a0a08963510621047/zipp-3.15.0-py3-none-any.whl
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... done
  Stored in directory: /home/pi/.cache/pip/wheels/65/f5/22/566d1b9c79b4edcda9799a71b59ffa6dbc18976caec3e29887
Successfully built cryptography
Installing collected packages: mutagen, mediafile, frozenlist, aiosignal, asynctest, multidict, typing-extensions, async-timeout, zipp, importlib-metadata, attrs, yarl, charset-normalizer, aiohttp, bitarray, requests, pycparser, cffi, miniaudio, cryptography, chacha20poly1305-reuseable, srptools, ifaddr, zeroconf, protobuf, pyatv
  The scripts mid3cp, mid3iconv, mid3v2, moggsplit, mutagen-inspect and mutagen-pony are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script normalizer is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script srptools is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts atvlog, atvproxy, atvremote and atvscript are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 asynctest-0.13.0 attrs-23.1.0 bitarray-2.7.5 cffi-1.15.1 chacha20poly1305-reuseable-0.2.5 charset-normalizer-3.1.0 cryptography-41.0.1 frozenlist-1.3.3 ifaddr-0.2.0 importlib-metadata-6.7.0 mediafile-0.11.0 miniaudio-1.59 multidict-6.0.4 mutagen-1.46.0 protobuf-4.23.3 pyatv-0.10.3 pycparser-2.21 requests-2.31.0 srptools-1.0.1 typing-extensions-4.6.3 yarl-1.9.2 zeroconf-0.69.0 zipp-3.15.0
pi@homebridge:/var/lib/homebridge $ atvremote scan
bash: atvremote: command not found
pi@homebridge:/var/lib/homebridge $ cd /home/pi/.local/bin
pi@homebridge:~/.local/bin $ atvremote scan
bash: atvremote: command not found
pi@homebridge:~/.local/bin $ cd /var/lib/homebridge
pi@homebridge:/var/lib/homebridge $ 

Am I dong something wrong? any help gratefully received Thanks

**Comment by postlund** [comment]
You get some hints here (similar for other scripts as well):
```
The scripts atvlog, atvproxy, atvremote and atvscript are installed in '/home/pi/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
You either have to run it with `~/.local/bin/atvremote` (alternatively `PATH="~/.local/bin/:$PATH" atvremote`) or add `~/.local/bin` to your PATH. I however recommend that you create a virtual environment and run it from there instead, see [this](https://pyatv.dev/documentation/#virtual-environment) page.

**Comment by Crox77** [comment]
> You get some hints here (similar for other scripts as well):
> 
> ```
> The scripts atvlog, atvproxy, atvremote and atvscript are installed in '/home/pi/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> ```
> 
> You either have to run it with `~/.local/bin/atvremote` (alternatively `PATH="~/.local/bin/:$PATH" atvremote`) or add `~/.local/bin` to your PATH. I however recommend that you create a virtual environment and run it from there instead, see [this](https://pyatv.dev/documentation/#virtual-environment) page.

thank you for your reply I can now get the scan to work, however I know get this error?

pi@homebridge:/var/lib/homebridge $ PATH="~/.local/bin/:$PATH" atvremote --id C8:D0:83:D9:E5:FE --protocol pair
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 717, in _run_application
    return await cli_handler(loop)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/atvremote.py", line 475, in cli_handler
    args = parser.parse_args()
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1936, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1864, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/pi/.local/lib/python3.7/site-packages/pyatv/scripts/__init__.py", line 24, in __call__
    "Valid protocols are: " + ", ".join(protocols.keys())
argparse.ArgumentTypeError: Valid protocols are: dmap, mrp, airplay, companion, raop

>>> An error occurred, full stack trace above

**Comment by postlund** [comment]
You need to specify one of the protocols as well:

    PATH="~/.local/bin/:$PATH" atvremote --id C8:D0:83:D9:E5:FE --protocol companion pair

**Comment by Crox77** [comment]
Many Thanks for your help, I have it all working fine now

**Comment by postlund** [comment]
Great, happy fiddling! 👍
