### ISSUE TITLE
Add MRP proxy script

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#207]
**Short feature/function description**
I made a small hack that acts an MRP proxy. It basically announces itself as another MRP capable device on the network and acts as a man-in-the-middle in order to capture messages unencrypted. It's not a perfect solution implementation-wise, but it's quite helpful sometimes. So I should add it to the repo in case someone finds it useful.

**What needs to be done?**
* Verify that the script still works (it was over a year ago I used it)
* Clean it up
* Write basic instructions

**Is this a breaking change?**
No

**Anything else worth knowing?**
No

**Comment by mattcrump** [comment]
Looking forward to seeing this.

**Comment by postlund** [comment]
I used pushed #215 with the proxy script. Will merge it as soon as the checks passes. Let me know if it works for you!

**Comment by mattcrump** [comment]
Works perfectly.  Very nice!
