### ISSUE TITLE
Sharing credentials across clients

### ISSUE THREAD

**Issue by IsakTheHacker** [postlund/pyatv#2085]
### What do you need help with?

Is it possible to share the credentials for one Apple TV with multiple other clients controlling it? Would there be any limitations when doing so, such as only one connection at one time with one set of credentials?

**Comment by IsakTheHacker** [comment]
Related: Would it be possible for one client to talk to multiple Apple TVs at the same time?

**Comment by postlund** [comment]
One client can talk to multiple devices at the same time, should be no problem. I believe that there should be no problem sharing credentials either, but I haven't tried that enough to be sure. Having multiple connections open with the same credentials have worked fine for me at least when testing,

**Comment by IsakTheHacker** [comment]
That's excellent to know, thank you
