### ISSUE TITLE
How can I stream audio to multiple devices at once?

### ISSUE THREAD

**Issue by msalmonw** [postlund/pyatv#2088]
### What do you need help with?

How can I stream audio to multiple devices at once? I want to stream audio to multiple speakers/devices at once, is there any way to achieve this?

**Comment by postlund** [comment]
Unfortunately I don't have added support for grouping devices yet, so it's not really possible (other than streaming the same audio in parallel, which wouldn't be synchronized).

**Comment by msalmonw** [comment]
Is there any workaround for this? If you have anything in your mind that could take me in the right direction, please let me know

**Comment by postlund** [comment]
Not using pyatv (I would have to implement support for that), but you can use other software that supports it, like [owntone](https://owntone.github.io/owntone-server/).

**Comment by msalmonw** [comment]
Is that something I could do myself? I'm developing an application in Python, so i'm stuck with pyatv

**Comment by postlund** [comment]
Owntone has an HTTP based API (REST I guess), so you could also run that separately and control it from python. Assuming that setup would be ok.

**Comment by msalmonw** [comment]
Yes, Owntone seems very promising now that I've studied it a little. Let's see if I can integrate it properly with my own application. Thanks a lot for your help!

**Comment by postlund** [comment]
Yeah, that's what I would recommend to use for now. Good luck! 👍
