### ISSUE TITLE
Change the name pyatv in Remote App and Devices

### ISSUE THREAD

**Issue by sayanlp99** [postlund/pyatv#2097]
### What do you need help with?

![Screenshot 2023-07-12 at 7 21 41 PM](https://github.com/postlund/pyatv/assets/28763093/574aad27-1674-4558-b809-c414cb8066d2)
Is there any way to change the name of pyatv to something alse, Like I am running it from a raspberry pi and i want the hostname of the pi in place of pyatv. Is it possible,  If so how can I do so. Thank you.

**Comment by postlund** [comment]
Yes, you can change that with `--remote-name` when pairing.
