### ISSUE TITLE
ERROR: Could not find any Apple TV on current network

### ISSUE THREAD

**Issue by raufis27** [postlund/pyatv#213]
Any ideas why this happens ? :
```shell
$ atvremote --id c869cd06126d --address 10.10.10.10 -a media_type   (or any other command)
ERROR: Could not find any Apple TV on current network
```

BUT:

```shell
$ atvremote scan
Name: Living Room
Address: 10.10.10.10
Id: aabbccddeeff 
Services:
 - Protocol: AirPlay, Port: 7000
 - Protocol: MRP, Port: 56845, Credentials: None
```

**Comment by postlund** [comment]
It happens a lot for lots of people, unfortunately. No idea what the main issue is, but zeroconf doesn't find the expected services. I suspect it has something to do with python-zeroconf, since other browser clients (like Avahi and dns-sd) seems to work. I am thinking of trying out aiozeroconf, which is an asyncio port of python-zeroconf instead. If it works better. Since it's based on the same codebase, there are no guarantees though. But if you could help me out, that would be great.

I will create a separate issue for this, in case other people want to help out as well. Hang tight.

**Comment by postlund** [comment]
Please see #214.

**Comment by postlund** [comment]
I had another look at this and I cannot really see the problem, assuming you are running a "late" version of pyatv (like current master). Can you re-run with `- - debug` and attach logs?

My output looks like this:
```shell
$ atvremote -a --address 10.0.10.81 --id aabbccddeeff playing
Media type: Unknown
Play state: Paused
```

**Comment by raufis27** [comment]
More information:
atvremote --id aabbccddeeff --address 10.10.10.10 -a play_state
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 492, in _run_application
    return await cli_handler(loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 314, in cli_handler
    return await _handle_commands(args, loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 407, in _handle_commands
    ret = await _handle_device_command(args, cmd, atv, loop)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 439, in _handle_device_command
    playing_resp = await atv.metadata.playing()
  File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/__init__.py", line 250, in playing
    await self.protocol.start()
  File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 70, in start
    await self.send_and_receive(msg)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 153, in send_and_receive
    return await self._receive(identifier, timeout)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 162, in _receive
    semaphore.acquire(), timeout, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

>>> An error occurred, full stack trace above`

Right after this error:
#atvremote --id aabbccddeeff --address 10.10.10.10 -a play_state
#ERROR: Could not find any Apple TV on current network

**Comment by raufis27** [comment]
` atvremote scan
Scan Results
========================================
    Name: Living Room
 Address: 10.10.10.10
      Id: aabbccddeeff
Services:
 - Protocol: AirPlay, Port: 7000
`
# atvremote --debug --id aabbccddeeff --address 10.10.10.10 -a play_state
#DEBUG: Discovering devices for 3 seconds
DEBUG: Ignoring unusable device Living Room
ERROR: Could not find any Apple TV on current network

**Comment by raufis27** [comment]
DEBUG:getmac:Raw MAC found: aabbccddeeff
DEBUG:pyatv:Auto-discovered Living Room at 10.10.10.10:7000 (protocol: 3)

**Comment by postlund** [comment]
> More information:
> 
> ```shell
> $ atvremote --id aabbccddeeff --address 10.10.10.10 -a play_state
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 492, in _run_application
>     return await cli_handler(loop)
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 314, in cli_handler
>     return await _handle_commands(args, loop)
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 407, in _handle_commands
>     ret = await _handle_device_command(args, cmd, atv, loop)
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/__main__.py", line 439, in _handle_device_command
>     playing_resp = await atv.metadata.playing()
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/__init__.py", line 250, in playing
>     await self.protocol.start()
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 70, in start
>     await self.send_and_receive(msg)
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 153, in send_and_receive
>     return await self._receive(identifier, timeout)
>   File "/usr/local/lib/python3.6/dist-packages/pyatv/mrp/protocol.py", line 162, in _receive
>     semaphore.acquire(), timeout, loop=self.loop)
>   File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError
> 
> >>> An error occurred, full stack trace above
> ```

This means that the Apple TV didn't respond in time. More or less impossible to know why, especially without debug logs (please run with `--debug`).

> Right after this error:
> 
> ```shell
> $ atvremote --id aabbccddeeff --address 10.10.10.10 -a play_state
> ERROR: Could not find any Apple TV on current network
> ```

Again, please run with `--debug` so that I can get some more insights into what is happening.

**Comment by postlund** [comment]
> ```shell
> $ atvremote scan
> Scan Results
> ========================================
>     Name: Living Room
>  Address: 10.10.10.10
>       Id: aabbccddeeff
> Services:
>  - Protocol: AirPlay, Port: 7000
> 
> $ atvremote --debug --id aabbccddeeff --address 10.10.10.10 -a play_state
> DEBUG: Discovering devices for 3 seconds
> DEBUG: Ignoring unusable device Living Room
> ERROR: Could not find any Apple TV on current network
> ```
> 
> Based on scan information we can see that there are no services available for aabbccddeeff except Airplay.

Here I guess that the scanning failed, like it does sometimes. I will try to improve the debug logging for this a bit.

**Comment by postlund** [comment]
Maybe we can close this now?

**Comment by postlund** [comment]
@raufis27 Can you confirm if this is till a problem? Otherwise I would like to close this.

**Comment by raufis27** [comment]
So, after some testing I found that AppleTV will stop responding to atvremote and RemoteApp if I use atvremote as part of my home automation. I am using OpenHub, and have function setup when OH runs command: “atvremote .... playing” every 30 seconds. I do this to display current state of ATV. So when this function is enabled ATV works fine couple of hours and then stops responding. To fix the issue I have to reboot ATV or reset network. Prior to TVOS 13 I didn’t have this problem.
I wanna try to increase timing from 30 seconds to 3 minutes and see if ATV can handle it. 
You can close this if you want.

**Comment by postlund** [comment]
> So, after some testing I found that AppleTV will stop responding to atvremote and RemoteApp if I use atvremote as part of my home automation. I am using OpenHub, and have function setup when OH runs command: “atvremote .... playing” every 30 seconds. I do this to display current state of ATV. So when this function is enabled ATV works fine couple of hours and then stops responding. To fix the issue I have to reboot ATV or reset network. Prior to TVOS 13 I didn’t have this problem.
> I wanna try to increase timing from 30 seconds to 3 minutes and see if ATV can handle it.
> You can close this if you want.

Yes, I totally agree that the issue still exists and must be looked into. But this issue started as something else and migrated over to timeout problem. Since #238 is basically the same thing, we can continue the discussion there.
