### ISSUE TITLE
Recognized Server Name by the AppleTV

### ISSUE THREAD

**Issue by MauroKTM** [postlund/pyatv#2138]
### What do you need help with?

When you pair the server with the Apple TV, on the AppleTV Menu "Remote App and Devices", the server is recognized as "Living Room". Is there a way to change this name?
Thank you

**Comment by postlund** [comment]
You can use `--remote-name <name>` when pairing.

**Comment by postlund** [comment]
This is now a setting and can be changed with `atvremote -s 10.0.10.81 change_setting=info.name,new_name`.
