### ISSUE TITLE
Missing Device ID

### ISSUE THREAD

**Issue by ckeehan** [postlund/pyatv#217]
**Describe the bug**
When using `atvremote scan`, the device name, address, services, and protocols all are returned correctly but the device ID says `Id: None`
When using `atvremote --address <IP> --debug --protocol mrp pair`, the following error is returned:
`pyatv.exceptions.DeviceIdMissingError: missing device id for <IP>`

**To Reproduce**
Unknown

**Expected behavior**
The device ID is returned successfully

**System Setup (please complete the following information):**
 - OS: Debian
 - Python: 3.5.3
 - pyatv: 0.4.0a1

**Additional context**
I have successfully connected to this Apple TV before but was recently unable to find it using `atvremote scan` on the latest release version. The latest dev version from Git is able to find it but the device ID is still missing.

**Comment by seishan** [comment]
I've recently (and intermittently) run into this issue as well. In my case, running `atvremote scan --debug` indicates that the device's MAC address is also not getting found.

**Comment by seishan** [comment]
I've noticed this issue recently. I was somehow able to work around the issue by running `getmac --ip <addr>`, which resolves the device ID, before running `atvremote scan`.

**Comment by postlund** [comment]
Issue #219 will deal with this.

**Comment by postlund** [comment]
I have made some progress now and hopefully this should work better on `master`. Just do `atvremote scan`, pick one of the identifiers for the device of interest and run:

```shell
$ atvremote -i <identifier> pair
```

**Comment by postlund** [comment]
Added some example output in #222 as well.

**Comment by postlund** [comment]
I have merged #224 now and people seem to have better luck with that. Perhaps you could try again @ckeehan and @seishan? Would love to know if it works better for you as well.

**Comment by ckeehan** [comment]
Works excellent now. Thank you!

**Comment by postlund** [comment]
Awesome! Thanks for reporting back! 👍
