### ISSUE TITLE
Can not install pyatv, i'm stuck on this 

### ISSUE THREAD

**Issue by diZzyc0de** [postlund/pyatv#2196]
### What do you need help with?

**Building wheels for collected packages: zeroconf
  Building wheel for zeroconf (pyproject.toml) ... \**
  
  everytime i will install the pyatv i'm stucking here 
  
  does anyone knows a solution? 
  
  thank you for your help

**Comment by postlund** [comment]
No more output at all? How long did you wait?

**Comment by diZzyc0de** [comment]
Hi, sorry that i bothered you, but now it is through the installation .  i do not know how, but it works now after 4/5 hours, lol. 

thanks anyway for the quick response :)

**Comment by postlund** [comment]
There should be wheels available for python-zeroconf, which doesn't seem to be the case here. What platform (CPU and operating system) are you running?
