### ISSUE TITLE
Verify that basic info is correct

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#226]
**Short feature/function description**
I believe that basic info (media title, artist, etc) is a little shaky at the moment. It needs to be verified to be correct.

**What needs to be done?**
Play some media and look at the debug logs to see what happens. Maybe some message is missing?

Debug log man be obtained via:
```shell
$ atvremote-i <id> --debug playing
```

**Is this a breaking change?**
No

**Anything else worth knowing?**
No

**Comment by raufis27** [comment]
I don't see media title in debug. 

DEBUG: >> Send (Data=080f122430393237393064392d656437392d346331312d383365302d3039333634316562663164622000a2017c0a2438623763333435302d393835642d343035662d393335612d306564343231306334663537120570796174761a066950686f6e65220531344736302a12636f6d2e6170706c652e545652656d6f746532063237332e31323801403a480150016211636f6d2e6170706c652e54564d75736963680170017801880102)
DEBUG: >> Send: Protobuf=type: DEVICE_INFO_MESSAGE
identifier: "xxxxxxxx"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "xxxxxxx"
  name: "pyatv"
  localizedModelName: "iPhone"
  systemBuildVersion: "14G60"
  applicationBundleIdentifier: "com.apple.TVRemote"
  applicationBundleVersion: "273.12"
  protocolVersion: 1
  lastSupportedMessageType: 58
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  sharedQueueVersion: 2
}

DEBUG: << Receive (Data=e802080f122430393237393064392d656437392d346331312d383365302d3039333634316562663164622000a201ba020a2435354443383937462d413337382d344246362d424644342d304634413738424544314136120b4c6976696e6720526f6f6d1a094170706c65c2a05456220531374b38322a16636f6d2e6170706c652e6d6564696172656d6f7465643801404d480150016211636f6d2e6170706c652e54564d757369636801700178018801029a012436364535414245382d353041452d343044322d413737372d323543434639463944463231a2011163383a36393a63643a30363a31323a3664a80104b00101c00100d2012444394441373243442d323239442d343144312d394339372d313733433730393833373837e80101f00100fa0112636f6d2e6170706c652e706f64636173747382022444394441373243442d323239442d343144312d394339372d3137334337303938333738378a02095456416972506c6179)
DEBUG: << Receive: Protobuf=type: DEVICE_INFO_MESSAGE
identifier: "xxxxxx"
priority: 0
[deviceInfoMessage] {
  uniqueIdentifier: "xxxxxx"
  name: "Living Room"
  localizedModelName: "Apple\302\240TV"
  systemBuildVersion: "17K82"
  applicationBundleIdentifier: "com.apple.mediaremoted"
  protocolVersion: 1
  lastSupportedMessageType: 77
  supportsSystemPairing: true
  allowsPairing: true
  systemMediaApplication: "com.apple.TVMusic"
  supportsACL: true
  supportsSharedQueue: true
  supportsExtendedMotion: true
  sharedQueueVersion: 2
  localReceiverPairingIdentity: "xxxxxxxx-50AE-40D2-A777-25CCF9F9DF21"
}

DEBUG: >> Send (Data=08242000)
DEBUG: >> Send: Protobuf=type: SET_READY_STATE_MESSAGE
priority: 0

DEBUG: >> Send (Data=08102000aa01080801100118012001)
DEBUG: >> Send: Protobuf=type: CLIENT_UPDATES_CONFIG_MESSAGE
priority: 0
[clientUpdatesConfigMessage] {
  artworkUpdates: true
  nowPlayingUpdates: true
  volumeUpdates: true
  keyboardUpdates: true
}

DEBUG: >> Send (Data=08292000)
DEBUG: >> Send: Protobuf=type: WAKE_DEVICE_MESSAGE
priority: 0

DEBUG: << Receive (Data=8b04080420004a84041a960308001291030a2439353444443944312d413137422d343937442d393646322d33313130453043454131424412e8020a19446973636f7665727920d0a0d0bed181d181d0b8d18f2048449801009902000000a0976e923fbd020000803fe2022439353444443944312d413137422d343937442d393646322d3331313045304345413142449a04850262706c6973743030d4010203040506070a582476657273696f6e592461726368697665725424746f7058246f626a6563747312000186a05f100f4e534b657965644172636869766572d1080954726f6f748001a30b0c1355246e756c6cd30d0e0f101112574e532e6b6579735a4e532e6f626a656374735624636c617373a0a08002d2141516175a24636c6173736e616d655824636c61737365735f10134e534d757461626c6544696374696f6e617279a31618195c4e5344696374696f6e617279584e534f626a65637408111a24293237494c5153575d646c777e7f808287929bb1b5c20000000000000101000000000000001a000000000000000000000000000000cbd1040401badc97b5c1412a044b6f6469300142004a560a150801120b4c6976696e6720526f6f6d18cc86bde204121008bc01120b636f6d2e746563682e74761a2b0a194d6564696152656d6f74652d44656661756c74506c61796572120e44656661756c7420506c6179657259d3f6bbdc97b5c1412208372000da031b0a1908bc01120b636f6d2e746563682e747620f5033a044b6f646919082e20009203120a1008bc01120b636f6d2e746563682e7476)
DEBUG: << Receive: Protobuf=type: SET_STATE_MESSAGE
priority: 0
[setStateMessage] {
  displayName: "Netflix"
  playbackState: 1
  playerPath {
    origin {
      type: 1
      displayName: "Living Room"
      identifier: xxxxxxx
    }
    client {
      processIdentifier: 188
      bundleIdentifier: "com.tech.tv"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
}

DEBUG: << Receive: Protobuf=priority: 0

DEBUG: << Receive: Protobuf=priority: 0

DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method MrpMetadata._handle_set_state of <pyatv.mrp.MrpMetadata object at 0x7f2c93f0f518>>, data=None)
DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method MrpPushUpdater._handle_update of <pyatv.mrp.MrpPushUpdater object at 0x7f2c93f0f550>>, data=None)
DEBUG: One-shot with message type 4 to Listener(func=<function MrpProtocol.start.<locals>._wait_for_updates at 0x7f2c96169bf8>, data=<asyncio.locks.Semaphore object at 0x7f2c95945208 [locked,waiters:1]>)
Media type: Unknown
Play state: Playing
DEBUG: Disconnected from device: None

**Comment by postlund** [comment]
> I don't see media title in debug.
> 
> DEBUG: >> Send (Data=080f122430393237393064392d656437392d346331312d383365302d3039333634316562663164622000a2017c0a2438623763333435302d393835642d343035662d393335612d306564343231306334663537120570796174761a066950686f6e65220531344736302a12636f6d2e6170706c652e545652656d6f746532063237332e31323801403a480150016211636f6d2e6170706c652e54564d75736963680170017801880102)
> DEBUG: >> Send: Protobuf=type: DEVICE_INFO_MESSAGE
> identifier: "xxxxxxxx"
> priority: 0
> [deviceInfoMessage] {
> uniqueIdentifier: "xxxxxxx"
> name: "pyatv"
> localizedModelName: "iPhone"
> systemBuildVersion: "14G60"
> applicationBundleIdentifier: "com.apple.TVRemote"
> applicationBundleVersion: "273.12"
> protocolVersion: 1
> lastSupportedMessageType: 58
> supportsSystemPairing: true
> allowsPairing: true
> systemMediaApplication: "com.apple.TVMusic"
> supportsACL: true
> supportsSharedQueue: true
> supportsExtendedMotion: true
> sharedQueueVersion: 2
> }
> 
> DEBUG: << Receive (Data=e802080f122430393237393064392d656437392d346331312d383365302d3039333634316562663164622000a201ba020a2435354443383937462d413337382d344246362d424644342d304634413738424544314136120b4c6976696e6720526f6f6d1a094170706c65c2a05456220531374b38322a16636f6d2e6170706c652e6d6564696172656d6f7465643801404d480150016211636f6d2e6170706c652e54564d757369636801700178018801029a012436364535414245382d353041452d343044322d413737372d323543434639463944463231a2011163383a36393a63643a30363a31323a3664a80104b00101c00100d2012444394441373243442d323239442d343144312d394339372d313733433730393833373837e80101f00100fa0112636f6d2e6170706c652e706f64636173747382022444394441373243442d323239442d343144312d394339372d3137334337303938333738378a02095456416972506c6179)
> DEBUG: << Receive: Protobuf=type: DEVICE_INFO_MESSAGE
> identifier: "xxxxxx"
> priority: 0
> [deviceInfoMessage] {
> uniqueIdentifier: "xxxxxx"
> name: "Living Room"
> localizedModelName: "Apple\302\240TV"
> systemBuildVersion: "17K82"
> applicationBundleIdentifier: "com.apple.mediaremoted"
> protocolVersion: 1
> lastSupportedMessageType: 77
> supportsSystemPairing: true
> allowsPairing: true
> systemMediaApplication: "com.apple.TVMusic"
> supportsACL: true
> supportsSharedQueue: true
> supportsExtendedMotion: true
> sharedQueueVersion: 2
> localReceiverPairingIdentity: "xxxxxxxx-50AE-40D2-A777-25CCF9F9DF21"
> }
> 
> DEBUG: >> Send (Data=[08242000](tel:08242000))
> DEBUG: >> Send: Protobuf=type: SET_READY_STATE_MESSAGE
> priority: 0
> 
> DEBUG: >> Send (Data=08102000aa01080801100118012001)
> DEBUG: >> Send: Protobuf=type: CLIENT_UPDATES_CONFIG_MESSAGE
> priority: 0
> [clientUpdatesConfigMessage] {
> artworkUpdates: true
> nowPlayingUpdates: true
> volumeUpdates: true
> keyboardUpdates: true
> }
> 
> DEBUG: >> Send (Data=[08292000](tel:08292000))
> DEBUG: >> Send: Protobuf=type: WAKE_DEVICE_MESSAGE
> priority: 0
> 
> DEBUG: << Receive (Data=8b04080420004a84041a960308001291030a2439353444443944312d413137422d343937442d393646322d33313130453043454131424412e8020a19446973636f7665727920d0a0d0bed181d181d0b8d18f2048449801009902000000a0976e923fbd020000803fe2022439353444443944312d413137422d343937442d393646322d3331313045304345413142449a04850262706c6973743030d4010203040506070a582476657273696f6e592461726368697665725424746f7058246f626a6563747312000186a05f100f4e534b657965644172636869766572d1080954726f6f748001a30b0c1355246e756c6cd30d0e0f101112574e532e6b6579735a4e532e6f626a656374735624636c617373a0a08002d2141516175a24636c6173736e616d655824636c61737365735f10134e534d757461626c6544696374696f6e617279a31618195c4e5344696374696f6e617279584e534f626a65637408111a24293237494c5153575d646c777e7f808287929bb1b5c20000000000000101000000000000001a000000000000000000000000000000cbd1040401badc97b5c1412a044b6f6469300142004a560a150801120b4c6976696e6720526f6f6d18cc86bde204121008bc01120b636f6d2e746563682e74761a2b0a194d6564696152656d6f74652d44656661756c74506c61796572120e44656661756c7420506c6179657259d3f6bbdc97b5c1412208372000da031b0a1908bc01120b636f6d2e746563682e747620f5033a044b6f646919082e20009203120a1008bc01120b636f6d2e746563682e7476)
> DEBUG: << Receive: Protobuf=type: SET_STATE_MESSAGE
> priority: 0
> [setStateMessage] {
> displayName: "Netflix"
> playbackState: 1
> playerPath {
> origin {
> type: 1
> displayName: "Living Room"
> identifier: xxxxxxx
> }
> client {
> processIdentifier: 188
> bundleIdentifier: "com.tech.tv"
> }
> player {
> identifier: "MediaRemote-DefaultPlayer"
> displayName: "Default Player"
> }
> }
> }
> 
> DEBUG: << Receive: Protobuf=priority: 0
> 
> DEBUG: << Receive: Protobuf=priority: 0
> 
> DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method MrpMetadata._handle_set_state of <pyatv.mrp.MrpMetadata object at 0x7f2c93f0f518>>, data=None)
> DEBUG: Dispatching message with type 4 (SetStateMessage) to Listener(func=<bound method MrpPushUpdater._handle_update of <pyatv.mrp.MrpPushUpdater object at 0x7f2c93f0f550>>, data=None)
> DEBUG: One-shot with message type 4 to Listener(func=<function MrpProtocol.start.._wait_for_updates at 0x7f2c96169bf8>, data=<asyncio.locks.Semaphore object at 0x7f2c95945208 [locked,waiters:1]>)
> Media type: Unknown
> Play state: Playing
> DEBUG: Disconnected from device: None

Try `atvremote ... push_updates`, maybe it arrives later?

**Comment by postlund** [comment]
> Nope, nothing. Remote App does show title.

Ok, thanks for trying! I will have to put some effort into getting the connection flow (protocol-wise) in bear-time. Guess that's what is missing.

**Comment by postlund** [comment]
Right, there'a lot more information in `SET_STATE_MESSAGE` than meets the eye. I manually decided (so I don't have the definition here), but it looks good:
```shell

1: 4
4: 0
9 {
  3 {
    1: 0
    2 {
      1: "954DD9D1-A17B-497D-96F2-3110E0CEA1BD"
      2 {
        1: "Discovery \320\240\320\276\321\201\321\201\320\270\321\217 HD"
        19: 0
        35: 0x3f926e97a0000000
        39: 0x3f800000
        44: "954DD9D1-A17B-497D-96F2-3110E0CEA1BD"
        67: "bplist00\324\001\002\003\004\005\006\007\nX$versionY$archiverT$topX$objects\022\000\001\206\240_\020\017NSKeyedArchiver\321\010\tTroot\200\001\243\013\014\023U$null\323\r\016\017\020\021\022WNS.keysZNS.objectsV$class\240\240\200\002\322\024\025\026\027Z$classnameX$classes_\020\023NSMutableDictionary\243\026\030\031\\NSDictionaryXNSObject\010\021\032$)27ILQSW]dlw~\177\200\202\207\222\233\261\265\302\000\000\000\000\000\000\001\001\000\000\000\000\000\000\000\032\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\313"
        74: 0x41c1b597dcba0104
      }
    }
  }
  5: "Kodi"
  6: 1
  8: ""
  9 {
    1 {
      1: 1
      2: "Living Room"
      3: 1280262988
    }
    2 {
      1: 188
      2: "com.tech.tv"
    }
    3 {
      1: "MediaRemote-DefaultPlayer"
      2: "Default Player"
    }
  }
  11: 0x41c1b597dcbbf6d3
}
4: "7 \000\332\003\033\n\031"
1: 188
2: "com.tech.tv"
4: 501
7: "Kodi"
```
Did you watch Discovery HD here, @raufis27? There's some Unicode stuff in there, not sure how to decide that for now. Will have to see later.

**Comment by raufis27** [comment]
Yes I did. Thanks.

**Comment by postlund** [comment]
I merged a bunch of message definition updates in #233. Feel free to try them out, you should see more useful data in the logs now. More output will help me implement the missing parts.

**Comment by postlund** [comment]
I began re-working how all metadata is handled in #242. It is very untested but would love some feedback if and what works (preferably with debug logs).

**Comment by postlund** [comment]
I believe that this information is correct, but there's still a minor thing with #200 to deal with. But it's getting close to release.
