### ISSUE TITLE
Deleted pairing on Apple TV now error when found, how to reset pairing

### ISSUE THREAD

**Issue by Glec6** [postlund/pyatv#2277]
### What do you need help with?

I delete the pairing on the Apple TV, and now having trouble repairing. Every time I try to repair it error’s out or says it’s already paired which it isn’t. Tried to uninstall Pyatv and retinstall it in terminal, still same thing happens. Any idea’s?

**Comment by maxileith** [comment]
@Glec6 credentials are cached in `~/.pyatv.conf`. You need to delete that file or remove the credentials from that. If you are coming from https://github.com/maxileith/homebridge-appletv-enhanced/issues/12, the issue is solved :)

**Comment by Glec6** [comment]
Awesome worked for me! Thanks!

**Comment by postlund** [comment]
👍
