### ISSUE TITLE
pip3 install pyatv (on homebridge ) error: externally-managed-environment 

### ISSUE THREAD

**Issue by qwertz2021** [postlund/pyatv#2375]
### What do you need help with?

Hello guys,

following situation:

- fresh install of homebridge on my raspberry 4 using the Raspberry Pi Imager
- I tried to install paytv but I get these error. How can I solve this - any ideas?

<img width="1432" alt="Bildschirmfoto 2024-03-18 um 19 50 49" src="https://github.com/postlund/pyatv/assets/81743856/e20b12ab-f156-4ba3-a175-d8d52ae25e3b">

- OS: Debian GNU/Linux Bookworm (12)
- Node.js Version v20.11.0

**Comment by postlund** [comment]
You should install using a virtual environment:

https://pyatv.dev/documentation/#virtual-environment

I believe there is a flag to pip to circumvent this, but I do not recommend it at all. It can cause all sorts of problems.

**Comment by ncc0624** [comment]
When using a virtual environment, how do you send commands to it via node-red exec commands if you have to start the virtual environment every time by shell?
