### ISSUE TITLE
Downgrade minimum Cryptography requirement to 3.4.8

### ISSUE THREAD

**Issue by IsakTheHacker** [postlund/pyatv#2400]
### What to change?

I'm using pyatv in an environment where it is extremely hard to compile things that are written in Rust. Would it be possible to downgrade the minimum required version of Cryptography to 3.4.8, which is the last version that doesn't need Rust?

**Comment by postlund** [comment]
I understand your issue, but I believe that version of cryptography is ancient enough to not be feasibly pozole i I'm afraid.

**Comment by IsakTheHacker** [comment]
okay 😢
