### ISSUE TITLE
Possible to get power state of connected tv?

### ISSUE THREAD

**Issue by Jacob-Bishop** [postlund/pyatv#2491]
### What feature would you like?

Does the apple tv report anything about the tv that it's connected to? Would it be possible to add the power state of that tv to push_updates for atvremote?

### Describe the solution you'd like

add the power state of the tv (NOT apple tv) to push_updates for atvremote (or as another command)

### Any other information to share?

The use case here for me is mostly working around unfortunate behavior elsewhere in the stack - I have a dac/pre-amp that's connected to both my tv and a computer, and HDMI-CEC seems to turn on my tv when I turn on the apple tv if the dac is currently accepting input from my tv but not if the dac is accepting input from the computer instead.

**Comment by postlund** [comment]
Unfortunately no, I have not seen any information of that sort in any protocol.

**Comment by Jacob-Bishop** [comment]
Bummer! Thanks for the speedy reply.
