### ISSUE TITLE
plist parsing fails, causing airplay play_url to fail

### ISSUE THREAD

**Issue by edwinolson** [postlund/pyatv#277]
Running version from: pip3 install pyatv==0.4.0a4

Steps to reproduce:
1. Pair with AppleTV using airplay credentials. (This works fine)
2. Attempt to use provided atvremote program to play_url; looks like my appletv occasionally returns empty plists, which causes plistlib.loads to throw an exception. 

Wrapping the loads in a try/except seems to work, per below. Sorry if this is hackish, not a python guy.

Modified player.py near line 79:

                try:
                    parsed = plistlib.loads(data)
                except:
                    attempts -= 1

**Comment by postlund** [comment]
I need to know the source behind this this. Firstly, did the video play as expected? Is it a stream that you can share so I can test it myself? If possible, try re-running with `--debug` and provide the logs.

**Comment by postlund** [comment]
@edwinolson Can you update to the latest version and see if this issue persists? If it doesn't, feel free to close the issue.

**Comment by postlund** [comment]
I believe this is fixed, will close issue. Re-open if problem persists.
