### ISSUE TITLE
Convert Home Assistant integration to custom component (for now)

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#278]
**Short feature/function description**
I'm re-writing the Home Assistant component in #209 and doing it in-tree. The reason for doing it in-tree is because zeroconf is not supported for custom compoments, this however makes it a lot harder for users to test. So I have taken the decision to convert current implementation to a custom component and just let the zeroconf be for the moment (code can be there, albeit unused). This way I can distribute it in such a way that it can be installed via HACS for instance, making it a lot easier to test.

I'm gonna make some adjustments to the config flow, so new devices can be added either via identifier, name or IP-address (identifier is stored in the end). Since a scan is performed when adding a new device, I can present a list of suggestions in the flow to simplify for the user.

**What needs to be done?**
* Set up a new repo and move the code there
* Makes changes for adding devices in the flow as described above
* Add persistent notification with link to where bugs should be reported (you will have to suffer this if you beta test)

**Is this a breaking change?**
N/A

**Anything else worth knowing?**
As mentioned, zeroconf will not be supported so new devices will not be automatically found by Home Assistant.

Sine the domain `apple_tv` is already used, I will have to use another name for this, e.g. `apple_tv_beta`.

**Comment by junologue** [comment]
Does this mean that it is installable on hassio? And does it work on tvos13?

**Comment by postlund** [comment]
> Does this mean that it is installable on hassio? And does it work on tvos13?

Yes and yes!

**Comment by junologue** [comment]
And you already accomplished all of this, while having a newborn? 

Hands down! Amazing work man. Thanks for everything

**Comment by postlund** [comment]
> And you already accomplished all of this, while having a newborn? Hands down! Amazing work man. Thanks for everything
> […](#)
> 25 nov. 2019 kl. 21:36 skrev Pierre Ståhl ***@***.***>: ﻿ Does this mean that it is installable on hassio? And does it work on tvos13? Yes and yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, now I have 😄  It is available here: https://github.com/postlund/hass-atv-beta
