### ISSUE TITLE
Error setting up entry appletv for apple_tv

### ISSUE THREAD

**Issue by ahkaroly** [postlund/pyatv#279]
I installed the component and after pairing it does not create the entities. The pairing was complete without error.

I found the following errors in my log:

` Error setting up entry appletv for apple_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/config/custom_components/apple_tv/__init__.py", line 44, in async_setup_entry
    atv = await pyatv.connect(conf, hass.loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 161, in connect
    await atv.connect()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/__init__.py", line 308, in connect
    await self._protocol.start()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/protocol.py", line 64, in start
    self.service.credentials).client_id
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/srp.py", line 34, in parse
    split = detail_string.split(':')
AttributeError: 'Credentials' object has no attribute 'split' `

System Setup
 - Apple TV 4K: Model: A1842 (32GB) , tvOS 13.3
 - OS: HASS.IO / Home Assistant 0.102.2 / Raspberry Pi 4
 - Python: 3.7.4
 - pyatv: Apple TV Beta Component / 99851f8

**Comment by postlund** [comment]
D'oh! My bad 😕 I made a new pre-release with a fix for this and pushed an update to the component. Can you update and try again? You might have to delete the entity and add integration again, but I believe it should work as-is.

**Comment by ahkaroly** [comment]
I updated and deleted old entities.

It asks for the first code when pairing, but then Unexpected error
exits with error.

Contents of the error log:

` Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_pair_with_pin
    return await self.async_begin_pairing()
  File "/config/custom_components/apple_tv/config_flow.py", line 133, in async_begin_pairing
    await self._pairing.close()
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 32, in close
    await self.connection.close()
TypeError: object NoneType can't be used in 'await' expression `

**Thank you very much for your work :)**

**Comment by postlund** [comment]
> I updated and deleted old entities.
> 
> It asks for the first code when pairing, but then Unexpected error
> exits with error.
> 
> Contents of the error log:
> 
> `Unexpected exception Traceback (most recent call last): File "/config/custom_components/apple_tv/config_flow.py", line 177, in async_step_pair_with_pin return await self.async_begin_pairing() File "/config/custom_components/apple_tv/config_flow.py", line 133, in async_begin_pairing await self._pairing.close() File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/pairing.py", line 32, in close await self.connection.close() TypeError: object NoneType can't be used in 'await' expression`
> 
> **Thank you very much for your work :)**

Yes, that sounds a lot better 😊 It is a stupid bug, pushed a fix for it: #282. Will have to make a new release, etc... Will get back to you once I am done.

**Comment by postlund** [comment]
New update is pushed, please update component and try again!

**Comment by ahkaroly** [comment]
**Pairing works. Thanks!**

One question.

"No Title" appears during playback. Is this still in beta or is it a problem for me?

Should shutdown and power on work?

**Comment by postlund** [comment]
> **Pairing works. Thanks!**
> 
> One question.
> 
> "No Title" appears during playback. Is this still in beta or is it a problem for me?
> 
> Should shutdown and power on work?

Perfect! Thanks for testing! 😊

Title should work, so it's probably a bug. If you can write a new issue and include a debug log, that would be great. You can probably use `atvremote --debug ID playing` directly and get a shorter log. You get ID from `atvremote scan`. Pick one of the identifiers from your device.

Shutdown and power on is still work in progress. Shutdown will only be partial for now, until I know a way of shutting down properly.
