### ISSUE TITLE
Issue with atvremote scan from Docker container

### ISSUE THREAD

**Issue by Juggels** [postlund/pyatv#286]
First: thanks a lot for the work you are putting into this!

I seem to be running into an issue when trying to connect to my Apple TV from within a Docker container (running in host networking mode). For clarity: my Apple TV is on the same network as the `ens160` interface.

**Steps:**
- I have installed the component through HACS and restarted Home Assistant
- Went into Integrations and selected _Apple TV_
-  In the popup I tried the device name, IP address and the identifier that I got when running `atvremote scan` from my laptop
- The component searches for a few seconds, but then reports that the device could not be found.

Looking into the logs, I see the following error:

```
2019-11-26 21:07:01 DEBUG (MainThread) [pyatv] Discovering devices for 3 seconds
2019-11-26 21:07:01 ERROR (MainThread) [aiozeroconf.aiozeroconf] initializing comm af 10 on interfaces ['lo', 'ens160', 'docker0', 'flannel.1', 'cni0', 'vethf615c93b', 'veth998fb5b5', 'veth6b0fee29', 'vethdc1cfe5b', 'veth359a74a7', 'vethee28aa86', 'vethceb9c585', 'vethd19a6f6c', 'veth48c7e814', 'veth333be5a2', 'vethfd989e09', 'veth795fd6c2', 'vethc1c6dab9', 'veth811160b5', 'vetha6521ef2', 'vethedba6adb', 'veth72a8e939']: [Errno 97] Address family not supported by protocol
```

Afterwards I tried to run the `atvremote scan` command directly from the container, resulting in the same error:
```
bash-5.0# atvremote scan
ERROR: initializing comm af 10 on interfaces ['lo', 'ens160', 'docker0', 'flannel.1', 'cni0', 'vethf615c93b', 'veth998fb5b5', 'veth6b0fee29', 'vethdc1cfe5b', 'veth359a74a7', 'vethee28aa86', 'vethceb9c585', 'vethd19a6f6c', 'veth48c7e814', 'veth333be5a2', 'vethfd989e09', 'veth795fd6c2', 'vethc1c6dab9', 'veth811160b5', 'vetha6521ef2', 'vethedba6adb', 'veth72a8e939']: [Errno 97] Address family not supported by protocol
```

I hope this provides enough info as a starting point, but I'm more than willing to run some more tests

**Comment by postlund** [comment]
Hmm, this is an issue with `aiozeroconf`. I don't know where to guess what is wrong here, I'll see if I can find some time to dig deeper into this.

Meanwhile, could you try running this inside the container:
```python
python3 -m aiozeroconf -s
```
You might have to source the environment with aiozeronf (or manually install it).

**Comment by Juggels** [comment]
I've tried running that command, but it gives me the following:
```
__main__.py: error: argument -s/--service: expected one argument
```

When I run `python3 -m aiozeroconf -s _airplay._tcp.local.`, I get the following from both directly on my laptop and from the Docker container on my server:
```
Service Apple TV Woonkamer._airplay._tcp.local. of type _airplay._tcp.local. state changed: ServiceStateChange.Added
  IPv4 Address: 192.168.25.62:7000
  IPv6 Address: fe80::1ce7:974:bf7b:6a38:7000
  Weight: 0, priority: 0
  Server: Apple-TV-Woonkamer.local.
  Properties are:
    acl: 0
    <truncated>
```

When running `python3 -m aiozeroconf -s _mediaremotetv._tcp.local.` it just seems to hang (again, both on my laptop and on the server container on 
```
Browsing services, press Ctrl-C to exit...
```

Running `atvremote scan` on my laptop correctly returns the Apple TV with both MRP and Airplay info. The container keeps returning the aforementioned error. and an empty list for "Scan results"

**Comment by Juggels** [comment]
I think I figured out the root cause... The Error code 97 eventually put me on the right track. After some googling I found the following page: https://bugs.launchpad.net/apt-zeroconf/+bug/478426

This reminded me that I have ipv6 turned off on all of my servers. After enabling it, the integration worked without issue. So i guess a way to specify or fall back to "ipv4 only" might be desired?

**Comment by postlund** [comment]
By the looks of it, "10" seems to be AF_INET6, i.e. IPv6, so you are probably right regarding that. Looking at the code in aiozeronf, I see this:

```python

    async def initialize(self, address_family):
        for af in address_family:
            try:
                if af == netifaces.AF_INET:
                    listener, senders = setup_inet(self.interfaces)
                elif af == netifaces.AF_INET6:
                    listener, senders = setup_inet6(self.interfaces)
                else:
                    raise ValueError('Only IPv4 and IPv6 are supported')
            except Exception as e:
                log.error('initializing comm af %s on interfaces %s: %s', af, self.interfaces, e)
                continue
   ...
```
And it is called like this:
```python

    def __init__(
            self,
            loop,
            address_family=[netifaces.AF_INET, netifaces.AF_INET6],
            iface=None
    ):
        ...
        self._init = self.loop.create_task(self.initialize(address_family))

```
So it should try to setup both IPv4 and IPv6, with guard in case setup of either fails. From my understanding, IPv4 should still work. Maybe you could try enabling debug logs and see if you get any wiser? Aiozeronf seems to print more stuff, like which interfaces it binds to.

**Comment by Juggels** [comment]
I ran some more tests on a machine which also had ipv6 disabled, and I think it's due to the way I disabled it... It was completely disabled on both GRUB, kernel module and sysctl levels. I think that caused netifaces / aiozeroconf to choke. Probably best to chalk this one up to a weird edge case on my side, as everything is working perfectly now.

**Comment by postlund** [comment]
It seems like an odd-case, indeed. But I still think that it should work. If you feel that you have the time, you could try setting up IPv4 only and see if that works. Easiest way is to just modify `pyatv/__init__.py` and change:

```python
    zeroconf = Zeroconf(loop)
```

Into something along the lines of:

```python
    import netifaces
    zeroconf = Zeroconf(loop, address_family=[netifaces.AF_INET])
```
And see if it works. I don't "officially" support IPv6 anways, so it would be OK to disable it for now until I actually try to add full support for it.

**Comment by Juggels** [comment]
Thanks for the potential workaround... I'll try to find some time this weekend to test this, and will update you on the results

**Comment by Juggels** [comment]
I managed to try this yesterday, and I can confirm that forcing IPv4 makes the error go away when I have the ipv6 stuff disabled on the host.

**Comment by postlund** [comment]
That is "good" news. Perhaps it's wise to disable IPv6 for now and enable it later, when it is more stable. It could be a flag to `pyatv` somehow.
