### ISSUE TITLE
start playlist on AppleTV

### ISSUE THREAD

**Issue by poudenes** [postlund/pyatv#314]
Hi All,

Happy with the developers who build a great peace of code.
Is there a option to build something in that makes possible to start a playlist on AppleTV?

**Comment by postlund** [comment]
Hey! Should definitely be possible. Will add it as a feature request.

**Comment by thmang82** [comment]
Would it be possible to start a WebRadio Stream URL this way? (.m3u or .mp3)
I am thinking about moving from a Kodi box to AppleTV, but I would need to start WebRadio via a Hardware Button in my SmartHome :-)
It's easy with the Kodi API, but I did not find anything how to achieve this for an AppleTV ...

**Comment by postlund** [comment]
I would assume so, currently I have no clue on how this would be done. But maybe you can play via AirPlay?
