### ISSUE TITLE
Remote hold_secs

### ISSUE THREAD

**Issue by Veldkornet** [postlund/pyatv#318]
**Describe the bug**
When using the remote service for the AppleTV, the hold_secs option doesn’t appear to be functioning. 

**To Reproduce**
Call the remote.send_command service with the following options:
entity_id: remote.appltv
command: home
hold_secs: 2

**Expected behavior**
The “side menu” should pop-up on the AppleTV, allowing you to put the AppleTV to sleep, but instead (because the button is not held) it opens the AppleTV app instead. 

**System Setup (please complete the following information):**
 - OS: Hass.io [HA 0.102.3]
 - Python: 3.7.4
 - pyatv: 0.4.0a9

**Additional context**

**Comment by postlund** [comment]
There's a dedicated "button" for holding the Home-button, called `home_hold`. Can you try that instead? 

```yaml
entity_id: remote.appletv
command: home_hold
```
Currently the `remote` component (or `pyatv` for the matter) does not support arguments to buttons either, so it's a hardcoded "hold time".

**Comment by Veldkornet** [comment]
Ah yes! That works, thanks!
