### ISSUE TITLE
Finding Apple TVs without Home Sharing enabled

### ISSUE THREAD

**Issue by robbiet480** [postlund/pyatv#33]
Thanks to a bit of panic from me and @dale3h we determined that an Apple TV without Home Sharing enabled will broadcast the `touch-able._tcp.local.` service but NOT the `_appletv-v2._tcp.local.` service. We should check to see if we don't have a corresponding `_appletv-v2._tcp.local.` service and if so alert the user that they need to enable Home Sharing.

**Comment by postlund** [comment]
I saw that the base issue here was probably related pyhon-zeroconf or something similar, as other clients were able to find ``_appletv-v2._tcp.local.``. We be very good if we could figure out the base issue. Anyways, I don't think we can use the information from ``touch-able._tcp.local.´`to login as it doesn't have a HSGID. So pairing is probably the way to go. I'll have to think about this.
