### ISSUE TITLE
Remote control commands design

### ISSUE THREAD

**Issue by pierrickrouxel** [postlund/pyatv#34]
Is it voluntary to use `topmenu` rather than `top_menu` to name  the remote control command? It does not match the design of `set_position`.

This is not really important but as it is a fresh project, there is still time to change :)

**Comment by postlund** [comment]
It's just a straight translation from the API as the underlaying function (sent to the device) is called ``topmenu``. So that's the reason :) But you are right, it might be good to change to be consistent. Feel free to send a PR! :)
