### ISSUE TITLE
Showing idle when playing from some danish apps

### ISSUE THREAD

**Issue by SalkinDK** [postlund/pyatv#341]
**Describe the bug**
Doesnt change status from idle to playing when playing live tv or archive stuff from the Danish apps "TV2" and "DRTV"
Works fine from Netflix

**To Reproduce**
play something from one of the apps
**Expected behavior**
Changing to playing when something is playing going to pause when paused and going back to idle.
**System Setup (please complete the following information):**
- Hassio  0.103.2
- HassOS HassOS 3.7
- Supervisor Version 193
- Newest from HACS (4a627fe)
**Additional context**

**Comment by jdebardi** [comment]
This is a bug in those apps. I find quite a few media apps report the wrong status to the TvOS/iOS layer

**Comment by SalkinDK** [comment]
> This is a bug in those apps. I find quite a few media apps report the wrong status to the TvOS/iOS layer

Hmm, ok sad to hear that. 
i had a old version of the mrp apple tv custom component and that worked fine.
Bu after updating to this version it stopped working.

**Comment by postlund** [comment]
This is as stated behavior defined by the apps themselves. I don't say that it's impossible to infer the idle state anyway, but I don't know how yet. It would be good to investigate this further. First thing to verify is what the iOS Remote app says as that is our golden reference.

I only know about one other custom component that implemented MRP support (which was a copy of pyatv and a modified version of the HA component), and that does not support idle state for MRP. I cannot see how that would be technically possible. Looking at the pyatv code reveals only support for playing and paused:

https://github.com/chamberlain2007/apple_tv_mrp/blob/master/custom_components/apple_tv_mrp/pyatv_mrp/mrp/__init__.py#L145

And by looking at the platform:

https://github.com/chamberlain2007/apple_tv_mrp/blob/master/custom_components/apple_tv_mrp/media_player.py#L126

Idle state would only be returned if play state was one of idle, no media or loading. At least to me this doesn't add up. Are you 100% sure you actually got idle from the media player?

**Comment by SalkinDK** [comment]
> This is as stated behavior defined by the apps themselves. I don't say that it's impossible to infer the idle state anyway, but I don't know how yet. It would be good to investigate this further. First thing to verify is what the iOS Remote app says as that is our golden reference.
> 
> I only know about one other custom component that implemented MRP support (which was a copy of pyatv and a modified version of the HA component), and that does not support idle state for MRP. I cannot see how that would be technically possible. Looking at the pyatv code reveals only support for playing and paused:
> 
> https://github.com/chamberlain2007/apple_tv_mrp/blob/master/custom_components/apple_tv_mrp/pyatv_mrp/mrp/__init__.py#L145
> 
> And by looking at the platform:
> 
> https://github.com/chamberlain2007/apple_tv_mrp/blob/master/custom_components/apple_tv_mrp/media_player.py#L126
> 
> Idle state would only be returned if play state was one of idle, no media or loading. At least to me this doesn't add up. Are you 100% sure you actually got idle from the media player?

Sorry that is my poor way of explaining.
I have seen it changing state to play and from play to pause.
But now it doesnt change state at all, it just stay idle when i try to play anything from the to apps.

Sorry i wasnt clear. ;(

**Comment by postlund** [comment]
@SalkinDK  Sorry for the delay, I missed this issue 😔

Ok, that sounds more reasonable. It sounds like a bug to me. Can you enable debug logs and run again? I can have a look and see what happens.

**Comment by SalkinDK** [comment]
@postlund no problem, busy here as well..
I think they maybe updated the two danish apps. 
I just tried both live tv and on demand programs, and nothing is showing up in the official apple remote app.

So i think that as i understand it, it is there fault, and there is nothing ypu can do about it.
If so, i just want to say the BIGGEST thank you for putting this together and keeping it updated.

**Comment by postlund** [comment]
@SalkinDK That sounds reasonable. If it doesn't even work in the official app, then it's probably out of my hands as well. But it would be interesting to see the logs anyways, so see what they report. Can you upload a dump so I can take a look?

Thank you for your kind words and for using `pyatv`! ❤️

**Comment by postlund** [comment]
I will close this now as I don't think there is anything more I can do. If you get the time @SalkinDK, please provide some logs so that I can for sure say if it is a bug or not.
