### ISSUE TITLE
will not find Apple TV 4K when adding correct IP address of unit...

### ISSUE THREAD

**Issue by k-rock** [postlund/pyatv#342]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [e.g. Debian]
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]

**Additional context**

**Comment by postlund** [comment]
Please see #343 and help me out fixing this.

**Comment by postlund** [comment]
Grooming isssues... Since this issue is not filled in properly, I will close it. I have no idea if this related to pyatv or the HA component. For HA component, see #292 instead. Please write a new issue and fill in the details if your issue persists.
