### ISSUE TITLE
Investigate alternative scanning strategy using unicast requests

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#343]
**What to investigate**
Since a lot of people are still having problems with scanning, I need to find a workaround until the underlying issue is solved. One idea I have is to allow selective "scanning" by sending lookup requests to a specific host, instead of relying on multicast. Since regular unicast is a safer bet than both broad- and multicast, I hope that it works better. My investigations with wireshark has shown that `pyatv` (or `aiozeroconf` to be exact) sends the request correctly and an answer is received at the interface, but it seems to be filtered somewhere before reaching the application again. Hopefully unicast allows me to bypass this problem.

The biggest drawback, expect for having to roll my own workaround-solution, is that it's not really "auto discovery" anymore. The requests must be sent to specific hosts. I intend to support specifying a list of hosts to "scan" or even a range, to simulate the behavior. But one needs to be aware of that this is slow.

**Expected outcome**
First and foremost I want to create a prototype. This will just be a simple script, not tied to `pyatv`. It will be added to this issue. Then I need people with scanning issues to test it, so I can be sure that it works before integrating it with `pyatv`.

I feel that this is important so I want I see it in 0.4.0 and will delay the release until I know that this works.

**Comment by postlund** [comment]
I have spent some NIH-time implementing the basic parts required to do unicast DNS requests to obtain MDNS properties now. At least it works for me, but it would help a lot to get input from other people having problems scanning for devices. What I basically need help with is:

1. Download https://raw.githubusercontent.com/postlund/pyatv/udns_proto/udns.py
2. Run: python3 udns.py [IP to Apple TV]
3. Report back if it worked (you should see a lot of data about your device if it did)

Remember to run on the same machine you are having problems on.

This script will do the same thing (basically) as aiozeroconf, but instead of multi casting the request to all hosts, it will send the request to a single host.

**Comment by villaocho** [comment]
here is mine (I have no idea why MRP it is not available in the ATV4, I have issues there)

[udns.txt](https://github.com/postlund/pyatv/files/4021382/udns.txt)

**Comment by postlund** [comment]
Looks good in the log @villaocho, thanks! It's probably the usual reliability issues you see with MRP (why you not see it). I'm gonna do a write-up about it later. I'm thinking about rolling my own multicast implementation. That way we at least get rid of these half-results.

**Comment by postlund** [comment]
So, now I have pushed an initial commit for supporting unicast scanning in pyatv and atvremote. It is available here: #349. Instructions are in the PR. Would be awesome to get it tested before integrating it fully. But I feel that this is a good addition.

**Comment by postlund** [comment]
I have merged #349, so unicast scanning is now a thing. Will close issue.
