### ISSUE TITLE
Remaining work in Home Assistant component

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#360]
This is a list of all work that is left to do in order to finalize the Home Assistant component. I will add things here as I think of them. References to [Quality Scale](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html) when applicable.

# Things left to do

## Features and fixes left to do

- [X] Improve retry interval to not spam (binary exponential backoff with upper limit of 10 minutes)
- [x] General improvements to config flow message dialogs and errors
- [x] Handle expired/invalid credentials (trigger flow again?)
- [X] Set PARALLEL_UPDATES to 0 in `media_player.py` and `remote.py` since no polling is done
- [X] Pass aiothttp session from Home Assistant when connecting and pairing

Things not checked under *Quality Scale* are also applicable.

## General things left to do

- [x] Release of pyatv 0.4.0
- [x] General code clean up
- [ ] Write tests for component
- [x] Run black on code
- [x] Fix linting issues

## Last things to do

- [x] Submit PR to Home Assistant repo
- [ ] Archive `postlund/hass-atv-beta` repo
- [x] Submit PR to Home Assistant documentation repo

# Quality Scale

The intention is reach platinum level on the quality scale. So I keep the scales here and tick boxes when I feel I have finished something. Reference page is [here](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html).

Note: A rationale stating why a quality scale item is closed shall be provided. It will act as proof.

## No score

- [x] Satisfy all requirements for creating components and creating platforms.
  - **Rationale:** 
- [x] Configurable via configuration.yaml
  - **Rationale:** Prototype implemented and tested. Needs some additional work.

## Silver

- [X] Connection/configuration is handled via a component.
  - **Rationale:** A component is used for this.
- [X] Set an appropriate SCAN_INTERVAL (if a polling integration)
  - **Rationale:** N/A as component is not polling.
- [X] Raise PlatformNotReady if unable to connect during platform setup (if appropriate)
  - **Rationale:** N/A due to the way `pyatv` works. Platform will always be setup and (re-)connection logic is taken care of by a manager.
- [x] Handles expiration of auth credentials. Refresh if possible or print correct error and fail setup. If 
based on a config entry, should trigger a new config entry flow to re-authorize.
  - **Rationale:** 
- [X] Handles internet unavailable. Log a warning once when unavailable, log once when reconnected.
  - **Rationale:** N/A as this integration only communicates with local devices.
- [x] Handles device/service unavailable. Log a warning once when unavailable, log once when reconnected.
  - **Rationale:** Only partially for now (logs one time when connection is lost but not when re-established).
- [X] Set available property to False if appropriate (docs)
  - **Rationale:** N/A due to the way connections are managed.
- [X] Entities have unique ID (if available) (docs)
  - **Rationale:** Fully implemented, see *Identifiers* at [this](https://postlund.github.io/pyatv/documentation/concepts/) page.

## Gold

This is a solid integration that is able to survive poor conditions and can be configured via the user interface.

- [x] Configurable via config entries.
  - [X] Don't allow configuring already configured device/service (example: no 2 entries for same hub)
  - **Rationale:** Checks are available to prevent this from happening.
  - [x] Tests for the config flow
  - **Rationale:** 
  - [X] Discoverable (if available)
  - **Rationale:** Implemented via zeroconf.
- [X] Entities have device info (if available) (docs)
  - **Rationale:** It is available to the extent possible today (will be improved with more fine-grained details over time, see #220)
- [X] States are translated in the frontend (text-based sensors only, docs)
  - **Rationale:** This component does not have any text-based sensors (only `media_player` and `remote`).
- [ ] Tests for reading data from/controlling the integration (docs)
  - **Rationale:** 
- [X] Has a code owner (docs)
  - **Rationale:** I am the code owner (@postlund)

## Platinum

- [X] Set appropriate PARALLEL_UPDATES constant
  - **Rationale:** Set to 0 since no polling is used.
- [x] Support config entry unloading (called when config entry is removed)
  - **Rationale:** 
- [X] Integration + dependency are async
  - **Rationale:** Both component and `pyatv` are async.
- [X] Uses aiohttp and allows passing in websession (if making HTTP requests)
  - **Rationale:** `pyatv` depends on `aiohttp` for AirPlay and DMAP support. Pure TCP-connection is used for MRP.

**Comment by soffes** [comment]
Thanks again for all of your effort on this! Super appreciate you! Can't wait to use this!

**Comment by postlund** [comment]
I've made good progress the last couple of days and most things are implemented now. The code is kinda messy (especially the config flows as there are quite a few of them now), so I must clean up the code now. But I believe that the only "feature" remaining to implement is a better retry-mechanism. Support for unloading properly will have to wait until the `remote` component has support for config entries.

So my main focus forward will be fixing the retry-mechanism firstly and then clean up (which will include formatting with black and linting as well). After that I will make another release of the component before I start adding tests and finalizing the work.

**Comment by postlund** [comment]
I added a simple binary exponential backoff as retry-mechanism with an upper limit of ten minutes. So retries will be made according (pseudo code): `min(randrange(2**connection_attemps), 600)`. This should be good enough to not hammer but also reconnect quite rapidly. Will improve later if necessary.

**Comment by postlund** [comment]
I'm almost done with tests for config flow. Some clean ups and tweaks left but I might be able to push them today. After that I will start working on tests for the rest of the component. I also need to start thinking about how to clean up the config flow code because it's messy...

**Comment by The-sultan** [comment]
Hi @postlund,
This is unbelievable, the work you're doing at the speed you're progressing. You're making people happy! 
On another note, I'm experiencing the following problem: I installed the component yesterday and everything work flawlessly. Then I turn the apple tv off (4k recently bought). After that when I turn it back on I don't get any updates on the entity's status. It remains in "off". If I restart home assistant it connects back and I get the proper status and following status changes.
I've checked the logs and can't find anything unusual related to the component.
I have installed using HACS based on your recommendation.
I couldn't find anyone else having the same issue so I figured I would ask you first and then proceed to report the issue. Is there anything you would like me to test on my environment? Let me know and again, thanks for your hard work!

**Comment by postlund** [comment]
Hi and thank you @The-sultan! As you say, I've put quite a bit of work into this and I hope people can benefit from it 😄 

I've had a report not really related to this, but that could have a side-effect of the component not trying to re-connect again. This was via email, so it's not visible here I'm afraid. It should however be visible in the log in case this happens. The best thing would be if you enabled log points for `pyatv` and the component and see what happens when you turn off and on your Apple TV. Suggested log points are these:

```yaml
logger:
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

The error I mentioned above is at this line:

https://github.com/postlund/hass-atv-beta/blob/master/custom_components/apple_tv/__init__.py#L167

It should say:
```python
        _LOGGER.warning('Connection lost to Apple TV "%s"', self.atv.name)
```

So you could try changing that manually and see if it helps. But the logs should otherwise tell you more. Feel free to attach here somehow or email them to me and I'll have a look.

**Comment by The-sultan** [comment]
Hi @postlund,
I did some basic tasting looking at the logs.
When the Apple TV is turned off I see this:

`2020-02-14 21:48:50 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf: type: SET_CONNECTION_STATE_MESSAGE
identifier: "XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
priority: 115
[setConnectionStateMessage] {
  state: Disconnected
}
2020-02-14 21:48:57 DEBUG (MainThread) [pyatv.mrp.connection] Disconnected from device: None
2020-02-14 21:48:57 DEBUG (MainThread) [custom_components.apple_tv] Updating state: connected=False, disconnected=True`

When turning it back on, nothing appears in the logs and the state continues to be 'off'.
I believe the problem is not when turning it off but when turning the apple tv on, here's why:
The only way I can get updates from the apple tv is if I restart home assistant WHILE the apple tv is ON. In that case everything works as expected. 
If I restart home assistant with the Apple tv off then nothing happens ever.

Let me know if this is helpful and if I can do something else on my setup.

On a side note, the log that you mentioned never appeared on my log.

**Comment by postlund** [comment]
> Hi @postlund,
> I did some basic tasting looking at the logs.
> When the Apple TV is turned off I see this:
> 
> `2020-02-14 21:48:50 DEBUG (MainThread) [pyatv.mrp.connection] << Receive: Protobuf: type: SET_CONNECTION_STATE_MESSAGE identifier: "XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" priority: 115 [setConnectionStateMessage] { state: Disconnected } 2020-02-14 21:48:57 DEBUG (MainThread) [pyatv.mrp.connection] Disconnected from device: None 2020-02-14 21:48:57 DEBUG (MainThread) [custom_components.apple_tv] Updating state: connected=False, disconnected=True`
> 
> When turning it back on, nothing appears in the logs and the state continues to be 'off'.
> I believe the problem is not when turning it off but when turning the apple tv on, here's why:
> The only way I can get updates from the apple tv is if I restart home assistant WHILE the apple tv is ON. In that case everything works as expected.
> If I restart home assistant with the Apple tv off then nothing happens ever.
> 
> Let me know if this is helpful and if I can do something else on my setup.
> 
> On a side note, the log that you mentioned never appeared on my log.

Ok, I see what happens here. In `pyatv`, there are two callbacks dealing with loss of connection. One is for expected loss, e.g. you intentionally disconnect from the device by calling `close`. The other one is for unintentional, i.e. connection was lost for some unforeseen reason. When the connection is lost, the component is supposed to re-connect, which these callbacks handle. In the last commit I however removed this restarting in the "intentional loss of connection"-callback. I figured that it shouldn't be there as the general case would be that the user pressed power off. But... putting the device to sleep will yield this case as well, since it will close the TCP connection gracefully. So this call must be put back.

You can try this out yourself by adding the following call *after* this line https://github.com/postlund/hass-atv-beta/blob/master/custom_components/apple_tv/__init__.py#L177:

```yaml
self._start_connect_loop()
```

This will be ok. Remember that this component uses random exponential back off for reconnecting (with max value of five minutes), so it might take up to five minutes before the component re-connects. I hope to be able to improve this over time, but thIs is the case for now. Best is to not put it to sleep manually as that will keep the connection up  at all time.

**Comment by postlund** [comment]
@The-sultan I have pushed an update with mentioned fixes, pleas give it a spin!

**Comment by postlund** [comment]
Just or the sake of it... my goal will be to finish this up this week. I will leave tests for the component until later, just focus on getting the config flow code/tests up to shape. After that I will see if I can fix unloading for the remote component and finally submit a PR back to Home Assistant. Otherwise I will never get this done.

**Comment by soffes** [comment]
@postlund super appreciate your effort on this 💖

**Comment by postlund** [comment]
Tests are done. Just need to run black and tidy up some comments. Will continue fixing #448 before moving on to unloading (which should be easy). After that I'm more or less done. This means I will have to look over the tasks above to see I haven't missed anything. Also continue looking into bugs and minor fixes. But everything looks good so far 👍

**Comment by postlund** [comment]
Only thing remaining now is writing tests for the rest of the component, but since I won't do that now I feel that this issue has played its part 🎉
