### ISSUE TITLE
Duration traceback / NaN value

### ISSUE THREAD

**Issue by stp6778** [postlund/pyatv#364]
Hi,

sometimes the duration can't be retrieve by apps using their own video player.
There is a traceback when the duration value is NaN.

I change mrp/\_\_init__.py 225: 
        return None if duration is None else int(duration)
by:
       return None if duration != duration or duration is None else int(duration)

**Comment by postlund** [comment]
Can you provide the full trace back for reference? The comparison `duration != duration` seems strange to me, that will always be false. So I can't see how that helps?

**Comment by stp6778** [comment]
Comparison seems to be a usual to test nan values : https://stackoverflow.com/questions/944700/how-can-i-check-for-nan-values

2020-01-11 18:21:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/config/custom_components/apple_tv/media_player.py", line 172, in media_duration
    return self._playing.total_time
  File "/usr/local/lib/python3.7/site-packages/pyatv/mrp/__init__.py", line 217, in total_time
    return None if duration is None else int(duration)
ValueError: cannot convert float NaN to integer

**Comment by postlund** [comment]
That was new to me. Very strange that the device would respond with a field set to NaN, why include it at all? So I guess a check is needed, but I would prefer to use `math.isnan` as that is much clearer.

Could you perhaps include a full log from `atvremote --debug ... playing` (insert whatever id and credentials you need)? I'm very interested in seeing what the message looks like.

I will prepare a PR right away.

**Comment by postlund** [comment]
PR #365 should fix this. Please try it out and let me know.

**Comment by stp6778** [comment]
I try PR #365, the fix works fine.
The debug message with duration nan value:

DEBUG: << Receive (Data=9306080420004a8c0612450a04080110010a04080210010a04080310010a0d08121001210000000000003e400a0d08131001210000000000003e400a04080510010a04080610010a07082d10018001001abe04080012b9040a0e31333038383032325f353030363112a6040a134c61206368616e736f6e2073656372c3a874653a8c01496e766974c3a973203a20526963686172642042657272792c20466175766520486175746f742c205069657272652050616c6d6164652c204461646a752c2041726e617564204475637265742c204d696368656c2046756761696e2c204c6f726965205065737465722c2044617669642048616c6c796461792065742044656e69732042726f676e6961727471000000000000f87f980101fa010a696d6167652f6a70656799020000000000000000bd020000803fe2020e31333038383032325f35303036319a04850262706c6973743030d4010203040506070a582476657273696f6e592461726368697665725424746f7058246f626a6563747312000186a05f100f4e534b657965644172636869766572d1080954726f6f748001a30b0c1355246e756c6cd30d0e0f101112574e532e6b6579735a4e532e6f626a656374735624636c617373a0a08002d2141516175a24636c6173736e616d655824636c61737365735f10134e534d757461626c6544696374696f6e617279a31618195c4e5344696374696f6e617279584e534f626a65637408111a24293237494c5153575d646c777e7f808287929bb1b5c20000000000000101000000000000001a000000000000000000000000000000cbd104dafe4fde38e5c141d9040a1231d838e5c141820528333866313032363762633063326337363931366663393130373466313234313361643565633333312a076d7943414e414c300142004a6c0a150801120b6174765f6368616d62726518cc86bde2041226089a011221636f6d2e63616e616c706c7573646973747269622e6d7963616e616c2e70726f641a2b0a194d6564696152656d6f74652d44656661756c74506c61796572120e44656661756c7420506c6179657259179b06de38e5c1413b08372000da03340a32089a011221636f6d2e63616e616c706c7573646973747269622e6d7963616e616c2e70726f6420f5033a076d7943414e414c2f082e20009203280a26089a011221636f6d2e63616e616c706c7573646973747269622e6d7963616e616c2e70726f64)
DEBUG: << Receive: Protobuf=type: SET_STATE_MESSAGE
priority: 0
[setStateMessage] {
  supportedCommands {
    supportedCommands {
      command: Play
      enabled: true
    }
    supportedCommands {
      command: Pause
      enabled: true
    }
    supportedCommands {
      command: TogglePlayPause
      enabled: true
    }
    supportedCommands {
      command: SkipForward
      enabled: true
      preferredIntervals: 30.0
    }
    supportedCommands {
      command: SkipBackward
      enabled: true
      preferredIntervals: 30.0
    }
    supportedCommands {
      command: NextTrack
      enabled: true
    }
    supportedCommands {
      command: PreviousTrack
      enabled: true
    }
    supportedCommands {
      command: SeekToPlaybackPosition
      enabled: true
      canScrub: 0
    }
  }
  playbackQueue {
    location: 0
    contentItems {
      identifier: "13088022_50061"
      metadata {
        title: "La chanson secr\303\250te"
        trackArtistName: "Invit\303\251s : Richard Berry, Fauve Hautot, Pierre Palmade, Dadju, Arnaud Ducret, Michel Fugain, Lorie Pester, David Hallyday et Denis Brogniart"
        duration: nan
        artworkAvailable: true
        artworkMIMEType: "image/jpeg"
        elapsedTime: 0.0
        playbackRate: 1.0
        contentIdentifier: "13088022_50061"
        nowPlayingInfoData: "bplist00\324\001\002\003\004\005\006\007\nX$versionY$archiverT$topX$objects\022\000\001\206\240_\020\017NSKeyedArchiver\321\010\tTroot\200\001\243\013\014\023U$null\323\r\016\017\020\021\022WNS.keysZNS.objectsV$class\240\240\200\002\322\024\025\026\027Z$classnameX$classes_\020\023NSMutableDictionary\243\026\030\031\\NSDictionaryXNSObject\010\021\032$)27ILQSW]dlw~\177\200\202\207\222\233\261\265\302\000\000\000\000\000\000\001\001\000\000\000\000\000\000\000\032\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\313"
        elapsedTimeTimestamp: 600469948.624965
        inferredTimestamp: 600469936.383363
        artworkIdentifier: "38f10267bc0c2c76916fc91074f12413ad5ec331"
      }
    }
  }
  displayName: "myCANAL"
  playbackState: Playing
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      type: 1
      displayName: "atv_chambre"
      identifier: 1280262988
    }
    client {
      processIdentifier: 154
      bundleIdentifier: "com.canalplusdistrib.mycanal.prod"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 600469948.051608
}

**Comment by postlund** [comment]
Great, thank you for verifying and providing a log! It helps a lot. This was a brand new case for me.
