### ISSUE TITLE
Pair start failed

### ISSUE THREAD

**Issue by idenu** [postlund/pyatv#377]
**Describe the bug**
I am able to discover my Apple TV 4K using the IP address and the PIN Code is displayed. However, when I submit the code, I am presented with the following error message: [https://imgur.com/reWcypZ](https://imgur.com/reWcypZ) 

**Logs**
```
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 163, in async_begin_pairing
    await self._pairing.begin()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/pairing.py", line 57, in begin
    return await self.auther.start_authentication()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/auth.py", line 34, in start_authentication
    raise DeviceAuthenticationError('pair start failed')
pyatv.exceptions.DeviceAuthenticationError: pair start failed
```

**To Reproduce**
Click integrations, +, Apple TV, type IP, add, type PIN Code

**Expected behavior**
As this is the final step before the ATV is added, I just expect it to be added.

**System Setup:**
 - OS: Ubuntu 18.04
 - Python: 3.7.6
 - Home Assistant: 0.103.6
 - pyatv: 0.4.0a11
 - tvOS: 13.2(17K82)

**Comment by postlund** [comment]
Hmm, this is strange. Have you made any configuration changes related to AirPlay? Two things that is worth testing:

* Reboot Apple TV and try again
* If same error after reboot: `atvremote --id <id> --debug --protocol airplay pair` and provide logs here

**Comment by idenu** [comment]
Based on your question whether I had made any changed related to the AirPlay settings on ATV, I found that I had enabled "Only People Sharing This Home" under the "Allow Access" settings. After I changed this setting to "Anyone on the Same Network" I was able to finalise the configuration of the Integration.

Thank you for helping!

**Comment by postlund** [comment]
Great! Would be good to have better support for this but that might be another day. I'll try to add this to the documentation as well so I can refer to it in the dialog.
