### ISSUE TITLE
Category if stream is a serie, movie, documentary, etc

### ISSUE THREAD

**Issue by poudenes** [postlund/pyatv#383]
Do you know if Netflix and/or Apple send the categorie also ? Like is the stream a Movie, Show, Documentary etc? If so, will there be a possibility that you can implement this as a sensor?

We watching movies here with light dimmed, we watch series mostly with more lights and documentary with full lights on. If there is a sensor I can automate this, so for every type his own light scene.

**Comment by postlund** [comment]
As I said on the HA forum, I will look into it 👍

**Comment by postlund** [comment]
I've explored this a bit over time, looking at logs and trying to figure out if I can do something better. Unfortunately I don't see any good (or bad) ways of doing that. It is up to the app to set all metadata, so if the app doesn't provide it there's no way of knowing what is played. Most apps, like Netflix, doesn't seem to do a good job in this area I'm afraid and there's nothing I can do about it. We will just have to wait and hope that it imrpoves over time. Will close issue for now, we can re-open or create a new issue if state changes.
