### ISSUE TITLE
Unable to add device

### ISSUE THREAD

**Issue by muster021** [postlund/pyatv#391]
Installed the integration via HACS.
Adding new integration. The component finds 2 ATV's and 5 Sonos speakers and presents their IP. Entering ATV IP in the dialog box generates:

"A device was found but could not identify any way to establish a connection."

Entering another ATV IP generates "Do you want to setup integration of NAME in Home Assistant?
Pressing Send (should be Yes) generates dialog name "Cancelled".
HASS 0.104.3
ATV: IOS 13.3

**Comment by muster021** [comment]
Worked after a restart

**Comment by postlund** [comment]
Yes, this basically means that an AirPlay service was found but nothing else. I assume you rebooted the Apple TV? I have seen this behavior myself, when the device stops responding to some services. A reboot usually helps. I will add some instructions for that to clarify.
