### ISSUE TITLE
Cant add apple tv 4k

### ISSUE THREAD

**Issue by yfaber** [postlund/pyatv#403]
**Describe the bug**
Followed all the steps, got to the integrations and clicked on Apple TV, typed ip address and got a message saying device cannot be found
**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: mac
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]

**Additional context**

**Comment by postlund** [comment]
I will need some more detailed information here, e.g. logs. It's impossible for me to say anything based on current information here. Maybe you can start by trying if `atvremote` works?

https://postlund.github.io/pyatv//documentation/atvremote/

**Comment by yfaber** [comment]
I'm still stuck, newbie here... any chance you can take a look at this with me?

**Comment by yfaber** [comment]
I don't know how to run the ATV? Can you describe step by step?

**Comment by postlund** [comment]
I need to see some logs in order to say anything at all. Simplest is if you add this to your configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```
Then try to add your Apple TV (specify IP-address in the dialog) and attach `home-assistant.log` here.

**Comment by yfaber** [comment]
I messaged you on the discord chat, i'm stuck stil...

**Comment by yfaber** [comment]
Just added the code to the configuration yaml and than tried to add the Ip address..

**Comment by yfaber** [comment]
I got this now. 

2020-02-08 19:34:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by The-sultan** [comment]
@yfaber This is the normal log when running a custom component inside home assistant, you need to find something else related to the apple tv component. If I were you I would check the logs right after you experience the error.

**Comment by yfaber** [comment]
It's working now! Amazing job Peter!
