### ISSUE TITLE
Small UI suggestion when adding new device

### ISSUE THREAD

**Issue by SeanPM5** [postlund/pyatv#406]
**What feature would you like?**
Currently when adding an Apple TV the screen has something similar to this:

```
If any devices were automatically discovered on your network, they are shown below.

Sean's Apple TV (192.168.86.102), Living Room (192.168.86.98)
```

This requires either typing it out or copying and pasting into the text field underneath. Not a big deal at all, but it could be made a tiny bit more convenient :) 

**Describe the solution you'd like**
Here is a quick little mockup, it would show the Apple TV's in an easier to read list format and you could either click on one to pre-fill the details in the field below, or maybe click the checkbox to add multiple devices at once.

![proposed](https://i.imgur.com/8t4kSuZ.jpg)

(Also changed the heading from "Add new device" to "Add new Apple TV" as that looks a little nicer and is more descriptive.)

I realize the focus right now is more on making things work and fixing bugs, but just thought I'd just share this idea for later on.

**Comment by postlund** [comment]
Yes, this would be great if possible 😄 I will have to investigate what is possible to do with the data entry flow framework as that is what I have to play with. But this would definately make it look a lot nicer!

**Comment by postlund** [comment]
So, I've looked into this and it is unfortunately not possible to mimic your excellent mockup (today) 🙁 The data entry flow framework supports picking from multiple options, but only in the form of a drop-down list. It would of course be possible to use that but... I see a few issues:

* Combining both the drop-down list and input field in the same dialog is confusing - which is used?
* Presenting a drop-down list with choices and a "custom entry", which proceeds to a new dialog containing a text input makes the flow a nightmare both for the user and to implement (it is *really* complex as-is)
* It is not possible to localize text for entries in the drop-down list, so the special entry meaning "Let me enter something" would not be translatable (de-select is not possible)
* Dialog is not dynamic, so it's not possible to populate the text input based on what is chosen from the drop-down list - rules are in frontend

So I think we will have to wait some time before this can happen 🙁

**Comment by postlund** [comment]
I will keep this in mind going forward, but we need to see some improvements to data entry flow in the front end for this to happen. Will close this now to tidy up issues.
