### ISSUE TITLE
Unpin requirements

### ISSUE THREAD

**Issue by balloob** [postlund/pyatv#42]
It can cause issues downstream if libraries pin their requirements. It means that for users of your library (in this case Home Assistant) to upgrade to a new version of pyatv, we also need to match the aiohttp requirement to avoid conflicts.

If you don't depend on specific features in libs, may I suggest that you try to match your requirements as low as possible.

**Comment by postlund** [comment]
Yeah, sorry about the problems with that. I'm gonna unpin to lower requirements that I know works, thanks for the feedback!
