### ISSUE TITLE
Question regarding hardware requirements

### ISSUE THREAD

**Issue by jc13git** [postlund/pyatv#420]
Hi - I was just getting started with pyatv and was trying out atvremote and have a question regarding hardware requirements.  I loaded up an RPI3b with an updated Raspbian Buster (lite) and a fresh install of pyatv.  What I'm seeing is that any action I try to do with atvremote takes 20-25 seconds.  That seems a little excessive, but I didn't know what top expect running on the RPI hardware.  Is there something I'm missing or have I done something wrong?  The version of python installed is either 3.7 or 3.8 (can verify if necessary), and there is nothing else installed outside of the normal Raspbian image.  Thanks for any input!

**Comment by postlund** [comment]
Hey! This seems like a valid concern that I haven't bothered much about. So... I took a spin at my raspberry pi 3 (similar setup as you) and I get times around 7,5s:

```
time atvremote -n Vardagsrum -s 10.0.10.81 playing
  Media type: Unknown
Device state: Idle

real 0m7.546s
user 0m7.299s
sys  0m0.171s
```

Quick look with logs enabled reveals that almost all time is spent on loading python modules in the beginning. It's really fast after that. I will have to look into where the actual culprit is and if it's possible to improve. I guess quality (speed) of SD-card and general system load has to be taken into account as well.

**Comment by postlund** [comment]
Biggest culprit seems to be tlslite (chacha20poly1305) used for encryption in MRP (roughly 5,5s). My intention is to make an overhaul of the crypto libraries I use in the near future and replace pure python implementations (like tlslite) with faster C-implementations. Also see if I can do with fewer libraries as well. Hopefully that will improve load time and make `pyatv` faster.

**Comment by jc13git** [comment]
Thanks for the response and for checking into it.  Very cool project!

**Comment by postlund** [comment]
Thanks for checking in, hope it works for you! 👍

**Comment by jc13git** [comment]
Just closing the loop...  I had inadvertently pulled out the slowest / oldest Pi (B+) to try out pyatv with.  It took 38 seconds to get the now playing info with the B+, and less than 4 seconds with the Pi4. 

**Raspberry Pi Model B Plus Rev 1.2**
$ time ./atvremote -n Sunroom -s 192.168.1.189 playing
  Media type: Unknown
Device state: Playing
       Title: The Simpsons
      Artist: FXX
       Album: 
    Position: 75/3635s (2.1%)

real	0m37.985s
user	0m36.454s
sys	0m0.847s



**Raspberry Pi 4 Model B Rev 1.1**
$ time ./atvremote -n Sunroom -s 192.168.1.189 playing
  Media type: Unknown
Device state: Playing
       Title: The Simpsons
      Artist: FXX
       Album: 
    Position: 408/3635s (11.2%)

real	0m3.718s
user	0m2.687s
sys	0m0.276s

**Comment by postlund** [comment]
That is quite slow (first gen rpi), not to say the least. But I'm not very surprised. I am however surpised about speed on rpi4 as 3,7s is also quite slow. Lots of room for improvement.

**Comment by postlund** [comment]
@jc13git Just wanted to give some heads up that I will start working on #424 today (hopefully), which replaces all crypto libraries with just `cryptography`. This will hopefully speed up loading times a lot. Not sure how long it will take, but shouldn't be long. I'll ping you again when a PR is ready, would love it if you could help out and test it!

**Comment by jc13git** [comment]
Great!  I'll be happy to give it a go.  Thanks!

**Comment by postlund** [comment]
Porting to `cryptography` was easier than I anticipated, I'm almost done. Just have to switch ED25519 in `MRP`. Gonna do some other stuff now, but I will most certainly finish this tonight.

**Comment by postlund** [comment]
@jc13git PR #485 is ready now, you should hopefully see a pretty good speedup. Or so I hope at least.

**Comment by postlund** [comment]
It might be the case that `cryptography` does not support `Ed25519` on ARM or that my (old) version of OpenSSL doesn't support it. I get this:

```python
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
ImportError: No module named 'cryptography.hazmat.primitives.asymmetric.ed25519'
```

Do you see the same thing?

**Comment by postlund** [comment]
Continuing... was using an old venv with python 3.5 and old `cryptography` version. But my guess that openssl does not support ed25519 seems correct:
```shell
Traceback (most recent call last):
  File "/home/pi/pyatv/pyatv/mrp/protocol.py", line 110, in _connect_and_encrypt
    await pair_verifier.verify_credentials()
  File "/home/pi/pyatv/pyatv/mrp/auth.py", line 98, in verify_credentials
    _, public_key = self.srp.initialize()
  File "/home/pi/pyatv/pyatv/mrp/srp.py", line 97, in initialize
    self._signing_key = Ed25519PrivateKey.from_private_bytes(os.urandom(32))
  File "/home/pi/pyatv/venv/lib/python3.7/site-packages/cryptography-2.8-py3.7-linux-armv7l.egg/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 63, in from_private_bytes
    _Reasons.UNSUPPORTED_PUBLIC_KEY_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: ed25519 is not supported by this version of OpenSSL.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/pyatv/pyatv/__main__.py", line 641, in _run_application
    return await cli_handler(loop)
  File "/home/pi/pyatv/pyatv/__main__.py", line 457, in cli_handler
    return await _handle_commands(args, config, loop)
  File "/home/pi/pyatv/pyatv/__main__.py", line 545, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol)
  File "/home/pi/pyatv/pyatv/__init__.py", line 275, in connect
    await atv.connect()
  File "/home/pi/pyatv/pyatv/mrp/__init__.py", line 492, in connect
    await self._protocol.start()
  File "/home/pi/pyatv/pyatv/mrp/protocol.py", line 75, in start
    await self._connect_and_encrypt()
  File "/home/pi/pyatv/pyatv/mrp/protocol.py", line 114, in _connect_and_encrypt
    raise exceptions.AuthenticationError(str(ex)) from ex
pyatv.exceptions.AuthenticationError: ed25519 is not supported by this version of OpenSSL.
````
Not sure what I want to do now...

**Comment by postlund** [comment]
Ok, so what I did was to merge the changes and basically require a newer version of OpenSSL. Can not rely on old software forever.

**Comment by jc13git** [comment]
Sounds good - I’ll give it a go.  Thanks!

**Comment by MTuner** [comment]
I can confirm a significant speedup on my raspberry pi4, thank you!

**atvremote 0.4.0:**
```
$ time atvremote
atvremote  2.55s user 0.14s system 99% cpu 2.711 total
$ time atvremote scan
atvremote scan  2.77s user 0.10s system 49% cpu 5.830 total
```

**atvremote 0.4.1a1 (master):**
```
$ time atvremote
atvremote  1.10s user 0.12s system 99% cpu 1.227 total
$ time atvremote scan
atvremote scan  1.25s user 0.13s system 31% cpu 4.331 total
```

**Comment by postlund** [comment]
@MTuner Great, thanks for pitching in some result 😄 I believe that we can conclude this session now. More optimizations can be made in the future, but this was a good improvement in many ways 👍

**Comment by FezVrasta** [comment]
I get these times on a Synology DS118 with a WD Red 6TB on it. But the most concerning thing is that the command can take up to 30% of the CPU.

Do you think there's anything else that could be done to reduce CPU usage?


```
$ time atvremote
real	0m3.147s
user	0m3.010s
sys	0m0.110s

$ time atvremote scan
real	0m6.186s
user	0m3.210s
sys	0m0.100s
```
