### ISSUE TITLE
Make use of HDMI CEC

### ISSUE THREAD

**Issue by cadavre** [postlund/pyatv#425]
**What feature would you like?**

This MRP implementation is awesome! Finally we can control things like `wakeup` and `suspend` which makes automations a charm. Working with original Apple TV Remote – using it (and pressing same buttons as we could via pyatv) we can suspend the Apple TV which will inform connected devices (via CEC) to also go to sleep.

Unfortunately this doesn't happen when we control Apple TV via pyatv remote. This strictly says that control protocol may support allowing CEC.

**Describe the solution you'd like**

It would be awesome to have change to "enable CEC" for remote when using with sending a `wakeup` or `suspend` commands. No idea if this is possible with pyatv or even MRP.

Any signs is it's possible?

**Comment by postlund** [comment]
As of what anyone (at least public) know, it is not possible. Not possible in the sense that we can't tell if it is or not, but currently it's not as we have not found a way. You will have to manually use `home_hold` and navigate to suspend. If anyone figures this out properly, I would gladly accept a PR for it!

**Comment by cadavre** [comment]
The thing is that manually using `home_hold` + `select` (== `suspend`) doesn't do the job. :) TV still stays on. Doing the same with ATV Remote turns off the TV too. That's funny, isn't it? :)

Looks like I'll need to find a way to control TV via IR in the end. :) Thanks for your reply.

**Comment by postlund** [comment]
That *is* interesting. When you say use the original remote, you mean holding down the home button and selecting suspend in the exact same way?

**Comment by jdebardi** [comment]
> The thing is that manually using `home_hold` + `select` (== `suspend`) doesn't do the job. :) TV still stays on. Doing the same with ATV Remote turns off the TV too. That's funny, isn't it? :)
> 
> Looks like I'll need to find a way to control TV via IR in the end. :) Thanks for your reply.

Home_hold and select absolute DOES send CEC standby to the TV. If yours is not then check that you have your settings > remotes and devices > control TVs and receivers as On.

MRP Suspend command doesn’t.

**Comment by cadavre** [comment]
@postlund yes, _exact_ same way.

I had to re-check this twice again.

Indeed – using "pyatv" remote **does not** turns off my TV with home_hold+select, while original Apple TV Remote **does**.

Looks like I'm s**t out of luck. :)

**Comment by postlund** [comment]
@cadavre Very strange, it should be the same. One thing you can do is to use the proxy (`scripts/proxy.py`) so we can intercept traffic from the traffic from original app and compare.

**Comment by cadavre** [comment]
```
python scripts/proxy.py (cat creds) <ip_of_pc_launching_the_mrp_server?> <ip_of_atv> <random_port?>
```

I can see "Proxy" in my Apple TV iOS app, but when I try to connect – it gives me info about my iPhone and after few seconds: `futures.TimeoutError()` in `"./scripts/proxy.py", line 94, in start`.

**Comment by cadavre** [comment]
Oh BTW – Apple TV iOS app also **does not** turn off my TV.

**Comment by jdebardi** [comment]
I’m on TVoS 13.2, upgrading to 13.3.1 now to see if it makes it break/behave as @cadavre  is reporting. Will be very annoying if it does!!

**Comment by cadavre** [comment]
I tested it on 13.3 and 13.3.1.

**Comment by jdebardi** [comment]
Updated to 13.3.1 and still works with iOS remote and pyatv sending home_hold+select.

So thinking something is unique about @cadavre ’s setup.

I’m testing with a ATV 4K 64GB.

TV is a 10 year old Samsung LED.

**Comment by jdebardi** [comment]
A quick google shows this being widespread since TVOS 13

For many the solution is simply to unplug everything from eachother and power for a minute and then try again. Others have found something going on with TV remote key mappings doing odd stuff which may be related.

I have occasional CEC issues with my other TV (Panasonic) and the ONLY solution is to power everything off and on completely (which I guess forces all devices to re-find eachother over HDMI CEC). I’d try that first.

Ref: https://www.reddit.com/r/appletv/comments/ehobi5/my_apple_tv_no_longer_works_with_cec_on_my/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
https://discussions.apple.com/thread/250729703?page=1

**Comment by cadavre** [comment]
Super-strange. Indeed cycling power on both devices started to work with home_hold+select from any: ATV Remote, iOS app and pyatv. Until... I called `wakeup`. Than it no longer works.

Looks like there's more than what we've found to MRP. :) Thanks for motivating me to test it all.

**Comment by jdebardi** [comment]
I wakeup using top_menu and it works fine

From my experience Apples MRP implementation is definitely very odd RE sleeping/suspending/waking up - thus I’m not using any commands like suspend or wakeup

**Comment by postlund** [comment]
> From my experience Apples MRP implementation is definitely very odd RE sleeping/suspending/waking up - thus I’m not using any commands like suspend or wakeup

MRP is quite over-engineered IMHO... Many strange things in there.

**Comment by postlund** [comment]
So, I deprecated `suspend` and `wakeup` because they don't work as one might expect. @stickpin has added a power interface that allows turning on and off a device (by menu navigation and using `WakeDevice` for turning on the device). It can be tested with `atvremote ... turn_on` and `turn_off` respectively. This will work with CEC as requested, so I guess we can call it a day.

**Comment by cadavre** [comment]
Wow! Good news! Thank, I'll try it today.
