### ISSUE TITLE
Unclear in de documentation how to get the 3 credentials of the atv beta integration

### ISSUE THREAD

**Issue by YRRK** [postlund/pyatv#433]
Hi Pierre,

Thanks for updating the ATV plugin, it's been very missing.

Could you explain how to get the 3! credentials:
      mrp: <creds>
      airplay: <creds>
      dmap: <creds>
Because that is completely unclear. The previous atv method gave you 1 key, but In his new plugin you ask to fill in 3. I dunnow why and don't know how.

With kind regards!

**Comment by YRRK** [comment]
I mean the example with the 3 things you nee to fill in the configyaml

apple_tv:
  - host: 10.0.0.1
    identifier: <id>
    name: Living Room
    protocol: MRP
    credentials:
      mrp: <creds>
      airplay: <creds>
      dmap: <creds>

**Comment by postlund** [comment]
Yeah, the instructions are a bit unclear and I will be improving them before including the component in home assistant. I can guide you if you really want, but I would definitely recommend adding your Apple TV from the Integrations page instead. In the end it's the exact same thing (adding in `configuration.yaml` triggers the same config flow as in the UI, so there's no real benefit here).

**Comment by YRRK** [comment]
Oke, i'll wait until the iOS13 is back the official integration then. Hope it is final soon :-)

**Comment by postlund** [comment]
Sure, or just use the config flow since that is easier and the recommended way to add a device 😄

**Comment by postlund** [comment]
@YRRK Do you want assistance with using integration config flow or do you want to wait? Assuming the later, can the issue be closed?

**Comment by YRRK** [comment]
> @postlund No i'm waiting for the official integration update to use AppleTV again with iOS13
I know how to do the thing with obtaining the keys for the ATV 4K (but they don't communicate at te moment because ot that new tv os.) So if that stays the same then i'm fine.

**Comment by postlund** [comment]
With the new integration (this one) you should not have to deal with credentials. It takes care of it for you in the config flow.

**Comment by YRRK** [comment]
Oke but i'm using Home Assistant 0.105.3, and I haven't seen any update in the blog that the updated ATV integration is included in this version.

**Comment by postlund** [comment]
No, I have not submitted a PR for that yet as I'm not done with tests. But this custom component is exactly the same component that will be merged back into Home Assistant at some point.

**Comment by YRRK** [comment]
Ah no I have to wait then. If I include the custom_component folder with atv in it. Then home assistaant removes the "offical" atv component for future use I noticed. Even If I delete the custom integration later the "official" AppleTV integration won't come back anymore. Last time I tried to test your ios13 compatible integration, the Developer tools>Services>apple_tv.apple_tv_scan or autheticate>Call disappeared. After removing your beta version again, the buildin functionality didn't return, so I couldn't install an older Apple TV anymore as a temp placeholder. I had to do a complete re-install of HomeAssistant on my Pie to get everyhing out-of-the-box normal again. So I'm a bit holding back beta testing now because I seem to have no clue what i'm acutally doing to the HomeAssistant in de background and how to get it fixed again. I conclued to better stay away nexttime and better wait until it's fixed instead trying to be a beta tester. :-)

**Comment by postlund** [comment]
That seems really strange. Removing the custom component should restore the builtin version, I'll have to test that myself to see what happens. The custom component should work equally fine with older devices as well, so you shouldn't have to revert back anyway. Would really appreciate some additional testing on Apple TV 2/3 as well 👍 

Don't get too hooked up on the old Apple TV services. They are deprecated and fully replaced by the config flow. They are not needed.

**Comment by YRRK** [comment]
Hi, i'm currently went on vacation. I'll take a new test when i'm back. Thanks for your support.
This case can be closed. I'll open one if I find a bug ;-)
