### ISSUE TITLE
Error setting up entry after latest update

### ISSUE THREAD

**Issue by Krocko** [postlund/pyatv#452]
> **Describe the bug**

After the latest update I get the following error:
```
Error setting up entry AppleTV for apple_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/apple_tv/__init__.py", line 119, in async_setup_entry
    discovery.async_load_platform(hass, "remote", DOMAIN, entry.data, entry.data)
NameError: name 'discovery' is not defined
```
**To Reproduce**

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: [Synology DSM]
 - Python: [?]
 - pyatv: [e.g. 0.4.0a16]
- Home Assistant: 0.105.5

**Additional context**

**Comment by postlund** [comment]
Damn it, I mixed up what was going to Home Assistant and remain in the custom component. I will push a fix for it.

**Comment by postlund** [comment]
Update pushed now, please give it a spin!

**Comment by postlund** [comment]
Tried it myself and it seems to work!

**Comment by Krocko** [comment]
Yes, problem is solved. 
Thank you.

**Comment by postlund** [comment]
Great, thanks!
