### ISSUE TITLE
Crash when scanning for devices

### ISSUE THREAD

**Issue by hwikene** [postlund/pyatv#48]
(venv)pi@hassbian:~/venv $ atvremote scan
Found Apple TVs:
Traceback (most recent call last):
File "/home/pi/venv/lib/python3.4/site-packages/pyatv/main.py", line 245, in _run_application
asyncio.wait_for((yield from cli_handler(loop)), timeout=15)
File "/home/pi/venv/lib/python3.4/site-packages/pyatv/main.py", line 81, in cli_handler
yield from _handle_scan(args, loop)
File "/home/pi/venv/lib/python3.4/site-packages/pyatv/main.py", line 108, in _handle_scan
_print_found_apple_tvs(atvs)
File "/home/pi/venv/lib/python3.4/site-packages/pyatv/main.py", line 116, in _print_found_apple_tvs
outstream.writelines(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 0: ordinal not in range(128)

            An error occurred, full stack trace above

**Comment by postlund** [comment]
I think your problem is that you have a non-ASCII character in your Apple TV name and the locale in your terminal is not compatible with that (it's non-UTF8). Can you type ``locale`` in a terminal and paste the output here?

**Comment by hwikene** [comment]
here is my output from "locale"
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by postlund** [comment]
After discussion on gitter, we came to the conclusion that the crash (as expected) is locale-related. The terminal defaulted back to "C", which is not unicode-compatible. Setting LC_ALL=en_GB.UTF-8 fixed this.
