### ISSUE TITLE
Missing config entry support in remote component

### ISSUE THREAD

**Issue by hekm77** [postlund/pyatv#504]
**Describe the bug**

After updating to the latest version of Apple TV Beta Component via HACS, I get an error in the log after restarting the Home Assistant (0.106.6)

**System Setup (please complete the following information):**
 - Home Assistant in Docker, RPi 3B
 - Python: 3.7.6
 - pyatv: 0.4.0a16 update 2 (ddef67b)

**Additional context**
```
Error setting up entry Apple TV Зал for remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 214, in async_setup
    result = await component.async_setup_entry(  # type: ignore
AttributeError: module 'homeassistant.components.remote' has no attribute 'async_setup_entry'
```

**Comment by postlund** [comment]
Ah, damn. I thought the changes to `remote` was merged to 0.106 already. The solution for now will have to be defer upgrading until 0.107 is released, which is just two days away more or less. My time is too limited for me to make an interim solution. Sorry about that! I will try to update the readme to inform about this, so it's shown in HACS.

**Comment by postlund** [comment]
@hekm77 Release 0.107 is out, can you make another try with that? Should fix the problem.

**Comment by hekm77** [comment]
Yes, 0.107 has solved the problem.
Thank you.
