### ISSUE TITLE
HASS Beta plugin config flow issues

### ISSUE THREAD

**Issue by stickpin** [postlund/pyatv#514]
Hi @postlund,

I've found two issues with your latest commit.
First one related to the config_flow.py:
I cannot explain why but this code was giving me troubles to save settings: 
```
class AppleTVOptionsFlow(config_entries.OptionsFlow):
    """Handle Apple TV options."""

    def __init__(self, config_entry):
        """Initialize Apple TV options flow."""
        self.config_entry = config_entry
        self.options = dict(config_entry.options)

    async def async_step_init(self, user_input=None):
        """Manage the Apple TV options."""
        if user_input is not None:
            self.options[CONF_START_OFF] = user_input[CONF_START_OFF]
            self.options[CONF_PWR_MGMT] = user_input[CONF_PWR_MGMT]
            return self.async_create_entry(title="", data=self.options)

        return self.async_show_form(
            step_id="device_options",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_START_OFF,
                        default=self.config_entry.options.get(
                            CONF_START_OFF, DEFAULT_START_OFF
                        ),
                    ): bool,
                    vol.Optional(
                        CONF_PWR_MGMT,
                        default=self.config_entry.options.get(
                            CONF_PWR_MGMT, DEFAULT_PWR_MGMT
                        ),
                    ): bool,
                }
            ),
        )
```

Once I've reverted back to:
```
class AppleTVOptionsFlow(config_entries.OptionsFlow):
    """Handle Apple TV options."""

    def __init__(self, config_entry):
        """Initialize Apple TV options flow."""
        self.config_entry = config_entry
        self.options = dict(config_entry.options)

    async def async_step_init(self, user_input=None):
        """Manage the Apple TV options."""
        return await self.async_step_device_options()

    async def async_step_device_options(self, user_input=None):
        """Manage the devices options."""        
        if user_input is not None:
            self.options[CONF_START_OFF] = user_input[CONF_START_OFF]
            self.options[CONF_PWR_MGMT] = user_input[CONF_PWR_MGMT]
            return self.async_create_entry(title="", data=self.options)

        return self.async_show_form(
            step_id="device_options",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_START_OFF,
                        default=self.config_entry.options.get(
                            CONF_START_OFF, DEFAULT_START_OFF
                        ),
                    ): bool,
                    vol.Optional(
                        CONF_PWR_MGMT,
                        default=self.config_entry.options.get(
                            CONF_PWR_MGMT, DEFAULT_PWR_MGMT
                        ),
                    ): bool,
                }
            ),
        )
```

Everything works as expected.

My env:
HASS: v0.107
pyatv: v0.5.0

Full code is [here](https://github.com/stickpin/hass-atv-beta/blob/master/custom_components/apple_tv/config_flow.py) in my repo.

The second issue will report in my next post.

Thanks in advance!

**Comment by postlund** [comment]
Ah, this is a translation error. I managed to fix it locally. I can push a fix for it but I'd like to look at your other issue first, in case I can fix that one as well.

**Comment by stickpin** [comment]
@postlund ok, first one I've fixed by changing `step_id="device_options"` to `step_id="init"`.

The second issue it's a bit strange and I think it has to do something with last `identifiers` change.
Now I've also updated my code to your latest commit and just added a my power management part.

The issue is reproducible only if two Apple TVs are paired to the same HASS system.
After pairing both and enabling the Power Management option on both. If I turn on or turn off one of them, the latest paired Apple TV will react, meaning turn off or turn on.

In addition, also `pyatv` connection in the remote app on the first paired Apple TV is in "Non Connected" state.

Let me know if it's clean enough or you need more info.

Thanks in advance!

**Comment by postlund** [comment]
I'm in a bit of a hurry right now, so I will look at it later. But did you remove all Apple TV's and re-pair them? My latest change was a breaking change which I haven't mentioned yet.

**Comment by postlund** [comment]
Which commit are you basing you fork off? Did you try to import from my HA PR or from custom component repo?

**Comment by stickpin** [comment]
@postlund from custom component.
HA PR I know that may not work.

**Comment by postlund** [comment]
@stickpin What are you referring with my last `identifier` commit?

**Comment by stickpin** [comment]
the one with 0.107 support.

**Comment by stickpin** [comment]
from this upward: https://github.com/postlund/hass-atv-beta/commit/ddef67bc945b6a2f4fa2f99e1668413fce588e34

**Comment by postlund** [comment]
Wow, what have I done. That is so bad. I'll write a test to smoke this out.

**Comment by stickpin** [comment]
@postlund I will also try to find some time tonight to work on it.
I will let you know if I will be able to find something.

**Comment by postlund** [comment]
@stickpin I know what the problem is. I cannot use unique_id the way I do since I haven't set unique_id in config_flow.py. It will be None for all config entries. I have converted config_flow.py to do so locally (comment from code review), so it will be fixed. I just want to have a test for it for the future.

You could manually try to revert those changes in __init__.py and see if it works. Should be fine.

**Comment by postlund** [comment]
Here's the fixed version:

https://github.com/postlund/hass-atv-beta/pull/1

You will have to remove your integrations and pair them again.

**Comment by stickpin** [comment]
@postlund thanks a lot! Will do it and will report back!

**Comment by postlund** [comment]
This could potentially be the fix for the connection problems people are seeing. I hope so.

**Comment by stickpin** [comment]
@postlund I can confirm the issue has been resolved after merging your commit. 
btw, do we want to include power management integration into the main plugin? :)

**Comment by postlund** [comment]
@stickpin Great 😀 Yes, I would prefer if we could bring it into Home Assistant by default. Since pyatv has a real API for it now, it's fair game. I'm trying to get the component in shape in the PR so we can get it merged. I also want to incorporate the "features API" and running app as well.

Will merge the PR tomorrow, must fix the README and a that.

**Comment by postlund** [comment]
@stickpin PR is merged now!

**Comment by stickpin** [comment]
@postlund thanks a lot!
I will create a PR for Power Management's future on the HASS Plugin side.

**Comment by postlund** [comment]
@stickpin That will be great!

I added a start of a "fake device" script (#518) that should be possible to use when testing. Documentation is here:

https://github.com/postlund/pyatv/wiki/Fake-Device

Still very basic, but pretty cool. I tried it with the HA component and it worked great (you can't *do* anything with it, but adding it and turning it on/off works fine).
