### ISSUE TITLE
Disconnecting after HA Restart

### ISSUE THREAD

**Issue by geekofweek** [postlund/pyatv#515]
**Describe the bug**
Loosing Connectivity on Restart
**To Reproduce**
Restart Home Assistant
**Expected behavior**
Device remains connected
**System Setup (please complete the following information):**
 - OS: [e.g. Debian] Docker (Ubuntu 18.04.4)
 - Python: [e.g. 3.6.2] 3.7.6
 - pyatv: [e.g. 0.3.10] 0.5.0

**Additional context**
Since the last release, and the current release, the connectivity between HA and the Apple TV appears to get lost after a restart.  The state is `Unknown` and the media comes back as `Connected, waiting for update...`

The only re-course I've found so far is to re-pair the device.  Log files don't show any errors.

**Comment by postlund** [comment]
I think I found the bug. Did you add by IP address?

**Comment by geekofweek** [comment]
@postlund yes by IP address

**Comment by postlund** [comment]
@geekofweek Ok, good, then I know what to do.

**Comment by geekofweek** [comment]
good deal, let me know and I can test it if needed.

**Comment by postlund** [comment]
@geekofweek New update pushed, please give it a try!

**Comment by geekofweek** [comment]
Initial testing looks good, did a few restarts and everything sticks.  Reading over the explanation makes sense as to what I was seeing.  Single instance would stay no problem, multiple would get lost.  Turning one off turned the rest off.  Nice work

**Comment by postlund** [comment]
Great stuff, thanks! 👍
