### ISSUE TITLE
Apple TV State is always "Connected, waiting for update"

### ISSUE THREAD

**Issue by codylv7** [postlund/pyatv#516]
**Describe the bug**
Apple TV state always shows "Connected, waiting for update"

**To Reproduce**
Add Apple TV

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Docker
 - Python: ?
 - pyatv: 0.5.0

**Additional context**

**Comment by postlund** [comment]
Just pushed an update, please upgrade and let me know if it works!

**Comment by geekofweek** [comment]
Believe it's related to this one https://github.com/postlund/pyatv/issues/515

Check the latest update, should be resolved.

**Comment by codylv7** [comment]
I installed the latest version and now all Apple TVs show as Unavailable, log shows:

2020-03-20 13:47:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: remote.master_bedroom. Platform apple_tv does not generate unique IDs

Do I need to remove all Apple TVs and re-add them?

**Comment by geekofweek** [comment]
@codylv7 yes that was part of the release notes, unfortunate side effect of the fix.

**Comment by codylv7** [comment]
Ah okay, sorry about that, I'll re-add them and report back.

**Comment by codylv7** [comment]
All better, thanks for the fix =)

**Comment by postlund** [comment]
👍
