### ISSUE TITLE
remote command top_menu acting as home-button single-press click

### ISSUE THREAD

**Issue by fitim7** [postlund/pyatv#522]
**Describe the bug**
In the pyatv docs this is defined: "top_menu - Go to main menu (long press menu)".
But that's not working. The top_menu command has the functionality of the single-click home-button, and not as expected the long-press menu-button. On the real remote the long-press menu-button is working as expected.
**To Reproduce**
```
remote.send_command:
  command: top_menu
```
--> this will lead to a home-button single-press on the ATV.
**Expected behavior**
--> it should lead to a long-press menu-button.
**System Setup (please complete the following information):**
 - OS: Home Assistant 0.107.1
 - Python: newest custom component of ATV integration
 - pyatv: newest custom component of ATV integration

**Additional context**

**Comment by postlund** [comment]
I tried to fix it yesterday, but I think the "home" button internally is more like the TV-button. Long-pressing it brought me to the TV app instead. So I need to investigate the traffic again to figure out the correct button.

**Comment by postlund** [comment]
Hmm, looking at the traffic looks like it is the home button. Not sure why it didn't work when I tried, guess I will have to try again.

**Comment by fitim7** [comment]
Hmm ... okay. Since I don’t know how I should help, I want just to thank you. 
Thanks for your effort :)

**Comment by postlund** [comment]
This will be fixed in `pyatv` once #579 is merged but not in the HA component until I release a new version of `pyatv` and bump to that version in the component. Hopefully I will do that quite soon.

**Comment by postlund** [comment]
I just released pytav 0.6.0 with this fix and updated the component. Feel free to upgrade and give it a try 👍  (and close the issue if it works)

**Comment by fitim7** [comment]
I just testet the update. Everything is working as expected now. Thanks for your effort, im closing this issue now.
