### ISSUE TITLE
Keyboard control (services) for when the keyboard pops up

### ISSUE THREAD

**Issue by Apple2T4ch** [postlund/pyatv#584]
**What feature would you like?**
I would like to be able to send a service to trigger a keyboard letter/number, (hope that makes sense)
**Describe the solution you'd like**
Just add a service, if possible.
**Any other information to share?**
Hoping to make a remote control card with a keyboard for mobile.

**Comment by postlund** [comment]
It is planned for 0.7.0 or so (there's another issue for it, #145).

**Comment by postlund** [comment]
Keyboard support is in place in pyatv, it is not implemented in home Assistant however. But since this is the issue tracker for pyatv, I will treat this issue as done.
