### ISSUE TITLE
Turn off or sleep device

### ISSUE THREAD

**Issue by yfaber** [postlund/pyatv#604]
How can I change the status to sleep or turn off?

**Comment by postlund** [comment]
The power interface is used for that:

https://pyatv.dev/development/power_management/

https://pyatv.dev/api/interface#pyatv.interface.Power

You can also test it with atvremote, e.g. `atvremote ... turn_off`. It is worth noting that it ain't 100% foolproof. It's best effort and only works with devices running tvOS.

**Comment by davidsielert** [comment]
@postlund  this doesn't work for me. doesn't throw errors just nothing happens

**Comment by postlund** [comment]
Please attach some debug logs and I'll have a look if I see something strange.

**Comment by postlund** [comment]
Did you by any chance get any logs? Also, when powering off, have a look at the screen. Turning off is simulated by holding the home button and selecting standby. So you should see that happen.

**Comment by postlund** [comment]
I will close the issue due to lack of response. Feel free to open it again and attach some logs.
