### ISSUE TITLE
Power state expected to be off but atvscript returns "on"

### ISSUE THREAD

**Issue by crxporter** [postlund/pyatv#606]
Last issue for the week - I hope.

**Describe the bug**
Things had been working just great with `atvscript` and today I noticed that putting to sleep the apple tv is not triggering a "power off" message.

**To Reproduce**
Running atvscript, put the apple tv to sleep by holding "home" and clicking "sleep"

**Expected behavior**
`atvscript` returns power off message.

**System Setup (please complete the following information):**
 - OS: raspbian
 - Python: 3.7.3
 - pyatv: 0.5.0 (pulled from github today)
- Apple TV: 4k, newest os

**Additional context**
After noticing the issue I moved my script to run on a different pi so I could run it with debug mode. Files are on [my typical share](https://www.icloud.com/iclouddrive/0ANcppdDNC4grXSPAuoPogJIQ#powererror). Check the powererror.log file for this one. The only thing in the log should be starting atvscript once, letting it run for a few minutes, then restarting atvscript. ATV should have been "off" the whole time.

`atvscript` output is this:
```
{"result": "success", "datetime": "2020-04-21T18:26:58.734390-05:00", "power_state": "on"}
{"result": "success", "datetime": "2020-04-21T18:26:58.736548-05:00", "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1", "media_type": "unknown", "device_state": "idle", "title": null, "artist": null, "album": null, "genre": null, "total_time": null, "position": null, "shuffle": "off", "repeat": "off", "app": null, "app_id": null}
SIGTERM
{"result": "success", "datetime": "2020-04-21T18:30:18.433405-05:00", "power_state": "on"}
{"result": "success", "datetime": "2020-04-21T18:30:18.435418-05:00", "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1", "media_type": "unknown", "device_state": "idle", "title": null, "artist": null, "album": null, "genre": null, "total_time": null, "position": null, "shuffle": "off", "repeat": "off", "app": null, "app_id": null}
```

**Comment by crxporter** [comment]
A soft-restart of the apple tv has it working again. I'm not sure why it stopped, I don't know what I'm looking for in the logs. 

I uploaded another log file `powererrorRESTARTED.log` which includes the logs from just now after restarting and watching a movie preview then turning off the same way as before.

I'm hoping to be able to depend on the power_state messages from atvscript to reliably turn off my TVs. I have vizio TVs which about 6 months ago got "updated firmware" and now the CEC power sleep command from ATV is ignored (used to work fine)...

**Comment by postlund** [comment]
Yeah, it's a bit weird. In the first log more or less nothing happens. It's just a regular connection set up flow, nothing more. I would expect the device to initiate a proper sleep cycle, like in the second log. In the first case, it would have been interesting to see some other traffic, e.g. playing something, just to see that the connection just doesn't hang after connecting (similar to what you did in the other log). But it just seems strange, not sure how to go on with this.

**Comment by crxporter** [comment]
If it happens again I'll re-open and run through some playing, "waking up" and "sleeping".
