### ISSUE TITLE
"UnboundLocalError: local variable 'credentials' referenced before assignment" in documentation code

### ISSUE THREAD

**Issue by dnicolson** [postlund/pyatv#620]
**Describe the bug**
The [Managing credentials](https://pyatv.dev/development/scan_pair_and_connect/) section of the documentation contains problematic example code.

**To Reproduce**
Run the following code:
```
for protocol, credentials in credentials.items():
    atv.set_credentials(protocol, credentials)
```

**Expected behavior**
To iterate over `credentials`. One of the `credentials` variables must be renamed to fix the issue.

**System Setup (please complete the following information):**
 - OS: Linux raspberrypi 4.19.97-v7l+ #1294 SMP
 - Python: 3.7.3
 - pyatv: 0.5.0
 - Apple TV: 4K tvOS 13.4.5 build 17L5543d

**Additional context**

**Comment by postlund** [comment]
It's a bit confusing, I do agree with that. But the code should work, it's just a case of shadowing (so linting tools will complain). Here's an example that works fine for me:

```python
credentials = {"foo": "bar"}
for protocol, credentials in credentials.items():
    print(protocol, credentials)
```

Running as a script produces expected output:

```shell
$ python3 test.py
foo bar
```

I will create a PR and rename one of the variables.
