### ISSUE TITLE
Wrong state when watching TV.

### ISSUE THREAD

**Issue by Tobbe82** [postlund/pyatv#642]
When using Telia Play on Apple-TV it report "Paused" instead of "playing"

Should say "playing" 

**System Setup (please complete the following information):**
 - OS: Debian (OpenMediaVault)
 - Python: whats included in Hass Core 109.2
 - pyatv: [latest as of date, b48af45]
- Apple TV: [e.g. Apple TV 4, latest TVos]

![Skärmklipp](https://user-images.githubusercontent.com/43826954/81005690-a2508280-8e4e-11ea-93e5-be8d065d3990.PNG)

**Comment by postlund** [comment]
Can you check what the Remote app in iOS says? Additional logs (especially for pyatv) is needed for further debugging.

**Comment by Tobbe82** [comment]
![442B1409-360D-4C4E-A009-A72C807D7D7A](https://user-images.githubusercontent.com/43826954/81007252-302d6d00-8e51-11ea-8d28-a9e7858efdf8.png)

Where to find the pyatv log?

**Comment by postlund** [comment]
You can enable it like this:

```yaml
logger:
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

I suspect it has something to do with live tv. Would be good if you could press play and pause a couple of times so I can see how that affects the state.

**Comment by Tobbe82** [comment]
Ill do some tests and will try to get the logger running. But I’ve seen the behavior before when watching TV. Unsure if that was live.. 
but I’ll return when checked a bit more 👍🏼

**Comment by postlund** [comment]
@Tobbe82 Did you manage to get any logs?

**Comment by Tobbe82** [comment]
Had a very intensive month, just got the logger up, and it grows for every second. Is there a way to get rid of all other stuff in the log or do you want the whole file?
Watching TV3 tonight and it does report state as paused as I watch, like it did last time. Tried to change channel to TV4 and seems to still be paused

**Comment by Tobbe82** [comment]
> Had a very intensive month, just got the logger up, and it grows for every second. Is there a way to get rid of all other stuff in the log or do you want the whole file?
> Watching TV3 tonight and it does report state as paused as I watch, like it did last time. Tried to change channel to TV4 and seems to still be paused

I fixed it, setting default to critical for the rest.. hope it doesn't ruin anything for pyatv

**Comment by postlund** [comment]
> I fixed it, setting default to critical for the rest.. hope it doesn't ruin anything for pyatv

That is perfect!

Once you have the logs ready, just let me know. If you can provide a time stamp when the state is wrong, that could help me to narrow down where to look.

**Comment by Tobbe82** [comment]
Want me to send the file via mail? Could do anytime, have the wrong state during the whole time the logger been up. 
Actually had time to sit down the evening.
Thinking of it... last time was this gala.. live, tonight its Efterlyst and then news on TV4, both of them live?
I need to switch channel to something thats not live...

**Comment by postlund** [comment]
Sure, email works fine! Seems like a good idea to try a few different things to watch, both live and not live. My guess is that it's the live shows that doesn't work.

**Comment by Tobbe82** [comment]
Switched to Kanal9, Dunkirk isnt live, but still showing paused.

**Comment by Tobbe82** [comment]
> Switched to Kanal9, Dunkirk isnt live, but still showing paused.

 But iOS remote app actually says Direktsänt even for Dunkirk

Well I sent you the log now

**Comment by postlund** [comment]
I actually don't see anything strange here, at least when it comes to the play state. Would it be possible for you to install pyatv and run atvremote to check if it reports the same as well? They way I can also provide a variant with additional debug logs.

**Comment by postlund** [comment]
Ah, no, now I see it. It's because playbackRate is zero. This makes it a bit tricky. Can you reproduce and do play, pause, play, fast forward and play? Just so I can see how it behaves.

**Comment by KibosJ** [comment]
This happens to me when using Amazon Prime Video, I get "playing" with every app (Netflix, Plex, Infuse, etc.) but Amazon Prime Video shows as "paused" all the time

**Comment by postlund** [comment]
@KibosJ Would be great if you could provide some logs as well (doing the same thing as instructed in my previous post).

**Comment by KibosJ** [comment]
So playbackRate is zero on Amazon Prime Video too.

Playing, fast forwarding, rewinding doesn't seem to change the state.

[pyatv.log](https://github.com/postlund/pyatv/files/4705750/pyatv.log)

**Comment by postlund** [comment]
Thanks for the log @KibosJ! Glanced through it and it looks like the same problem reported by @Tobbe82. Based on what's in the messages, I can provide a hack-ish solution that reports "playing" correctly, but everything else (like seeking) will be reported as "paused". That's the best I can do. Will try to push a PR later tonight, so if any one of you can try it out it would be swell. It's tedious to get it working with the HA component (as I would have to make a pypi release and all that), so using `atvremore` is recommended.

In the end, I do believe this is really an issue with the app.

**Comment by KibosJ** [comment]
I think it definitely has to be the app, because a few of them do it, it happens with BBC iPlayer too and it also reports playbackRate as zero.

Thanks for the hack solution though 😁

**Comment by postlund** [comment]
Great work for looking into that @KibosJ 😊 The fact that this might yield incorrect state updates is something worth adding to the documentation ([FAQ](https://pyatv.dev/support/faq/#apps-tvos)). But anyway, good to get it confirmed!

I pushed #673 which mitigates the problem with the solution described above. Feel free to give it a test run!

**Comment by Tobbe82** [comment]
I’ve tried to reach out to the developers today at Telia reporting this as a bug in their app. But the dude at customer service didnt seem to bother much... as this was a little more to request than expected from their service 😂
how do I do to try out your fix postlund?

**Comment by postlund** [comment]
Yeah, these minor things are not always easy to get through 😉

Something like this should work:
```
$ python3 -m venv pyatv_tmp
$ source pyatv_tmp/bin/activate
$ pip install git+https://github.com/postlund/pyatv.git@refs/heads/playstate_fix
$ atvremote -s <Apple TV IP> playing
```
Hopefully the correct state should be printed to the terminal

**Comment by KibosJ** [comment]
> Yeah, these minor things are not always easy to get through 😉
> 
> Something like this should work:
> 
> ```
> $ python3 -m venv pyatv_tmp
> $ source pyatv_tmp/bin/activate
> $ pip install git+https://github.com/postlund/pyatv.git@refs/heads/playstate_fix
> $ atvremote -s <Apple TV IP> playing
> ```
> 
> Hopefully the correct state should be printed to the terminal

Confirmed 🙂

Amazon Prime Video, atvremote output

```Media type: Video
Device state: Playing
       Title: The Little Things You Do Together
    Position: 4/2617s (0.2%)
      Repeat: Off
     Shuffle: Off

**Comment by postlund** [comment]
Great @KibosJ, thanks for verifying 👍I'll give @Tobbe82 a chance to try as well 😉

**Comment by magnus200OK** [comment]
Hi, we've made some bug fixes in the Telia Play app so we correctly report the playback rate for live TV. (MPNowPlayingInfoPropertyPlaybackRate = 1.0 and also fixed wrong media type too).

**Comment by postlund** [comment]
Great @magnus200OK! Thanks for fixing this and reaching out 😀

**Comment by postlund** [comment]
@Tobbe82 Did you manage to verify my changes as well?

**Comment by Tobbe82** [comment]
> @Tobbe82 Did you manage to verify my changes as well?

I got an error when trying to install the fix, so haven’t been able to confirm it. Tried two methods of install, I could try tomorrow again and copy the error for you to see?

**Comment by postlund** [comment]
> > @Tobbe82 Did you manage to verify my changes as well?
> 
> I got an error when trying to install the fix, so haven’t been able to confirm it. Tried two methods of install, I could try tomorrow again and copy the error for you to see?

Yeah, let's do that. Hopefully we can figure out what the problem is!

**Comment by Tobbe82** [comment]
Installed the fix and turned the app back to the AppStore-version, can confirm the fix also works for me
Well done 👍🏼

**Comment by postlund** [comment]
That is great! I will merge the PR so we can put this issue to rest!
