### ISSUE TITLE
Guess I'm doing something wrong...?

### ISSUE THREAD

**Issue by TOAOQ** [postlund/pyatv#646]
Hi,

New to HASS and setting up my home now. When adding my Apple TV's I got them added as integrations and each has 2 entities.
The problem I have is that when trying to turn them on, the devices are not found.

in the setup, the identifiers are entered for both (had to use **atvremote** scan as the mentioned service **apple_tv_scan** is not available in HASS.

My credentials now all still have <creds> as I don't know what to fill in for none (according to the scan I have no credentials set:

**Services:**
 **- Protocol: MRP, Port: 49152, Credentials: None**
 **- Protocol: AirPlay, Port: 7000, Credentials: None**

How can I have them found by HASS?

![image](https://user-images.githubusercontent.com/40427096/81287996-08622300-9064-11ea-837a-e0a15ea74af1.png)

Log:

Logger: custom_components.apple_tv
Source: custom_components/apple_tv/__init__.py:315
Integration: Apple TV (documentation)
First occurred: 1:00:41 PM (7 occurrences)
Last logged: 1:01:21 PM
Failed to connect

Traceback (most recent call last):
  File "/config/custom_components/apple_tv/__init__.py", line 225, in _connect_loop
    await self._connect(conf)
  File "/config/custom_components/apple_tv/__init__.py", line 315, in _connect
    self.atv = await connect(conf, self.hass.loop, session=session)
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 314, in connect
    airplay = AirPlayStreamAPI(config, loop)
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 31, in __init__
    self.credentials = self._get_credentials()
  File "/usr/local/lib/python3.7/site-packages/pyatv/airplay/__init__.py", line 48, in _get_credentials
    f"invalid credentials: {self.service.credentials}"
pyatv.exceptions.InvalidCredentialsError: invalid credentials: <creds>

**Comment by postlund** [comment]
I believe you still have some old cruft left in your configuration. With this integration you should not worry about identifiers, manual scanning or credentials like before. Just add the Apple TVs from the integration page, sort be by name or by IP address (hopefully you should get suggestions in the initial dialog). Based on the logs you have managed to get empty AirPlay credentials into your configuration somehow. Do you have any yaml config in there? If you do I suggest that you remove it. Then remove the integrations and add them again.

**Comment by TOAOQ** [comment]
Thanks! Was indeed the case!
