### ISSUE TITLE
card always shows: Nothing playing

### ISSUE THREAD

**Issue by Mariusthvdb** [postlund/pyatv#647]
**Describe the bug**
have installed the beta integration successfully, and HA recognizes a media_player with the correct name.
However, this is the only thing I ever see:

<img width="478" alt="Schermafbeelding 2020-05-07 om 23 22 16" src="https://user-images.githubusercontent.com/33354141/81345920-9ddbd200-90b9-11ea-9e8d-1664ecade077.png">

**To Reproduce**

**Expected behavior**
Would have thought it to show what I am playing, Netflix, streams whatever, maybe especially the feed from the Appletv App...

**System Setup (please complete the following information):**
 - OS: [e.g. Debian] Hassio
 - Python: [e.g. 3.6.2]
 - pyatv: [e.g. 0.3.10]
- Apple TV: [e.g. Apple TV 4K tvOS 13.4] Apple TV 4K tvOS 13.4

**Additional context**
doesnt matter if I stream from my iPhone to my smart tv which has a appletv app builtin, or use my appletv directly

**Comment by postlund** [comment]
It should definitely show more than that. I will need some logs to troubleshoot though (instructions are at the bottom of the reader in hass-atv-beta repo).

**Comment by Veldkornet** [comment]
I have the same problem. Well, at first it works okay, but after a while it no longer seems to work. That include the “remote” service not working. Then I need to remove the integration and re-add to get everything working again.

**Comment by postlund** [comment]
@Mariusthvdb Any chance you can provide some debug logs for me so that I can see what's going on?

@Veldkornet Does the problem occur after putting the device to sleep or just at some seemingly random time?

**Comment by postlund** [comment]
I just pushed an update to the component using pyatv 0.7.0, can you try it out and see if it works better?

**Comment by postlund** [comment]
Please retry with latest version of Home Assistant and let me know if it works (custom component not needed).

**Comment by postlund** [comment]
@Mariusthvdb @Veldkornet Is this still a problem with the latest release? If it is, it would be great if you provided some logs for me to look at.

**Comment by Veldkornet** [comment]
Sorry for the rather late response...

I haven't noticed it recently, so I'd say it's not a problem.

**Comment by postlund** [comment]
No worries! Let's assume that it is fixed and close the issue. Thanks for reporting back! 👍
