### ISSUE TITLE
Commands take ~8s to respond

### ISSUE THREAD

**Issue by parautenbach** [postlund/pyatv#649]
I'm testing out the latest version in anticipation of an updated HASS integration. Thank you so much for the work on this. 

While experimenting with the commands, I see every command I've tried takes about 8s to respond. I'm not sure whether it's supposed to be like this or whether it's still beta code. If this isn't supposed to be the case, I'd be happy to log a bug and submit info that would help to debug this.

**Comment by postlund** [comment]
That's not how it's supposed to be. Some logs would likely help me troubleshooting. There are some instructions in the hass-atv-beta repo readme file (at the bottom).

**Comment by parautenbach** [comment]
Cool, I'll check the docs and hopefully submit you a log a bit later.

I did spot the section on logging within HASS. I should perhaps have mentioned that I'm using the `atvremote` command line tool.

**Comment by postlund** [comment]
Ah, if you are using atvremote then it's another matter. What hardware are you running on?

**Comment by parautenbach** [comment]
Right, I was wondering whether it might make a difference (guessing it establishes a new connection with a lot of handshaking overhead every time). 

I found the [logging docs](https://github.com/postlund/pyatv/blob/master/docs/documentation/atvremote.md) for `atvremote`.

**Comment by postlund** [comment]
Every time you run a command a new connection (with encryption and all that) is set up. That part is relatively fast though, even on low-end hardware. Loading all libraries into memory from a slow SD-card adds some penalty when it comes to loading times. Biggest culprit is however scanning to find the device, which is done for every command and set to 3s. If you are on the same subnet as the device and have assigned it a static IP, you can utilize unicast scanning by providing `-s x.x.x.x`. It will be a lot faster. You can also omit `--id` when doing so if you like.

**Comment by parautenbach** [comment]
Ah, thanks for that. In this case, I'm running it on a Pi 3B+ with an SD. With your suggestions, it knows a few seconds off the call. 

```
(venv) xxxxx:~/pyatv $ atvremote --debug --verbose -s www.xxx.yyy.zzz --mrp-credentials `cat credentials.txt` power_state
2020-05-11 12:13:36 DEBUG: Knocking at port 3689 on www.xxx.yyy.zzz
2020-05-11 12:13:36 DEBUG: Knocking at port 7000 on www.xxx.yyy.zzz
2020-05-11 12:13:36 DEBUG: Knocking at port 49152 on www.xxx.yyy.zzz
2020-05-11 12:13:36 DEBUG: Knocking at port 32498 on www.xxx.yyy.zzz
2020-05-11 12:13:36 DEBUG: Sending DNS request to www.xxx.yyy.zzz 
...
2020-05-11 12:13:36 DEBUG: Auto-discovered ABC at www.xxx.yyy.zzz:pppp (Protocol.AirPlay)
...
2020-05-11 12:13:36 DEBUG: Connection made to device
...
2020-05-11 12:13:37 DEBUG: Updated client
2020-05-11 12:13:38 DEBUG: Updated client
2020-05-11 12:13:39 DEBUG: Updated client
2020-05-11 12:13:40 DEBUG: Updated client
PowerState.Off
2020-05-11 12:13:40 DEBUG: ... Closing connection
2020-05-11 12:13:40 DEBUG: ... Disconnected from device: None
```

**Comment by langmeister** [comment]
Thanks for this. I'm also running a RPI 3B+.

Is there a better way, other than atvremote -s <ip> to make it even faster?  Navigation with 5s delays is painful!

**Comment by postlund** [comment]
I haven't made any benchmarks with the latest version on rpi 3, but 5s sounds an awful lot. But in order to get good performance you need some kind of daemon running in the background that maintains a persistent connection. I'm not sure how many alternatives there are for that right now, other than Home Assistant. Would be a great project for a 3rd party developer IMHO (as I focus more on the library) 👍

**Comment by langmeister** [comment]
Ok...so after 15 minutes, it stopped being discovered again.

As a test, I installed pyatv on another RPI that's plugged into the same switch.  It also cannot find it.

Baffling...

**Comment by sadanro100** [comment]
I've been having the same problem with a Homebdrige plugin. The developer behind it said he could implement something if pyatv shipped some sort of persistent state.

https://github.com/NorthernMan54/homebridge-cmd-television/issues/26
