### ISSUE TITLE
MediaPlayerDevice and RemoteDevice is deprecated Warning Messages in HA 0.110.x log

### ISSUE THREAD

**Issue by Gio76** [postlund/pyatv#654]
**Describe the bug**
The WARNING messages MediaPlayerDevice and RemoteDevice is deprecated are now showing in the HA log since upgrading to 0.110.x

**To Reproduce**
upgrade to 0.110.x and check logs

**System Setup:**
- arch | x86_64
- chassis | laptop
- dev | false
- docker | true
- hassio | true
- host_os | Ubuntu 18.04.4 LTS
- installation_type | Home Assistant Supervised
- os_name | Linux
- os_version | 5.3.0-51-generic
- python_version | 3.7.7
- supervisor | 222
- timezone | Asia/Bangkok
- version | 0.110.0b2
- virtualenv | false

**Additional context**
See below the full log:

`2020-05-14 21:26:48 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify AppleTvDevice to extend MediaPlayerEntity`

`2020-05-14 21:26:48 WARNING (MainThread) [homeassistant.components.remote] RemoteDevice is deprecated, modify AppleTVRemote to extend RemoteEntity`

**Comment by postlund** [comment]
Thanks for reporting, will try fix that soon!

**Comment by postlund** [comment]
Should be fixed by https://github.com/postlund/hass-atv-beta/pull/4 after comments have been fixed.

**Comment by Gio76** [comment]
Thanks @postlund
