### ISSUE TITLE
Support for "companion" protocol

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#655]
**What feature would you like?**
As it turns out, there can never be too many protocols. Apparently there's a protocol called "companion link", announced as the zeroconf service `_companion-link._tcp.local.`. I'm not entirely sure what all the use cases for it are, but I do know that this is the protocol used by the Apple TV widget in action center since iOS 13 (prior to that MRP was used) and it is also used to launch apps from Shortcuts. I'm especially interested in the latter in order to implement #303. I suspect that this protocol is used by Handoff and Continuity as well.

**Describe the solution you'd like**
Preferably I would like a generic implementation of the protocol next to the other ones and use that to implement #303. Perhaps there are other interesting features this can be used for as well (e.g. fetch list of installed apps).

**Any other information to share?**
Not much is written about this protocol from what I have gathered. So this is quite uncharted territories and will probably need a lot of work. I have started hacking on an implementation outside of `pyatv` as a test. It doesn't work yet, it's just a start and my intention is to lift this work in to `pyatv` and start working on support for pairing. I'm gonna share as much as possible publicly in case someone wants to help reverse engineering this protocol.

I will need some time to prepare a PR.

**Comment by postlund** [comment]
I will likely push something tonight or tomorrow as I have successfully integrated my work so far into `pyatv`. Working on some documentation now.

**Comment by postlund** [comment]
Took some additional time but is now available in #657. Enjoy!

**Comment by postlund** [comment]
I think the encryption part is more or less complete. In the sense of knowing how it works. Finalizing the implementation will take a lot more time.

Next I will continue with support in `atvproxy` so I can intercept traffic. It's gonna be great!

**Comment by tal** [comment]
Super excited for what this could enable.

**Comment by postlund** [comment]
Yeah, I am too! At least launching apps and getting the list of installed apps, but maybe more. It will be fun to explore!

**Comment by tal** [comment]
Sorry to bug but just wanting to see if there’s been any progress on this. 

Just want to know how much to prioritize some of the automation I was going to build around this.

Thanks!

**Comment by postlund** [comment]
The focus on pyatv and the Apple TV component is kinda low right now, doing some other things. It got a bit too much for long a long time (and I'm on parental leave with two kids, so not much time), so I need to focus on something else for a while to find the spark again. Current status is that I have a few outstanding issues, e.g. connection hangs after a while and MDNS discovery does not work properly. Assuming I can fix that so that feature development can start again, the companion protocol will be the first thing I will get working on. It's by far the most interesting feature and will be the main thing in the 0.8 roadmap. So I'm sorry to be the bearer of some bad news here, but I promise that this is the first thing I will start working on once I get going on pyatv again. Shouldn't be that long into the future. I currently work on improvements in the localtuya custom component. Once I'm done there I will get back on this horse.

**Comment by postlund** [comment]
I've picked up this work again and making some progress. My current focus is getting server-side support in `atvproxy`, so I can pair my phone with the proxy in order to intercept traffic. I need this as I have no idea what kind of payload is sent over the protocol.

I'm "done" (at a very hacky state) up until last SRP state (M6). The pairing request fails and I'm not sure why yet, it looks like this in the `rapportd` logs on my phone:

```
förval	09:00:55.468389+0200	rapportd	136: PairSetup next (229 bytes)
förval	09:00:55.468539+0200	rapportd	CLinkCnx-136: Pair-setup client M6 -- exchange response
    0x06 (State),           1 bytes, 06 |^|
    0x05 (EncryptedData)
        +0000: a3fc4835 ce96bc03 a5cde796 505ddbf2 |^^H5^^^^^^^^P]^^| (217 bytes)
        +0010: 630ccefd f2f5c698 188fcd99 38be25d0 |c^^^^^^^^^^^8^%^|
        +0020: 344c9c9f 1caffac4 d67dac5e 412a284a |4L^^^^^^^}^^A*(J|
        +0030: e17dd527 388f921d fde696ab adea99c5 |^}^'8^^^^^^^^^^^|
        +0040: 0c008313 e74eb83a 505b2569 5266f258 |^^^^^N^:P[%iRf^X|
        +0050: 69e18adb 1296fb43 41f989b2 a5d66f7a |i^^^^^^CA^^^^^oz|
        +0060: 538b7f67 59ef07bd b4e38164 bc4f81a4 |S^^gY^^^^^^d^O^^|
        +0070: 82b742ed d6ed5c03 b4160957 5f14c4db |^^B^^^\^^^^W_^^^|
        +0080: ddd87b86 22afef86 743fe954 e5938b37 |^^{^"^^^t?^T^^^7|
        +0090: 7ca83668 040ceb1c e86d487d 32ed1ab7 ||^6h^^^^^mH}2^^^|
        +00A0: 8c23ebe9 084928e9 bc2cbd90 9e119fed |^#^^^I(^^,^^^^^^|
        +00B0: e9cdc40b 34954a5a e50aa563 f5ea510d |^^^^4^JZ^^^c^^Q^|
        +00C0: 711b9a9c 8b7c75bc <…>
förval	09:00:55.468704+0200	rapportd	CLinkCnx-136: ### Pair-setup client state 6 failed: -6727/0xFFFFE5B9 kNotFoundErr
    0x06 (State),           1 bytes, 06 |^|
    0x05 (EncryptedData)
        +0000: a3fc4835 ce96bc03 a5cde796 505ddbf2 |^^H5^^^^^^^^P]^^| (217 bytes)
        +0010: 630ccefd f2f5c698 188fcd99 38be25d0 |c^^^^^^^^^^^8^%^|
        +0020: 344c9c9f 1caffac4 d67dac5e 412a284a |4L^^^^^^^}^^A*(J|
        +0030: e17dd527 388f921d fde696ab adea99c5 |^}^'8^^^^^^^^^^^|
        +0040: 0c008313 e74eb83a 505b2569 5266f258 |^^^^^N^:P[%iRf^X|
        +0050: 69e18adb 1296fb43 41f989b2 a5d66f7a |i^^^^^^CA^^^^^oz|
        +0060: 538b7f67 59ef07bd b4e38164 bc4f81a4 |S^^gY^^^^^^d^O^^|
        +0070: 82b742ed d6ed5c03 b4160957 5f14c4db |^^B^^^\^^^^W_^^^|
        +0080: ddd87b86 22afef86 743fe954 e5938b37 |^^{^"^^^t?^T^^^7|
        +0090: 7ca83668 040ceb1c e86d487d 32ed1ab7 ||^6h^^^^^mH}2^^^|
        +00A0: 8c23ebe9 084928e9 bc2cbd90 9e119fed |^#^^^I(^^,^^^^^^|
        +00B0: e9cdc40b 34954a5a e50aa563 f5ea510d |^^^^4^JZ^^^c^^Q^|
       <…>
förval	09:00:55.468799+0200	rapportd	CLinkCnx-136: ### Pairing failed: -6727/0xFFFFE5B9 kNotFoundErr
förval	09:00:55.468852+0200	rapportd	CLinkCnx-136: ### Pairing failed: kNotFoundErr
förval	09:00:55.468892+0200	rapportd	136: ### PairSetup client completion failed: kNotFoundErr
```
I need to figure out what to do from here.

**Comment by postlund** [comment]
Ok, so that was a minor and embarrassing error on my end (copy-paste...), so now it seems to pair correctly:
```
förval	09:25:20.513499+0200	rapportd	CLinkCnx-144: Pair-setup client M6 -- exchange response
    0x06 (State),           1 bytes, 06 |^|
    0x05 (EncryptedData)
        +0000: bcfc1136 1b19779a 49c7114a 5c49b6db |^^^6^^w^I^^J\I^^| (255 bytes)
        +0010: 46682351 3bc60ee8 910cfe41 db9c8d40 |Fh#Q;^^^^^^A^^^@|
        +0020: 05767090 6b5177ab 83b5bb62 175eb01d |^vp^kQw^^^^b^^^^|
        +0030: d545f806 8f593319 3c935109 4feadc4c |^E^^^Y3^<^Q^O^^L|
        +0040: 1185ffff 43d39da0 ef475c97 534290ea |^^^^C^^^^G\^SB^^|
        +0050: 39dbff20 d1bc7049 c2c9d0de ae7e4127 |9^^ ^^pI^^^^^~A'|
        +0060: 8f60897d dc880a54 22cc5c6a 91071287 |^`^}^^^T"^\j^^^^|
        +0070: f4401a64 accaf079 26389d6d 8578555b |^@^d^^^y&8^m^xU[|
        +0080: 82d16561 4f87b4ea f6a6a8f5 df744ae8 |^^eaO^^^^^^^^tJ^|
        +0090: 7735d05e ee386b49 96c21193 48f8d4e8 |w5^^^8kI^^^^H^^^|
        +00A0: 16bca4cc a2abc7c6 15c354c5 23e1801e |^^^^^^^^^^T^#^^^|
        +00B0: 4cf05f60 5ee79a26 816e33e0 27ab491a |L^_`^^^&^n3^'^I^|
        +00C0: c0ff6b73 2ab07342 <…>
förval	09:25:20.523570+0200	rapportd	CLinkCnx-144: Pair-setup client done -- server authenticated
förval	09:25:20.524228+0200	rapportd	CLinkCnx-144: Pairing completed
förval	09:25:20.524287+0200	rapportd	CLinkCnx-144: Open stream 'main'
förval	09:25:20.524342+0200	rapportd	144: PairSetup completed client
förval	09:25:20.524391+0200	rapportd	Client auth completion: kNoErr
```

I need to read up a bit on my previous work since I don't really know where to go from here right now. But this was certainly the biggest road block so far! 🎉

**Comment by postlund** [comment]
After some trial-and-error, I've managed to fix the verify process as well (it's what is used every time after pairing has been performed to generate a new session key). What I need to do now is to figure out how I derive encryption keys correctly and try to get that into a working state. Most code seems to be complete in `atvproxy` otherwise, so when re-encryption works everything should work.

**Comment by postlund** [comment]
I don't wanna be *that* guy, but I think I have cracked the verification and encryption process. An example of of a message that is transferred (`_systemInfo` I think) looks like this:

```
{
    "_btHP" = 0;
    "_c" =     {
        "_bf" = 0;
        "_clFl" = 128;
        "_dC" = 1;
        "_hkUID" =         (
            "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX"
        );
        "_i" = ffeeddccbbaa;
        "_idsID" = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX";
        "_pubID" = "XX:XX:XX:XX:XX:XX";
        "_sf" = 256;
        "_siriInfo" =         {
            collectorElectionVersion = 1;
            deviceCapabilities =             {
                seymourEnabled = 1;
                voiceTriggerEnabled = 2;
            };
            sharedDataProtoBuf = {length = 867, bytes = xxx };
        };
        "_stA" =         (
            "com.apple.LiveAudio",
            "com.apple.siri.wakeup",
            "com.apple.Seymour",
            "com.apple.announce",
            "com.apple.coreduet.sync",
            "com.apple.SeymourSession"
        );
        "_sv" = "230.1";
        model = "iPhone10,6";
        name = "Pierres iPhone";
    };
    "_i" = "_systemInfo";
    "_t" = 2;
    "_x" = 1354622533;
}
```
I have a few bugs and missing features in my OPACK implementation, so I have a few decoding issue. Will work on that, at least to the extent that I understand how it works.

Can't stress this enough: this is good progress, but it's gonna be a loooong time until I have something usable. Long time. It's just a lot of hacks. Gonna continue by incorporating my changes into the proxy in order to intercept what is sent between the ATV and Shortcuts.

**Comment by postlund** [comment]
So, I have made some clean ups (still lots to to) and I think I've ironed out most things in OPACK. So I will move on to the proxy implementation now, with hopes of it going quite smoothly...

**Comment by postlund** [comment]
I've managed to hack-n-slash my way forward and I think it will be a tough challenge from here. Once connected, there's seems to be an additional identify verification. Which in my case fails, as I have probably managed to stick the wrong identifiers in somewhere. The proxy does not appear in the Shortcuts list either, which I suspect is because it's not verified or something. Just speculating...

Here are some excerpts from the log (on the Apple TV).
```raw
...
förval	14:32:54.055046+0200	rapportd	1489: IdentityProofsVerify RP: yes, 0x0 < >
förval	14:32:54.057195+0200	rapportd	1489: IdentityProofsVerify HKO: kAuthenticationErr (Signature verify failed)
förval	14:32:54.057415+0200	rapportd	1489: IdentityProofsVerify check HKU: ID XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
...
förval	14:32:54.074815+0200	rapportd	FindPairedPeer found: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', HAP, 4 ms
förval	14:32:54.075900+0200	rapportd	1489: IdentityProofsVerify verify HKU: ID XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, kAuthenticationErr (Signature verify failed)
förval	14:32:54.076215+0200	rapportd	1488: Invalidating
förval	14:32:54.076491+0200	rapportd	CLinkCnx-1488: Invalidating
förval	14:32:54.076638+0200	rapportd	CLinkCnx-1488: Abort reads: kCanceledErr (Invalidated (I))
förval	14:32:54.076957+0200	rapportd	1488: ### Receive failed: kCanceledErr (Invalidated (I))
...
```

The identifier `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` is part of the response from the Apple TV. What it actually means and if it's possible to create an identifier for pyatv is unclear to me. Maybe this part isn't really needed for my main cases, e.g. launching apps, but since I don't know what to send... It becomes tricky.

**Comment by postlund** [comment]
Woah, I just tried some stuff, this in particular:

```
{"_i": "_launchApp", "_x": 123, "_t": "2", "_c": {"_bundleID": "com.netflix.Netflix"}}
```

And it actually opened Netflix. Just like magic. Will have to play around with this a bit more, but definitely exciting!

**Comment by postlund** [comment]
This one is pretty fun:
```raw
>> {"_i": "FetchLaunchableApplicationsEvent", "_x": 123, "_t": "2", "_c": {}}

<< {'_c': {'com.apple.podcasts': 'Podcaster', 'com.apple.TVMovies': 'Filmer', 'com.apple.TVWatchList': 'TV', 'com.apple.TVPhotos': 'Bilder', 'com.apple.TVAppStore': 'App\xa0Store', 'se.cmore.CMore2': 'C More', 'com.apple.Arcade': 'Arcade', 'com.apple.TVSearch': 'Sök', 'emby.media.emby-tvos': 'Emby', 'se.tv4.tv4play': 'TV4 Play', 'com.apple.TVHomeSharing': 'Datorer', 'com.google.ios.youtube': 'YouTube', 'se.svtplay.mobil': 'SVT Play', 'com.plexapp.plex': 'Plex'}, 'com.MTGx.ViaFree.se': 'Viafree', 'com.apple.TVSettings': 'Inställningar'}
```
So I can list installed apps as well as launch them now, pretty cool I would say 😎

**Comment by postlund** [comment]
`FetchUserAccountsEvent` seems to fetch profiles on the device and can probably be used with `SwitchUserAccountEvent` to switch user. 

`ToggleReduceLoudSounds` and 
`ToggleSystemApperance` also seems interesting.

**Comment by crxporter** [comment]
I just gotta say, this is fun to watch. I'm excited to see what else you find.

**Comment by postlund** [comment]
Yeah, it's really exciting to see where this leads. Getting app list and launching apps is the bare minimum of what I want to achieve to start with. On good track with that, it's just the matter of having time to complete it.

**Comment by postlund** [comment]
A few additional commands:

* Sleep - `_i`=`hidC`, with `_c` = `{"_hBtS": 2, "_hidC": 12}`
* Wake- `_i`=`hidC`, with `_c` = `{"_hBtS": 2, "_hidC": 13}`

They seem to work as expected, so might replace current MRP hack at some point.

**Comment by postlund** [comment]
If everything goes smoothly, I will hopefully have something that can be tested out by next week. A couple of volunteers for beta testing would be great 👍

**Comment by postlund** [comment]
The documentation part is pretty much done at the stage where it can be called "good enough". I have some clean ups left that I want to do, but after that I should be able to merge the protocol implementation. After that I can start working on an initial draft of the API, hopefully by tomorrow with Thursday being target for something testable.

**Comment by postlund** [comment]
I just pushed all my work so far (#657). Need to work it a bit more, but it's getting closer to something useable.

Currently thinking a bit about the API. This is
My idea so far:

```python
class Apps:
    async def launch(self, bundle_id)
    async def fetch_list(self):
    def active(self)
```
Will let these mature a bit during my sleep time.

**Comment by crxporter** [comment]
Any chance there's a magic push message to help with #958 ?

🤞

**Comment by postlund** [comment]
Unfortunately no, I don't think so. First and foremost, I need to figure out how to properly set up a "session". Seems like the Apple TV drops the connection due to timeout otherwise. After that I need to look at how to subscribe to events (and implement support for that). It's a bit tricky and I don't really need any of that to support app launching (which is my goal for now). I will just use Companion for one-shots, i.e. connect, do what I need and then disconnect. I will leave other things for the future.

The reason why I suspect it won't help is that the protocol features seems to be built on top of other services, like mediaremoted. So data comes from the same place as MRP, which shouldn't give me any additional information. I can of course be wrong (hopefully), but that's what I know at the moment.

**Comment by crxporter** [comment]
Cool. I'll keep watching. 

Your comment about proper "wake" and "sleep" commands got me wondering if maybe there was something for push. No worries, carry on!

**Comment by postlund** [comment]
Yeah, I agree that it sounds somewhat promising. Maybe it can be achieved some day, we'll see.

**Comment by oviano** [comment]
Does anyone know if the Companion protocol is able to transmit pan/swipe gestures directly to a connected Apple TV? i.e. the X/Y translations that you can usually receive in an objective C application in response to the gesture recognisers/touch events?

I know pyatv does not support this, but the native iOS Apple TV virtual remote app is able to convert the touch events and send them across as these raw positions for the Apple TV to interpret. You can see evidence of this by going to the Apple TV Home Screen and swiping slowly on the iOS remote app and observing small animation/movement of the highlighted app on the Apple TV.

I turned off bluetooth and it still works, so it must be sending these co-ords over IP and not directly via bluetooth or something....so maybe Companion Link has this capability but we haven't yet discovered it yet?
