### ISSUE TITLE
Bug with Repeat Management

### ISSUE THREAD

**Issue by Wators** [postlund/pyatv#662]
**Describe the bug**

First thank you for your work.

I am using version 0.6.1. and I encounter a bug with the management of repeat with the ATV4 while on the ATV3, no problem.

I can explain myself by this table :

ATV3 |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  | On ATV 3 Screen by apple remote |   | In Playing PyATV |   | Command PyATV |  
  |   |   |   |   |   |  
  | Repeat All | <=> | Repeat All | <=> | set_repeat = 2 |  
  | Repeat 1 | <=> | Repeat Track | <=> | set_repeat = 1 |  
  | Repeat Off | <=> | Repeat Off | <=> | set_repeat = 0 |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
ATV4 |   |   |   |   |   |  
  | On ATV 4 screen by apple remote |   | In Playing PyATV |   |   |  
  | From |   | to |   |   |  
  | Repeat All | <=> | Repeat All |   |   |  
  | Repeat 1 | != | Repeat All |   |   |  
  | Repeat Off | != | Repeat Track |   |   |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
  |   | in the other direction |   |   |  
  |   |   |   |   |   |  
  | Command PyATV |   | In Playing PyATV |   | On ATV 4 |  
  | From |   | to | **but**  | to |  
  | set_repeat = 2 | = | Repeat All | != | Repeat Track |  
  | set_repeat = 1 | = | Repeat Track | != | Repeat Off |  
  | set_repeat = 0 | = | Repeat Off | != | stop musique |  
I hope my information is clear.

**To Reproduce**

just playing with appleTV remote and see on aTVremote playing

**Expected behavior**

I would like the management of repeat to be the same as for ATV 3

**System Setup (please complete the following information):**
 - OS: Linux Host-006 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux [9.12]
 - Python: 3.7.3
 - pyatv: 0.6.1
- Apple TV: Apple TV 3 "3 ATV SW 8.4.4"
                    Apple TV 4 "4 tvOS 13.4 build 17L256"

**Additional context**

**Comment by postlund** [comment]
I think I understand what you mean and I will look into it. It should work the same for both protocols, so likely a bug. Thanks for reporting!

**Comment by postlund** [comment]
Also, related to #645.

**Comment by postlund** [comment]
Ok, so I have the repeat state definition wrong. I will fix that, which should fix this problem.

**Comment by postlund** [comment]
Pleas try out #685 and let me know if it works!

**Comment by NebzHB** [comment]
Sorry for the delay, i'm trying and come back to you but it seems promising !

**Comment by NebzHB** [comment]
For your information, we are embedding your library into the Jeedom french domotic solution 
![image](https://user-images.githubusercontent.com/28622481/84230683-db82af00-aaec-11ea-89a0-03303d2467ca.png)

**Comment by postlund** [comment]
Yeah, I actually stumbled upon the thread on your forums. Don't speak French so didn't understand much though 😉 Just keep posting issues when you find them and let me know if you need integration help or miss something!

**Comment by postlund** [comment]
Any chance to get this verified so I can merge the PR?

**Comment by NebzHB** [comment]
on my side it's ok.

and you @Wators  ?

**Comment by Wators** [comment]
It’s ok for me too.

**Comment by postlund** [comment]
Great, then I will merge the fix!
