### ISSUE TITLE
Unable to run atvremote after installing

### ISSUE THREAD

**Issue by 33masterman33** [postlund/pyatv#663]
I installed pyatv with the pip3 install command but am having problems running it. I found the directory where it installed to verify all the files are there but when I try to run atvremote the command doesn't exist. Help would be appreciated.

**Comment by postlund** [comment]
Are you installing globally in the system or with a virtual environment? I recommend the latter.

**Comment by 33masterman33** [comment]
> Are you installing globally in the system or with a virtual environment? I recommend the latter.

I'm not sure. I'm not really that familiar with installing python modules. Some extra information I forgot to include is my python version is 3.7.3 and I am running Raspbian.

**Comment by postlund** [comment]
Run:
```shell
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install pyatv
```
This will create a virtual environment in a directory called `venv` (where you are currently standing) and install pyatv in it. You should be able to run atvremote now.

When you launch a new shell you will have to run the second command again (`source ...`) or the command will not be found.

**Comment by 33masterman33** [comment]
@postlund Thanks it works now :)
