### ISSUE TITLE
Home Assistant Plugin - Power management support - Beta Testers needed.

### ISSUE THREAD

**Issue by stickpin** [postlund/pyatv#672]
Hi All, (FYI @postlund)

We are looking for beta testers to test the Power management support for Home Assistant Plugin.

**Power management functionality:** 
- Current Apple TV power status (On/Off).
- To turn On and Off your Apple TV.
<img width="498" alt="Screenshot 2020-05-30 at 11 29 08" src="https://user-images.githubusercontent.com/630000/83324945-d447df80-a268-11ea-8c0e-af4e7900800c.png">

**Pre-requisites:**
- Apple TV Gen 4 or Apple TV 4K with tvOS 13+
- Home Assistant v0.110+
- HACS

PR already submitted to the main repo: https://github.com/postlund/hass-atv-beta/pull/5

To install the plugin, add custom repo to HACS: https://github.com/stickpin/hass-atv-beta
Once plugin installed restart HASS and pair your Apple TV.
Once Apple TV paired check "Allow to Home Assistant to use power management functionality" in the integration options.
<img width="503" alt="Screenshot 2020-05-30 at 11 09 35" src="https://user-images.githubusercontent.com/630000/83324540-2f2c0780-a266-11ea-9b39-dcb07c4829e7.png">
<img width="483" alt="Screenshot 2020-05-30 at 11 09 48" src="https://user-images.githubusercontent.com/630000/83324545-35ba7f00-a266-11ea-8321-947bdd2b4a90.png">

Please report in this thread if you found some issues.

Thanks in advance!

**Comment by toby17780** [comment]
Hey @stickpin, 
I tried it out and it works how directly from pyatv. Really nice!

But I found an problem:
When I play a song, in HA frontend I see the three buttons back, pause and forward. Normally everything ok.
After turn_off and turn_on this buttons remain, but the playing song is paused.
And in this situation, I cannot bringt the song playing. (no play button)
It works, when I pause the song before i turn_off the ATV. 

I hope you can reproduce this.
Thank you! ;-)

**Comment by fenderle** [comment]
Works perfect for me. When will it be merged?

**Comment by beliy1985** [comment]
Works perfect for me

**Comment by vincentto13** [comment]
Hi I've tried https://github.com/stickpin/hass-atv-beta and I'm not seeing the option for enable power management functionality. I must say I'd be happy to see this option working, Can I somehow verify why I'm not seeing this option in integration configuration?

**Comment by vincentto13** [comment]
After some tweaks - mostly to my environemnt I've found it working, but for some reason when in most cases when I turn on AppleTV through UI. The only option I have is a Play button. I'm not able to turn off the device from Dashboard media player card, but I can do it calling media_player.turn_off service call

**Comment by chrisaljoudi** [comment]
@postlund out of curiosity, now that the core HA integration uses `pyatv`, are you open to having power management support exposed there?

Happy to help if there are needed things on the critical path, or also happy to submit a PR on the integration side if you’re open to that.

**Comment by postlund** [comment]
@chrisaljoudi Sure, that was sorta the plan all along. The code merged to HA is a bit different (simplified) compared to the beta component, so some mangling is needed to get current code up to standards. Or maybe a rewrite. You are more than welcome to submit a PR for it, I encourage it 👍 But remember to make it an optional feature (just like current PR does) as it will probably not work for everyone .

**Comment by postlund** [comment]
I think we can close this in favor of this now:

https://github.com/home-assistant/core/pull/51520
