### ISSUE TITLE
MediaPlayerEntity

### ISSUE THREAD

**Issue by ramondunker** [postlund/pyatv#675]
**Describe the bug**
Home Assistant does not allow me to setup Apple TV with the custom component after pyatv 0.6.1 update 3. It gives me the following error:

Unable to prepare setup for platform apple_tv.media_player: Platform not found (cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)).

**To Reproduce**
Select Apple TV from integrations and add it.

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Raspbian 10
 - Python: Latest
 - pyatv: Latest
- Apple TV 4K tvOS 13.4.5

**Comment by postlund** [comment]
I believe that you need Home Assistant 0.110 for this to work. I should have stated that, sorry about that!

**Comment by postlund** [comment]
Did you manage to upgrade and get it working?

**Comment by ramondunker** [comment]
I have indeed! But I can't seem to find where I can add your repo to HACS.

**Comment by postlund** [comment]
Try navigating to HACS -> Integrations > Three dots in upper right corner -> Custom repositories, perhaps?

**Comment by ramondunker** [comment]
Thanks. I didn't find it yesterday.
