### ISSUE TITLE
support for long key press

### ISSUE THREAD

**Issue by sooslaca** [postlund/pyatv#71]
Would it be possible to code in support for long key presses? eg long press "top_menu" would bring up the shutdown options on ATV4. Thank you, project is awesome!

**Comment by postlund** [comment]
AFAIK there is no "modifier" for making a short or long press. Each press is its own command and it's up to the client (e.g. Remote app) to determine what that press means command-wise. I've tried to trigger the corresponding "long press" for menu on my ATV3 to put it in standby, but it doesn't seem possible to mimic that in the app (only on the real, physical remote). It might be different on the ATV4, but as I don't own such a device I'm not able to sniff that traffic I'm afraid. But I'm all for implementing support for it if someone figures out the command.

**Comment by postlund** [comment]
It was not my intention to close the issue...

**Comment by sooslaca** [comment]
I tried to capture on ATV4 but that device speaks MediaRemoteTV protocol on port tcp/49152 which looks to be encrypted. Also I cannot force tcp/3689 so not sure how I can capture it. Anyway thanks for checking it on ATV3, I believe DAAP - as you said - not capable to send this command, so lets close thread.

**Comment by postlund** [comment]
Yeah, I kind figured that. There was some progress made on that protocol a while back over at https://github.com/jeanregisser/mediaremotetv-protocol, but I'm not sure how complete it is. I'm waiting for the 5th gen device and once I get that I might look further on MediaRemoteTV. But until we know more, lets close this as you said.
