### ISSUE TITLE
atv remote for home assistant

### ISSUE THREAD

**Issue by ranrinc** [postlund/pyatv#710]
How do I setup the remote for home-assistant. I only have remote.atv but there is nothing. Is there a sample yaml setup for the remote so I can have buttons? Thanks

**Comment by postlund** [comment]
The remote component in itself is pretty dumb. It's just a service you can call to send a command. You have an example in the upcoming documentation:

https://github.com/home-assistant/home-assistant.io/blob/8399c0177ed9ef67fd8515b3535cd18c98857b52/source/_integrations/apple_tv.markdown#remote

**Comment by ranrinc** [comment]
thank for the explanation @postlund

**Comment by postlund** [comment]
Great! I guess we can close this issue?
