### ISSUE TITLE
how to add new device?

### ISSUE THREAD

**Issue by Mariusthvdb** [postlund/pyatv#716]
**What to investigate**

not sure if this is the correct thread, so point me to it if not please, but I want to know how to proceed adding a new device after the integration has been installed alright.

Only way I found it to work now, is to click on the orange Plus sign in the integrations page, select AppleTv, have it 'install' the integration, which of course is already there, and then it finds the newly activated Apple TV.

**Expected outcome**

Simply add a new device, by clicking add new device....
sorry if this have been answered elsewhere, I just exploring this in the new 0.111.1 HA setup
thanks!

**Comment by postlund** [comment]
I'm not really sure what the problem is here? You add new devices exactly like you explain, via + on the Integrations page. If everything works as expected the config flow should provide a list of available devices. Otherwise just enter device name or IP address in the input box. You can d as also use yaml right now, but I think I will have to remove support for that due to policy of dropping support for yaml for new integrations.

**Comment by Mariusthvdb** [comment]
well,  the plus sign if for adding an integration, not for adding a device of an already installed integration.
This is what happens:
<img width="501" alt="Schermafbeelding 2020-06-13 om 12 20 36" src="https://user-images.githubusercontent.com/33354141/84566344-9373be80-ad70-11ea-9a4f-2ee7637d75a1.png">

after clicking the orange Plus button:

<img width="508" alt="Schermafbeelding 2020-06-13 om 12 20 49" src="https://user-images.githubusercontent.com/33354141/84566362-b0a88d00-ad70-11ea-8244-259b9d3ab2d5.png">
It wants to re-install the integration.... while it should only find a new device.

It would be more appropriate if we could add a new device by clicking an option button on the integration card, eg like on this integration:

<img width="271" alt="Schermafbeelding 2020-06-13 om 12 22 28" src="https://user-images.githubusercontent.com/33354141/84566379-ccac2e80-ad70-11ea-86ef-f1ea4bb00ffd.png">

Would make it more obvious imho?

**Comment by postlund** [comment]
No, that's not really how it works. The plus-sign is to add a new device of a given integration. That the integration is being installed simply means that home Assistant installs any requirements that the integration has, I.e. pyatv in this case. It will always try to install requirements first (even if it is installed) and then start the config flow to add the device, that's just how it works. If a flow for adding a new device is not started after the "installation screen", then something must have failed and you should check the logs.

The options button is to change options for the integration. I can only add simple options there, not something to add a device. What buttons are available here are decided by the frontend design.

**Comment by Mariusthvdb** [comment]
ok, thanks for confirming. Glad I can try the integration like this, lets not under stress that ;-)

any lookout for official integration yet? Would really be very nice indeed.

**Comment by postlund** [comment]
Yeah, it's quite convenient to allow testing as custom component 😊

I've had a PR out for a few months, but it's big so it takes time. I also don't stress it too much as I would like to have pyatv 0.7.0 out the door for that as a lot of improvements have been made since 0.6.1.

**Comment by postlund** [comment]
I guess this can be closed now, unless you have any other issues?

**Comment by Mariusthvdb** [comment]
of course, thanks, closed!
