### ISSUE TITLE
Launching tvOS apps

### ISSUE THREAD

**Issue by technicalpickles** [postlund/pyatv#73]
Does this support launching application on an AppleTV? I'm guessing it does not currently, but didn't see this said one way or the other in the README and figured I'd ask.

The use case I am thinking of is to update [homeassistant](https://home-assistant.io/)'s AppleTV support to expose selecting different apps as 'input', so you can do automation around launching apps. For example, make a switch "HBO" that you can control from Alexa, and it handles launching the HBO Go app.

**Comment by robbiet480** [comment]
There's no way to currently through the Apple Remote app so unless that changes or someone seriously reverse engineers the API I don't expect this to happen anytime soon.

**Comment by postlund** [comment]
As @robbiet480 says, this is (probably) not supported by the DAAP-protocol, so it is not possible to do I'm afraid. Maybe it's possible with MediaKit, but that's only a guess and I don't that that's fully reverse engineered yet.

**Comment by technicalpickles** [comment]
Thanks for the info!

Feel free to close as you prefer. Only thing I might suggest is to have a note in the README that it's not supported, but up to you.

**Comment by postlund** [comment]
Sure, that can be clarified. I'll add it when I prepare for the next release. Closing issue for now.
