### ISSUE TITLE
Idle state on Apple TV 4

### ISSUE THREAD

**Issue by mKeRix** [postlund/pyatv#74]
Hey there,

I did some more digging regarding home-assistant/home-assistant#6293 (card flickering because image cannot be found). I saw that you utilize `pyatv.const.PLAY_STATE_NO_MEDIA` to tell HASS that the Apple TV is idle - however on my Apple TV 4 it actually never goes to this state. This is the state when nothing is playing (home menu):

```
state: paused
media_title: No title
media_duration: 0
entity_picture: /api/media_player_proxy/media_player.apple_tv?token=token&cache=cache
supported_features: 21427
media_position: 0
media_content_type: movie
media_position_updated_at: 2017-03-26T12:39:33.996764+00:00
hidden: true
friendly_name: Apple TV
```

This state causes HASS to think that there is artwork available (the artwork of the 'paused movie No Title'), causing the card to flicker while it tries to update and fails.

I __think__ that this is something that can be fixed from this underlying library, however I am not quite sure where to start here. I haven't quite understood all of the inner workings of this library, so please correct me if I'm wrong!

**Comment by postlund** [comment]
Hi!

Yes, I think you are right and I have noticed similar behavior too (regarding state). The "no media" state can happen for short intervals, usually it passes by this state when starting a YouTube clip for instance. This is not a problem with pyatv per se, but a a change that should be made in Home Assistant to look at some other state.

I have some changes laying around locally that I will submit when I have some time. But I would like to finish of pairing support first and also verify button press support.

**Comment by postlund** [comment]
Hopefully fixed by https://github.com/home-assistant/home-assistant/pull/7189. Will close once I get confirmation from some users.

**Comment by mKeRix** [comment]
Did the update last night - works great! Thank you so much for your work on this component again.
