### ISSUE TITLE
Anyone running tvOS 14 beta?

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#741]
**What's on your heart?**
Anyone running tvOS 14 beta and able to try if pyatv (or the Home Assistant integration) works with it? Would be nice to catch any potential issues early.

**Comment by kdvlr** [comment]
I do.. My lights automation does not work properly. At an initial level, it looks like sometimes, when playing media, it shows as 'paused' which is throwing off my automations. Will look at it further and let you know what I find.

**Comment by postlund** [comment]
Ok, good to know! If you provide me with some logs I can have a look as well (feel free to email me if you prefer). Did it work prior to upgrading to tvOS 14?

**Comment by BVGorp** [comment]
i have tvOS 14 too. for me it seems to work nicely. i have triggers on idle playing and pauzed and they all are working fine.
With the upgrade to 0.112.1 i had to remove, reboot and reinstall the plugin

**Comment by kdvlr** [comment]
It seems to be working ok for me now.

**Comment by postlund** [comment]
Ok, great! We should still be aware that this is beta, so things might break because of that as well. What I'm mainly after is changes to the protocol.

**Comment by kdvlr** [comment]
I don’t know if this is changes to the protocol, but there seems to be a lag on pushing state from Apple TV to Home assistant.

Sometimes, I see a bunch of changes at the same time stamp.

**Comment by postlund** [comment]
@kdvlr Can you poo provide some logs? Don't think it's related to tvOS 14, but interesting nonetheless.

**Comment by Dodoooh** [comment]
@postlund i have risked it and updated an Apple TV to tvOS14, it worked for a short time. but now it doesn't work anymore. what logs would be helpful to you? which one exactly?

**Comment by postlund** [comment]
@Dodoooh I suggest these:

```yaml
logger:
  default: error
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

**Comment by Dodoooh** [comment]
> @Dodoooh I suggest these:
> 
> ```yaml
> logger:
>   default: error
>   logs:
>     pyatv: debug
>     custom_components.apple_tv: debug
> ```


I uploaded it here
https://pastebin.com/NBhFysJm

first it worked, then I got nothing delivered back.But I can still start the music in home assistant, but the control field doesn't change it's always blue as usual. 
Now after a while it works again...

Feel free to tell me if you want me to run a scenario that would be useful to you. 
Thank you very much for your work, a great integration!

**Comment by postlund** [comment]
I don't think that is related to tvOS 14, sounds like the issues other people are already seeing. But great to have some logs, I will have a look at them! When you say that you can "start the music", do you mean that the remote control works? Or airplay?

**Comment by jimdhope** [comment]
I've been unable to pair the two Apple TVs I get through the first pin but the AirPlay pin does not show up on either screen.

**Comment by postlund** [comment]
@jimdhope Can you verify if second point at https://pyatv.dev/support/troubleshooting/ works?

**Comment by jimdhope** [comment]
> @jimdhope Can you verify if the second point at https://pyatv.dev/support/troubleshooting/ works?

So I've experimented after following the instruction at the link above. It turns out that I need to disable the password set in the Allow Access menu under AirPlay and HomeKit. Thanks for the help.

**Comment by jddayley** [comment]
Thanks for the great work here.   I have 3 apple tvs.  The one with tv OS 14 does not work reliability.  To make it work, I recover it by restarting the appletv.  This happens at least once a day.  Happy to share debug logs.

**Comment by postlund** [comment]
I think most issues related to tvOS 14 has been sorted now and the remaining bug fixes will be part of next pyatv release. Will close this now.
