### ISSUE TITLE
add delay between commands in atvremote

### ISSUE THREAD

**Issue by regissg** [postlund/pyatv#742]
**What feature would you like?**
I want to use atvremote with a suit of commands to launch a specific app. 

**Describe the solution you'd like**
I would like the option to add short delays between some commands to take into account the appletv latency.  For example: `atvremote -i 00:11:22:33:44:54 home 1000 right right select 1500 down select`
where the number represent a delay in millisecond

**Any other information to share?**
Today I have to use multiple instances of atvremote to add delays but then I have a fixed latency of at least 3 sec at each instance

**Comment by postlund** [comment]
Sure, I've thought about that too. I can add support for it later tonight I think. It will look like:

    atvremote ... left delay=1000 select

As that is easiest to do.

**Comment by regissg** [comment]
Thanks for your quick reaction. This will be really great

**Comment by postlund** [comment]
Now you can give #743 a spin 😊

**Comment by regissg** [comment]
Thanks,

I am not expert in Github, where could I find v0.7.0?

**Comment by postlund** [comment]
It is only available as a PR right now, so you need to uninstall your current version and follow the latter instructions here:

https://pyatv.dev/documentation/#specific-branch-or-a-pull-request

Just replace <id> with 743.

**Comment by regissg** [comment]
I have installed 743 and delay is working as expected. Many thanks for that. I will use it more extensively and let you if I found problems

**Comment by postlund** [comment]
Great, thanks for testing! 👍 Will merge this!
