### ISSUE TITLE
Transform command lines into a script

### ISSUE THREAD

**Issue by oculist37** [postlund/pyatv#751]
**What's on your heart?**
Hi,

I am a newbie. I try to send different commands at a precise time. I succeed in installing pyatv, pairing and sending atvremote commands (very cool by the way).

Now, I would like to transform theese commands into a script, so that I can launch the script at a precise date & time. I first naively put the different commands in a script. But I always have a syntax error : 
`atvremote --id mon_appleTV home
                   ^
SyntaxError: invalid syntax
`

I try to declare via a function and without. Still the same. My Python's knowledge is very new and light. Am I in the good direction ? Is it possible to do so ?

Thanks for your help.

**Comment by postlund** [comment]
Hey and thanks for using `pyatv`! 😀

I believe that you are mixing shell commands and python. You are basically trying to call `atvremote` in python, which is not gonna work. You can do something like this:

```shell
#!/bin/bash

atvremote --id mon_appleTV home
```

Save it as something, e.g. `script.sh`, add the exec flag with `chmod +x script.sh` and run with `./script.sh`. Hopefully that should work better!

**Comment by oculist37** [comment]
Thanks for your quick answer which works marvellously !

Thanks again.

I’m going to work on this, trying to get some inputs from the apple TV and make a smarter script.

Do you know if it’s possible to get which icon is highlighted in the main menu ? or to select the app « computers » of the family sharing ? As you can understand, I’m trying to play a movie from a library shared on the network. And I would like to know if there is a way to be sure I am in the good menu, in the good playlist before playing the movie.

I am going to dig little.

Thank you very much one more time for your answer, it helps me a lot for my beginning.

Have a pleasant day.

**Comment by postlund** [comment]
Great! 👍

Unfortunately no, I don't think that's possible. At least not with the protocols I use (that I am certain of). I would expect such functionality only exists in development context, in case someone wants to write tests on a functional level. But there's really no point in providing a generic API for it.

**Comment by postlund** [comment]
Anything else I can help you with or can we close the issue?

**Comment by oculist37** [comment]
Thanks, 

Your tips were very useful. 

One more thing, if I can ask, how can you know which version of pyatv is installed ? I’ve tried several command lines like "pyatv -v", "atvremote -v" but it doesn’t work. And the next question is how to upgrade to the next version when it will be available.

**Comment by postlund** [comment]
Sure! You get the installed version with `atvremote --version` and upgrade with `pip3 install --upgrade pyatv`.

**Comment by postlund** [comment]
A new version will land later tonight, so you can test with that if you like.

**Comment by oculist37** [comment]
Tanks again for your quick answers. 

I’m looking forward for the new upgrades.  

Great job

**Comment by postlund** [comment]
Glad to help 👍 Version 0.7.0 has now been pushed to pypi so it should be installable!

**Comment by postlund** [comment]
Will close this now, please write a new issue if you need further assistance 👍
