### ISSUE TITLE
Any reason PyATV (via hass atv beta) would trigger 2FA?

### ISSUE THREAD

**Issue by rothomas** [postlund/pyatv#753]
I set up the beta AppleTV integration yesterday, and everything seems to be working, except now all my apple devices get 2FA allow/deny popups every thirty minutes.  It doesn't seem like the integration ought to be responsible, because it doesn't require my iCloud credentials at all (and thus I don't have even the kludgey way of passing in a 2FA code along with the password), but sure enough if I shut down HA just before the 30m mark, then I don't get the alert, but then immediately get it when starting up HA again (and back to every 30 minutes after that), and adding the AppleTV integration is the only change I've made.

Any help understanding why this is happening?  Or even better, a workaround that isn't "turn off 2FA"?

**Comment by postlund** [comment]
No idea why this would happen as the integration (nor pyatv) utilize any keychain. Never heard about anyone seeing this either. Perhaps someone subscribed to this project has a clue?

**Comment by rothomas** [comment]
On further investigation, this was coincidence.  Seems the iCloud integration somehow lost auth around the same time I installed HACS and the Apple TV beta, and it was responsible for the popups.

**Comment by postlund** [comment]
I was just about to ask if you used that integration. But I guess I got my answer 😉
