### ISSUE TITLE
Remote Control Volume Commands Not Working

### ISSUE THREAD

**Issue by celawlor** [postlund/pyatv#755]
I made a UI that calls the volume_up and volume_down commands and they are not changing the volume.

Here is my button:

              - type: button
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    command: volume_up
                    entity_id: remote.master_bedroom
                hold_action:
                  action: none
                show_icon: true
                show_name: false
                entity: remote.master_bedroom
                name: Volume up
                icon: 'mdi:volume-plus'

I expected that pressing this button would behave the same as pressing the volume up button on the Apple TV remote and increment the volume level by 1.

**System Setup:**
 - OS: Linux
 - Python: 3.7.7
 - pyatv: 0.6.1 update 4
- Apple TV: Apple TV 4K tvOS 13.4.6.    -and-
- Apple TV: Apple TV non-4K tvOS 13.4.6

Apple TV 4K --> Samsung TV --> Samsung Soundbar (optical)
Apple TV --> Samsung TV --> Bose Solo Soundbar (optical)

Both apple remotes are able to control both of the soundbars without issue as they are configured in the apple TV settings.

**Comment by postlund** [comment]
When you say the "Apple remote", do you mean the physical remote? Because those use the IR blaster when changing volume. You must enable CEC on your devices for these services to work. If volume up/down on your iOS device works while using the Remote app or widget, then it should work here as well.

**Comment by celawlor** [comment]
I do mean the physical remote.  CEC is definitely enabled and has been working fine for years.  When you say "remote app or widget" what does that mean?  I have an iPad that I know has an apple TV remote when I pull down from the top of the screen.  Is that what you are referring to?  If so, there are no volume buttons on that for the two Apple TVs I tested. If it is something else, I could definitely use some hints on finding and trying it!

**Comment by postlund** [comment]
Yeah, the widget is the one you find in action center (when you pull down from the top). The app is the one you install for App Store. If volume control is supported for MRP, you should be able to change the volume by using the physical volume buttons while either of them are open. Does that work?

**Comment by celawlor** [comment]
The widget and the app did not have volume buttons.  I also checked the config for the Apple TVs and you were right, they were configured via IR.  I had another Apple TV that I checked it's configuration for and it was via HDMI CEC and, sure enough, the volume buttons worked like a champ! Thanks for the help on this (and for a great integration)! If you need any help testing in the future, let me know. I have 5 of these things...
