### ISSUE TITLE
Could not integrate ATV4 (unexpected error)

### ISSUE THREAD

**Issue by cpohli** [postlund/pyatv#766]
First: Thanks for all the efforts with this!

I just wanted to add my ATV4 (latest OS, not beta) to my (latest version) HA.
I installed the component via HACS, went to "Integrations", two of my ATVs were found.
After picking my ATV4 (found with name and IP) i see this:

```
Logger: custom_components.apple_tv.config_flow
Source: custom_components/apple_tv/config_flow.py:272
Integration: Apple TV (documentation)
First occurred: 18:39:24 (3 occurrences)
Unexpected exception
```

```
Traceback (most recent call last):
  File "/config/custom_components/apple_tv/config_flow.py", line 272, in async_begin_pairing
    zeroconf=zeroconf_instance,
  File "/usr/local/lib/python3.7/site-packages/pyatv/__init__.py", line 103, in pair
    return handler(config, await net.create_session(session), loop, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'zeroconf'
```

Any idea what's happening here?

Thank you very much!

**Comment by cpohli** [comment]
Ah, great. Thank you! :-)

**Comment by postlund** [comment]
Just pushed fix!

**Comment by cpohli** [comment]
@postlund Jippie! Works like a charm. Just had to push in 2 PINS (ATV and Remote) and everything is up and running!
Now i will continue to Automations and so on in Homa Assistant.
Thnaks you so much again for the work you put into this! :-)
