### ISSUE TITLE
Apple TV 4K does not return an identifier other than MAC address

### ISSUE THREAD

**Issue by a7ypically** [postlund/pyatv#772]
Hi,

I have three Apple TVs two of them 4K and one an older version.
I'm having an issue with just one of the 4K ATVs. After a while, scanning the device does not return the longer identifier. After I reboot the ATV it works again.

I'm using HASS and so it disconnects from the ATV and can't find the device until I reboot it (the ATV).
I tried scanning from a different computer using the latest master but I still don't get an identifier.

Any tips on how to debug the issue?

Here's the output when I don't get an identifier:

```
atvremote --scan-hosts 192.168.8.26 --debug scan
2020-07-16 10:41:21 DEBUG: Knocking at port 3689 on 192.168.8.26
2020-07-16 10:41:21 DEBUG: Knocking at port 7000 on 192.168.8.26
2020-07-16 10:41:21 DEBUG: Knocking at port 49152 on 192.168.8.26
2020-07-16 10:41:21 DEBUG: Knocking at port 32498 on 192.168.8.26
2020-07-16 10:41:21 DEBUG: Sending DNS request to 192.168.8.26 (Data=xx)
2020-07-16 10:41:21 DEBUG: Received DNS response from 192.168.8.26 (Data=xx..)
2020-07-16 10:41:21 DEBUG: Cleaning up after UDNS request
2020-07-16 10:41:21 DEBUG: Cleaning up after UDNS request
2020-07-16 10:41:21 DEBUG: Cleaning up after UDNS request
2020-07-16 10:41:21 DEBUG: Auto-discovered Upstairs Apple TV at 192.168.8.26:7000 (Protocol.AirPlay)
2020-07-16 10:41:21 DEBUG: Auto-discovered Upstairs Apple TV at 192.168.8.26:55183 (Protocol.MRP)
Scan Results
========================================
       Name: Upstairs Apple TV
   Model/SW: 4K tvOS 13.4.6 build 17L570
    Address: 192.168.8.26
        MAC: C8:XX:XX:XX:XX:XX
 Deep Sleep: False
Identifiers:
 - C8:XX:XX:XX:XX:XX
 -
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None
 - Protocol: MRP, Port: 55183, Credentials: None
```

**Comment by postlund** [comment]
Did it work as expected before my previous update? It seems strange though that the identifier would be missing. Only way this would happen would be if the identifier was an empty string, otherwise it wouldn't work at all. I can manually decode the response and try to figure out what is happening if you provide the output from:

    PYATV_BINARY_MAX_LINE=10000 atvremote --debug scan

You can send it by email to me if you prefer that.

**Comment by a7ypically** [comment]
I'm not sure if this is something new.
I will try an older version once it occurs again and will send by email the debug output.
Thanks!

**Comment by postlund** [comment]
@a7ypically Have you seen this issue again?

**Comment by a7ypically** [comment]
No. Did not see it again. I do have some other issues of the ATV closing connection when going to sleep and pyatv reconnecting upon keep alive failure, which created a loop of connection and disconnection until at some point the ATV refuses any more connections from pyatv until I restart it. I'm solving this by having HASS turn off the component which avoids the reconnection attempts.

**Comment by postlund** [comment]
Can you possibly provide some logs for this so I can see what is happening?

**Comment by postlund** [comment]
I've been thinking about this a bit. Does this happen (`TheDeviceIsGoingToSleep`) even when you have the device turned on, e.g. watching it on a TV? I'm starting to think that the device is *actually* going to deep sleep, which it can do under the right circumstances. Perhaps the other Apple TV serves as sleep proxy for the first one, being the reason why that doesn't go to sleep? Not sure. One thing you could try is to constantly ping the device and see if there are gaps (i.e. ping timeouts or redirects) whenever the device goes to sleep. That would suggest the device is going to deep sleep.

**Comment by postlund** [comment]
Initial issue seems to be solved (or at least not happen anymore), so I'm closing this issue for now. The fact that the device goes to sleep is a separate problem.
