### ISSUE TITLE
Most of the home assistant event loop is spent calling the copy in `pyatv.mrp.playing`

### ISSUE THREAD

**Issue by bdraco** [postlund/pyatv#773]
<img width="891" alt="Screen Shot 2020-07-17 at 2 52 29 PM" src="https://user-images.githubusercontent.com/663432/87840816-4d14f200-c83d-11ea-9392-b228990236c8.png">
<img width="893" alt="Screen Shot 2020-07-17 at 2 52 19 PM" src="https://user-images.githubusercontent.com/663432/87840819-4e461f00-c83d-11ea-8dfa-87b7eb211cea.png">

**Comment by bdraco** [comment]
Looks like the change in #567 

I wonder if we need a `deepcopy` and a `copy` would be good enough to cover the use case

**Comment by postlund** [comment]
This is a good catch, it's certainly because of #567. I will comment in the PR.
