### ISSUE TITLE
Support for Airport Express

### ISSUE THREAD

**Issue by varunl** [postlund/pyatv#78]
Hi, I have an airport express which has a 3.5mm audio out. Is it possible to set that up as a device?

**Comment by postlund** [comment]
Currently no, not really sure how that works but it requires some encryption stuff based on what I have read. Would be a great addition though (even if it's a bit out of scope for this library). I might look into in the future in case someone else doesn't take on the task. If I'm lucky, it works with my Yamaha reciver as well.

**Comment by varunl** [comment]
Thanks! It would be awesome if this works. I would probably need quite a bit of ramp up to figure out how to solve this.

**Comment by postlund** [comment]
Same here, I think it would be a bit tricky.

**Comment by postlund** [comment]
I have decided that RAOP is out of scope for this library (there are other libraries that does this), so I', closing this issue.
