### ISSUE TITLE
Unable to Integrate

### ISSUE THREAD

**Issue by alexifranco** [postlund/pyatv#782]
**What to investigate**
I'm attempting to install this beta on a raspberry pi running HassOS 4.11 and Home Assistant 0.113.1. Following the instructions (with minor tweaks for HassOS) I:

1. Click on **Supervisor**, then **Add-on Store**, and click on the 3-dots on the top-right.
2. **Paste** in the following url: https://github.com/postlund/hass-atv-beta, then click on **Add**
3. Click on **Close**
4. Navigate to **Configuration** from the menu and click on **Server Controls**
5. Click on **Check Configuration** and once successful, click on **Restart**
6. Once the system returns, click on **Configuration** from the menu and then on **Integrations**
7. Click on the **+** to search for **AppleTV**

Issue:
The entry appears on the list of repositories though the name appears as "unknown"
Apple TV does not appear on the list of available integrations

**Expected outcome**
The documentation needs to be updated for HassOS as the menu has changed
The name is displaying as "unknown" in the list of add-on repositories
The integration does not show as an integration once added and the system has been restarted (unless I'm missing something)

**Comment by postlund** [comment]
This is not an addon so you cannot add it via the supervisor. You must use HACS.

**Comment by alexifranco** [comment]
Sorry about that. Don't integrate before coffee. I mistook hacs for hassos. Thank you.
