### ISSUE TITLE
Light tap is currently not supported.. right..?

### ISSUE THREAD

**Issue by sebamattsson** [postlund/pyatv#783]
**What's on your heart?**
Hello there,

Recently found this project and went through all the cool commands supported today.
One I could not find, and I tend to use quite a bit, is the 'light' tap on the touch surface, often to check how much there is left of a movie etc.
Also, reading through the issues section, could not find this discussed too much, closest I could find was the support for touch-gestures, would this 'light tap' go in the same category?

Thanks a lot in advance and keep up the good work!
Sebastian

**Comment by postlund** [comment]
Hey! 👋 Yes, you are right. It is currently not supported as it's a touch feature and I haven't started working on that yet. Supporting that particular command should be easy, but I do need to design an interface for it first (to make sure it works with all future commands).

**Comment by sebamattsson** [comment]
Got it, no worries, just wanted to make sure I didn't miss it somehow! Would it make sense to somewhere explicitly mention which features currently are NOT supported (seems you got quite a lot covered already!)?
I'll keep follow the project page for future updates, unfortunately don't think I can contribute with much else than testing :)
Tack!

**Comment by postlund** [comment]
I try to keep the list of supported feature at [pyatv.dev](https://pyatv.dev) as updated as I can. Doing a list of the opposite is much more work and harder to get right, so I'm gonna stick with that. The assumption is that if it's not listed it's not supported.

Adding touch support is on the list to be implemented, but it will probably not happen for a while as I have less free time now. But I'll give you a ping once I need testers 👍
