### ISSUE TITLE
Play State Does Not Update on tvOS 14

### ISSUE THREAD

**Issue by evanreichard** [postlund/pyatv#795]
**Describe the bug**
It appears that in tvOS 14 the `protobuf.SET_NOW_PLAYING_CLIENT_MESSAGE` no longer fires. Instead, the listener for `protobuf.SET_STATE_MESSAGE` fires.

In addition, the format of the message is different: It is now nested under `playerPath`.

```
playbackState: Playing
playbackQueueCapabilities {
}
playerPath {
  origin {
    displayName: "Living Room"
    identifier: 1280262988
  }
  client {
    processIdentifier: 1583
    bundleIdentifier: "com.firecore.infuse.pro.6"
  }
  player {
    identifier: "MediaRemote-DefaultPlayer"
    displayName: "Default Player"
  }
}
playbackStateTimestamp: 619054613.006949
```

**To Reproduce**
atvremote push_updates does not work when ATV is tvOS 14.

**Expected behavior**
push_updates should report properly.

**System Setup (please complete the following information):**
 - OS: Alpine Linux v3.12 (Docker)
 - Python: Python 3.8.3
 - pyatv: 0.7.0
- Apple TV: Apple TV 4K tvOS 14

**Additional context**
I was able to get around it by tweaking the [player_state.py](https://github.com/postlund/pyatv/blob/master/pyatv/mrp/player_state.py) file.

I added the following to `async def _handle_set_state(self, message, _):` in order to call `_handle_set_now_playing_client`:
```
        if setstate.HasField("playbackState"):
            await self._handle_set_now_playing_client(message, _)
```

Then updated `async def _handle_set_now_playing_client(self, message, _)` to reference the new `[...].client.bundleIdentifier` correctly:

```
        identifier = message.inner().playerPath.client.bundleIdentifier
```

I know this is a hack, which is why I didn't submit a PR. I only started looking at this code base today, so will continue to dig into it.

**Comment by postlund** [comment]
At first glance this sounds more like a bug in tvOS or the app you are using. The SET_STATE_MESSAGE is only used to push state information about something (so it's sent at least once for each app that has an active state on the device), not what is currently playing. Changing this would break the protocol. Can you try playing something and, do `atvremote -s <ip> --debug playing` and provide the output? Also check if the Remote app shows what is actually playing.

**Comment by evanreichard** [comment]
Results from `atvproxy` from my Apple Watch to the ATV4k. My iPhone Remote is properly interpreting it - I can see artwork, progress, and pause button that properly changes when I use the actual remote.

```
2020-08-15 05:15:39 DEBUG: 10.0.20.183:44972<->10.0.20.181:49153 << Receive: Protobuf: type: SET_STATE_MESSAGE                                                                                     [0/1862]
errorCode: NoError
[setStateMessage] {
  playbackState: Paused
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 170
      bundleIdentifier: "com.spotify.client"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 619161339.747215
}
85: "A85AEB9E-9ED9-4E33-8D12-0C63CCDD37B4"
2020-08-15 05:15:39 DEBUG: ATV->APP (Raw=080420004a6a300242004a5b0a13120b4c6976696e6720526f6f6d18cc86bde204121708aa011212636f6d2e73706f746966792e636c69656e741a2b0a194d6564696152656d6f74652d44656661756c74
506c61796572120e44656661756c7420506c6179657259bea4df7dd373c241aa052441383541454239452d394544392d344533332d384431322d304336334343444433374234)
2020-08-15 05:15:39 INFO: ATV->APP Parsed: type: SET_STATE_MESSAGE
errorCode: NoError
[setStateMessage] {
  playbackState: Paused
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      displayName: "Living Room"
      identifier: 1280262988
    }
    client {
      processIdentifier: 170
      bundleIdentifier: "com.spotify.client"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
  playbackStateTimestamp: 619161339.747215
}
```

**Comment by postlund** [comment]
Can you provide the complete log? Only the snippets are not enough since they have always been sent before as well.

**Comment by evanreichard** [comment]
Full output:

https://pastebin.com/jF1NssBa

**Comment by evanreichard** [comment]
Hm. Something weird was going on. I restarted and things started working. My fault. Should have done that earlier.

**Comment by postlund** [comment]
Probably related to being beta (Apple is kinda known for introducing strange bugs in late betas every now and then). But we should monitor the situation in case something changes.
