### ISSUE TITLE
New Apple TV Integration, removed old and no entities are appearing

### ISSUE THREAD

**Issue by trebolcinco** [postlund/pyatv#815]
I changed to a new Apple TV and have been unable to add the new TV.  I disconnected the old one and only want the one Apple TV.  When I try to add the Apple TV integration it says it already exists at ip x.x.x.67.  I tried deleting the integration and the HACS repo, re-install and same error.  I do have a single "media_player.tv" of integration type: Media Player appearing in the list of entities which I cannot remove, hide or do anything with.  I thought when I had it working before it was of type Apple TV.

I see messages in the log about auto-discovery on x.x.x.67 with the correct name.  But I am not seeing the entities show up.

**Comment by postlund** [comment]
If you look in the integration page, do you see the Apple TV listed there? How are you adding the device (config flow or yaml)? The exact error message would be good as well logs, if you can provide that.

I kindly also ask you to stay with the issue template in the future (they exist for a reason). Thanks! 👍

**Comment by trebolcinco** [comment]
Apologies about template, was not aware of it.  It never gets added to the HA Integration page, it only shows up in the HACS page.  When I try to add through the HA + Integration it prompts for host and when I enter the IP it says it is already configured.  I searched everywhere and that IP is not anywhere in all the files nor is it there by name.  Double checked configuration.yaml and any related files.  Is there a config in .storage that I can wipe out?

**Comment by postlund** [comment]
This would mean that a config entry already exists for the device, for which you should see entities and also connection attempts. If you enable logs you'll be able to see if this happens:

```yaml
logger:
  default: critical
  logs:
    pyatv: debug
    custom_components.apple_tv: debug
```

**Comment by trebolcinco** [comment]
```
2020-08-24 15:40:34 DEBUG (MainThread) [pyatv.support.scan] Auto-discovered Kitchen (2) at x.254.28.18:7000 (Protocol.AirPlay)
2020-08-24 15:40:34 DEBUG (MainThread) [pyatv.support.scan] Auto-discovered Samsung Q80 Series (75) at x.0.0.68:49546 (Protocol.AirPlay)
220-08-24 15:40:34 DEBUG (MainThread) [pyatv.support.scan] Auto-discovered Entertainment Room at x.0.0.67:49152 (Protocol.MRP)
2020-08-24 15:40:34 DEBUG (MainThread) [pyatv.support.scan] Auto-discovered Entertainment Room at x.0.0.67:7000 (Protocol.AirPlay)
```

**Comment by postlund** [comment]
Nothing more than that? If you look for "apple_tv" in core.config_entries, do you find anything? The address is less important, the check is based on identifiers.

**Comment by trebolcinco** [comment]
There is this in the core.config_entries, not sure what the ignore is about:
` {
                "connection_class": "local_push",
                "data": {},
                "domain": "apple_tv",
                "entry_id": "edef215311e3421b955e72dbfa730d78",
                "options": {},
                "source": "ignore",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "Ignored",
                "unique_id": "2D88C3F0-222B-4A0F-A0E3-94889804D80B",
                "version": 1
            },`

**Comment by trebolcinco** [comment]
The 10.0.0.67 is the one I am trying to add, the one that is getting picked up in the auto discover.  Full message on screen is:

`This device has already been configured. Please pick another device.`

**Comment by trebolcinco** [comment]
I renamed .storage and restarted and then put it back and restarted and all then the integration showed up and asked for pin.  So there must have been some latent config mucking up the works.  I will close, appreciate the assist.

**Comment by postlund** [comment]
Yeah, was about to write that the config entry looked to be broken. The data section was empty. If you want you can keep your old .storage and just remove that entry, should yield the same result.
