### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'print'

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#82]
There's an issue with version 0.10.4 of the netifaces package, which is required by python-zeroconf. Will not go into details here, I wrote an issue at https://github.com/jstasiak/python-zeroconf/issues/103.

This is a blocker for the next release.

**Comment by drewcovi** [comment]
@postlund is there a workaround in the meantime? or is there a way for us to leverage gn3-netifaces instead?

**Comment by postlund** [comment]
@drewcovi Not that I know of, unfortunately. Since it's a dependency of python-zeroconf there's not much I can do.

**Comment by clyra** [comment]
Is there a way to get arrow keys working on a atv4? Installing from pip doesn't have it, but installing from git is broken right now.

**Comment by postlund** [comment]
I will not release it to pypi (pip) until the dependency issue is solved. Not sure when that will happen. If you clone from git and pin python-zeroconf version to something earlier than 0.19.0, then it should work (e.g. change >= to ==).

**Comment by clyra** [comment]
it worked! thanks!

**Comment by postlund** [comment]
Latest update on this is that I created an issue over at the netifaces project. Progress can be followed here:
https://bitbucket.org/al45tair/netifaces/issues/49

**Comment by drewcovi** [comment]
Nice work! Looks like you were able to move the ball forward, and that fix was merged.

**Comment by postlund** [comment]
Yeah, it's looking great! Hopefully this can be sorted out in the next few days. That would be awesome!

**Comment by postlund** [comment]
Added a note about the new release of netifaces over at python-zeroconf, lets hope we can get a new release out!

**Comment by postlund** [comment]
A new version of python-zeroconf is out and it works excellent! I'll see if I can get 0.3.0 out the door soon.
