### ISSUE TITLE
An irrecoverable connection problem occurred when connecting to f{name}. Please go to the Integrations page and reconfigure it

### ISSUE THREAD

**Issue by parautenbach** [postlund/pyatv#828]
**Describe the bug**
```
An irrecoverable connection problem occurred when connecting to f{name}. Please go to the Integrations page and reconfigure it
```

**To Reproduce**
I have not idea but it's happened about 3 times after a day or 2. 

**Expected behavior**

**System Setup (please complete the following information):**
 - OS: Raspbian
 - Python: 3.7.3
 - pyatv: 0.7.2
- Apple TV: Apple TV (A1652) tvOS 13.4.8

**Additional context**
This bug started appearing out of the blue during the past week (I don't know if my Apple TV updated but otherwise I didn't update anything). When this happens I need to power cycle my Apple TV as it won't turn on. Otherwise, I haven't had any trouble using the beta.

**Comment by durrav** [comment]
I get the exact same issue and it has happened every few days for at least a month now.

**Comment by parautenbach** [comment]
Oddly, it hasn't happened again since I posted this... My Apple TV is still on the same version. Didn't upgrade anything else either.

**Comment by parautenbach** [comment]
I'm going to assume it was some transient issue since it hasn't happened again. Will reopen if it does.
