### ISSUE TITLE
delay between control arguments 

### ISSUE THREAD

**Issue by jhnwmr** [postlund/pyatv#830]
Hello,
I want to control my ATV.
My commands are relatively simple, but the ATV does not execute them.
If I enter them one by one in the terminal with "delay=1000" they work.
The commands are Home-Home-Select.

How can I insert a delay in my code?

```
import sys
import asyncio
import pyatv

LOOP = asyncio.get_event_loop()

async def control_app(loop):
    print("Find ATV")
    atvs = await pyatv.scan(loop, identifier='..MAC..')
    atv = await pyatv.connect(atvs[0], loop)
    rc = atv.remote_control
    try:
        await rc.home()
        #delay
        await rc.home()
        #delay
        await rc.select()
    finally:
        print("Exit")



if __name__ == "__main__":
    LOOP.run_until_complete(control_app(LOOP))
```

**Comment by postlund** [comment]
Use `await asyncio.sleep(1000)`. This particular example can also be accomplished with `atvremote` if you like:

    atvremote --id <id> home delay=1000 home delay=1000 select

**Comment by jhnwmr** [comment]
Thanks for this fast support. Now its working.
