### ISSUE TITLE
FR: Add Media Browser support

### ISSUE THREAD

**Issue by SeanPM5** [postlund/pyatv#832]
**What feature would you like?**
Home Assistant 0.115 (now in beta, [beta release notes](https://rc.home-assistant.io/blog/2020/09/07/release-115/#media-browser)) has a great standout new feature called Media Browser. It's already supported by many of the major Home Assistant media player integrations like Spotify, Roku, Plex, Kodi, Sonos, etc.. I think almost every media player integration will adopt this fairly quickly.

I know you're still working on getting the ATV integration merged into core, so no rush, but it would be super cool if this could be supported in the future :)

**Describe the solution you'd like**

**Any other information to share?**
Here is an example of the Roku integration. Clicking the browse button shows this dialog and you can select any app, and it will launch it on your TV.

![image](https://i.imgur.com/bCzWVnr.png)

**Comment by postlund** [comment]
Will definitely add it, but it has #303 as a prerequisite. If I manage to reverse engineer the companion protocol completely I will be able to implement this.

**Comment by postlund** [comment]
There's a bit of work left that I want to work out until I make a new release of `pyatv`, but it should be possible to implement this with what is currently on `master`. So it's not that far away.

**Comment by postlund** [comment]
Initial support for launching apps just landed in the beta component repo, feel free to try it out and let me know how it works. You need Home Assistant 2021.12.0 beta to run it though (out on saturday).

**Comment by postlund** [comment]
Support was merged to core yesterday, so it will be in the next Home Assistant release.
