### ISSUE TITLE
Pairing with TVOS 13

### ISSUE THREAD

**Issue by ideen1** [postlund/pyatv#833]
Pairing with the TVOS 13 on Apple TV 4K(4gen) seems to have changed since the documentation. The Apple TV no longer has a place to enter a pin and instead displays a pin to be entered for the pairing process. This seems to work occasionally through the atvremote cli however support for any connections such as OpenHAB is completely broken. Any fixes for the new OS?

**Comment by postlund** [comment]
Which documentation are you referring to? Support for tvOS 13 has been in place since 0.4.0.

**Comment by postlund** [comment]
Ping.

**Comment by ideen1** [comment]
This is my bad, I had confused the pyatv-openhab bridge documentation with the ones of this project. Sorry!
