### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by atxbyea** [postlund/pyatv#836]
**Describe the bug**
Not possible to turn on apple tv from Home assistant, logs just say : [pyatv.mrp.connection] Keep-alive not supported: FreeBSD does not support keep-alive

**To Reproduce**
Home-assistant 114.4 in a FreeBSD 12.1 jail 

**Expected behavior**
AppleTV to turn on

**System Setup (please complete the following information):**
 - OS: FreeBSD 12.1
 - Python: 3.8.5
 - pyatv: 0.7.2
- Apple TV: AppleTV 4 HD

**Additional context**

**Comment by postlund** [comment]
Ok, I should add support for FreeBSD. The errors are unrelated however as that is just a warning (and means that unexpected loss of network connections won't be detected, e.g. if the Apple TV crashes or cable is pulled). Please enable additional logging and attach them here.

**Comment by atxbyea** [comment]
Sorry for the late reply, this should contain the requested info.
[pyatv.log](https://github.com/postlund/pyatv/files/5282194/pyatv.log)

**Comment by postlund** [comment]
At a quick glance I don't see anything strange here. When you say "not possible to turn on", what do you actually mean by that? What isn't working?

If I prepare a commit with keepalive support for FrreBSD, can you help out testing that with `atvremote`?

**Comment by atxbyea** [comment]
Aye, it didn't turn on, I can play more and log more as needed, and test as needed

**Comment by postlund** [comment]
Do you mean in Home Assistant (so it doesn't show any state) or do you mean turn on as in it shows something on your screen?

**Comment by atxbyea** [comment]
Toggling the `remote.` entity does nothing :-)

**Comment by postlund** [comment]
The integration does not support power management, so that is expected. It only toggles if the entity is on or off.

**Comment by atxbyea** [comment]
Sorry, my bad, I meant the `media_player.` entity, this button 
![Screenshot_20201008-211333_Home Assistant](https://user-images.githubusercontent.com/46269073/95503198-4e246e00-09ab-11eb-97e4-1e1d5ff897f5.jpg)

**Comment by postlund** [comment]
It's the same, `turn_on` and `turn_off` use the exact same logic for both `media_player` and `remote`.

**Comment by atxbyea** [comment]
Good to know, so the turn on\off isn't supposed to work at all, would it be possible to remove the button somehow or is that hard coded in the device features ?
If you need me to test anything for keepalive I can do that when needed.

**Comment by postlund** [comment]
It currently only turns on or off the entity, not the device. There has been some work to support power management in #672, but it will get a bit outdated as the component will look a bit different when included in Home Assistant (so some re-write will be needed). I however doubt that feature will ever be really stable as the Apple TV is not designed to be used like this. 

It's not possible to remove the button. For some people the button is useful to turn off the entity as their TV equipment is turned on (via CEC) when the Apple TV is connected to. So you will have to just not use the button until we have proper power management.

I will try to upload a PR with keep-alive support for FreeBSD. If I understand it correctly, it should be the same syscalls as for Linux so it should work in the same way.

**Comment by atxbyea** [comment]
Did you get around to it @postlund ? I can test anything you need.

**Comment by postlund** [comment]
@atxbyea FreeBSD support for keep-alive has been added by @paxswill and its merged. So you can try from master if you like. Also just realized that you maintain the samsungrac custom component I just submitted a PR to, small world 😉
