### ISSUE TITLE
State is not pushed from Apple TV unless clientUpdatesConfigMessage is acknowledged

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#849]
**Describe the bug**
The Apple TV normally push the state of all players when connecting. For some reason it has stopped doing so (in tvOS 14?) if the `clientUpdatesConfigMessage` is not acknowledged (I.e. `identifier` is included and response awaited).

**To Reproduce**
Try printing what is playing with debug enabled:

    atvremote -s 10.0.0.10 --debug playing

No `SET_STATE_MESSAGE` is received and "nothing" is always returned.

**Expected behavior**
Should return what is currently playing.

**System Setup (please complete the following information):**
 - OS: any
 - Python: any
 - pyatv: 0.7.2
- Apple TV: Apple TV 4K tvOS 14.0.1

**Additional context**

**Comment by lucasec** [comment]
One interesting note here I'm still trying to make sense of—using atvproxy I notice the remote app on my device sends one clientUpdatesConfigMessage with an identifier:
```
2020-12-29 11:30:42 INFO: (DEC Phone->ATV): type: CLIENT_UPDATES_CONFIG_MESSAGE
identifier: "0AFE299E-BCBD-4BB8-A7F3-C72249CFDDD5"
errorCode: NoError
[clientUpdatesConfigMessage] {
  artworkUpdates: true
  nowPlayingUpdates: false
  volumeUpdates: true
  keyboardUpdates: false
  outputDeviceUpdates: false
}
```

But after receiving all of the initial state it sends another one without:
```
2020-12-29 11:30:42 INFO: (DEC Phone->ATV): type: CLIENT_UPDATES_CONFIG_MESSAGE
errorCode: NoError
[clientUpdatesConfigMessage] {
  artworkUpdates: true
  nowPlayingUpdates: true
  volumeUpdates: true
  keyboardUpdates: false
  outputDeviceUpdates: false
}
```
(also flips `nowPlayingUpdates` to true). Haven't been able to find any evidence yet as to whether that later update is significant.

**Comment by postlund** [comment]
That's... kinda interesting. It contradicts itself in some ways. But yeah, if you find anything useful I'm interested to know!
