### ISSUE TITLE
Apple TV not turning off

### ISSUE THREAD

**Issue by csdevto** [postlund/pyatv#870]
I installed the plugin using HACS, but the Apple TV doesn't turn off when clicking the switch or power button.

**Comment by postlund** [comment]
Yes, that is not supported or implemented yet.

**Comment by csdevto** [comment]
not even to sleep? would this change in the future?

**Comment by postlund** [comment]
Not even sleep. You will have to manually navigate through menus to do that now. The whole "sleep" thing is extremely complex to get right. There has been work to support this in another issue/PR (which will have to be adjusted to current changes at some point), but I haven't put any efforts into supporting it myself as I see no use for it. Even when support is added, I expect it to be somewhat unreliable so I wouldn't trust it to 100% either. Best effort is what I would say,

**Comment by postlund** [comment]
I will close this as we already have an issue regarding power management.
