### ISSUE TITLE
State of ATV in HA changing when no state change on device itself

### ISSUE THREAD

**Issue by bverkron** [postlund/pyatv#872]
**Describe the bug**
State of ATV in home assistant keeps toggling between Playing and Idle despite no changes to playback on ATV (it's continuously playing and had not been paused)

**To Reproduce**

**Expected behavior**
Playback state in HA only changes when playback on device changes

**System Setup (please complete the following information):**
- OS: Home Assistant OS + beta integration via HACS
- Python: 3.8.5 according to HA > Configuration > Info
- pyatv: 0.7.3 I believe. Just installed last night via HACS
- Apple TV: Apple TV 4K tvOS 14.0.1

**Additional context**
![image](https://user-images.githubusercontent.com/19174503/98057685-ba05c500-1df7-11eb-9851-e6f91521db68.png)

**Comment by bverkron** [comment]
Oops. Forgot to grab some logs. Will try to attach soon.

**Comment by listentochaos** [comment]
Im also experiencing the same issue:
![image](https://user-images.githubusercontent.com/13469390/98345554-bb5c0b00-200c-11eb-918e-66a53fbfa61a.png)

Logs:

[https://pastebin.com/g7TswGa8](url)

**Comment by postlund** [comment]
I suspect this is the reason:

```
2020-11-06 08:45:19 DEBUG (MainThread) [pyatv.mrp.connection] 192.168.86.102:47934<->192.168.86.100:49153 << Receive: Protobuf: type: SET_CONNECTION_STATE_MESSAGE
identifier: "52343EA1-DA82-4B82-82C1-B2E5ECBC7A9F"
errorCode: TheDeviceIsGoingToSleep
[setConnectionStateMessage] {
state: Disconnected
}
```
It's hard, as a client, to deal with the device going to sleep. Not much that I can do about it. I guess recommending to disable auto-sleep is one way to go. Otherwise I would need a way to (reliably) get a notification that a device was woken up and re-connect when that happens. Now I just re-connect immediately, which wakes the device and restarts this endless cycle. Can you try to disable auto-sleep, just to see if it works as expected?

**Comment by nzapponi** [comment]
I'm having this issue as well.
Actually, funny enough, I have two Apple TVs and two HA deployments, and only one of them is exhibiting this behaviour.

Both are configured the same way, and Auto-Sleep is enabled on both.
The only difference I can think of is that one is connected via Wi-Fi (causing logs), and the other via Ethernet (no logs).

Could that be it?
Thanks!

**Comment by postlund** [comment]
I've heard people report different behavior depending on if being connected via wifi or cable. I guess it might be a power management thing, but I'm not sure. Putting both on wifi and/or cable for testing purposes is one way to figure it out. Turning off auto-sleep is the only true workaround as I see it. The device needs to be on for the integration to function anyways, so there's no benefit to having it enabled anyways (if you want the integration to work).

**Comment by postlund** [comment]
In case problem persists (or if someone else finds this issue with the same problem), make sure to disable auto-sleep and try again. That should hopefully solve the problem.
