### ISSUE TITLE
Installing an app through atvremote or a Python script

### ISSUE THREAD

**Issue by rtrimana** [postlund/pyatv#873]
Hello, thanks so much for providing such an awesome tool/library! 

I have a question. Is it possible to use `pyatv` to **install a certain app**, for example, through `atvremote`---I couldn't find any option to do that on [https://pyatv.dev/documentation/atvremote/](https://pyatv.dev/documentation/atvremote/)? And I am assuming that anything we can do with `atvremote` should also be possible to do using the `pyatv` library (as mentioned on [https://pyatv.dev/](https://pyatv.dev/)).

The closest thing is just that I could look into the metadata of an active app, for example (taken from that page):

```
$ atvremote --id 00:11:22:33:44:54 app
App: Musik (com.apple.TVMusic)
```

So, I am wondering if we could install this `com.apple.TVMusic` app using `atvremote`.

Thanks and hopefully someone could help with some insights.

**Comment by postlund** [comment]
You mean install via App Store? There's no API for that AFAIK. The only way would be to navigate through menus, but installing apps is probably too complex for that. There is a way to fetch a list of all installed apps and launch any app, but I haven't managed to reverse engineer that part yet so it's not supported.

**Comment by rtrimana** [comment]
Yes, I think you got my question entirely. :) Well too bad it's not supported yet. Nevertheless, thank you so much for your explanation and clarification.

**Comment by postlund** [comment]
👍
