### ISSUE TITLE
Suspend deprecated

### ISSUE THREAD

**Issue by strunker** [postlund/pyatv#876]
DeprecationWarning: Call to deprecated function suspend.

if suspend is being deprecated is there anything to replace it? I use pyatv to "suspend" all connected devices thus turning them off. Thanks.

**Comment by strunker** [comment]
How does it work with general commands, like play, pause, next, etc? Both wake_up and suspend are as you noted deprecated and will be removed soon. They don't work as expected so we should not consider them. It should however work with turn_on/turn_off, but there's a known issue where the device stops responding like this that I have not figured out yet. Would expect the same thing to happen on tvOS 13.

i think I see so the replacement is simply turn_off or turn_on. will give it a try.

**Comment by strunker** [comment]
Error trapped for AppleTV: 'MrpRemoteControl' object has no attribute 'turn_off'
Apple TV Error: 'MrpRemoteControl' object has no attribute 'turn_off'

turn_on and turn_off dont seem to work unfortunately.

**Comment by strunker** [comment]
both wakeup and suspend work perfectly fine for me for now. outside of the deprecation error being thrown they actually DO work. turn_on and turn_off do absolutely nothing and just throw the error seen above.

**Comment by strunker** [comment]
Can we not deprecate these and instead just leave them? I read several other posts which state the power options turn on \ off \ suspend \ wake arent reliable and kind of vary from device to device. So perhaps the messaging is just to use at your own risk and they arent guaranteed to work across the board. 

All I can say is on my apple 4k tv, which I have set to control my soundbar (CEC style control). when i suspend the apple tv 4k it is turning my soundbar off and sleeping (no lights on front). Wake brings the apple tv back up as well as the soundbar so working totally without flaw. 

Can we consider not deprecating and removing the warnings?

**Comment by strunker** [comment]
Sorry for all the spam. I removed the deprecated decorators in init.py for this so that it stops raising warnings for this. So I think I am good. 

https://github.com/postlund/pyatv/issues/791

this post from just a few months ago confirms what I found to also be true. Suspend\wake work fine. turn_off\turn_on\Power.turn_off\Power.turn_on do nothing and generate errors. I dont really want to pull request to fix this because I trust you planned to deprecate them for a reason. But I am finding the opposite to be true of what the official suggestion\docs are stating.

**Comment by postlund** [comment]
What I can say first is that you have not tried `turn_on` or `turn_off` yet as that is part of the power interface. You can read about that here:

https://pyatv.dev/development/power_management/

The `suspend` and `wakeup` commands have acted very bad, at least in the past, silly putting the device in a state where it's not usable. So that's why I don't want to use them. That might of course have changed since then, so we can re-evaluate. But to do that we need input from more users, otherwise I will keep the implementation as-is. And please also stick to the issue templates in the future, they are there for a reason. Thanks 👍

**Comment by strunker** [comment]
Got it. Missed that in the docs. And it works great. Just cut my code over to that, also neat that you can get the power state, makes toggling simpler and more accurate since you don't need to try and track the power state on your own with boolean variables. Making complete.
