### ISSUE TITLE
Support for keyboard entry over MediaRemoteTV protocol

### ISSUE THREAD

**Issue by sofakng** [postlund/pyatv#879]
According to this [MediaRemoteTV protocol](https://github.com/jeanregisser/mediaremotetv-protocol) information, there is the ability to send keyboard commands to the AppleTV.

This is extremely useful for applications such as [Channels DVR](https://getchannels.com/dvr-server/) so you can input channel numbers directly or use other keyboard shortcuts to control the application.

I think there are a few issues discussing this (#584, #145, #148, #583) but I'm not sure these are discussing the same issue.  (ie. MediaRemoteTV protocol to send keyboard inputs unless there is different method?)

**Comment by postlund** [comment]
Implemented in version 0.12.0 but via Companion (that is what apple uses nowadays).

**Comment by tresby** [comment]
> Implemented in version 0.12.0 but via Companion (that is what apple uses nowadays).

Hey postlund, been trying to get the hang of atvremote via terminal on my Mac and have gotten pretty much all the commands down pat, except for keyboard input. 

Wanting to use this for ChannelsDVR via their guide or live channels, how would I use atvremote to send something like '506' to my Apple TV.

Thanks!
