### ISSUE TITLE
Hass version 0.118.5 - media player failed to update

### ISSUE THREAD

**Issue by meazzaflavio** [postlund/pyatv#888]
**Describe the bug**
After playing something on Apple TV, in the log there is an error indicating a failure on updating the media player. It takes the app id as media player instead off the entity id

**System Setup (please complete the following information):**
 - OS: HassOS 4.17 on VM
- Apple TV: tvOS 14.2
- Home Assistant version 0.118.5

**The status of the service is paused**
media_position_updated_at: '2020-12-07T09:50:15.962949+00:00'
media_title: No title
app_id: com.apple.TVAirPlay
app_name: ''
friendly_name: appletv
supported_features: 21427

Sometimes the app_id field contain com.neflix.Neflix

**In the log I found this error:**
Logger: pyatv.mrp.player_state
Source: /usr/local/lib/python3.8/site-packages/pyatv/mrp/player_state.py:215 
First occurred: 10:50:15 (1 occurrences) 
Last logged: 10:50:15

Received UpdateClientMessage for unknown player com.apple.TVAirPlay
Received UpdateClientMessage for unknown player com.netflix.Netflix

I've tried to uninstall completely the integration, removed the Lovelace and reboot all, then install it again but with the same result

**Comment by postlund** [comment]
Can you elaborate a bit more and include the actual error? I don't understand what you mean. Also fill in the fields under `System Setup`.

**Comment by meazzaflavio** [comment]
Yes sorry @postlund 
I've updated the post with the missing informations

**Comment by postlund** [comment]
Thank you! This is fixed on `master` and will be fixed in the component once I make a new release. Will be in the next few days as I would prefer to have it included with Home Assistant 1.0.

**Comment by postlund** [comment]
Fixed in #880 btw.

**Comment by meazzaflavio** [comment]
Thanks a lot @postlund . I'm pretty new on Github. Can you explain me if there is a way to download the master in the meaning time?

Thanks a lot

**Comment by postlund** [comment]
As Home Assistant only allows installing from pypi, a release is more or less required. It's very difficult to work around when using HassOS I'm afraid.

**Comment by meazzaflavio** [comment]
@postlund do you have nay news about the update of the Apple TV integration?
Thanks

**Comment by postlund** [comment]
@meazzaflavio The mentioned fixed is in 0.7.5 that has been bumped in Home Assistant. So it should be part of HA 1.0 released on Sunday.

**Comment by postlund** [comment]
@meazzaflavio Have you tried the HA release? The fix is included there.

**Comment by meazzaflavio** [comment]
Hello,
Yes I've tried it and seems working fine. I will let you know in those days
if I discover something.
Thanks a lot and Merry Christmas

Il giorno mer 23 dic 2020 alle ore 22:47 Pierre Ståhl <
notifications@github.com> ha scritto:

**Comment by postlund** [comment]
Any problems or can we close the issue?

**Comment by meazzaflavio** [comment]
You can close it, issue resolved
Thanks

Il ven 26 feb 2021, 22:40 Pierre Ståhl <notifications@github.com> ha
scritto:
