### ISSUE TITLE
Automatic reconnect

### ISSUE THREAD

**Issue by SayWhat69** [postlund/pyatv#889]
How can I achieve an automatic reconnect when the connection is lost?

I tried it with the ConnectionLost Listener but it isnt called.

When losing connection I get the following error:

`Fatal read error on socket transport
protocol: <pyatv.mrp.connection.MrpConnection object at 0x7fac4ff3ad68>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 812, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out`

My Listeners look like this:
`    def connection_lost(self, exception):
        print("Lost connection:", str(exception))
        asyncio.get_event_loop().run_until_complete(main())`

`    def connection_closed(self):
        print("Connection closed!")
        asyncio.get_event_loop().run_until_complete(main())`

But they are not called.

**Comment by postlund** [comment]
Can you include the full code snippet, so I can see what you are doing? It's supposed to be set up like this:

https://pyatv.dev/development/listeners/#device-updates

Make sure the listener object is long lived as the listener you set is just a weak reference.

**Comment by SayWhat69** [comment]
`class MyPushListener(PushListener, DeviceListener):
    movie = ""
    progress = 0.0

    def playstatus_update(self, updater, playstatus):
        ...

    def playstatus_error(self, updater, exception):
        print("Got an exception:", exception)

    def connection_lost(self, exception):
        print("Lost connection:", str(exception))
        asyncio.get_event_loop().run_until_complete(main())

    def connection_closed(self):
        print("Connection closed!")
        asyncio.get_event_loop().run_until_complete(main())`

`listener = MyPushListener()
  atv.push_updater.listener = listener
  atv.push_updater.start()`

**Comment by postlund** [comment]
As I said, you will need to make sure that the `listener` object does not go out of scope as it will be garbage collected due to being stored as a weak reference. If you have something like this:

```python
def foobar(atv):
    listener = MyPushListener()
    atv.push_updater.listener = listener
    atv.push_updater.start()
```

Then `listener` will have no reference once foobar returns, making it subject for garbage collection. You should create it so that it lives as long as the `ATV` object (at least).

This will not work either:

    asyncio.get_event_loop().run_until_complete(main()))

You can only call `run_until_complete` on a loop that isn't running, which isn't the case here (you will get an exception). You can however create a new task calling your method instead:

    asyncio.create_task(main())

**Comment by SayWhat69** [comment]
```
    atv = await pyatv.connect(atvs[0], loop)
    listener = MyPushListener()
    try:
        atv.push_updater.listener = listener
        atv.push_updater.start()

        print("Press ENTER to quit")
        await loop.run_in_executor(None, sys.stdin.readline)
    except:
        atv.close()
```

This is what I have, is this a weak reference? And how can I get it better?

**Comment by SayWhat69** [comment]
Nevermind had an typo
