### ISSUE TITLE
Pairing

### ISSUE THREAD

**Issue by robbiet480** [postlund/pyatv#9]
I tried to throw together a pairing functionality tonight but still haven't figured my way out around asyncio. The guide at the top of [this](http://dacp.jsharkey.org/) page worked perfectly for me to pair my Apple TV gen 4 though, so shouldn't be too hard to implement!

Used this on my Mac to get a ZeroConf service registered: `dns-sd -R pyATV _touch-remote._tcp local 3689 DvNm=pyATV RemV=10000 DvTy=computer RemN=Remote txtvers=1 Pair=0000000000000001`

**Comment by postlund** [comment]
Yeah, that part should be pretty easy. I can have a look at it in the next couple of days and see if I can implement it.

**Comment by postlund** [comment]
I'm making good progress on this, shouldn't take too long. Since it requires addition of a "pairing guid" beside the already used "hsgid", some updates regarding that is needed, updates to atvremote, documentation and so on. Also testing is a bit tricky. But I should finish it off quite soon.

**Comment by robbiet480** [comment]
Dang! Wish my phone wasn't on silent. I just got [this](https://gist.github.com/robbiet480/e0291fce8a9e58e683a19b5dee5c1be5) done. Learned quite a bit about async in the process. Both of the GUID generation options are somewhat unstable, hoping you can come up with a better solution. They're both converted from Python2 code I found. There's some other goodies in there you may want, like validating the `pairingcode` sent in the `/pair` URL.

**Comment by robbiet480** [comment]
Also we should if possible use a dynamic PIN and pair code because aTV 4 has issues otherwise. I can't delete pairs without restarting first for example.

**Comment by postlund** [comment]
I'm fast... ;) Just finishing things up and I believe I have something that is OK enough to start with. Documentation is not done yet, but I have a not-so-good-looking test for it. Might have to work on that later, but it's nice to have something that verifies that everything works. Will push a PR soon.

**Comment by postlund** [comment]
I've pushed what I currently have, you can have a look at #13 if you are curious.

**Comment by postlund** [comment]
I fixed some stuff and I believe that I am done. Please try it out before I merge it.

**Comment by postlund** [comment]
This is on master now!
