### ISSUE TITLE
media player interacting

### ISSUE THREAD

**Issue by jrspowers** [postlund/pyatv#900]
Hello postlund

is it possible to add the function? that we can see what is playing, so that we can use the media player again like the hacs version? then work very well and fine? can you play / pause and stuff from ha? further now you can not make anything besides a custom remote?

thanks in advance!

**Comment by postlund** [comment]
I'm not sure what you are asking for? Are you using the integration shipped with Home Assistant 2020.12? It is 99% the same as the beta version. If something isn't working, please write a proper bug reports for what is not working and attach logs if appropriate so I can help debugging.
