### ISSUE TITLE
No more app_id attribute in HA?

### ISSUE THREAD

**Issue by grolnn** [postlund/pyatv#903]
Not sure whether this is a bug or not. When I was running the custom integration with HACS before it was integrated in the latest HA version, I no longer see the app_id attribute. I'm not completely sure it's caused by the transition from HACS to native HA, but I don't see any other reason really.

Kind of annoying as I had some automations set up with that attribute (dim lights when status is playing and app_id is xxxx).

So is this a bug or a deliberate decision? If the former: could you add it again in a future version? If the latter: what's the reason to remove it?

Ps. Thanks for your work, other than this the integration works really well :)

**Comment by postlund** [comment]
Some things didn't make it to the first release, app_id bring one of them. It has been merged and will be available in 2021.1.0 again.

**Comment by grolnn** [comment]
Ah great, thanks for your prompt reply!
