### ISSUE TITLE
Interaction between pytest-xdist and pytest-timeout

### ISSUE THREAD

**Issue by paxswill** [postlund/pyatv#904]
I mentioned this in [my mDNS PR](https://github.com/postlund/pyatv/pull/899#issuecomment-749177273), but I feel it's distinct enough for a separate discussion.

So, the root cause (ref: [failing test](https://github.com/postlund/pyatv/pull/899/checks?check_run_id=1590787840#step:8:116)) seems to be the default implementations of `pytest-xdist` and `pytest-timeout` not playing nice. `execnet` (how `pytest-xdist` communicates across different runners) [defaults to a threaded implementation](https://codespeak.net/execnet/basics.html#threading-models-gevent-eventlet-thread). `pytest-timeout` [defaults to using signals](https://github.com/pytest-dev/pytest-timeout/#timeout-methods) when possible, falling back to a thread-based implementation. This causes a problem because signal handlers can only be [set on the main thread](https://docs.python.org/3/library/signal.html#signals-and-threads). Both plugins are aware of the issue (pytest-dev/pytest-timeout#8, pytest-dev/pytest-xdist#117), but it doesn't look like they have any near-term plans to fix it (`execnet` in particular is in maintenance mode).

Both plugins *do* have workarounds though, but they aren't as nice:
* `pytest-timeout` can be told to always use the threaded implementation, but with `pytest-xdist` it has a chance to just hang. Using `--forked` so each test is run in a separate process seems to alleviate the issue though. Windows is a bit different: I *think* it's already using thread-based timeouts, but it doesn't support `--forked`. The downside of this method is that test failures aren't as readable (you just get tracebacks from all threads).
* The `execnet` threaded implementation can be swapped out for either eventlet or gevent. I was able to test with eventlet, and it seemed to fix the signal issue. Downside of this is I think `execnet` is monkeypatching the standard library when using eventlet, which might cause issues elsewhere.

For reproducing the issue, nice-ing the test runners down to almost nothing, while also using more runners than hardware threads seems to trigger it fairly reliably (usually within 10 runs of the test suite). This is the command I was using for testing things:

```shell
declare -i loop_count=0
time while pytest --log-level=debug --timeout=5 --tx=8*popen//nice=20//execmodel=thread --dist=load --timeout-method=thread --forked -q; do
    loop_count+=1
done
echo "Loop count: ${loop_count}"
```

Using the threads and forking, I wasn't able to reproduce the issue after about 20 hours (>3000 loops) on macOS. I wasn't able to reproduce it running in WSL either, but I didn't run it for nearly as long there (about 10 minutes, >70 loops). With signal timeouts and without forking, I'm able to reproduce it within two (usually the first) try on WSL, and usually within 5 tries on macOS.

**Comment by postlund** [comment]
Really good digging! This issue has been around for a long time but I haven't bothered looking into it. Since it only happens every now and then and a re-trigger usually works, that has been good enough... You are free to suggest any changes to improve the situation if you like!

**Comment by postlund** [comment]
I actually think this has been fixed now and I haven't seen the problem in ages, so I will close this now.
