### ISSUE TITLE
Regular fatal error when using push_updates

### ISSUE THREAD

**Issue by acbeers** [postlund/pyatv#934]
**Describe the bug**
push_updates regularly exits with an error about failure to convert a Nan

**To Reproduce**
Run push_updates while the AppleTV is being actively used.

**Expected behavior**
Just updates, no errors.

**System Setup (please complete the following information):**
 - OS: MacOS BigSur
 - Python: 3.7.6
 - pyatv: 0.7.5
- Apple TV: 4 tvOS 14.3 build 18K561

**Additional context**

Here's a stacktrace of the error:

```
cannot convert float NaN to integer
Traceback (most recent call last):
  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py\", line 88, in _run
    self._context.run(self._callback, *self._args)
  File \"/Users/beers/.local/share/virtualenvs/pyatv-mIjQfnbK/lib/python3.7/site-packages/pyatv/scripts/atvscript.py\", line 40, in playstatus_update
    self.formatter(output_playing(playstatus, self.atv.metadata.app)),
  File \"/Users/beers/.local/share/virtualenvs/pyatv-mIjQfnbK/lib/python3.7/site-packages/pyatv/scripts/atvscript.py\", line 129, in output_playing
    values = {k: _convert(getattr(playing, k)) for k in commands.keys()}
  File \"/Users/beers/.local/share/virtualenvs/pyatv-mIjQfnbK/lib/python3.7/site-packages(pyatv)
```

**Comment by postlund** [comment]
This stack trace does not look complete, can you attach the full one?

**Comment by acbeers** [comment]
I can try, but that was the stack trace emitted by atvscript in its final JSON object when it exited, reformatted for readability.

**Comment by postlund** [comment]
I forgot the fact that I added a debug flag to `atvscript`. If you add `--debug`, a file called atvscript.log will be created with a debug log. If you can reproduce and provide me that log, I can probably figure out what's going on. I suspect that current position is NaN for some reason, but I would like to verify that.

**Comment by postlund** [comment]
Any luck reproducing?

**Comment by postlund** [comment]
This is old now, so I'll close it. Feel free to re-open if it happens again.
