### ISSUE TITLE
Question: Accessing play_state in PushListener

### ISSUE THREAD

**Issue by sde91** [postlund/pyatv#945]
Hello

I'm currently trying to use pyatv to send a web request to an external PHP Script, whenever the Play state on the Apple TV changes. I found some example snippets and built the following script which currently works for the states "Playing" and Paused" via device_state.

```python
import sys
import asyncio
import pyatv
import requests
from pyatv.interface import PushListener

class MyPushListener(PushListener):

    def __init__(self):
        self.lastState = ''
    
    def playstatus_update(self, updater, playstatus):
        # Get current state (Playing, Paused)
        currentState = str(playstatus.device_state).replace("DeviceState.", "")
        
        # Check if current state was not used before
        if currentState != self.lastState:
            print(currentState)
            
            # Construct uri
            uri = 'http://192.168.1.100/HueCinema/HueCinema.php?SetEvent=' + currentState
            
            # Fire WebHook to HueCinema
            requests.get(uri)
            
            # Assign current state to last state
            self.lastState = currentState
            
           
    def playstatus_error(self, updater, exception):
        print("Got an exception:", exception)

async def main():
    loop = asyncio.get_event_loop()

    atvs = await pyatv.scan(loop, identifier="aa:bb:cc:dd:ee:ff")
    if not atvs:
        print("No device found", file=sys.stderr)
        return

    atv = await pyatv.connect(atvs[0], loop)
    listener = MyPushListener()
    try:
        atv.push_updater.listener = listener
        atv.push_updater.start()

        print("Press ENTER to quit")
        await loop.run_in_executor(None, sys.stdin.readline)
    except:
        atv.close()


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```

Little bit of context. The external PHP Scripts dims and brightens my living room lights. I wrote it a while back for receiving Webhooks from Plex Media Server. This works fine whenever I use Plex on my Apple TV, however all other Apps (Netflix, YouTube, etc.) obviously won't work. This is why I'd like to switch to pyatv as trigger.

My issue currently is, that I can only get "Playing" and "Paused" out of device_state. In this [issue ](https://github.com/postlund/pyatv/issues/197) I found some details, that there is a more detailed play_state available which should contain all the infos that I need. 

I'd appreciate any help in how I can access the play_state in the playstatus_update method.

Thanks :)

**Comment by postlund** [comment]
I don't think the issue is with your code, it's either with what the app reports or an issue in pyatv. The upcoming release will contain a lot of fixes related to device state, so I suggest that you try with `master` and see if it works better. Hopefully it does.

You can use `playing.device_state.name` to get the name as a string (e.g. Playing or Paused). You should also not use `requests` for making the web request as that is a synchronous blocking call, so it will block the event loop. I suggest that you use `aiohttp` instead (it as a dependency of pyatv, so you already have it) or at least make the call in an executor instead.

Also, `play_state` is the old name for `device_state`. So it's not used anymore. All valid values are [here](https://pyatv.dev/api/const#pyatv.const.DeviceState).

**Comment by sde91** [comment]
Thanks for the answer, I'll try using the master branch including aiohttp for the web request.

**Comment by postlund** [comment]
Release 0.7.6 is out now which is based on master. So you can use that instead if you like.

**Comment by sde91** [comment]
Awesome, thanks.

I currently get the following states out of my Apple TV using 0.7.6: "Idle", "Playing" and "Paused".

The one I'm most interested in is "Seeking". Right now pyatv outputs "Paused" whenever I start seeking.  Basically this is correct because the Video is in fact paused during seeking. However, this triggers my lamps to turn back on which is something I'd like to prevent.

**Comment by postlund** [comment]
That sounds like a bug to me. Can you run `atvremote --debug -s <ATV IP> push_updates`, start fast forwarding, press play and then quit by hitting enter? I would like to have a look at the log.

**Comment by sde91** [comment]
Just that we talk about the same thing. Seeking for me is pressing once on the Apple TV Main Touch Button (which pauses the video) and the swipe forward or backwards and press the Main Touch Button again to restart the video on the selected place.

Here is the  Debug log:
[pyatv_debug_log.txt](https://github.com/postlund/pyatv/files/5895562/pyatv_debug_log.txt)

**Comment by postlund** [comment]
Ok, then with that clarification the behavior is as expected because there's no feedback when seeking like that. So it's unfortunately not possible for pyatv to know that's happening.

**Comment by sde91** [comment]
Sorry for the misunderstanding. In that case seeking would be pressing on the Right Touch Control to fast forward a few seconds?

**Comment by postlund** [comment]
Yeah, I think that should work. Haven't used it much myself to be honest.... I think you can press and hold on either left or right side to fast forward or backwards continuously as well.

**Comment by postlund** [comment]
Anything more we can do here?

**Comment by sde91** [comment]
Thanks for asking. All good :)

I'm currently spinning my head around on how to implement the suggested aiohttp webcall, but that has nothing to do with the initial issue.
