### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by lorenzoCuevas** [postlund/pyatv#985]
Hi, I'm trying to install pyatv on a raspberry pi 4 running Raspbian GNU/Linux buster and have a pathlib error while installing it. Is there a way to fix that?

**Comment by postlund** [comment]
You will have to provide more detailed information on how you are trying to install and what the actual error message is. I can't help you based on this. Please also stick to the issue template, it's there for a reason.

**Comment by lorenzoCuevas** [comment]
Here is the information that it showed me:

pi@raspberrypi:~ $ pip install pyatv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyatv
  Using cached https://files.pythonhosted.org/packages/76/7f/aba3e457d718c74aebf22f6e88353530efec5dc2f9f1703e4e72eddd3b6b/pyatv-0.7.6.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7Swa9j/pyatv/setup.py", line 4, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7Swa9j/pyatv/

It says that I have an import error for pathlib and when I try to install pathlib into the pi , I still have the same message.

**Comment by postlund** [comment]
`pip` probably maps to python 2, so you need to use pip3 instead. Would recommend that you use a venv as well:

https://pyatv.dev/documentation/#installing-pyatv

**Comment by lorenzoCuevas** [comment]
It works, thanks!

**Comment by postlund** [comment]
👍
