### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by lorenzoCuevas** [postlund/pyatv#986]
Hi again,so my problem this time is running the code you've showed on your website for showing what's currently playing on the raspberry pi because it's giving me a syntax error even though I've checked and everything looks fine. Here is the code I've copied and pasted:
import sys
import asyncio
import pyatv

LOOP = asyncio.get_event_loop()

# Method that is dispatched by the asyncio event loop
async def print_what_is_playing(loop):
    """Find a device and print what is playing."""
    print('Discovering devices on network...')
    atvs = await pyatv.scan(loop, timeout=5)

    if not atvs:
        print('No device found', file=sys.stderr)
        return

    print('Connecting to {0}'.format(atvs[0].address))
    atv = await pyatv.connect(atvs[0], loop)

    try:
        playing = await atv.metadata.playing()
        print('Currently playing:')
        print(playing)
    finally:
        # Do not forget to close
        atv.close()

if __name__ == '__main__':
    # Setup event loop and connect
    LOOP.run_until_complete(print_what_is_playing(LOOP))

and here is the error info:
File "pyatv.py", line 9
    async def print_what_is_playing(loop):
            ^
SyntaxError: invalid syntax

------------------
(program exited with code: 1)

Could you see anything wrong that I have done? If so reply to me.

**Comment by lorenzoCuevas** [comment]
Sorry, here is the correct error shown here:
 File "pyatv.py", line 9
    async def print_what_is_playing(loop):
                  ^
SyntaxError: invalid syntax


------------------
(program exited with code: 1)

**Comment by lorenzoCuevas** [comment]
The carrot is under the "f" on def on the syntax error.

**Comment by postlund** [comment]
You are probably running with python 2 again? Try `python3 file.py`.

**Comment by lorenzoCuevas** [comment]
Okay, I'll check that out thanks!

**Comment by postlund** [comment]
I assume this is fixed, so I'll close the issue.
