### ISSUE TITLE
MRP I've found some extra commands & Keyboard support

### ISSUE THREAD

**Issue by chimpzilla** [postlund/pyatv#989]
I've been using pyatv to workout how to control Apple TV and it's been very useful.
It doesn't look like the ability to send keyboard text has been implemented yet. I can get back what is currently in a text box (like search) on the Apple TV, but can't figure out how to send it? 
Even if it's not in pyatv, does anybody know what the raw data looks like to send it?

This is what raw unencrypted data looks like received by the client from the ATV for "abcde" being the current text
08172000E2011B08041A101A0E080010001800300038004000480022056162636465AA052431464136313839422D313541372D343237382D383043432D313544333745304131433132

It would be very useful for searching, Apple TV is the first device I've found that the built in keyboard actually works in 3rd party apps like Netflix/Amazon etc.

I've also found some new commands that don't seem to be in pyatv... here they are in their raw pre chacha form:

Shake up shuffle:
0801122446464646464646462d464646462d464646462d464646462d46464646464646464646464620003202083F

Like:
0801122446464646464646462d464646462d464646462d464646462d464646464646464646464646200032020816

Thumbs down:
0801122446464646464646462d464646462d464646462d464646462d464646464646464646464646200032020817

**Comment by postlund** [comment]
I would recommend that you set up `atvproxy` and just look at the protobuf messages sent from the real Remote app. I think all the message definitions already exists, I just haven't come around implementing any of it.

See the section about *MRP Proxy*:

https://pyatv.dev/documentation/atvproxy/

**Comment by postlund** [comment]
If you want to decode a raw message, you can do that like this (from within the `pyatv` repo):

```
$ ./scripts/protobuf.py decode 0801122446464646464646462d464646462d464646462d464646462d464646464646464646464646200032020816
type: SEND_COMMAND_MESSAGE
identifier: "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF"
errorCode: NoError
[sendCommandMessage] {
  command: LikeTrack
}
```

**Comment by postlund** [comment]
I'm trying to clean up issues a bit and as there's already an issue regarding keyboard support, #879, lets use that for future work (in case you want to work on support for that).
