### ISSUE TITLE
AppleTV app briefly switches to Idle state when UI shows like "Skip preview"

### ISSUE THREAD

**Issue by deviantintegral** [postlund/pyatv#994]
**Describe the bug**

When watching an ATV+ show, there's currently two "skip" buttons that can show:

1. During a trailer that gets injected before a video
2. During the recap

So, when playing an episode (I can currently reproduce with S2E4 and E5 of For All Mankind):

1. State switches to playing when starting the video
2. After a few seconds, it switches back to idle when the trailer starts
3. After a few more seconds, it switches to playing
4. The trailer ends or is skipped, and the recap starts. Player state switches to idle.
5. Finally it switches and sticks to playing.

I see similar behaviour at the end of a show when the UI shows up over the credits, but before the credits are done.

I can get more verbose reporting if needed, but using `atvremote ... push_updates` shows the problem pretty clearly:

```log
# I pressed play on the video in the ATV app. This section was showing the ATV+ logo.
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 0/3849s (0.0%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 5/3849s (0.1%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 9/3849s (0.2%)
      Repeat: Off
     Shuffle: Off

# This fired right when "Skip trailer" showed up and the trailer started.
--------------------
  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off

# This logged when the button timed out and hid itself, with the trailer continuing.
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 19/3849s (0.5%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 34/3849s (0.9%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 38/3849s (1.0%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 40/3849s (1.0%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 44/3849s (1.1%)
      Repeat: Off
     Shuffle: Off
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 45/3849s (1.2%)
      Repeat: Off
     Shuffle: Off

# Recap begins here, with Skip recap button
--------------------
  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off

# Recap continues with no skip button visible.
--------------------
  Media type: Video
Device state: Playing
       Title: For All Mankind
    Position: 55/3849s (1.4%)
      Repeat: Off
     Shuffle: Off

# I paused the playback
--------------------
  Media type: Video
Device state: Paused
       Title: For All Mankind
    Position: 55/3849s (1.4%)
      Repeat: Off
     Shuffle: Off
```

**Expected behavior**

* The Device state should stay at "playing" even if UI shows up overtop of it.

**System Setup (please complete the following information):**
 - OS: macOS 11.2 / replicated on my Home Assistant install too
 - Python:3.9.2
 - pyatv: 0.7.7
- Apple TV: Apple TV 4K 14.4

**Additional context**

If this is an issue with the ATV reporting itself and can't be worked around in the library, I think in most cases this can be managed by setting longer timeouts on actions tied to the state. For example, I have lights triggered by this state, and I can likely set them to delay by 10s before taking an action

**Comment by postlund** [comment]
Unfortunately this behavior is defined by the apps, so nothing I can do about it I'm afraid. It's very annoying. If you attach debug log with an as simple case as possible, I can take a quick look to make sure they haven't changed anything so that I can actually fix it somehow. It was quite some time ago I checked this lately.

Just post the log here and use this format:

~~~
```log
put log lines here
```
~~~

**Comment by deviantintegral** [comment]
Here's debug logs mirroring the above; a trailer, a recap, and then the episode itself: https://gist.github.com/deviantintegral/3721c8504cbe8d141a2e640ac532c974

**Comment by postlund** [comment]
Looks to me like what I described earlier, so not much I can do about it I'm afraid. My suggestion is to add a note about this in the documentation which can be used as a reference in the future and close this issue. I can take care of that.
